/**
 * @file src/app/(authenticated)/mold/columns.tsx
 * @description S-PARTS 8화면의 그리드 컬럼 정의.
 *
 * 표시 규칙은 지그관리와 같은 것을 쓴다(`@/components/shared/grid-format`) — 코드컬럼은 뜻을 보여주고
 * 코드는 괄호로 함께 둔다. 같은 규칙을 두 번 정의하지 않는다.
 */
import type { ColumnDef } from '@tanstack/react-table';
import { codeWithName, dateOnly, dateTime, num } from '@/components/shared/grid-format';
import type {
  MoldBillRow,
  MoldInventoryRow,
  MoldIssueRow,
  MoldIssueTargetRow,
  MoldMasterRow,
  MoldOrderGroupRow,
  MoldOrderRow,
  MoldPriceRow,
  MoldReceiptRow,
  MoldReceiptTargetRow,
  MoldRepairItemRow,
  MoldRepairRow,
  MoldRepairTargetRow,
  MoldRequestRow,
} from './types';

/** 단가 조회 함수가 -2 를 돌려주면 '단가없음'으로 보여준다 (PB 반환규약) */
const priceOrNone = (value: unknown) => {
  const parsed = Number(value);
  if (value == null || Number.isNaN(parsed)) return '';
  return parsed < 0 ? '단가없음' : parsed.toLocaleString();
};

const right = { align: 'right' } as const;

export const moldMasterColumns: ColumnDef<MoldMasterRow>[] = [
  { id: 'moldGroupName', header: 'S-PARTS 그룹', size: 140, accessorFn: (r) => codeWithName(r.moldGroup, r.moldGroupName) },
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldSpec', header: '규격', size: 160 },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'moldUseStatusName', header: '사용상태', size: 110, accessorFn: (r) => codeWithName(r.moldUseStatus, r.moldUseStatusName) },
  { id: 'moldInOutName', header: '입출고', size: 90, accessorFn: (r) => codeWithName(r.moldInOut, r.moldInOutName) },
  { accessorKey: 'moldUom', header: '단위', size: 70 },
  { id: 'moldTypeName', header: 'S-PARTS 유형', size: 150, accessorFn: (r) => codeWithName(r.moldType, r.moldTypeName) },
  { id: 'moldLineTypeName', header: '거래유형', size: 120, accessorFn: (r) => codeWithName(r.moldLineType, r.moldLineTypeName) },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'drawingNo', header: '도면번호', size: 120 },
  { accessorKey: 'rawMaterial', header: '재질', size: 100 },
  { accessorKey: 'punchNo', header: '펀치번호', size: 100 },
  { accessorKey: 'safetyInventory', header: '안전재고', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'orderLeadtime', header: '발주 L/T', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldRowQty', header: '열수', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldUsefullRowQty', header: '유효열수', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'breakValue', header: '한계수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'actualValue', header: '실적수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetQty', header: 'SET수량', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'moldWarehouseName', header: '창고', size: 100, accessorFn: (r) => codeWithName(r.moldWarehouseCode, r.moldWarehouseName) },
  { accessorKey: 'locationCode', header: '보관위치', size: 110 },
  { accessorKey: 'applyModelName', header: '적용모델', size: 140 },
  { accessorKey: 'itemCode', header: '품목코드', size: 130 },
  { accessorKey: 'itemUnitQty', header: '품목당 수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'cycleTime', header: 'C/T', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'machineCapacity', header: '설비능력', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'gasYn', header: '가스사용', size: 90 },
  { accessorKey: 'itemGasQty', header: '가스량', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'autoReceiptYn', header: '자동입고', size: 90 },
  { accessorKey: 'nationCode', header: '국가', size: 80 },
  { accessorKey: 'lastReceiptDate', header: '최종입고일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'lastIssueDate', header: '최종출고일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'comments', header: '설명', size: 180 },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
  { accessorKey: 'lastModifyBy', header: '수정자', size: 90 },
  { accessorKey: 'lastModifyDate', header: '수정일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

export const moldBillColumns: ColumnDef<MoldBillRow>[] = [
  { accessorKey: 'itemCode', header: '품목코드', size: 140 },
  { accessorKey: 'itemName', header: '품목명', size: 180 },
  { accessorKey: 'itemSpec', header: '규격', size: 150 },
  { accessorKey: 'itemUom', header: '단위', size: 70 },
  { accessorKey: 'unitQty', header: '소요량', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'breakValue', header: '한계수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  {
    accessorKey: 'bomCheck', header: 'BOM 등록', size: 90,
    cell: (c) => (Number(c.getValue() ?? 0) > 0 ? '등록' : '미등록'),
  },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

export const moldInventoryColumns: ColumnDef<MoldInventoryRow>[] = [
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'moldGroupName', header: '그룹', size: 130, accessorFn: (r) => codeWithName(r.moldGroup, r.moldGroupName) },
  { accessorKey: 'moldSpec', header: '규격', size: 150 },
  { accessorKey: 'inventoryQty', header: '재고수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'inventoryPrice', header: '재고단가', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'inventoryAmt', header: '재고금액', size: 110, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'moldUseStatusName', header: '사용상태', size: 110, accessorFn: (r) => codeWithName(r.moldUseStatus, r.moldUseStatusName) },
  { id: 'moldInOutName', header: '입출고', size: 90, accessorFn: (r) => codeWithName(r.moldInOut, r.moldInOutName) },
  { id: 'rentStatusName', header: '임대상태', size: 100, accessorFn: (r) => codeWithName(r.rentStatus, r.rentStatusName) },
  { id: 'lineTypeName', header: '거래유형', size: 120, accessorFn: (r) => codeWithName(r.lineType, r.lineTypeName) },
  { accessorKey: 'moldRowQty', header: '열수', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldUsefullRowQty', header: '유효열수', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetQty', header: 'SET수량', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'breakValue', header: '한계수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'actualValue', header: '실적수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'moldWarehouseName', header: '창고', size: 100, accessorFn: (r) => codeWithName(r.moldWarehouseCode, r.moldWarehouseName) },
  { accessorKey: 'locationCode', header: '보관위치', size: 110 },
  { accessorKey: 'moldRentLocationCode', header: '임대위치', size: 110 },
  { accessorKey: 'applyModelName', header: '적용모델', size: 140 },
  { id: 'lineName', header: '라인', size: 110, accessorFn: (r) => codeWithName(r.lineCode, r.lineName) },
  { id: 'workstageName', header: '공정', size: 120, accessorFn: (r) => codeWithName(r.workstageCode, r.workstageName) },
  { accessorKey: 'machineCode', header: '설비코드', size: 110 },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'barcode', header: '바코드', size: 130 },
  { accessorKey: 'moldVersionSpec', header: '버전규격', size: 130 },
  { accessorKey: 'moldImageExistsYn', header: '이미지', size: 80 },
  { accessorKey: 'lastReceiptDate', header: '최종입고일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'lastIssueDate', header: '최종출고일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'lastAdjustDate', header: '최종조정일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'comments', header: '설명', size: 180 },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

export const moldOrderColumns: ColumnDef<MoldOrderRow>[] = [
  { accessorKey: 'orderNo', header: '주문번호', size: 140 },
  { accessorKey: 'orderGroupNo', header: '주문그룹', size: 120 },
  { accessorKey: 'purchaseOrderDate', header: '주문일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'deliveryDate', header: '납기일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldSpec', header: '규격', size: 140 },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'orderQty', header: '주문수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'receiptQty', header: '입고수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'remainQty', header: '미입고', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'unitPrice', header: '단가', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'orderAmt', header: '주문금액', size: 120, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'currencyName', header: '통화', size: 90, accessorFn: (r) => codeWithName(r.currency, r.currencyName) },
  { id: 'lineTypeName', header: '거래유형', size: 120, accessorFn: (r) => codeWithName(r.lineType, r.lineTypeName) },
  { id: 'deliveryMethodName', header: '운송방법', size: 100, accessorFn: (r) => codeWithName(r.deliveryMethod, r.deliveryMethodName) },
  { accessorKey: 'deliveryPlace', header: '납품장소', size: 130 },
  { accessorKey: 'attnName', header: '수신자', size: 100 },
  { accessorKey: 'ccName', header: '참조자', size: 100 },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

export const moldOrderGroupColumns: ColumnDef<MoldOrderGroupRow>[] = [
  { accessorKey: 'orderGroupNo', header: '주문그룹', size: 130 },
  { id: 'supplierName', header: '공급처', size: 160, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'purchaseOrderDate', header: '주문일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'deliveryDateFrom', header: '납기 시작', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'deliveryDateTo', header: '납기 종료', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'orderCount', header: '주문건수', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'orderQty', header: '주문수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'receiptQty', header: '입고수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'orderAmt', header: '주문금액', size: 120, meta: right, cell: (c) => num(c.getValue()) },
];

export const moldReceiptColumns: ColumnDef<MoldReceiptRow>[] = [
  { accessorKey: 'receiptDate', header: '입고일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'receiptSequence', header: '입고항번', size: 100, meta: right },
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { id: 'receiptDeficitName', header: '입출고구분', size: 110, accessorFn: (r) => codeWithName(r.receiptDeficit, r.receiptDeficitName) },
  { accessorKey: 'receiptQty', header: '입고수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'unitPrice', header: '단가', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'receiptAmt', header: '입고금액', size: 120, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'currencyName', header: '통화', size: 90, accessorFn: (r) => codeWithName(r.currency, r.currencyName) },
  { id: 'receiptStatusName', header: '입고상태', size: 100, accessorFn: (r) => codeWithName(r.receiptStatus, r.receiptStatusName) },
  { accessorKey: 'invoiceNo', header: '인보이스', size: 130 },
  { accessorKey: 'orderNo', header: '주문번호', size: 140 },
  { accessorKey: 'locationCode', header: '보관위치', size: 110 },
  { id: 'lineTypeName', header: '거래유형', size: 120, accessorFn: (r) => codeWithName(r.lineType, r.lineTypeName) },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

export const moldReceiptTargetColumns: ColumnDef<MoldReceiptTargetRow>[] = [
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldSpec', header: '규격', size: 140 },
  { id: 'moldGroupName', header: '그룹', size: 130, accessorFn: (r) => codeWithName(r.moldGroup, r.moldGroupName) },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'inventoryQty', header: '현재고', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'safetyInventory', header: '안전재고', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'confirmedUnitPrice', header: '승인단가', size: 110, meta: right, cell: (c) => priceOrNone(c.getValue()) },
  { accessorKey: 'confirmedCurrency', header: '통화', size: 80 },
  { accessorKey: 'moldUom', header: '단위', size: 70 },
  { accessorKey: 'locationCode', header: '보관위치', size: 110 },
  { accessorKey: 'orderLeadtime', header: '발주 L/T', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'lastReceiptDate', header: '최종입고일', size: 110, cell: (c) => dateOnly(c.getValue()) },
];

export const moldIssueColumns: ColumnDef<MoldIssueRow>[] = [
  { accessorKey: 'issueDate', header: '출고일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'issueSequence', header: '출고항번', size: 100, meta: right },
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'moldIssueAccountName', header: '출고계정', size: 120, accessorFn: (r) => codeWithName(r.moldIssueAccount, r.moldIssueAccountName) },
  { id: 'issueDeficitName', header: '출고구분', size: 110, accessorFn: (r) => codeWithName(r.issueDeficit, r.issueDeficitName) },
  { accessorKey: 'issueQty', header: '출고수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'issuePrice', header: '출고단가', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'issueAmt', header: '출고금액', size: 120, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'currencyName', header: '통화', size: 90, accessorFn: (r) => codeWithName(r.currency, r.currencyName) },
  { id: 'issueStatusName', header: '출고상태', size: 100, accessorFn: (r) => codeWithName(r.issueStatus, r.issueStatusName) },
  { id: 'workstageName', header: '공정', size: 120, accessorFn: (r) => codeWithName(r.workstageCode, r.workstageName) },
  { id: 'lineName', header: '라인', size: 110, accessorFn: (r) => codeWithName(r.lineCode, r.lineName) },
  { accessorKey: 'machineCode', header: '설비코드', size: 110 },
  { accessorKey: 'locationCode', header: '보관위치', size: 110 },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

export const moldIssueTargetColumns: ColumnDef<MoldIssueTargetRow>[] = [
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldSpec', header: '규격', size: 140 },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'inventoryQty', header: '현재고', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'moldUseStatusName', header: '사용상태', size: 110, accessorFn: (r) => codeWithName(r.moldUseStatus, r.moldUseStatusName) },
  { id: 'moldInOutName', header: '입출고', size: 90, accessorFn: (r) => codeWithName(r.moldInOut, r.moldInOutName) },
  { id: 'moldGroupName', header: '그룹', size: 130, accessorFn: (r) => codeWithName(r.moldGroup, r.moldGroupName) },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'unitPrice', header: '단가', size: 100, meta: right, cell: (c) => priceOrNone(c.getValue()) },
  { accessorKey: 'moldRowQty', header: '열수', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'breakValue', header: '한계수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'actualValue', header: '실적수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'locationCode', header: '보관위치', size: 110 },
  { accessorKey: 'machineCode', header: '설비코드', size: 110 },
];

export const moldRequestColumns: ColumnDef<MoldRequestRow>[] = [
  { accessorKey: 'requestDate', header: '청구일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'requestSequence', header: '청구항번', size: 100, meta: right },
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 170 },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'requestQty', header: '청구수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'requestStatusName', header: '청구상태', size: 100, accessorFn: (r) => codeWithName(r.requestStatus, r.requestStatusName) },
  { accessorKey: 'inventoryQty', header: '현재고', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'locationCode', header: '보관위치', size: 110 },
  { accessorKey: 'issueDate', header: '출고일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'issueSequence', header: '출고항번', size: 100, meta: right },
  { accessorKey: 'issueQty', header: '출고수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

export const moldRepairColumns: ColumnDef<MoldRepairRow>[] = [
  { accessorKey: 'repairRequestDate', header: '신청일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'repairSequence', header: '수리항번', size: 100, meta: right },
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { id: 'moldGroupName', header: '그룹', size: 130, accessorFn: (r) => codeWithName(r.moldGroup, r.moldGroupName) },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'repairStatusName', header: '수리상태', size: 120, accessorFn: (r) => codeWithName(r.repairStatus, r.repairStatusName) },
  { id: 'repairReasonName', header: '수리원인', size: 120, accessorFn: (r) => codeWithName(r.repairReasonCode, r.repairReasonName) },
  { id: 'repairVendorName', header: '수리업체', size: 150, accessorFn: (r) => codeWithName(r.repairVendorCode, r.repairVendorName) },
  { accessorKey: 'repairBy', header: '수리자', size: 100 },
  { accessorKey: 'repairDate', header: '수리일자', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'repairReceiptDate', header: '수리입고일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'repairIssueDate', header: '수리출고일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'repairQty', header: '수리수량', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'repairTime', header: '수리시간', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'repairAmt', header: '수리금액', size: 120, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'currencyName', header: '통화', size: 90, accessorFn: (r) => codeWithName(r.currency, r.currencyName) },
  { id: 'lineName', header: '라인', size: 110, accessorFn: (r) => codeWithName(r.lineCode, r.lineName) },
  { accessorKey: 'applyMachineCode', header: '적용설비', size: 110 },
  { accessorKey: 'comments', header: '신청내용', size: 180 },
  { accessorKey: 'repairComments', header: '수리내용', size: 180 },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

export const moldRepairTargetColumns: ColumnDef<MoldRepairTargetRow>[] = [
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldSpec', header: '규격', size: 140 },
  { id: 'moldGroupName', header: '그룹', size: 130, accessorFn: (r) => codeWithName(r.moldGroup, r.moldGroupName) },
  { accessorKey: 'moldVersion', header: '버전', size: 70, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'moldSetSerial', header: 'SET번호', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'repairTerm', header: '수리주기(일)', size: 110, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'inventoryLastReceiptDate', header: '최종입고일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { id: 'moldUseStatusName', header: '사용상태', size: 110, accessorFn: (r) => codeWithName(r.moldUseStatus, r.moldUseStatusName) },
  { id: 'rentStatusName', header: '임대상태', size: 100, accessorFn: (r) => codeWithName(r.rentStatus, r.rentStatusName) },
  { id: 'moldInOutName', header: '입출고', size: 90, accessorFn: (r) => codeWithName(r.moldInOut, r.moldInOutName) },
  { accessorKey: 'inventoryQty', header: '현재고', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'breakValue', header: '한계수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'actualValue', header: '실적수명', size: 100, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'locationCode', header: '보관위치', size: 110 },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'drawingNo', header: '도면번호', size: 120 },
  { accessorKey: 'comments', header: '설명', size: 180 },
];

export const moldRepairItemColumns: ColumnDef<MoldRepairItemRow>[] = [
  { accessorKey: 'repairItemCode', header: '수리품목', size: 150 },
  { accessorKey: 'repairItemName', header: '품목명', size: 180 },
  { accessorKey: 'repairItemSpec', header: '규격', size: 150 },
  { accessorKey: 'repairItemUom', header: '단위', size: 70 },
  { accessorKey: 'repairItemQty', header: '수량', size: 90, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'comments', header: '설명', size: 180 },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];

/** PB 트리의 그룹 라벨 — DECODE 계산값을 한국어로 보여준다 */
const PRICE_STATUS: Record<string, string> = {
  RUNNING: '적용중',
  FUTURE: '적용예정',
  EXPIRED: '만료',
};

export const moldPriceColumns: ColumnDef<MoldPriceRow>[] = [
  {
    accessorKey: 'status', header: '적용상태', size: 100,
    cell: (c) => PRICE_STATUS[String(c.getValue() ?? '')] ?? String(c.getValue() ?? ''),
  },
  { accessorKey: 'moldCode', header: 'S-PARTS 코드', size: 150 },
  { accessorKey: 'moldName', header: 'S-PARTS 명', size: 180 },
  { accessorKey: 'moldSpec', header: '규격', size: 140 },
  { id: 'supplierName', header: '공급처', size: 150, accessorFn: (r) => codeWithName(r.supplierCode, r.supplierName) },
  { accessorKey: 'dateset', header: '적용일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'dateend', header: '종료일', size: 110, cell: (c) => dateOnly(c.getValue()) },
  { accessorKey: 'unitPrice', header: '단가', size: 110, meta: right, cell: (c) => num(c.getValue()) },
  { accessorKey: 'standardUnitPrice', header: '기준단가', size: 110, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'currencyName', header: '통화', size: 90, accessorFn: (r) => codeWithName(r.currency, r.currencyName) },
  { accessorKey: 'taxRate', header: '세율', size: 80, meta: right, cell: (c) => num(c.getValue()) },
  { id: 'priceTypeName', header: '단가유형', size: 110, accessorFn: (r) => codeWithName(r.priceType, r.priceTypeName) },
  { id: 'lineTypeName', header: '거래유형', size: 120, accessorFn: (r) => codeWithName(r.lineType, r.lineTypeName) },
  { id: 'deliveryName', header: '수출/내수', size: 100, accessorFn: (r) => codeWithName(r.delivery, r.deliveryName) },
  { id: 'priceChangeConfirmName', header: '단가승인', size: 100, accessorFn: (r) => codeWithName(r.priceChangeConfirmYn, r.priceChangeConfirmName) },
  { accessorKey: 'confirmBy', header: '승인자', size: 100 },
  { accessorKey: 'confirmDate', header: '승인일시', size: 150, cell: (c) => dateTime(c.getValue()) },
  { accessorKey: 'approvalNo', header: '승인번호', size: 120 },
  { accessorKey: 'priceChangeReason', header: '변경사유', size: 150 },
  { accessorKey: 'moldUom', header: '단위', size: 70 },
  { accessorKey: 'enterBy', header: '등록자', size: 90 },
  { accessorKey: 'enterDate', header: '등록일시', size: 150, cell: (c) => dateTime(c.getValue()) },
];
