-- 설비비가동을 작업지시가 아닌 설비 기준으로 전환하는 스키마 변경 (ADR 0002)
-- 대상: IP_EQUIP_DOWNTIME_RESULT
-- 적용일: 2026-08-27 / 사이트: ES_JSIDC (INFINITY21_JSMES) — 적용 완료
--
-- RUN_NO를 nullable로 낮추고 PK를 (DT_SEQ, ORGANIZATION_ID)로 재설계한다.
-- 기존 DT_SEQ는 RUN_NO 단위 채번이라 전역 중복(1,1,2)이 있어 재채번이 필요하다.
-- PK를 먼저 제거한 뒤 재채번해야 갱신 도중 유니크 위반이 나지 않는다.
--
-- 적용 전: PK(RUN_NO,DT_SEQ,ORGANIZATION_ID) · RUN_NO NOT NULL · 3건(DT_SEQ 1,1,2) · 진행중 0건
-- 적용 후: PK(DT_SEQ,ORGANIZATION_ID)        · RUN_NO NULL     · 3건(DT_SEQ 1,2,3) · 시퀀스 다음값 4

-- 1) 기존 PK 제거
ALTER TABLE IP_EQUIP_DOWNTIME_RESULT DROP CONSTRAINT PK_IP_EQUIP_DOWNTIME_RESULT
/

-- 2) RUN_NO nullable — 작업지시 없이 발생한 비가동은 NULL
ALTER TABLE IP_EQUIP_DOWNTIME_RESULT MODIFY (RUN_NO NULL)
/

-- 3) DT_SEQ 전역 유니크로 재채번 (기존 RUN_NO/DT_SEQ 순서 보존)
MERGE INTO IP_EQUIP_DOWNTIME_RESULT t
USING (SELECT ROWID AS rid, ROW_NUMBER() OVER (ORDER BY RUN_NO, DT_SEQ) AS rn
         FROM IP_EQUIP_DOWNTIME_RESULT) s
   ON (t.ROWID = s.rid)
 WHEN MATCHED THEN UPDATE SET t.DT_SEQ = s.rn
/

-- 4) 새 PK
ALTER TABLE IP_EQUIP_DOWNTIME_RESULT
  ADD CONSTRAINT PK_IP_EQUIP_DOWNTIME_RESULT PRIMARY KEY (DT_SEQ, ORGANIZATION_ID)
/

-- 5) DT_SEQ 채번 시퀀스 (재채번 후 최대값 3 → 4부터)
CREATE SEQUENCE SEQ_IP_EQUIP_DOWNTIME START WITH 4 INCREMENT BY 1 NOCACHE NOCYCLE
/

-- 6) 설비 기준 조회 인덱스 — 기존 PK 선두컬럼(RUN_NO)이 더 이상 주 조회 경로가 아니다
CREATE INDEX IX_IP_EQUIP_DOWNTIME_MACHINE
  ON IP_EQUIP_DOWNTIME_RESULT (ORGANIZATION_ID, MACHINE_CODE, DT_SEQ)
/

COMMENT ON COLUMN IP_EQUIP_DOWNTIME_RESULT.RUN_NO IS '작업지시번호 (선택 — 작업지시 없이 발생한 비가동은 NULL)'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_RESULT.DT_SEQ IS '비가동 일련번호 (SEQ_IP_EQUIP_DOWNTIME 전역 채번)'
/
