-- 설비별 비가동 사유 연계 (헤더-디테일) DDL
-- IP_EQUIP_DOWNTIME_MAP     : 설비 단위 연계 헤더 (설비 1행)
-- IP_EQUIP_DOWNTIME_MAP_DTL : 설비×비가동사유 매핑 디테일
-- 사유 상세(사유명/구분/OEE반영)는 IP_EQUIP_DOWNTIME_REASON 조인으로 조회한다.

CREATE TABLE IP_EQUIP_DOWNTIME_MAP (
  MACHINE_CODE      VARCHAR2(30)  NOT NULL,
  ORGANIZATION_ID   NUMBER        NOT NULL,
  ENTER_BY          VARCHAR2(20),
  ENTER_DATE        DATE,
  LAST_MODIFY_BY    VARCHAR2(20),
  LAST_MODIFY_DATE  DATE,
  CONSTRAINT PK_IP_EQUIP_DT_MAP PRIMARY KEY (MACHINE_CODE, ORGANIZATION_ID)
)
/

CREATE TABLE IP_EQUIP_DOWNTIME_MAP_DTL (
  MACHINE_CODE      VARCHAR2(30)  NOT NULL,
  REASON_CODE       VARCHAR2(20)  NOT NULL,
  ORGANIZATION_ID   NUMBER        NOT NULL,
  SORT_NO           NUMBER,
  ENTER_BY          VARCHAR2(20),
  ENTER_DATE        DATE,
  CONSTRAINT PK_IP_EQUIP_DT_MAP_DTL PRIMARY KEY (MACHINE_CODE, REASON_CODE, ORGANIZATION_ID)
)
/

COMMENT ON TABLE IP_EQUIP_DOWNTIME_MAP IS '설비별 비가동 사유 연계 헤더'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP.MACHINE_CODE IS '설비코드 (IMCN_MACHINE.MACHINE_CODE)'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP.ORGANIZATION_ID IS '조직ID'
/
COMMENT ON TABLE IP_EQUIP_DOWNTIME_MAP_DTL IS '설비×비가동사유 매핑 디테일'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP_DTL.MACHINE_CODE IS '설비코드'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP_DTL.REASON_CODE IS '비가동사유코드 (IP_EQUIP_DOWNTIME_REASON.REASON_CODE)'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP_DTL.SORT_NO IS '표시 순서'
/
