CREATE TABLE IP_EQUIP_DOWNTIME_REASON (
  REASON_CODE       VARCHAR2(20)  NOT NULL,
  ORGANIZATION_ID   NUMBER        NOT NULL,
  REASON_NAME       VARCHAR2(100) NOT NULL,
  DESCRIPTION       VARCHAR2(500),
  REASON_TYPE       VARCHAR2(10),
  OEE_REFLECT_YN    VARCHAR2(1)   DEFAULT 'Y',
  DISPLAY_ORDER     NUMBER        DEFAULT 0,
  STD_TIME_YN       VARCHAR2(1)   DEFAULT 'N',
  STD_TIME_VALUE    NUMBER        DEFAULT 0,
  STD_TIME_UNIT     VARCHAR2(10),
  USE_YN            VARCHAR2(1)   DEFAULT 'Y',
  ENTER_BY          VARCHAR2(20),
  ENTER_DATE        DATE,
  LAST_MODIFY_BY    VARCHAR2(20),
  LAST_MODIFY_DATE  DATE,
  CONSTRAINT PK_IP_EQUIP_DOWNTIME_REASON PRIMARY KEY (REASON_CODE, ORGANIZATION_ID)
)
/
COMMENT ON TABLE IP_EQUIP_DOWNTIME_REASON IS '설비 비가동 사유코드 관리'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.REASON_CODE IS '사유코드'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.ORGANIZATION_ID IS '조직ID'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.REASON_NAME IS '사유명'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.DESCRIPTION IS '사유 설명'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.REASON_TYPE IS '비가동 사유구분: PLAN=계획, UNPLAN=비계획'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.OEE_REFLECT_YN IS 'OEE 반영여부: Y=반영, N=미반영'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.DISPLAY_ORDER IS '화면 표시 순서'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.STD_TIME_YN IS '표준시간 대상 여부: Y/N'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.STD_TIME_VALUE IS '표준시간 수치'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.STD_TIME_UNIT IS '표준시간 단위: HOUR=시간, MIN=분, SEC=초'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.USE_YN IS '사용구분: Y=사용, N=미사용'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.ENTER_BY IS '등록자'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.ENTER_DATE IS '등록일자'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.LAST_MODIFY_BY IS '최종수정자'
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.LAST_MODIFY_DATE IS '최종수정일자'
/
