CREATE TABLE IP_PRODUCT_ST_MASTER (
  ITEM_CODE         VARCHAR2(20)  NOT NULL,
  DATESET           DATE          NOT NULL,
  ORGANIZATION_ID   NUMBER        NOT NULL,
  DATEEND           DATE,
  ST_VALUE          NUMBER,
  CT_VALUE          NUMBER,
  NT_VALUE          NUMBER,
  TT_VALUE          NUMBER,
  REMARK            VARCHAR2(500),
  ENTER_BY          VARCHAR2(20),
  ENTER_DATE        DATE,
  LAST_MODIFY_BY    VARCHAR2(20),
  LAST_MODIFY_DATE  DATE,
  CONSTRAINT PK_IP_PRODUCT_ST_MASTER PRIMARY KEY (ITEM_CODE, DATESET, ORGANIZATION_ID)
)
/
COMMENT ON TABLE IP_PRODUCT_ST_MASTER IS '표준시간 관리 - 품목(모델)별 ST/CT/NT/TT 표준시간 · 적용기간 리비전'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ITEM_CODE IS '품목코드(모델코드) - ID_ITEM 참조'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.DATESET IS '적용 시작일'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ORGANIZATION_ID IS '조직ID'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.DATEEND IS '적용 종료일 (개방형 9999-12-31=현재 적용)'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ST_VALUE IS '표준시간 ST(Standard Time, 초)'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.CT_VALUE IS 'Cycle Time(초)'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.NT_VALUE IS 'Neck Time(초)'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.TT_VALUE IS 'Takt Time(초)'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.REMARK IS '비고'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ENTER_BY IS '등록자'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ENTER_DATE IS '등록일자'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.LAST_MODIFY_BY IS '최종수정자'
/
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.LAST_MODIFY_DATE IS '최종수정일자'
/
