import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(__dirname, "page.tsx"), "utf8");

assert.match(source, /import PartSearchModal from "@\/components\/shared\/PartSearchModal"/);
assert.match(source, /const \[orderItems, setOrderItems\] = useState<ShipOrderLine\[\]>\(\[\]\)/);
assert.match(source, /items: orderItems\.map\(\(item\) => \(\{/);
assert.match(source, /await api\.post\("\/shipping\/orders", payload\)/);
assert.doesNotMatch(source, /await api\.post\("\/shipping\/orders", form\)/);
assert.doesNotMatch(source, /setForm\(\{ shipOrderNo: ""/);
assert.doesNotMatch(source, /\.\.\.form,\s*items:/);
assert.doesNotMatch(source, /canSave = form\.shipOrderNo\.trim\(\)\.length > 0/);
assert.match(source, /shipOrderNo: editingItem\.shipOrderNo/);
assert.match(source, /shipOrderNo: t\("common\.autoGenerated"/);
assert.match(source, /disabled=\{!canEditCurrentOrder \|\| !canSave \|\| saving\}/);
assert.match(source, /orderItems\.length > 0/);
