-- esh_mes(61.105.35.54/XE) 적용용 — 컬럼 추가분
-- 생성일 2026-09-21 · ESDBPDB와 비교해 대상 DB에 없는 컬럼만 추린 것
-- 대상 테이블에는 이미 데이터가 있으므로 모두 NULL 허용으로 추가한다.

-- [IP_PRODUCT_RUN_CARD] 2개 컬럼 추가
ALTER TABLE IP_PRODUCT_RUN_CARD ADD (MACHINE_CODE VARCHAR2(30))
/
COMMENT ON COLUMN IP_PRODUCT_RUN_CARD.MACHINE_CODE IS '설비코드 (IMCN_MACHINE.MACHINE_CODE)'
/
ALTER TABLE IP_PRODUCT_RUN_CARD ADD (WORKSTAGE_CODE VARCHAR2(10))
/
COMMENT ON COLUMN IP_PRODUCT_RUN_CARD.WORKSTAGE_CODE IS '공정코드 (IP_PRODUCT_WORKSTAGE.WORKSTAGE_CODE)'
/

-- [IP_PRODUCT_SENSOR_ACTUAL] 4개 컬럼 추가
ALTER TABLE IP_PRODUCT_SENSOR_ACTUAL ADD (MACHINE_CODE VARCHAR2(30))
/
COMMENT ON COLUMN IP_PRODUCT_SENSOR_ACTUAL.MACHINE_CODE IS '설비코드 (IMCN_MACHINE.MACHINE_CODE) - 수기 실적 전용, 센서 배치는 NULL'
/
ALTER TABLE IP_PRODUCT_SENSOR_ACTUAL ADD (WORK_TIME NUMBER)
/
COMMENT ON COLUMN IP_PRODUCT_SENSOR_ACTUAL.WORK_TIME IS '작업시간(분) - 수기 실적 전용'
/
ALTER TABLE IP_PRODUCT_SENSOR_ACTUAL ADD (WORKER_NAME VARCHAR2(100))
/
COMMENT ON COLUMN IP_PRODUCT_SENSOR_ACTUAL.WORKER_NAME IS '작업자명 - 수기 실적 전용'
/
ALTER TABLE IP_PRODUCT_SENSOR_ACTUAL ADD (WORKER_COUNT NUMBER)
/
COMMENT ON COLUMN IP_PRODUCT_SENSOR_ACTUAL.WORKER_COUNT IS '작업인원 - 수기 실적 전용'
/

-- [IP_PRODUCT_LINE] 3개 컬럼 추가
ALTER TABLE IP_PRODUCT_LINE ADD (PROCESS_CODE VARCHAR2(20))
/
ALTER TABLE IP_PRODUCT_LINE ADD (RESOURCE_TYPE VARCHAR2(20))
/
ALTER TABLE IP_PRODUCT_LINE ADD (PARENT_LINE_CODE VARCHAR2(20))
/

-- [V_OEE_PLAN_TIME] 뷰 정의가 달라 교체한다 (컬럼 3개 차이)
CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "V_OEE_PLAN_TIME" ("RESOURCE_ID", "ORGANIZATION_ID", "PROCESS_CODE", "WORK_DATE", "SHIFT", "SEGMENT_START_TIME", "SEGMENT_END_TIME", "PLANNED_MINUTES", "PLANNED_STOP_MINUTES", "NET_LOAD_MINUTES") AS 
  WITH dates AS (
  SELECT TRUNC(SYSDATE - (8.5 / 24)) AS WORK_DATE FROM DUAL
  UNION
  SELECT WORK_DATE FROM OEE_PLAN_TIME
  UNION
  SELECT WORK_DATE FROM OEE_PRODUCTION_RESULT
  UNION
  SELECT WORK_DATE FROM OEE_DOWNTIME_EVENT
), shift_windows AS (
  SELECT 'DAY' AS SHIFT,
         '08:30:00' AS START_CLOCK,
         '17:30:00' AS END_CLOCK,
         0 AS START_OFFSET,
         0 AS END_OFFSET
    FROM DUAL
  UNION ALL
  SELECT 'NIGHT',
         '20:30:00',
         '05:30:00',
         0,
         1
    FROM DUAL
), segments AS (
  SELECT r.RESOURCE_ID, r.ORGANIZATION_ID, r.PROCESS_CODE, d.WORK_DATE, w.SHIFT,
          CAST(d.WORK_DATE AS TIMESTAMP)
            + NUMTODSINTERVAL(w.START_OFFSET, 'DAY')
            + NUMTODSINTERVAL(
                TO_NUMBER(SUBSTR(w.START_CLOCK, 1, 2)) * 3600
                  + TO_NUMBER(SUBSTR(w.START_CLOCK, 4, 2)) * 60
                  + TO_NUMBER(SUBSTR(w.START_CLOCK, 7, 2)),
                'SECOND'
              ) AS SEGMENT_START_TIME,
          CAST(d.WORK_DATE AS TIMESTAMP)
            + NUMTODSINTERVAL(w.END_OFFSET, 'DAY')
            + NUMTODSINTERVAL(
                TO_NUMBER(SUBSTR(w.END_CLOCK, 1, 2)) * 3600
                  + TO_NUMBER(SUBSTR(w.END_CLOCK, 4, 2)) * 60
                  + TO_NUMBER(SUBSTR(w.END_CLOCK, 7, 2)),
                'SECOND'
              ) AS SEGMENT_END_TIME
     FROM OEE_RESOURCE r
     CROSS JOIN dates d
     CROSS JOIN shift_windows w
    WHERE r.USE_YN = 'Y'
      AND r.PROCESS_CODE IN ('SMT', 'ASSY')
      AND r.RESOURCE_TYPE IN ('LINE', 'CELL')
)
SELECT s.RESOURCE_ID, s.ORGANIZATION_ID, s.PROCESS_CODE, s.WORK_DATE, s.SHIFT,
       s.SEGMENT_START_TIME, s.SEGMENT_END_TIME,
       NVL(ov.PLANNED_MINUTES,
         540) AS PLANNED_MINUTES,
       NVL(ov.PLANNED_STOP_MINUTES, 60) AS PLANNED_STOP_MINUTES,
       NVL(ov.NET_LOAD_MINUTES, 480) AS NET_LOAD_MINUTES
  FROM segments s
  LEFT JOIN OEE_PLAN_TIME ov
    ON ov.RESOURCE_ID = s.RESOURCE_ID
   AND ov.ORGANIZATION_ID = s.ORGANIZATION_ID
   AND ov.WORK_DATE = s.WORK_DATE
   AND ov.SHIFT = s.SHIFT
   AND ov.OVERRIDE_YN = 'Y'
 WHERE s.SEGMENT_END_TIME > s.SEGMENT_START_TIME
/
