-- =====================================================================
-- esh_mes (61.105.35.54 / XE / INFINITY21_JSMES) 적용 스크립트 — 통합본
-- 생성일 2026-09-21
-- 원본   : ESDBPDB @ 139.150.82.207 (현재 개발/운영 중인 DB)
--
-- 두 DB의 차이 전량 (읽기 비교 결과)
--   1) 테이블 15개 + 시퀀스 1개  : 대상 DB에 없음 → 생성
--   2) 컬럼 9개 (테이블 3개)      : 대상 DB에 없음 → 추가 (모두 NULL 허용)
--   3) 뷰 V_OEE_PLAN_TIME         : 정의가 달라 교체
--   * 뷰·함수·프로시저·트리거 중 누락된 것은 없음(0건)
--
-- 실행 순서가 중요하다. 1번을 먼저 해야 뷰가 참조하는 OEE_DOWNTIME_EVENT가 생긴다.
-- DROP은 없다. 이미 있는 오브젝트는 ORA-00955로 해당 블록만 실패한다.
-- 데이터는 복사하지 않는다(구조만).
--
-- 실행:
--   python3 ~/.claude/skills/oracle-db/scripts/oracle_connector.py \
--     --site esh_mes --execute-file <이 파일 경로>
-- =====================================================================

-- ############ 1단계: 테이블·시퀀스 생성 ############

-- esh_mes(61.105.35.54/XE) 적용용 — ESDBPDB에서 추출한 OEE 단계 신규 오브젝트
-- 생성일 2026-09-21 · 테이블 15 · 시퀀스 1 · 인덱스 6 · 주석 55
-- DROP 없음. 이미 있으면 ORA-00955가 나므로 그 블록만 실패한다.

-- [SEQUENCE] SEQ_IP_EQUIP_DOWNTIME
CREATE SEQUENCE  "SEQ_IP_EQUIP_DOWNTIME"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

-- [TABLE] IP_EQUIP_DOWNTIME_REASON
CREATE TABLE "IP_EQUIP_DOWNTIME_REASON" 
   (	"REASON_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"REASON_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"REASON_TYPE" VARCHAR2(10), 
	"OEE_REFLECT_YN" VARCHAR2(1) DEFAULT 'Y', 
	"DISPLAY_ORDER" NUMBER DEFAULT 0, 
	"STD_TIME_YN" VARCHAR2(1) DEFAULT 'N', 
	"STD_TIME_VALUE" NUMBER DEFAULT 0, 
	"STD_TIME_UNIT" VARCHAR2(10), 
	"USE_YN" VARCHAR2(1) DEFAULT 'Y', 
	"ENTER_BY" VARCHAR2(20), 
	"ENTER_DATE" DATE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	 CONSTRAINT "PK_IP_EQUIP_DOWNTIME_REASON" PRIMARY KEY ("REASON_CODE", "ORGANIZATION_ID")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON
COMMENT ON TABLE IP_EQUIP_DOWNTIME_REASON IS '설비 비가동 사유코드 관리'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.REASON_CODE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.REASON_CODE IS '사유코드'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.ORGANIZATION_ID
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.ORGANIZATION_ID IS '조직ID'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.REASON_NAME
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.REASON_NAME IS '사유명'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.DESCRIPTION
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.DESCRIPTION IS '사유 설명'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.REASON_TYPE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.REASON_TYPE IS '비가동 사유구분: PLAN=계획, UNPLAN=비계획'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.OEE_REFLECT_YN
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.OEE_REFLECT_YN IS 'OEE 반영여부: Y=반영, N=미반영'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.DISPLAY_ORDER
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.DISPLAY_ORDER IS '화면 표시 순서'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.STD_TIME_YN
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.STD_TIME_YN IS '표준시간 대상 여부: Y/N'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.STD_TIME_VALUE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.STD_TIME_VALUE IS '표준시간 수치'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.STD_TIME_UNIT
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.STD_TIME_UNIT IS '표준시간 단위: HOUR=시간, MIN=분, SEC=초'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.USE_YN
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.USE_YN IS '사용구분: Y=사용, N=미사용'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.ENTER_BY
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.ENTER_BY IS '등록자'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.ENTER_DATE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.ENTER_DATE IS '등록일자'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.LAST_MODIFY_BY
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.LAST_MODIFY_BY IS '최종수정자'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_REASON.LAST_MODIFY_DATE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_REASON.LAST_MODIFY_DATE IS '최종수정일자'
/

-- [TABLE] IP_EQUIP_DOWNTIME_MAP
CREATE TABLE "IP_EQUIP_DOWNTIME_MAP" 
   (	"MACHINE_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"ENTER_BY" VARCHAR2(20), 
	"ENTER_DATE" DATE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	 CONSTRAINT "PK_IP_EQUIP_DT_MAP" PRIMARY KEY ("MACHINE_CODE", "ORGANIZATION_ID")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_EQUIP_DOWNTIME_MAP
COMMENT ON TABLE IP_EQUIP_DOWNTIME_MAP IS '설비별 비가동 사유 연계 헤더'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_MAP.MACHINE_CODE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP.MACHINE_CODE IS '설비코드 (IMCN_MACHINE.MACHINE_CODE)'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_MAP.ORGANIZATION_ID
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP.ORGANIZATION_ID IS '조직ID'
/

-- [TABLE] IP_EQUIP_DOWNTIME_MAP_DTL
CREATE TABLE "IP_EQUIP_DOWNTIME_MAP_DTL" 
   (	"MACHINE_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"REASON_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"SORT_NO" NUMBER, 
	"ENTER_BY" VARCHAR2(20), 
	"ENTER_DATE" DATE, 
	 CONSTRAINT "PK_IP_EQUIP_DT_MAP_DTL" PRIMARY KEY ("MACHINE_CODE", "REASON_CODE", "ORGANIZATION_ID")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_EQUIP_DOWNTIME_MAP_DTL
COMMENT ON TABLE IP_EQUIP_DOWNTIME_MAP_DTL IS '설비×비가동사유 매핑 디테일'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_MAP_DTL.MACHINE_CODE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP_DTL.MACHINE_CODE IS '설비코드'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_MAP_DTL.REASON_CODE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP_DTL.REASON_CODE IS '비가동사유코드 (IP_EQUIP_DOWNTIME_REASON.REASON_CODE)'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_MAP_DTL.SORT_NO
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_MAP_DTL.SORT_NO IS '표시 순서'
/

-- [TABLE] IP_EQUIP_DOWNTIME_RESULT
CREATE TABLE "IP_EQUIP_DOWNTIME_RESULT" 
   (	"RUN_NO" VARCHAR2(30), 
	"DT_SEQ" NUMBER NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"MACHINE_CODE" VARCHAR2(30), 
	"WORKSTAGE_CODE" VARCHAR2(10), 
	"REASON_CODE" VARCHAR2(20), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"MEMO" VARCHAR2(500), 
	"WORKER" VARCHAR2(100), 
	"ENTER_BY" VARCHAR2(20), 
	"ENTER_DATE" DATE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	"CAUSE_YN" VARCHAR2(1) DEFAULT 'N', 
	"LINE_CODE" VARCHAR2(20), 
	 CONSTRAINT "PK_IP_EQUIP_DOWNTIME_RESULT" PRIMARY KEY ("DT_SEQ", "ORGANIZATION_ID")
  USING INDEX  ENABLE
   )
/

-- [INDEX] IX_IP_EQUIP_DOWNTIME_MACHINE
CREATE INDEX "IX_IP_EQUIP_DOWNTIME_MACHINE" ON "IP_EQUIP_DOWNTIME_RESULT" ("ORGANIZATION_ID", "MACHINE_CODE", "DT_SEQ")
/

-- [COMMENT] IP_EQUIP_DOWNTIME_RESULT
COMMENT ON TABLE IP_EQUIP_DOWNTIME_RESULT IS '설비비가동 실적 (시작/종료, 종료 NULL=진행중)'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_RESULT.CAUSE_YN
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_RESULT.CAUSE_YN IS '원인설비 여부: Y=이 설비가 라인 정지의 원인, N=동반 정지'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_RESULT.LINE_CODE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_RESULT.LINE_CODE IS '생산라인 코드 (동일 조직의 IP_PRODUCT_LINE.LINE_CODE, 기존 실적은 NULL)'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_RESULT.RUN_NO
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_RESULT.RUN_NO IS '작업지시번호 (선택 — 작업지시 없이 발생한 비가동은 NULL)'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_RESULT.DT_SEQ
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_RESULT.DT_SEQ IS '비가동 일련번호 (SEQ_IP_EQUIP_DOWNTIME 전역 채번)'
/

-- [COMMENT] IP_EQUIP_DOWNTIME_RESULT.REASON_CODE
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_RESULT.REASON_CODE IS '비가동 사유코드 (IP_EQUIP_DOWNTIME_REASON.REASON_CODE)'
/

-- [TABLE] IP_PRODUCT_ST_MASTER
CREATE TABLE "IP_PRODUCT_ST_MASTER" 
   (	"ITEM_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"DATESET" DATE NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"DATEEND" DATE, 
	"ST_VALUE" NUMBER, 
	"CT_VALUE" NUMBER, 
	"NT_VALUE" NUMBER, 
	"TT_VALUE" NUMBER, 
	"REMARK" VARCHAR2(500), 
	"ENTER_BY" VARCHAR2(20), 
	"ENTER_DATE" DATE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	"MACHINE_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "PK_IP_PRODUCT_ST_MASTER" PRIMARY KEY ("ITEM_CODE", "MACHINE_CODE", "DATESET", "ORGANIZATION_ID")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_PRODUCT_ST_MASTER
COMMENT ON TABLE IP_PRODUCT_ST_MASTER IS '표준시간 관리 - 품목(모델)별 ST/CT/NT/TT 표준시간 · 적용기간 리비전'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.MACHINE_CODE
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.MACHINE_CODE IS '설비코드 (IMCN_MACHINE.MACHINE_CODE) — 설비별 표준시간 PK'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.ITEM_CODE
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ITEM_CODE IS '품목코드(모델코드) - ID_ITEM 참조'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.DATESET
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.DATESET IS '적용 시작일'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.ORGANIZATION_ID
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ORGANIZATION_ID IS '조직ID'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.DATEEND
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.DATEEND IS '적용 종료일 (개방형 9999-12-31=현재 적용)'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.ST_VALUE
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ST_VALUE IS '표준시간 ST(Standard Time, 초)'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.CT_VALUE
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.CT_VALUE IS 'Cycle Time(초)'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.NT_VALUE
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.NT_VALUE IS 'Neck Time(초)'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.TT_VALUE
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.TT_VALUE IS 'Takt Time(초)'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.REMARK
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.REMARK IS '비고'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.ENTER_BY
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ENTER_BY IS '등록자'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.ENTER_DATE
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.ENTER_DATE IS '등록일자'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.LAST_MODIFY_BY
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.LAST_MODIFY_BY IS '최종수정자'
/

-- [COMMENT] IP_PRODUCT_ST_MASTER.LAST_MODIFY_DATE
COMMENT ON COLUMN IP_PRODUCT_ST_MASTER.LAST_MODIFY_DATE IS '최종수정일자'
/

-- [TABLE] IP_PRODUCT_WORKSTAGE_LINE
CREATE TABLE "IP_PRODUCT_WORKSTAGE_LINE" 
   (	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"WORKSTAGE_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"WORKSTAGE_TYPE" VARCHAR2(1) NOT NULL ENABLE, 
	"LINE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"ENTER_BY" VARCHAR2(20), 
	"ENTER_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_IP_PRODUCT_WORKSTAGE_LINE" PRIMARY KEY ("ORGANIZATION_ID", "WORKSTAGE_CODE", "WORKSTAGE_TYPE", "LINE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_IP_PWL_WORKSTAGE" FOREIGN KEY ("WORKSTAGE_CODE", "ORGANIZATION_ID")
	  REFERENCES "IP_PRODUCT_WORKSTAGE" ("WORKSTAGE_CODE", "ORGANIZATION_ID") ENABLE, 
	 CONSTRAINT "FK_IP_PWL_LINE" FOREIGN KEY ("LINE_CODE", "ORGANIZATION_ID")
	  REFERENCES "IP_PRODUCT_LINE" ("LINE_CODE", "ORGANIZATION_ID") ENABLE
   )
/

-- [TABLE] IP_PRODUCT_WORK_DEFECT
CREATE TABLE "IP_PRODUCT_WORK_DEFECT" 
   (	"RUN_NO" VARCHAR2(30) NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"BAD_CODE" VARCHAR2(20), 
	"BAD_QTY" NUMBER DEFAULT 0, 
	"REMARK" VARCHAR2(500), 
	"ENTER_BY" VARCHAR2(20), 
	"ENTER_DATE" DATE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	 CONSTRAINT "PK_IP_PRODUCT_WORK_DEFECT" PRIMARY KEY ("RUN_NO", "ORGANIZATION_ID")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_PRODUCT_WORK_DEFECT
COMMENT ON TABLE IP_PRODUCT_WORK_DEFECT IS '작업지시 단위 대표불량 단일 등록 (실적과 독립)'
/

-- [COMMENT] IP_PRODUCT_WORK_DEFECT.BAD_CODE
COMMENT ON COLUMN IP_PRODUCT_WORK_DEFECT.BAD_CODE IS '대표 부적합코드 (ISYS_CODE_MASTER WQC BAD REASON CODE)'
/

-- [TABLE] IP_PRODUCT_CALENDAR_SHIFT
CREATE TABLE "IP_PRODUCT_CALENDAR_SHIFT" 
   (	"PLAN_DATE" DATE NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"LINE_CODE" VARCHAR2(20) DEFAULT '*' NOT NULL ENABLE, 
	"SHIFT_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"START_TIME" VARCHAR2(8) NOT NULL ENABLE, 
	"END_TIME" VARCHAR2(8) NOT NULL ENABLE, 
	"ENTER_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"ENTER_DATE" DATE NOT NULL ENABLE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	 CONSTRAINT "XPKIP_PRODUCT_CALENDAR_SHIFT" PRIMARY KEY ("PLAN_DATE", "ORGANIZATION_ID", "LINE_CODE", "SHIFT_CODE")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_PRODUCT_CALENDAR_SHIFT
COMMENT ON TABLE IP_PRODUCT_CALENDAR_SHIFT IS '생산월력 일자별 교대조 작업시간. LINE_CODE=''*''는 전사'
/

-- [TABLE] IP_PRODUCT_CALENDAR_BREAK
CREATE TABLE "IP_PRODUCT_CALENDAR_BREAK" 
   (	"PLAN_DATE" DATE NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"LINE_CODE" VARCHAR2(20) DEFAULT '*' NOT NULL ENABLE, 
	"BREAK_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"BREAK_MINUTES" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"ENTER_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"ENTER_DATE" DATE NOT NULL ENABLE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	 CONSTRAINT "XPKIP_PRODUCT_CALENDAR_BREAK" PRIMARY KEY ("PLAN_DATE", "ORGANIZATION_ID", "LINE_CODE", "BREAK_TYPE")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_PRODUCT_CALENDAR_BREAK
COMMENT ON TABLE IP_PRODUCT_CALENDAR_BREAK IS '생산월력 일자별 비작업(휴게/식사) 시간. LINE_CODE=''*''는 전사'
/

-- [TABLE] IP_PRODUCT_CALENDAR_LINE_RUN
CREATE TABLE "IP_PRODUCT_CALENDAR_LINE_RUN" 
   (	"PLAN_DATE" DATE NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"LINE_CODE" VARCHAR2(20) DEFAULT '*' NOT NULL ENABLE, 
	"RUN_SEQ" NUMBER NOT NULL ENABLE, 
	"RUN_LINE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"START_TIME" VARCHAR2(8) NOT NULL ENABLE, 
	"END_TIME" VARCHAR2(8) NOT NULL ENABLE, 
	"ENTER_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"ENTER_DATE" DATE NOT NULL ENABLE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	 CONSTRAINT "XPKIP_PRODUCT_CALENDAR_LINE_RUN" PRIMARY KEY ("PLAN_DATE", "ORGANIZATION_ID", "LINE_CODE", "RUN_SEQ")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_PRODUCT_CALENDAR_LINE_RUN
COMMENT ON TABLE IP_PRODUCT_CALENDAR_LINE_RUN IS '생산월력 일자별 라인 추가 운영. LINE_CODE=''*''는 전사 월력'
/

-- [COMMENT] IP_PRODUCT_CALENDAR_LINE_RUN.LINE_CODE
COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.LINE_CODE IS '월력 소유자. ''*''=전사'
/

-- [COMMENT] IP_PRODUCT_CALENDAR_LINE_RUN.RUN_SEQ
COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.RUN_SEQ IS '행 순번. 같은 라인 복수 구간 등록용'
/

-- [COMMENT] IP_PRODUCT_CALENDAR_LINE_RUN.RUN_LINE_CODE
COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.RUN_LINE_CODE IS '추가 운영 라인(IP_PRODUCT_LINE)'
/

-- [COMMENT] IP_PRODUCT_CALENDAR_LINE_RUN.START_TIME
COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.START_TIME IS '가동 시작 HH:MM'
/

-- [COMMENT] IP_PRODUCT_CALENDAR_LINE_RUN.END_TIME
COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.END_TIME IS '가동 종료 HH:MM. 시작보다 이르면 자정 넘김'
/

-- [TABLE] IP_SHIFT_TIME_BREAK
CREATE TABLE "IP_SHIFT_TIME_BREAK" 
   (	"DATESET" DATE NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"SHIFT_SLOT" VARCHAR2(10) NOT NULL ENABLE, 
	"BREAK_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"BREAK_MINUTES" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"ENTER_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"ENTER_DATE" DATE NOT NULL ENABLE, 
	"LAST_MODIFY_BY" VARCHAR2(20), 
	"LAST_MODIFY_DATE" DATE, 
	 CONSTRAINT "CK_SHIFT_TIME_BREAK_SLOT" CHECK (SHIFT_SLOT IN ('DAY', 'NIGHT')) ENABLE, 
	 CONSTRAINT "XPKIP_SHIFT_TIME_BREAK" PRIMARY KEY ("DATESET", "ORGANIZATION_ID", "SHIFT_SLOT", "BREAK_TYPE")
  USING INDEX  ENABLE
   )
/

-- [COMMENT] IP_SHIFT_TIME_BREAK
COMMENT ON TABLE IP_SHIFT_TIME_BREAK IS '교대시간 마스터의 슬롯별 비작업(휴게/식사) 시간. BREAK_TYPE은 공통코드 BREAK TYPE'
/

-- [TABLE] OEE_DOWNTIME_EVENT
CREATE TABLE "OEE_DOWNTIME_EVENT" 
   (	"EVENT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"RESOURCE_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"RESOURCE_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"PARENT_LINE_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"WORK_DATE" DATE NOT NULL ENABLE, 
	"WORK_SEGMENT" VARCHAR2(5) NOT NULL ENABLE, 
	"START_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"END_TIME" TIMESTAMP (6), 
	"REASON_CODE" VARCHAR2(100) NOT NULL ENABLE, 
	"MEMO" VARCHAR2(500), 
	"WORKER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"START_REQUEST_ID" VARCHAR2(64) NOT NULL ENABLE, 
	"END_REQUEST_ID" VARCHAR2(64), 
	"STARTED_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"ENDED_BY" VARCHAR2(20), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CK_OEE_DTE_RESOURCE" CHECK (RESOURCE_TYPE IN ('LINE', 'CELL')) ENABLE, 
	 CONSTRAINT "CK_OEE_DTE_PROCESS" CHECK (PROCESS_CODE IN ('SMT', 'ASSY')) ENABLE, 
	 CONSTRAINT "PK_OEE_DTE" PRIMARY KEY ("EVENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_OEE_DTE_START_REQ" UNIQUE ("ORGANIZATION_ID", "START_REQUEST_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CK_OEE_DTE_WORK_SEGMENT" CHECK (WORK_SEGMENT IN ('DAY', 'NIGHT')) ENABLE
   )
/

-- [INDEX] UX_OEE_DTE_END_REQ
CREATE UNIQUE INDEX "UX_OEE_DTE_END_REQ" ON "OEE_DOWNTIME_EVENT" (CASE  WHEN "END_REQUEST_ID" IS NOT NULL THEN "ORGANIZATION_ID" END , CASE  WHEN "END_REQUEST_ID" IS NOT NULL THEN "END_REQUEST_ID" END )
/

-- [INDEX] UX_OEE_DTE_OPEN
CREATE UNIQUE INDEX "UX_OEE_DTE_OPEN" ON "OEE_DOWNTIME_EVENT" (CASE  WHEN "END_TIME" IS NULL THEN "ORGANIZATION_ID" END , CASE  WHEN "END_TIME" IS NULL THEN "RESOURCE_TYPE" END , CASE  WHEN "END_TIME" IS NULL THEN "PARENT_LINE_CODE" END , CASE  WHEN "END_TIME" IS NULL THEN "RESOURCE_CODE" END )
/

-- [TABLE] OEE_ROUTING
CREATE TABLE "OEE_ROUTING" 
   (	"ROUTING_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"ROUTING_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"ITEM_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"VALID_FROM" DATE NOT NULL ENABLE, 
	"VALID_TO" DATE, 
	"USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(50), 
	"UPDATED_DATE" DATE, 
	 CONSTRAINT "CK_OEE_ROUTING_PROCESS" CHECK (PROCESS_CODE IN ('SMT', 'ASSY')) ENABLE, 
	 CONSTRAINT "CK_OEE_ROUTING_USE" CHECK (USE_YN IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CK_OEE_ROUTING_DATE" CHECK (VALID_TO IS NULL OR VALID_TO >= VALID_FROM) ENABLE, 
	 CONSTRAINT "PK_OEE_ROUTING" PRIMARY KEY ("ROUTING_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_OEE_ROUTING_CODE" UNIQUE ("ORGANIZATION_ID", "ROUTING_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_OEE_ROUTING_ORG_ID" UNIQUE ("ORGANIZATION_ID", "ROUTING_ID")
  USING INDEX  ENABLE
   )
/

-- [INDEX] IX_OEE_ROUTING_ITEM_EFFECTIVE
CREATE INDEX "IX_OEE_ROUTING_ITEM_EFFECTIVE" ON "OEE_ROUTING" ("ORGANIZATION_ID", "ITEM_CODE", "USE_YN", "VALID_FROM", "VALID_TO")
/

-- [TABLE] OEE_ROUTING_PROCESS
CREATE TABLE "OEE_ROUTING_PROCESS" 
   (	"ROUTING_PROCESS_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"ROUTING_ID" NUMBER NOT NULL ENABLE, 
	"PROCESS_SEQ" NUMBER NOT NULL ENABLE, 
	"WORKSTAGE_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"RESOURCE_ID" NUMBER NOT NULL ENABLE, 
	"OUTPUT_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(50), 
	"UPDATED_DATE" DATE, 
	 CONSTRAINT "CK_OEE_RP_SEQ" CHECK (PROCESS_SEQ > 0) ENABLE, 
	 CONSTRAINT "CK_OEE_RP_OUTPUT" CHECK (OUTPUT_YN IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CK_OEE_RP_USE" CHECK (USE_YN IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "PK_OEE_ROUTING_PROCESS" PRIMARY KEY ("ROUTING_PROCESS_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_OEE_ROUTING_PROCESS_SEQ" UNIQUE ("ORGANIZATION_ID", "ROUTING_ID", "PROCESS_SEQ")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_OEE_ROUTING_PROCESS_ORG_ID" UNIQUE ("ORGANIZATION_ID", "ROUTING_PROCESS_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_OEE_ROUTING_PROCESS_ROUTING" FOREIGN KEY ("ORGANIZATION_ID", "ROUTING_ID")
	  REFERENCES "OEE_ROUTING" ("ORGANIZATION_ID", "ROUTING_ID") ENABLE, 
	 CONSTRAINT "FK_OEE_RP_RESOURCE" FOREIGN KEY ("RESOURCE_ID")
	  REFERENCES "OEE_RESOURCE" ("RESOURCE_ID") ENABLE
   )
/

-- [INDEX] IX_OEE_RP_RESOURCE
CREATE INDEX "IX_OEE_RP_RESOURCE" ON "OEE_ROUTING_PROCESS" ("ORGANIZATION_ID", "RESOURCE_ID", "USE_YN")
/

-- [TABLE] OEE_ROUTING_MACHINE
CREATE TABLE "OEE_ROUTING_MACHINE" 
   (	"ORGANIZATION_ID" NUMBER NOT NULL ENABLE, 
	"ROUTING_PROCESS_ID" NUMBER NOT NULL ENABLE, 
	"MACHINE_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"PRIORITY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(50), 
	"UPDATED_DATE" DATE, 
	 CONSTRAINT "CK_OEE_RM_PRIORITY" CHECK (PRIORITY >= 0) ENABLE, 
	 CONSTRAINT "CK_OEE_RM_USE" CHECK (USE_YN IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "PK_OEE_ROUTING_MACHINE" PRIMARY KEY ("ORGANIZATION_ID", "ROUTING_PROCESS_ID", "MACHINE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_OEE_ROUTING_MACHINE_PROCESS" FOREIGN KEY ("ORGANIZATION_ID", "ROUTING_PROCESS_ID")
	  REFERENCES "OEE_ROUTING_PROCESS" ("ORGANIZATION_ID", "ROUTING_PROCESS_ID") ENABLE
   )
/

-- [INDEX] IX_OEE_ROUTING_MACHINE_CODE
CREATE INDEX "IX_OEE_ROUTING_MACHINE_CODE" ON "OEE_ROUTING_MACHINE" ("ORGANIZATION_ID", "MACHINE_CODE", "USE_YN")
/


-- ############ 2단계: 컬럼 추가 · 뷰 교체 ############

-- esh_mes(61.105.35.54/XE) 적용용 — 컬럼 추가분
-- 생성일 2026-09-21 · ESDBPDB와 비교해 대상 DB에 없는 컬럼만 추린 것
-- 대상 테이블에는 이미 데이터가 있으므로 모두 NULL 허용으로 추가한다.

-- [IP_PRODUCT_RUN_CARD] 2개 컬럼 추가
ALTER TABLE IP_PRODUCT_RUN_CARD ADD (MACHINE_CODE VARCHAR2(30))
/
COMMENT ON COLUMN IP_PRODUCT_RUN_CARD.MACHINE_CODE IS '설비코드 (IMCN_MACHINE.MACHINE_CODE)'
/
ALTER TABLE IP_PRODUCT_RUN_CARD ADD (WORKSTAGE_CODE VARCHAR2(10))
/
COMMENT ON COLUMN IP_PRODUCT_RUN_CARD.WORKSTAGE_CODE IS '공정코드 (IP_PRODUCT_WORKSTAGE.WORKSTAGE_CODE)'
/

-- [IP_PRODUCT_SENSOR_ACTUAL] 4개 컬럼 추가
ALTER TABLE IP_PRODUCT_SENSOR_ACTUAL ADD (MACHINE_CODE VARCHAR2(30))
/
COMMENT ON COLUMN IP_PRODUCT_SENSOR_ACTUAL.MACHINE_CODE IS '설비코드 (IMCN_MACHINE.MACHINE_CODE) - 수기 실적 전용, 센서 배치는 NULL'
/
ALTER TABLE IP_PRODUCT_SENSOR_ACTUAL ADD (WORK_TIME NUMBER)
/
COMMENT ON COLUMN IP_PRODUCT_SENSOR_ACTUAL.WORK_TIME IS '작업시간(분) - 수기 실적 전용'
/
ALTER TABLE IP_PRODUCT_SENSOR_ACTUAL ADD (WORKER_NAME VARCHAR2(100))
/
COMMENT ON COLUMN IP_PRODUCT_SENSOR_ACTUAL.WORKER_NAME IS '작업자명 - 수기 실적 전용'
/
ALTER TABLE IP_PRODUCT_SENSOR_ACTUAL ADD (WORKER_COUNT NUMBER)
/
COMMENT ON COLUMN IP_PRODUCT_SENSOR_ACTUAL.WORKER_COUNT IS '작업인원 - 수기 실적 전용'
/

-- [IP_PRODUCT_LINE] 3개 컬럼 추가
ALTER TABLE IP_PRODUCT_LINE ADD (PROCESS_CODE VARCHAR2(20))
/
ALTER TABLE IP_PRODUCT_LINE ADD (RESOURCE_TYPE VARCHAR2(20))
/
ALTER TABLE IP_PRODUCT_LINE ADD (PARENT_LINE_CODE VARCHAR2(20))
/

-- [V_OEE_PLAN_TIME] 뷰 정의가 달라 교체한다 (컬럼 3개 차이)
CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "V_OEE_PLAN_TIME" ("RESOURCE_ID", "ORGANIZATION_ID", "PROCESS_CODE", "WORK_DATE", "SHIFT", "SEGMENT_START_TIME", "SEGMENT_END_TIME", "PLANNED_MINUTES", "PLANNED_STOP_MINUTES", "NET_LOAD_MINUTES") AS 
  WITH dates AS (
  SELECT TRUNC(SYSDATE - (8.5 / 24)) AS WORK_DATE FROM DUAL
  UNION
  SELECT WORK_DATE FROM OEE_PLAN_TIME
  UNION
  SELECT WORK_DATE FROM OEE_PRODUCTION_RESULT
  UNION
  SELECT WORK_DATE FROM OEE_DOWNTIME_EVENT
), shift_windows AS (
  SELECT 'DAY' AS SHIFT,
         '08:30:00' AS START_CLOCK,
         '17:30:00' AS END_CLOCK,
         0 AS START_OFFSET,
         0 AS END_OFFSET
    FROM DUAL
  UNION ALL
  SELECT 'NIGHT',
         '20:30:00',
         '05:30:00',
         0,
         1
    FROM DUAL
), segments AS (
  SELECT r.RESOURCE_ID, r.ORGANIZATION_ID, r.PROCESS_CODE, d.WORK_DATE, w.SHIFT,
          CAST(d.WORK_DATE AS TIMESTAMP)
            + NUMTODSINTERVAL(w.START_OFFSET, 'DAY')
            + NUMTODSINTERVAL(
                TO_NUMBER(SUBSTR(w.START_CLOCK, 1, 2)) * 3600
                  + TO_NUMBER(SUBSTR(w.START_CLOCK, 4, 2)) * 60
                  + TO_NUMBER(SUBSTR(w.START_CLOCK, 7, 2)),
                'SECOND'
              ) AS SEGMENT_START_TIME,
          CAST(d.WORK_DATE AS TIMESTAMP)
            + NUMTODSINTERVAL(w.END_OFFSET, 'DAY')
            + NUMTODSINTERVAL(
                TO_NUMBER(SUBSTR(w.END_CLOCK, 1, 2)) * 3600
                  + TO_NUMBER(SUBSTR(w.END_CLOCK, 4, 2)) * 60
                  + TO_NUMBER(SUBSTR(w.END_CLOCK, 7, 2)),
                'SECOND'
              ) AS SEGMENT_END_TIME
     FROM OEE_RESOURCE r
     CROSS JOIN dates d
     CROSS JOIN shift_windows w
    WHERE r.USE_YN = 'Y'
      AND r.PROCESS_CODE IN ('SMT', 'ASSY')
      AND r.RESOURCE_TYPE IN ('LINE', 'CELL')
)
SELECT s.RESOURCE_ID, s.ORGANIZATION_ID, s.PROCESS_CODE, s.WORK_DATE, s.SHIFT,
       s.SEGMENT_START_TIME, s.SEGMENT_END_TIME,
       NVL(ov.PLANNED_MINUTES,
         540) AS PLANNED_MINUTES,
       NVL(ov.PLANNED_STOP_MINUTES, 60) AS PLANNED_STOP_MINUTES,
       NVL(ov.NET_LOAD_MINUTES, 480) AS NET_LOAD_MINUTES
  FROM segments s
  LEFT JOIN OEE_PLAN_TIME ov
    ON ov.RESOURCE_ID = s.RESOURCE_ID
   AND ov.ORGANIZATION_ID = s.ORGANIZATION_ID
   AND ov.WORK_DATE = s.WORK_DATE
   AND ov.SHIFT = s.SHIFT
   AND ov.OVERRIDE_YN = 'Y'
 WHERE s.SEGMENT_END_TIME > s.SEGMENT_START_TIME
/
