-- One-time bootstrap only. Routine deployment must not overwrite user-managed OEE resources.
DECLARE
BEGIN
  MERGE INTO OEE_RESOURCE target
  USING (
    SELECT l.ORGANIZATION_ID, 'SMT' PROCESS_CODE, 'LINE' RESOURCE_TYPE,
           l.LINE_CODE REF_CODE, l.LINE_NAME RESOURCE_NAME, NVL(l.MES_DISPLAY_SEQUENCE, TO_NUMBER(l.LINE_CODE)) SORT_ORDER
      FROM IP_PRODUCT_LINE l
     WHERE l.ORGANIZATION_ID = 1
       AND l.LINE_CODE IN ('01','02','03','04','05','06','07','08','09','10','11','12')
    UNION ALL
    SELECT l.ORGANIZATION_ID, 'ASSY', 'LINE', l.LINE_CODE, l.LINE_NAME,
           NVL(l.MES_DISPLAY_SEQUENCE, TO_NUMBER(l.LINE_CODE))
      FROM IP_PRODUCT_LINE l
     WHERE l.ORGANIZATION_ID = 1
       AND l.LINE_CODE IN ('19','20','21','22','23','24')
  ) source
  ON (target.ORGANIZATION_ID = source.ORGANIZATION_ID
      AND target.PROCESS_CODE = source.PROCESS_CODE
      AND target.RESOURCE_TYPE = source.RESOURCE_TYPE
      AND target.REF_CODE = source.REF_CODE)
  WHEN MATCHED THEN UPDATE SET target.RESOURCE_NAME = source.RESOURCE_NAME,
    target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = 'Y'
  WHEN NOT MATCHED THEN INSERT
    (ORGANIZATION_ID, PROCESS_CODE, RESOURCE_TYPE, REF_CODE, RESOURCE_NAME, IDEAL_CT, USE_YN, SORT_ORDER)
  VALUES
    (source.ORGANIZATION_ID, source.PROCESS_CODE, source.RESOURCE_TYPE, source.REF_CODE,
     source.RESOURCE_NAME, NULL, 'Y', source.SORT_ORDER);

  UPDATE OEE_RESOURCE target
     SET target.USE_YN = 'N'
   WHERE target.ORGANIZATION_ID = 1
     AND target.PROCESS_CODE IN ('SMT', 'ASSY')
     AND NOT EXISTS (
       SELECT 1
         FROM IP_PRODUCT_LINE source
        WHERE source.ORGANIZATION_ID = target.ORGANIZATION_ID
          AND source.LINE_CODE = target.REF_CODE
          AND ((target.PROCESS_CODE = 'SMT' AND source.LINE_CODE IN ('01','02','03','04','05','06','07','08','09','10','11','12'))
            OR (target.PROCESS_CODE = 'ASSY' AND source.LINE_CODE IN ('19','20','21','22','23','24')))
     );

  COMMIT;
END;
/
