DECLARE
  v_event_count NUMBER;
  v_fact_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_event_count
    FROM OEE_DOWNTIME_EVENT
   WHERE EVENT_ID = 22
     AND PROCESS_CODE = 'ASSY'
     AND RESOURCE_CODE = '50'
     AND START_REQUEST_ID = '819bf9a0-2bd9-43c9-9cf6-677305ff40f5'
     AND END_REQUEST_ID = 'df5b76cc-1d08-41e4-911e-3af901844c76';

  SELECT
    (SELECT COUNT(*) FROM OEE_OPERATION_LOG x JOIN OEE_RESOURCE r ON r.RESOURCE_ID=x.RESOURCE_ID
      WHERE r.PROCESS_CODE='ASSY' AND r.REF_CODE BETWEEN '50' AND '64')
    + (SELECT COUNT(*) FROM OEE_PLAN_TIME x JOIN OEE_RESOURCE r ON r.RESOURCE_ID=x.RESOURCE_ID
      WHERE r.PROCESS_CODE='ASSY' AND r.REF_CODE BETWEEN '50' AND '64')
    + (SELECT COUNT(*) FROM OEE_PRODUCTION_RESULT x JOIN OEE_RESOURCE r ON r.RESOURCE_ID=x.RESOURCE_ID
      WHERE r.PROCESS_CODE='ASSY' AND r.REF_CODE BETWEEN '50' AND '64')
    + (SELECT COUNT(*) FROM OEE_DAILY_SUMMARY x JOIN OEE_RESOURCE r ON r.RESOURCE_ID=x.RESOURCE_ID
      WHERE r.PROCESS_CODE='ASSY' AND r.REF_CODE BETWEEN '50' AND '64')
    INTO v_fact_count
    FROM DUAL;

  IF v_event_count <> 1 OR v_fact_count <> 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Unexpected OEE data exists for unapproved resources 50-64');
  END IF;

  DELETE FROM OEE_DOWNTIME_EVENT
   WHERE EVENT_ID = 22
     AND START_REQUEST_ID = '819bf9a0-2bd9-43c9-9cf6-677305ff40f5'
     AND END_REQUEST_ID = 'df5b76cc-1d08-41e4-911e-3af901844c76';

  DELETE FROM OEE_RESOURCE
   WHERE ORGANIZATION_ID = 1
     AND PROCESS_CODE = 'ASSY'
     AND RESOURCE_TYPE = 'CELL'
     AND REF_CODE BETWEEN '50' AND '64';

  COMMIT;
END;
/
