-- 의뢰검사 입력(QC_REQUEST_INSPECT) · 자주검사 이력(QC_SELF_INSPECT_HISTORY) 메뉴 등록
-- 두 메뉴는 menuConfig(QUALITY 카테고리)에 정의되어 있으나 MENU_CATEGORY_ITEMS에 미배정이라
-- 사이드바(/menu-categories/tree 기준 렌더)에 표시되지 않았다. QUALITY 카테고리에 배정한다.
-- QUALITY 기존 SORT_ORDER: QC_IQC(10)~QC_REWORK_INSPECT(60) → 신규는 70/80에 배치.
-- 경로/라벨은 프론트 menuConfig에서 매핑(QC_REQUEST_INSPECT → /quality/request-inspect,
-- QC_SELF_INSPECT_HISTORY → /quality/self-inspect-history).
-- 실행: oracle_connector.py --execute-file (블록 구분자 '/' 사용)

-- 메뉴 항목 (CREATED_BY/UPDATED_BY NOT NULL)
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'QC_REQUEST_INSPECT', 'QUALITY', 70, '40', '1000', 'system', 'system' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM MENU_CATEGORY_ITEMS WHERE MENU_CODE='QC_REQUEST_INSPECT' AND COMPANY='40' AND PLANT_CD='1000'
);
/

INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'QC_SELF_INSPECT_HISTORY', 'QUALITY', 80, '40', '1000', 'system', 'system' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM MENU_CATEGORY_ITEMS WHERE MENU_CODE='QC_SELF_INSPECT_HISTORY' AND COMPANY='40' AND PLANT_CD='1000'
);
/

-- 권한 (다수 품질 메뉴와 동일: MANAGER, OPERATOR)
INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'MANAGER', 'QC_REQUEST_INSPECT', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='MANAGER' AND MENU_CODE='QC_REQUEST_INSPECT' AND COMPANY='40' AND PLANT_CD='1000'
);
/

INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'OPERATOR', 'QC_REQUEST_INSPECT', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='OPERATOR' AND MENU_CODE='QC_REQUEST_INSPECT' AND COMPANY='40' AND PLANT_CD='1000'
);
/

INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'MANAGER', 'QC_SELF_INSPECT_HISTORY', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='MANAGER' AND MENU_CODE='QC_SELF_INSPECT_HISTORY' AND COMPANY='40' AND PLANT_CD='1000'
);
/

INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'OPERATOR', 'QC_SELF_INSPECT_HISTORY', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='OPERATOR' AND MENU_CODE='QC_SELF_INSPECT_HISTORY' AND COMPANY='40' AND PLANT_CD='1000'
);
/
