DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'PALLET_MASTERS'
     AND COLUMN_NAME = 'SHIP_ORDER_NO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PALLET_MASTERS ADD (SHIP_ORDER_NO VARCHAR2(50))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IX_PALLET_SHIP_ORDER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_PALLET_SHIP_ORDER ON PALLET_MASTERS (COMPANY, PLANT_CD, SHIP_ORDER_NO)';
  END IF;
END;
/
