-- 기타출고요청 메뉴 등록 (MAT_REQUEST_OTHER)
-- 작업지시 기반 출고요청(MAT_REQUEST)과 분리해 작업지시 없는 ISSUE_TYPE=MANUAL 요청만 관리한다.
-- 경로/라벨은 프론트 menuConfig(MAT_REQUEST_OTHER → /material/request-other, menu.material.requestOther).
-- 실행: oracle_connector.py --site JSHANES --execute-file apps/backend/src/migrations/2026-06-30_request_other_menu_seed.sql

INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'MAT_REQUEST_OTHER', 'MATERIAL', 87, '40', '1000', 'system', 'system' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM MENU_CATEGORY_ITEMS WHERE MENU_CODE='MAT_REQUEST_OTHER' AND COMPANY='40' AND PLANT_CD='1000'
);
/

INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'MANAGER', 'MAT_REQUEST_OTHER', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='MANAGER' AND MENU_CODE='MAT_REQUEST_OTHER' AND COMPANY='40' AND PLANT_CD='1000'
);
/
