-- Seed packable FG labels for /shipping/pack.
-- Target: JSHANES / company 40 / plant 1000
-- Scenario: pack N91H00-X9800 into BX2606260001.

MERGE INTO BOX_MASTERS dst
USING (
  SELECT 'BX2606260001' AS BOX_NO,
         'N91H00-X9800' AS ITEM_CODE,
         '40' AS COMPANY,
         '1000' AS PLANT_CD
    FROM DUAL
) src
ON (
  dst.BOX_NO = src.BOX_NO
  AND dst.COMPANY = src.COMPANY
  AND dst.PLANT_CD = src.PLANT_CD
)
WHEN NOT MATCHED THEN
  INSERT (
    BOX_NO, ITEM_CODE, QTY, SERIAL_LIST, PALLET_NO, STATUS, OQC_STATUS,
    SHIP_ORDER_NO, SHIPPED_AT, CLOSE_TIME,
    COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
  ) VALUES (
    src.BOX_NO, src.ITEM_CODE, 0, NULL, NULL, 'OPEN', NULL,
    NULL, NULL, NULL,
    src.COMPANY, src.PLANT_CD, 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
  )
WHEN MATCHED THEN
  UPDATE SET
    dst.ITEM_CODE = CASE
      WHEN NVL(dst.QTY, 0) = 0 AND dst.SERIAL_LIST IS NULL AND dst.SHIP_ORDER_NO IS NULL AND dst.SHIPPED_AT IS NULL
      THEN src.ITEM_CODE ELSE dst.ITEM_CODE END,
    dst.STATUS = CASE
      WHEN NVL(dst.QTY, 0) = 0 AND dst.SERIAL_LIST IS NULL AND dst.SHIP_ORDER_NO IS NULL AND dst.SHIPPED_AT IS NULL
      THEN 'OPEN' ELSE dst.STATUS END,
    dst.OQC_STATUS = CASE
      WHEN NVL(dst.QTY, 0) = 0 AND dst.SERIAL_LIST IS NULL AND dst.SHIP_ORDER_NO IS NULL AND dst.SHIPPED_AT IS NULL
      THEN NULL ELSE dst.OQC_STATUS END,
    dst.PALLET_NO = CASE
      WHEN NVL(dst.QTY, 0) = 0 AND dst.SERIAL_LIST IS NULL AND dst.SHIP_ORDER_NO IS NULL AND dst.SHIPPED_AT IS NULL
      THEN NULL ELSE dst.PALLET_NO END,
    dst.UPDATED_BY = 'seed',
    dst.UPDATED_AT = SYSTIMESTAMP
/

MERGE INTO FG_LABELS dst
USING (
  SELECT 'FG-N91-X9800-001' AS FG_BARCODE FROM DUAL UNION ALL
  SELECT 'FG-N91-X9800-002' AS FG_BARCODE FROM DUAL UNION ALL
  SELECT 'FG-N91-X9800-003' AS FG_BARCODE FROM DUAL UNION ALL
  SELECT 'FG-N91-X9800-004' AS FG_BARCODE FROM DUAL UNION ALL
  SELECT 'FG-N91-X9800-005' AS FG_BARCODE FROM DUAL
) src
ON (dst.FG_BARCODE = src.FG_BARCODE)
WHEN NOT MATCHED THEN
  INSERT (
    FG_BARCODE, ITEM_CODE, ORDER_NO, EQUIP_CODE, WORKER_CODE, LINE_CODE,
    ISSUED_AT, STATUS, REPRINT_COUNT, VOID_REASON, REPLACED_BY,
    CUSTOMER_BARCODE, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY,
    CREATED_AT, UPDATED_AT, INSPECT_PASS_YN, INSPECT_RESULT_ID, BOX_NO, STRUCTURE_YN
  ) VALUES (
    src.FG_BARCODE, 'N91H00-X9800', 'WO-SEED-N91-X9800', NULL, NULL, NULL,
    SYSTIMESTAMP, 'VISUAL_PASS', 0, NULL, NULL,
    NULL, '40', '1000', 'seed', 'seed',
    SYSTIMESTAMP, SYSTIMESTAMP, 'Y', NULL, NULL, 'Y'
  )
WHEN MATCHED THEN
  UPDATE SET
    dst.ITEM_CODE = CASE WHEN dst.BOX_NO IS NULL THEN 'N91H00-X9800' ELSE dst.ITEM_CODE END,
    dst.STATUS = CASE WHEN dst.BOX_NO IS NULL THEN 'VISUAL_PASS' ELSE dst.STATUS END,
    dst.INSPECT_PASS_YN = CASE WHEN dst.BOX_NO IS NULL THEN 'Y' ELSE dst.INSPECT_PASS_YN END,
    dst.COMPANY = CASE WHEN dst.BOX_NO IS NULL THEN '40' ELSE dst.COMPANY END,
    dst.PLANT_CD = CASE WHEN dst.BOX_NO IS NULL THEN '1000' ELSE dst.PLANT_CD END,
    dst.UPDATED_BY = 'seed',
    dst.UPDATED_AT = SYSTIMESTAMP
/
