-- 자재재고실사반영 메뉴 등록 (INV_MAT_PHYSICAL_INV_APPLY)
-- 자재재고실사관리(INV_MAT_PHYSICAL_INV, INVENTORY/30) 바로 뒤(35)에 배치.
-- 경로/라벨은 프론트 menuConfig(INV_MAT_PHYSICAL_INV_APPLY → /inventory/material-physical-inv-apply, menu.inventory.matPhysicalInvApply).
-- 실사등록(세션관리+모니터링)과 실사반영(수량입력+재고반영) 워크플로우 분리 목적.

-- 메뉴 항목
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'INV_MAT_PHYSICAL_INV_APPLY', 'INVENTORY', 35, '40', '1000', 'system', 'system' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM MENU_CATEGORY_ITEMS WHERE MENU_CODE='INV_MAT_PHYSICAL_INV_APPLY' AND COMPANY='40' AND PLANT_CD='1000'
);

-- 권한 (INV_MAT_PHYSICAL_INV와 동일: MANAGER)
INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'MANAGER', 'INV_MAT_PHYSICAL_INV_APPLY', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='MANAGER' AND MENU_CODE='INV_MAT_PHYSICAL_INV_APPLY' AND COMPANY='40' AND PLANT_CD='1000'
);
