DECLARE
  v_count NUMBER;
BEGIN
  -- 2026-06-16 입하재고/입고재고 분리.
  -- 실행: python C:/Users/hsyou/.codex/skills/oracle-db/scripts/oracle_connector.py --site JSHANES --execute-file apps/backend/src/migrations/2026-06-16_mat_arrival_stock_split.sql
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'MAT_ARRIVAL_STOCKS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE MAT_ARRIVAL_STOCKS (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        MAT_UID VARCHAR2(50) NOT NULL,
        ARRIVAL_NO VARCHAR2(50),
        ARRIVAL_SEQ NUMBER,
        WAREHOUSE_CODE VARCHAR2(50) NOT NULL,
        ITEM_CODE VARCHAR2(50) NOT NULL,
        QTY NUMBER DEFAULT 0 NOT NULL,
        AVAILABLE_QTY NUMBER DEFAULT 0 NOT NULL,
        STATUS VARCHAR2(20) DEFAULT ''AVAILABLE'' NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_MAT_ARRIVAL_STOCKS PRIMARY KEY (COMPANY, PLANT_CD, MAT_UID),
        CONSTRAINT CK_MAT_ARRIVAL_STOCK_QTY CHECK (QTY >= 0 AND AVAILABLE_QTY >= 0 AND AVAILABLE_QTY <= QTY)
      )';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'MAT_ARRIVAL_TRANSACTIONS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE MAT_ARRIVAL_TRANSACTIONS (
        TRANS_NO VARCHAR2(50) NOT NULL,
        TRANS_TYPE VARCHAR2(50) NOT NULL,
        TRANS_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        ARRIVAL_NO VARCHAR2(50),
        ARRIVAL_SEQ NUMBER,
        WAREHOUSE_CODE VARCHAR2(50),
        ITEM_CODE VARCHAR2(50) NOT NULL,
        MAT_UID VARCHAR2(50) NOT NULL,
        QTY NUMBER NOT NULL,
        UNIT_PRICE NUMBER(12,4),
        TOTAL_AMOUNT NUMBER(14,2),
        REF_TYPE VARCHAR2(50),
        REF_ID VARCHAR2(50),
        CANCEL_REF_ID VARCHAR2(50),
        WORKER_ID VARCHAR2(50),
        REMARK VARCHAR2(500),
        STATUS VARCHAR2(20) DEFAULT ''DONE'' NOT NULL,
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_MAT_ARRIVAL_TRANSACTIONS PRIMARY KEY (TRANS_NO)
      )';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_MAT_ARR_STOCK_ITEM';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MAT_ARR_STOCK_ITEM ON MAT_ARRIVAL_STOCKS (COMPANY, PLANT_CD, ITEM_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_MAT_ARR_STOCK_WH';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MAT_ARR_STOCK_WH ON MAT_ARRIVAL_STOCKS (COMPANY, PLANT_CD, WAREHOUSE_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_MAT_ARR_TX_DATE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MAT_ARR_TX_DATE ON MAT_ARRIVAL_TRANSACTIONS (TRANS_DATE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_MAT_ARR_TX_REF';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MAT_ARR_TX_REF ON MAT_ARRIVAL_TRANSACTIONS (REF_TYPE, REF_ID)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_MAT_ARR_TX_UID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MAT_ARR_TX_UID ON MAT_ARRIVAL_TRANSACTIONS (COMPANY, PLANT_CD, MAT_UID)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'STOCK_TRANSACTIONS_BAK_20260616';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE STOCK_TRANSACTIONS_BAK_20260616 AS SELECT * FROM STOCK_TRANSACTIONS WHERE 1 = 0';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'MAT_STOCKS_BAK_20260616';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE MAT_STOCKS_BAK_20260616 AS SELECT * FROM MAT_STOCKS WHERE 1 = 0';
  END IF;
END;
/

DECLARE
  v_null_uid_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_null_uid_count
    FROM STOCK_TRANSACTIONS
   WHERE TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL')
     AND MAT_UID IS NULL;

  IF v_null_uid_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20951, 'MAT_UID 없는 입하 원장이 있어 입하재고 분리 마이그레이션을 중단합니다.');
  END IF;
END;
/

INSERT INTO STOCK_TRANSACTIONS_BAK_20260616
SELECT st.*
  FROM STOCK_TRANSACTIONS st
 WHERE st.TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL')
   AND NOT EXISTS (
         SELECT 1
           FROM STOCK_TRANSACTIONS_BAK_20260616 b
          WHERE b.TRANS_NO = st.TRANS_NO
       );
/

INSERT INTO MAT_ARRIVAL_TRANSACTIONS (
  TRANS_NO,
  TRANS_TYPE,
  TRANS_DATE,
  ARRIVAL_NO,
  ARRIVAL_SEQ,
  WAREHOUSE_CODE,
  ITEM_CODE,
  MAT_UID,
  QTY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  REF_TYPE,
  REF_ID,
  CANCEL_REF_ID,
  WORKER_ID,
  REMARK,
  STATUS,
  COMPANY,
  PLANT_CD,
  CREATED_BY,
  UPDATED_BY,
  CREATED_AT,
  UPDATED_AT
)
SELECT st.TRANS_NO,
       CASE st.TRANS_TYPE
         WHEN 'MAT_IN' THEN 'ARRIVAL_IN'
         WHEN 'MAT_IN_CANCEL' THEN 'ARRIVAL_CANCEL'
         ELSE st.TRANS_TYPE
       END AS TRANS_TYPE,
       st.TRANS_DATE,
       ml.ARRIVAL_NO,
       ml.ARRIVAL_SEQ,
       COALESCE(st.TO_WAREHOUSE_ID, st.FROM_WAREHOUSE_ID) AS WAREHOUSE_CODE,
       st.ITEM_CODE,
       st.MAT_UID,
       st.QTY,
       st.UNIT_PRICE,
       st.TOTAL_AMOUNT,
       st.REF_TYPE,
       st.REF_ID,
       st.CANCEL_REF_ID,
       st.WORKER_ID,
       st.REMARK,
       st.STATUS,
       st.COMPANY,
       st.PLANT_CD,
       st.CREATED_BY,
       st.UPDATED_BY,
       st.CREATED_AT,
       st.UPDATED_AT
  FROM STOCK_TRANSACTIONS st
  LEFT JOIN MAT_LOTS ml
    ON ml.COMPANY = st.COMPANY
   AND ml.PLANT_CD = st.PLANT_CD
   AND ml.MAT_UID = st.MAT_UID
 WHERE st.TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL')
   AND st.MAT_UID IS NOT NULL
   AND NOT EXISTS (
         SELECT 1
           FROM MAT_ARRIVAL_TRANSACTIONS atx
          WHERE atx.TRANS_NO = st.TRANS_NO
       );
/

INSERT INTO MAT_STOCKS_BAK_20260616
SELECT ms.*
  FROM MAT_STOCKS ms
 WHERE EXISTS (
       WITH tx AS (
         SELECT COMPANY,
                PLANT_CD,
                ITEM_CODE,
                MAT_UID,
                SUM(CASE WHEN TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL') THEN QTY ELSE 0 END) AS ARRIVAL_QTY,
                SUM(CASE WHEN TRANS_TYPE = 'RECEIVE' THEN QTY ELSE 0 END) AS RECEIVE_QTY
           FROM STOCK_TRANSACTIONS
          WHERE TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL', 'RECEIVE')
            AND MAT_UID IS NOT NULL
          GROUP BY COMPANY, PLANT_CD, ITEM_CODE, MAT_UID
       ),
       pending AS (
         SELECT COMPANY,
                PLANT_CD,
                ITEM_CODE,
                MAT_UID,
                ARRIVAL_QTY - RECEIVE_QTY AS PENDING_QTY
           FROM tx
          WHERE ARRIVAL_QTY - RECEIVE_QTY > 0
       ),
       ranked_stock AS (
         SELECT COMPANY,
                PLANT_CD,
                WAREHOUSE_CODE,
                ITEM_CODE,
                MAT_UID,
                QTY,
                AVAILABLE_QTY,
                ROW_NUMBER() OVER (
                  PARTITION BY COMPANY, PLANT_CD, ITEM_CODE, MAT_UID
                  ORDER BY QTY DESC, AVAILABLE_QTY DESC, WAREHOUSE_CODE
                ) AS RN
           FROM MAT_STOCKS
          WHERE QTY > 0
            AND AVAILABLE_QTY > 0
       ),
       candidates AS (
         SELECT p.COMPANY,
                p.PLANT_CD,
                rs.WAREHOUSE_CODE,
                p.ITEM_CODE,
                p.MAT_UID,
                LEAST(p.PENDING_QTY, rs.QTY, rs.AVAILABLE_QTY) AS SAFE_QTY
           FROM pending p
           JOIN ranked_stock rs
             ON rs.COMPANY = p.COMPANY
            AND rs.PLANT_CD = p.PLANT_CD
            AND rs.ITEM_CODE = p.ITEM_CODE
            AND rs.MAT_UID = p.MAT_UID
            AND rs.RN = 1
       )
       SELECT 1
         FROM candidates c
        WHERE c.SAFE_QTY > 0
          AND c.COMPANY = ms.COMPANY
          AND c.PLANT_CD = ms.PLANT_CD
          AND c.WAREHOUSE_CODE = ms.WAREHOUSE_CODE
          AND c.ITEM_CODE = ms.ITEM_CODE
          AND c.MAT_UID = ms.MAT_UID
     )
   AND NOT EXISTS (
         SELECT 1
           FROM MAT_STOCKS_BAK_20260616 b
          WHERE b.COMPANY = ms.COMPANY
            AND b.PLANT_CD = ms.PLANT_CD
            AND b.WAREHOUSE_CODE = ms.WAREHOUSE_CODE
            AND b.ITEM_CODE = ms.ITEM_CODE
            AND b.MAT_UID = ms.MAT_UID
       );
/

INSERT INTO MAT_ARRIVAL_STOCKS (
  COMPANY,
  PLANT_CD,
  MAT_UID,
  ARRIVAL_NO,
  ARRIVAL_SEQ,
  WAREHOUSE_CODE,
  ITEM_CODE,
  QTY,
  AVAILABLE_QTY,
  STATUS,
  CREATED_BY,
  UPDATED_BY,
  CREATED_AT,
  UPDATED_AT
)
WITH tx AS (
  SELECT COMPANY,
         PLANT_CD,
         ITEM_CODE,
         MAT_UID,
         SUM(CASE WHEN TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL') THEN QTY ELSE 0 END) AS ARRIVAL_QTY,
         SUM(CASE WHEN TRANS_TYPE = 'RECEIVE' THEN QTY ELSE 0 END) AS RECEIVE_QTY
    FROM STOCK_TRANSACTIONS
   WHERE TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL', 'RECEIVE')
     AND MAT_UID IS NOT NULL
   GROUP BY COMPANY, PLANT_CD, ITEM_CODE, MAT_UID
),
pending AS (
  SELECT COMPANY,
         PLANT_CD,
         ITEM_CODE,
         MAT_UID,
         ARRIVAL_QTY - RECEIVE_QTY AS PENDING_QTY
    FROM tx
   WHERE ARRIVAL_QTY - RECEIVE_QTY > 0
),
ranked_stock AS (
  SELECT COMPANY,
         PLANT_CD,
         WAREHOUSE_CODE,
         ITEM_CODE,
         MAT_UID,
         QTY,
         AVAILABLE_QTY,
         ROW_NUMBER() OVER (
           PARTITION BY COMPANY, PLANT_CD, ITEM_CODE, MAT_UID
           ORDER BY QTY DESC, AVAILABLE_QTY DESC, WAREHOUSE_CODE
         ) AS RN
    FROM MAT_STOCKS
   WHERE QTY > 0
     AND AVAILABLE_QTY > 0
),
candidates AS (
  SELECT p.COMPANY,
         p.PLANT_CD,
         p.ITEM_CODE,
         p.MAT_UID,
         rs.WAREHOUSE_CODE,
         LEAST(p.PENDING_QTY, rs.QTY, rs.AVAILABLE_QTY) AS SAFE_QTY
    FROM pending p
    JOIN ranked_stock rs
      ON rs.COMPANY = p.COMPANY
     AND rs.PLANT_CD = p.PLANT_CD
     AND rs.ITEM_CODE = p.ITEM_CODE
     AND rs.MAT_UID = p.MAT_UID
     AND rs.RN = 1
)
SELECT c.COMPANY,
       c.PLANT_CD,
       c.MAT_UID,
       ml.ARRIVAL_NO,
       ml.ARRIVAL_SEQ,
       c.WAREHOUSE_CODE,
       c.ITEM_CODE,
       c.SAFE_QTY,
       c.SAFE_QTY,
       'AVAILABLE',
       'arrival-split-migration',
       'arrival-split-migration',
       SYSTIMESTAMP,
       SYSTIMESTAMP
  FROM candidates c
  LEFT JOIN MAT_LOTS ml
    ON ml.COMPANY = c.COMPANY
   AND ml.PLANT_CD = c.PLANT_CD
   AND ml.MAT_UID = c.MAT_UID
 WHERE c.SAFE_QTY > 0
   AND NOT EXISTS (
         SELECT 1
           FROM MAT_ARRIVAL_STOCKS mas
          WHERE mas.COMPANY = c.COMPANY
            AND mas.PLANT_CD = c.PLANT_CD
            AND mas.MAT_UID = c.MAT_UID
       );
/

MERGE INTO MAT_STOCKS ms
USING (
  WITH tx AS (
    SELECT COMPANY,
           PLANT_CD,
           ITEM_CODE,
           MAT_UID,
           SUM(CASE WHEN TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL') THEN QTY ELSE 0 END) AS ARRIVAL_QTY,
           SUM(CASE WHEN TRANS_TYPE = 'RECEIVE' THEN QTY ELSE 0 END) AS RECEIVE_QTY
      FROM STOCK_TRANSACTIONS
     WHERE TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL', 'RECEIVE')
       AND MAT_UID IS NOT NULL
     GROUP BY COMPANY, PLANT_CD, ITEM_CODE, MAT_UID
  ),
  pending AS (
    SELECT COMPANY,
           PLANT_CD,
           ITEM_CODE,
           MAT_UID,
           ARRIVAL_QTY - RECEIVE_QTY AS PENDING_QTY
      FROM tx
     WHERE ARRIVAL_QTY - RECEIVE_QTY > 0
  ),
  ranked_stock AS (
    SELECT COMPANY,
           PLANT_CD,
           WAREHOUSE_CODE,
           ITEM_CODE,
           MAT_UID,
           QTY,
           AVAILABLE_QTY,
           ROW_NUMBER() OVER (
             PARTITION BY COMPANY, PLANT_CD, ITEM_CODE, MAT_UID
             ORDER BY QTY DESC, AVAILABLE_QTY DESC, WAREHOUSE_CODE
           ) AS RN
      FROM MAT_STOCKS
     WHERE QTY > 0
       AND AVAILABLE_QTY > 0
  )
  SELECT p.COMPANY,
         p.PLANT_CD,
         rs.WAREHOUSE_CODE,
         p.ITEM_CODE,
         p.MAT_UID,
         LEAST(p.PENDING_QTY, rs.QTY, rs.AVAILABLE_QTY) AS SAFE_QTY
    FROM pending p
    JOIN ranked_stock rs
      ON rs.COMPANY = p.COMPANY
     AND rs.PLANT_CD = p.PLANT_CD
     AND rs.ITEM_CODE = p.ITEM_CODE
     AND rs.MAT_UID = p.MAT_UID
     AND rs.RN = 1
) c
ON (
  ms.COMPANY = c.COMPANY
  AND ms.PLANT_CD = c.PLANT_CD
  AND ms.WAREHOUSE_CODE = c.WAREHOUSE_CODE
  AND ms.ITEM_CODE = c.ITEM_CODE
  AND ms.MAT_UID = c.MAT_UID
)
WHEN MATCHED THEN UPDATE SET
  ms.QTY = ms.QTY - c.SAFE_QTY,
  ms.AVAILABLE_QTY = ms.AVAILABLE_QTY - c.SAFE_QTY,
  ms.UPDATED_BY = 'arrival-split-migration',
  ms.UPDATED_AT = SYSTIMESTAMP
WHERE c.SAFE_QTY > 0;
/

DELETE FROM MAT_STOCKS ms
 WHERE ms.QTY = 0
   AND ms.AVAILABLE_QTY = 0
   AND NVL(ms.RESERVED_QTY, 0) = 0
   AND EXISTS (
       SELECT 1
         FROM MAT_STOCKS_BAK_20260616 b
        WHERE b.COMPANY = ms.COMPANY
          AND b.PLANT_CD = ms.PLANT_CD
          AND b.WAREHOUSE_CODE = ms.WAREHOUSE_CODE
          AND b.ITEM_CODE = ms.ITEM_CODE
          AND b.MAT_UID = ms.MAT_UID
     );
/

DELETE FROM STOCK_TRANSACTIONS st
 WHERE st.TRANS_TYPE IN ('MAT_IN', 'MAT_IN_CANCEL')
   AND EXISTS (
       SELECT 1
         FROM MAT_ARRIVAL_TRANSACTIONS atx
        WHERE atx.TRANS_NO = st.TRANS_NO
     );
/

COMMIT;
/
