MERGE INTO COM_CODES t
USING (
  SELECT 'TRANSACTION_TYPE' AS GROUP_CODE,
         'DEFECT_IN' AS DETAIL_CODE,
         '불량창고입고' AS CODE_NAME,
         24 AS SORT_ORDER,
         'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300' AS ATTR1,
         '40' AS COMPANY,
         '1000' AS PLANT_CD
    FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN MATCHED THEN
  UPDATE SET t.CODE_NAME = s.CODE_NAME,
             t.SORT_ORDER = s.SORT_ORDER,
             t.USE_YN = 'Y',
             t.ATTR1 = s.ATTR1,
             t.UPDATED_BY = 'codex',
             t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, ATTR1, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES (s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y', s.ATTR1, s.COMPANY, s.PLANT_CD, 'codex', 'codex');
/

MERGE INTO COM_CODES t
USING (
  SELECT 'TRANSACTION_TYPE' AS GROUP_CODE,
         'DEFECT_IN_CANCEL' AS DETAIL_CODE,
         '불량창고입고취소' AS CODE_NAME,
         25 AS SORT_ORDER,
         'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300' AS ATTR1,
         '40' AS COMPANY,
         '1000' AS PLANT_CD
    FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN MATCHED THEN
  UPDATE SET t.CODE_NAME = s.CODE_NAME,
             t.SORT_ORDER = s.SORT_ORDER,
             t.USE_YN = 'Y',
             t.ATTR1 = s.ATTR1,
             t.UPDATED_BY = 'codex',
             t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, ATTR1, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES (s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y', s.ATTR1, s.COMPANY, s.PLANT_CD, 'codex', 'codex');
/
