-- PALLET_MASTERS.SHIPPED_TIME: 출하 확정 시각 컬럼 추가
-- SHIPPED 상태로 전환될 때 기록 (markAsShipped)
ALTER TABLE PALLET_MASTERS ADD SHIPPED_TIME TIMESTAMP;
COMMENT ON COLUMN PALLET_MASTERS.SHIPPED_TIME IS '출하 확정 시각 (LOADED→SHIPPED 전환 시 기록)';
