-- EQUIP_INSPECT_ITEM_MASTERS 시드 데이터
-- 설비유형별 점검항목 기준 마스터
-- COMPANY='40', PLANT_CD='1000'
-- INSPECT_TYPE: DAILY/PERIODIC/PM/WORKER

-- ─────────────────────────────────────────────
-- 공통 (NULL 설비유형) — 전 설비 공통 일상점검
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-CMN-001','전원 공급 정상 여부 확인','DAILY',NULL,'VISUAL','정상 점등, 이상 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-CMN-002','비상 정지 버튼 동작 확인','DAILY',NULL,'VISUAL','버튼 작동 정상, 미잠금','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-CMN-003','안전 커버·가드 체결 상태','DAILY',NULL,'VISUAL','고정 볼트 이완 없음, 커버 파손 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-CMN-004','구동부 이물질·오염 점검','DAILY',NULL,'VISUAL','이물질 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-CMN-P01','구동부 윤활유 보충 및 점검','PERIODIC',NULL,'VISUAL','적정 유량 유지','WEEKLY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-CMN-P02','에어 필터 청소 및 교체 점검','PERIODIC',NULL,'VISUAL','필터 막힘 없음','MONTHLY','Y')
/

-- ─────────────────────────────────────────────
-- 자동압착기 (AUTO_CRIMP)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-ATC-001','압착력 설정값 확인','DAILY','AUTO_CRIMP','VISUAL','설정값 일치 여부 확인','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-ATC-002','압착 단자 외관 샘플 검사','DAILY','AUTO_CRIMP','VISUAL','단자 변형·균열 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-ATC-003','압착 높이(CH) 측정','DAILY','AUTO_CRIMP','MEASURE','작업표준서 규격 이내',NULL,'Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-ATC-004','단자 공급 릴 잔량 확인','DAILY','AUTO_CRIMP','VISUAL','잔량 부족 시 교체','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-ATC-P01','압착 다이 마모 측정','PERIODIC','AUTO_CRIMP','MEASURE','마모 허용치 이내',NULL,'Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-ATC-PM1','압착 다이 교체','PM','AUTO_CRIMP','VISUAL','교체 후 압착 샘플 OK','MONTHLY','Y')
/

-- ─────────────────────────────────────────────
-- 단선절단기 (SINGLE_CUT)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-SCT-001','절단 길이 정확도 확인','DAILY','SINGLE_CUT','MEASURE','±0.5mm 이내',NULL,'Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-SCT-002','커터 날 마모 상태 육안 확인','DAILY','SINGLE_CUT','VISUAL','날 파손·이빠짐 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-SCT-003','탈피 길이 정확도 확인','DAILY','SINGLE_CUT','MEASURE','±0.3mm 이내',NULL,'Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-SCT-P01','커터 날 교체 주기 점검','PERIODIC','SINGLE_CUT','VISUAL','교체 후 샘플 검사 OK','WEEKLY','Y')
/

-- ─────────────────────────────────────────────
-- 다선절단기 (MULTI_CUT)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-MCT-001','각 채널 절단 길이 정확도','DAILY','MULTI_CUT','VISUAL','전 채널 길이 공차 이내','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-MCT-002','전선 공급 장력 설정 확인','DAILY','MULTI_CUT','VISUAL','장력 설정값 기준 이내','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-MCT-P01','다선 가이드 클리닝','PERIODIC','MULTI_CUT','VISUAL','이물질·선 걸림 없음','WEEKLY','Y')
/

-- ─────────────────────────────────────────────
-- 트위스트기 (TWIST)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-TWS-001','트위스트 횟수(피치) 설정 확인','DAILY','TWIST','VISUAL','작업표준서 설정값 일치','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-TWS-002','트위스트 외관 샘플 확인','DAILY','TWIST','VISUAL','꼬임 불량 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-TWS-P01','스핀들 베어링 상태 점검','PERIODIC','TWIST','VISUAL','소음·진동 없음','MONTHLY','Y')
/

-- ─────────────────────────────────────────────
-- 솔더링기 (SOLDER)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-SLD-001','납조 온도 확인','DAILY','SOLDER','MEASURE','설정온도 ±5°C',NULL,'Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-SLD-002','납 잔량 확인 및 보충','DAILY','SOLDER','VISUAL','기준선 이상 유지','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-SLD-003','납 외관 샘플 검사','DAILY','SOLDER','VISUAL','냉납·공납 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-SLD-P01','납조 슬래그 제거 및 청소','PERIODIC','SOLDER','VISUAL','슬래그 제거 완료','WEEKLY','Y')
/

-- ─────────────────────────────────────────────
-- 하우징기 (HOUSING)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-HSG-001','하우징 공급 호퍼 잔량 확인','DAILY','HOUSING','VISUAL','부족 시 보충','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-HSG-002','하우징 체결 걸림 감지 확인','DAILY','HOUSING','VISUAL','오(誤)감지 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-HSG-003','하우징 삽입력 기준 확인','DAILY','HOUSING','VISUAL','불완전 삽입 없음','DAILY','Y')
/

-- ─────────────────────────────────────────────
-- 검사기 (TESTER)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-TST-001','기준 와이어하네스 통전 테스트','DAILY','TESTER','VISUAL','PASS 판정','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-TST-002','저항 측정 기준값 확인','DAILY','TESTER','MEASURE','0.1Ω 이하',NULL,'Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-TST-003','프로브 접촉 상태 확인','DAILY','TESTER','VISUAL','접촉 불량 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-TST-P01','검사 지그 핀 마모 점검','PERIODIC','TESTER','VISUAL','마모·구부러짐 없음','WEEKLY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-TST-PM1','검사 장비 정기 캘리브레이션','PM','TESTER','VISUAL','성적서 발행 완료','ANNUAL','Y')
/

-- ─────────────────────────────────────────────
-- 라벨프린터 (LABEL_PRINTER)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-LBP-001','인쇄 품질 샘플 확인','DAILY','LABEL_PRINTER','VISUAL','바코드 판독 OK, 인쇄 번짐 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-LBP-002','라벨 잔량 확인','DAILY','LABEL_PRINTER','VISUAL','부족 시 교체','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-LBP-P01','인쇄 헤드 청소','PERIODIC','LABEL_PRINTER','VISUAL','이물질 제거 완료','WEEKLY','Y')
/

-- ─────────────────────────────────────────────
-- 검사설비 (INSPECTION)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-INS-001','검사 지그 고정 상태 확인','DAILY','INSPECTION','VISUAL','볼트 이완 없음, 지그 수평 OK','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-INS-002','조명 밝기·방향 확인','DAILY','INSPECTION','VISUAL','기준 조도 이상','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-INS-003','카메라 렌즈 청결 상태','DAILY','INSPECTION','VISUAL','이물질·지문 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-INS-P01','기준 샘플 판정 정확도 확인','PERIODIC','INSPECTION','VISUAL','OK/NG 판정 기준 일치','WEEKLY','Y')
/

-- ─────────────────────────────────────────────
-- 포장기 (PACKING)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-PKG-001','열 밀봉 온도 확인','DAILY','PACKING','MEASURE','설정온도 ±5°C',NULL,'Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-PKG-002','포장 밀봉 상태 샘플 확인','DAILY','PACKING','VISUAL','밀봉 불량 없음','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-PKG-P01','히터 바 청소 및 점검','PERIODIC','PACKING','VISUAL','이물질 없음, 변형 없음','WEEKLY','Y')
/

-- ─────────────────────────────────────────────
-- 기타 (OTHER)
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-OTH-001','설비 외관 및 주변 청결 상태','DAILY','OTHER','VISUAL','청결 유지','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-OTH-P01','설비 접지 상태 점검','PERIODIC','OTHER','VISUAL','접지선 이완 없음','MONTHLY','Y')
/

-- ─────────────────────────────────────────────
-- 작업자 점검 (WORKER) — 공통
-- ─────────────────────────────────────────────
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-WRK-001','작업 전 설비 주변 정리정돈','WORKER',NULL,'VISUAL','5S 기준 이상','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-WRK-002','보호구(안전화·귀마개) 착용 확인','WORKER',NULL,'VISUAL','착용 완료','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-WRK-003','작업 지시서 확인','WORKER',NULL,'VISUAL','작업표준서 확인 완료','DAILY','Y')
/
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE, CRITERIA, CYCLE, USE_YN)
VALUES ('40','1000','EI-WRK-004','설비 가동 전 이상음·진동 확인','WORKER',NULL,'VISUAL','이상음·이상진동 없음','DAILY','Y')
/
