-- AQL 표준 추가: 특별검사수준 S-1 · AQL 0.015
-- resolve-iqc-items 404 해결: DLMLS6-3-3 검사항목이 S-1/0.015를 참조하나 표준 부재였음.
-- AQL 0.015 유효 플랜: sample 80 Ac0/Re1. LOT보다 샘플수가 크거나 같으면 전수검사로 해석한다.

MERGE INTO AQL_STANDARDS s
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'AQL-S-1-0.015' AQL_CODE FROM DUAL) x
ON (s.COMPANY = x.COMPANY AND s.PLANT_CD = x.PLANT_CD AND s.AQL_CODE = x.AQL_CODE)
WHEN MATCHED THEN UPDATE SET
  s.AQL_NAME = '특별검사수준 S-1 · AQL 0.015',
  s.INSPECTION_LEVEL = 'S-1',
  s.AQL_VALUE = 0.015,
  s.USE_YN = 'Y',
  s.REMARK = 'ISO 2859-1 보통검사 1회 샘플링',
  s.UPDATED_BY = 'codex',
  s.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, AQL_NAME, INSPECTION_LEVEL, AQL_VALUE, USE_YN, REMARK, CREATED_BY)
VALUES ('40', '1000', 'AQL-S-1-0.015', '특별검사수준 S-1 · AQL 0.015', 'S-1', 0.015, 'Y', 'ISO 2859-1 보통검사 1회 샘플링', 'codex');
/

MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 2 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 8, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 1, r.CODE_LETTER = 'A', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 2, 8, 80, 0, 1, 1, 'A', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 9 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 15, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 2, r.CODE_LETTER = 'A', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 9, 15, 80, 0, 1, 2, 'A', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 16 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 25, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 3, r.CODE_LETTER = 'A', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 16, 25, 80, 0, 1, 3, 'A', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 26 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 50, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 4, r.CODE_LETTER = 'A', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 26, 50, 80, 0, 1, 4, 'A', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 51 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 90, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 5, r.CODE_LETTER = 'B', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 51, 90, 80, 0, 1, 5, 'B', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 91 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 150, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 6, r.CODE_LETTER = 'B', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 91, 150, 80, 0, 1, 6, 'B', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 151 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 280, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 7, r.CODE_LETTER = 'B', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 151, 280, 80, 0, 1, 7, 'B', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 281 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 500, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 8, r.CODE_LETTER = 'B', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 281, 500, 80, 0, 1, 8, 'B', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 501 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 1200, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 9, r.CODE_LETTER = 'C', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 501, 1200, 80, 0, 1, 9, 'C', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 1201 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 3200, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 10, r.CODE_LETTER = 'C', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 1201, 3200, 80, 0, 1, 10, 'C', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 3201 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 10000, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 11, r.CODE_LETTER = 'C', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 3201, 10000, 80, 0, 1, 11, 'C', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 10001 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 35000, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 12, r.CODE_LETTER = 'C', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 10001, 35000, 80, 0, 1, 12, 'C', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 35001 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 150000, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 13, r.CODE_LETTER = 'D', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 35001, 150000, 80, 0, 1, 13, 'D', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 150001 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 500000, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 14, r.CODE_LETTER = 'D', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 150001, 500000, 80, 0, 1, 14, 'D', 'codex');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C, '1000' P, 'AQL-S-1-0.015' A, 500001 F FROM DUAL) x ON (r.COMPANY = x.C AND r.PLANT_CD = x.P AND r.AQL_CODE = x.A AND r.LOT_QTY_FROM = x.F)
WHEN MATCHED THEN UPDATE SET r.LOT_QTY_TO = 999999999, r.SAMPLE_SIZE = 80, r.ACCEPT_QTY = 0, r.REJECT_QTY = 1, r.SORT_ORDER = 15, r.CODE_LETTER = 'D', r.UPDATED_BY = 'codex', r.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO, SAMPLE_SIZE, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CODE_LETTER, CREATED_BY) VALUES ('40', '1000', 'AQL-S-1-0.015', 500001, 999999999, 80, 0, 1, 15, 'D', 'codex');
/

COMMIT;
/
