DECLARE
  v_target_exists NUMBER;
  v_legacy_exists NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_target_exists
    FROM USER_TABLES
   WHERE TABLE_NAME = 'ISYS_COMM_CONFIGS';

  SELECT COUNT(*)
    INTO v_legacy_exists
    FROM USER_TABLES
   WHERE TABLE_NAME = 'COMM_CONFIGS';

  IF v_target_exists = 0 AND v_legacy_exists > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE COMM_CONFIGS RENAME TO ISYS_COMM_CONFIGS';
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE ISYS_COMM_CONFIGS RENAME CONSTRAINT PK_COMM_CONFIGS TO PK_ISYS_COMM_CONFIGS';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN RAISE; END IF;
    END;
    BEGIN
      EXECUTE IMMEDIATE 'ALTER INDEX IDX_COMM_CONFIGS_TYPE RENAME TO IDX_ISYS_COMM_CONFIGS_TYPE';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN RAISE; END IF;
    END;
    BEGIN
      EXECUTE IMMEDIATE 'ALTER INDEX IDX_COMM_CONFIGS_ORG RENAME TO IDX_ISYS_COMM_CONFIGS_ORG';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN RAISE; END IF;
    END;
  ELSIF v_target_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ISYS_COMM_CONFIGS (
        CONFIG_NAME VARCHAR2(100) NOT NULL,
        COMM_TYPE VARCHAR2(50) NOT NULL,
        DESCRIPTION VARCHAR2(500),
        HOST VARCHAR2(255),
        PORT NUMBER,
        PORT_NAME VARCHAR2(50),
        BAUD_RATE NUMBER,
        DATA_BITS NUMBER,
        STOP_BITS VARCHAR2(10),
        PARITY VARCHAR2(10),
        FLOW_CONTROL VARCHAR2(20),
        LINE_ENDING VARCHAR2(10) DEFAULT ''NONE'',
        EXTRA_CONFIG CLOB,
        USE_YN VARCHAR2(1) DEFAULT ''Y'' NOT NULL,
        ORGANIZATION_ID NUMBER NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_ISYS_COMM_CONFIGS PRIMARY KEY (CONFIG_NAME)
      )';

    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ISYS_COMM_CONFIGS_TYPE ON ISYS_COMM_CONFIGS (COMM_TYPE)';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ISYS_COMM_CONFIGS_ORG ON ISYS_COMM_CONFIGS (ORGANIZATION_ID)';
  END IF;
END;
/
