DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EQUIP_MASTERS'
     AND COLUMN_NAME = 'IMAGE_URL';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_MASTERS ADD (IMAGE_URL VARCHAR2(500))';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN EQUIP_MASTERS.IMAGE_URL IS '설비 사진 파일 URL (/uploads/equips/...)']';
END;
/
