-- ============================================================
-- 2026-06-12: 출하지시 / 출하확정 대상 / 출하이력 테스트 데이터
--
--   SHIPMENT_ORDERS  : SO-2606-001 (DRAFT), SO-2606-002 (CONFIRMED), SO-2606-003 (SHIPPED)
--   SHIPMENT_ORDER_ITEMS : 각 출하지시별 품목
--   FG_LABELS        : PACKED 상태 (SO-2606-002 출하확정 대상)
--   PRODUCT_STOCKS   : 완제품 재고 (PRD_UID='*' 집계행)
--   SHIPMENT_LOGS    : 출하이력 3건
--
-- 완제품 코드: FG-HNS-001 ~ FG-HNS-010 (BOM 시드 기준)
-- 재실행 안전: WHERE NOT EXISTS
-- ============================================================

-- ── 1. 출하지시 헤더 (SHIPMENT_ORDERS) ───────────────────────────────

-- DRAFT: 작성 중 (수정·취소 가능)
INSERT INTO SHIPMENT_ORDERS (
  SHIP_ORDER_NO, CUSTOMER_ID, CUSTOMER_NAME,
  DUE_DATE, SHIP_DATE, STATUS, REMARK,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT
  'SO-2606-001', 'CUS-HMC', '현대모비스',
  DATE '2026-06-20', NULL, 'DRAFT', '[SEED] 출하지시 작성중',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDERS WHERE SHIP_ORDER_NO = 'SO-2606-001' AND COMPANY = '40'
);
/

-- CONFIRMED: 확정 완료 (출하확정 대상)
INSERT INTO SHIPMENT_ORDERS (
  SHIP_ORDER_NO, CUSTOMER_ID, CUSTOMER_NAME,
  DUE_DATE, SHIP_DATE, STATUS, REMARK,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT
  'SO-2606-002', 'CUS-KIA', '기아자동차',
  DATE '2026-06-18', NULL, 'CONFIRMED', '[SEED] 출하확정 대상',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDERS WHERE SHIP_ORDER_NO = 'SO-2606-002' AND COMPANY = '40'
);
/

-- SHIPPED: 출하 완료
INSERT INTO SHIPMENT_ORDERS (
  SHIP_ORDER_NO, CUSTOMER_ID, CUSTOMER_NAME,
  DUE_DATE, SHIP_DATE, STATUS, REMARK,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT
  'SO-2606-003', 'CUS-HMC', '현대모비스',
  DATE '2026-06-12', DATE '2026-06-12', 'SHIPPED', '[SEED] 출하완료 샘플',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDERS WHERE SHIP_ORDER_NO = 'SO-2606-003' AND COMPANY = '40'
);
/

COMMIT;
/

-- ── 2. 출하지시 품목 (SHIPMENT_ORDER_ITEMS) ──────────────────────────

-- SO-2606-001 품목 (DRAFT)
INSERT INTO SHIPMENT_ORDER_ITEMS (
  SHIP_ORDER_ID, SEQ, ITEM_CODE, ORDER_QTY, SHIPPED_QTY,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'SO-2606-001', 1, 'FG-HNS-001', 100, 0,
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDER_ITEMS
  WHERE SHIP_ORDER_ID = 'SO-2606-001' AND SEQ = 1 AND COMPANY = '40'
);
/

INSERT INTO SHIPMENT_ORDER_ITEMS (
  SHIP_ORDER_ID, SEQ, ITEM_CODE, ORDER_QTY, SHIPPED_QTY,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'SO-2606-001', 2, 'FG-HNS-002', 80, 0,
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDER_ITEMS
  WHERE SHIP_ORDER_ID = 'SO-2606-001' AND SEQ = 2 AND COMPANY = '40'
);
/

INSERT INTO SHIPMENT_ORDER_ITEMS (
  SHIP_ORDER_ID, SEQ, ITEM_CODE, ORDER_QTY, SHIPPED_QTY,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'SO-2606-001', 3, 'FG-HNS-006', 50, 0,
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDER_ITEMS
  WHERE SHIP_ORDER_ID = 'SO-2606-001' AND SEQ = 3 AND COMPANY = '40'
);
/

-- SO-2606-002 품목 (CONFIRMED - 출하확정 대상)
INSERT INTO SHIPMENT_ORDER_ITEMS (
  SHIP_ORDER_ID, SEQ, ITEM_CODE, ORDER_QTY, SHIPPED_QTY,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'SO-2606-002', 1, 'FG-HNS-003', 50, 0,
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDER_ITEMS
  WHERE SHIP_ORDER_ID = 'SO-2606-002' AND SEQ = 1 AND COMPANY = '40'
);
/

INSERT INTO SHIPMENT_ORDER_ITEMS (
  SHIP_ORDER_ID, SEQ, ITEM_CODE, ORDER_QTY, SHIPPED_QTY,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'SO-2606-002', 2, 'FG-HNS-004', 60, 0,
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDER_ITEMS
  WHERE SHIP_ORDER_ID = 'SO-2606-002' AND SEQ = 2 AND COMPANY = '40'
);
/

INSERT INTO SHIPMENT_ORDER_ITEMS (
  SHIP_ORDER_ID, SEQ, ITEM_CODE, ORDER_QTY, SHIPPED_QTY,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'SO-2606-002', 3, 'FG-HNS-007', 40, 0,
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDER_ITEMS
  WHERE SHIP_ORDER_ID = 'SO-2606-002' AND SEQ = 3 AND COMPANY = '40'
);
/

-- SO-2606-003 품목 (SHIPPED - 출하완료)
INSERT INTO SHIPMENT_ORDER_ITEMS (
  SHIP_ORDER_ID, SEQ, ITEM_CODE, ORDER_QTY, SHIPPED_QTY,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'SO-2606-003', 1, 'FG-HNS-005', 30, 30,
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDER_ITEMS
  WHERE SHIP_ORDER_ID = 'SO-2606-003' AND SEQ = 1 AND COMPANY = '40'
);
/

INSERT INTO SHIPMENT_ORDER_ITEMS (
  SHIP_ORDER_ID, SEQ, ITEM_CODE, ORDER_QTY, SHIPPED_QTY,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'SO-2606-003', 2, 'FG-HNS-008', 20, 20,
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_ORDER_ITEMS
  WHERE SHIP_ORDER_ID = 'SO-2606-003' AND SEQ = 2 AND COMPANY = '40'
);
/

COMMIT;
/

-- ── 3. FG_LABELS (PACKED 상태 - 출하확정 가능) ───────────────────────
-- SO-2606-002 대상 완제품 라벨 4건 (FG-HNS-003 x2, FG-HNS-004 x2)

INSERT INTO FG_LABELS (
  FG_BARCODE, ITEM_CODE, ORDER_NO, STATUS, BOX_NO,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'FGB2606120001', 'FG-HNS-003', NULL, 'PACKED', 'BX260612001',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM FG_LABELS WHERE FG_BARCODE = 'FGB2606120001');
/

INSERT INTO FG_LABELS (
  FG_BARCODE, ITEM_CODE, ORDER_NO, STATUS, BOX_NO,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'FGB2606120002', 'FG-HNS-003', NULL, 'PACKED', 'BX260612001',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM FG_LABELS WHERE FG_BARCODE = 'FGB2606120002');
/

INSERT INTO FG_LABELS (
  FG_BARCODE, ITEM_CODE, ORDER_NO, STATUS, BOX_NO,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'FGB2606120003', 'FG-HNS-004', NULL, 'PACKED', 'BX260612002',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM FG_LABELS WHERE FG_BARCODE = 'FGB2606120003');
/

INSERT INTO FG_LABELS (
  FG_BARCODE, ITEM_CODE, ORDER_NO, STATUS, BOX_NO,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'FGB2606120004', 'FG-HNS-004', NULL, 'PACKED', 'BX260612002',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM FG_LABELS WHERE FG_BARCODE = 'FGB2606120004');
/

-- FG-HNS-007 대상 (SO-2606-002 seq=3)
INSERT INTO FG_LABELS (
  FG_BARCODE, ITEM_CODE, ORDER_NO, STATUS, BOX_NO,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'FGB2606120005', 'FG-HNS-007', NULL, 'PACKED', 'BX260612003',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM FG_LABELS WHERE FG_BARCODE = 'FGB2606120005');
/

-- 출하완료된 SO-2606-003 라벨 (SHIPPED 상태)
INSERT INTO FG_LABELS (
  FG_BARCODE, ITEM_CODE, ORDER_NO, STATUS, BOX_NO,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'FGB2606110001', 'FG-HNS-005', 'SO-2606-003', 'SHIPPED', 'BX260611001',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM FG_LABELS WHERE FG_BARCODE = 'FGB2606110001');
/

INSERT INTO FG_LABELS (
  FG_BARCODE, ITEM_CODE, ORDER_NO, STATUS, BOX_NO,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT 'FGB2606110002', 'FG-HNS-008', 'SO-2606-003', 'SHIPPED', 'BX260611002',
  '40', '1000', 'seed', 'seed', SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM FG_LABELS WHERE FG_BARCODE = 'FGB2606110002');
/

COMMIT;
/

-- ── 4. PRODUCT_STOCKS (완제품 재고 - PRD_UID='*' 집계행) ─────────────
INSERT INTO PRODUCT_STOCKS (
  COMPANY, PLANT_CD, WAREHOUSE_CODE, ITEM_CODE, PRD_UID,
  ITEM_TYPE, ORDER_NO, QTY, RESERVED_QTY, AVAILABLE_QTY, STATUS,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT '40', '1000', 'WH-FG', 'FG-HNS-003', '*',
  'FINISHED', NULL, 50, 0, 50, 'NORMAL',
  'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM PRODUCT_STOCKS
  WHERE COMPANY='40' AND PLANT_CD='1000' AND WAREHOUSE_CODE='WH-FG'
    AND ITEM_CODE='FG-HNS-003' AND PRD_UID='*'
);
/

INSERT INTO PRODUCT_STOCKS (
  COMPANY, PLANT_CD, WAREHOUSE_CODE, ITEM_CODE, PRD_UID,
  ITEM_TYPE, ORDER_NO, QTY, RESERVED_QTY, AVAILABLE_QTY, STATUS,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT '40', '1000', 'WH-FG', 'FG-HNS-004', '*',
  'FINISHED', NULL, 60, 0, 60, 'NORMAL',
  'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM PRODUCT_STOCKS
  WHERE COMPANY='40' AND PLANT_CD='1000' AND WAREHOUSE_CODE='WH-FG'
    AND ITEM_CODE='FG-HNS-004' AND PRD_UID='*'
);
/

INSERT INTO PRODUCT_STOCKS (
  COMPANY, PLANT_CD, WAREHOUSE_CODE, ITEM_CODE, PRD_UID,
  ITEM_TYPE, ORDER_NO, QTY, RESERVED_QTY, AVAILABLE_QTY, STATUS,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT '40', '1000', 'WH-FG', 'FG-HNS-007', '*',
  'FINISHED', NULL, 40, 0, 40, 'NORMAL',
  'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM PRODUCT_STOCKS
  WHERE COMPANY='40' AND PLANT_CD='1000' AND WAREHOUSE_CODE='WH-FG'
    AND ITEM_CODE='FG-HNS-007' AND PRD_UID='*'
);
/

COMMIT;
/

-- ── 5. SHIPMENT_LOGS (출하이력) ───────────────────────────────────────
INSERT INTO SHIPMENT_LOGS (
  SHIP_NO, SHIP_DATE, SHIP_TIME,
  VEHICLE_NO, DRIVER_NAME, DESTINATION, CUSTOMER,
  SHIP_ORDER_NO, PALLET_COUNT, BOX_COUNT, TOTAL_QTY,
  STATUS, ERP_SYNC_YN,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT
  'SH-2606-001', DATE '2026-06-10', TIMESTAMP '2026-06-10 09:30:00',
  '서울12가3456', '김운전', '현대모비스 아산공장', '현대모비스',
  NULL, 2, 10, 200,
  'SHIPPED', 'N',
  '40', '1000', 'seed', 'seed',
  SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP - INTERVAL '2' DAY
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_LOGS WHERE SHIP_NO = 'SH-2606-001' AND COMPANY = '40'
);
/

INSERT INTO SHIPMENT_LOGS (
  SHIP_NO, SHIP_DATE, SHIP_TIME,
  VEHICLE_NO, DRIVER_NAME, DESTINATION, CUSTOMER,
  SHIP_ORDER_NO, PALLET_COUNT, BOX_COUNT, TOTAL_QTY,
  STATUS, ERP_SYNC_YN,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT
  'SH-2606-002', DATE '2026-06-11', TIMESTAMP '2026-06-11 14:00:00',
  '경기34나5678', '박기사', '기아자동차 광명공장', '기아자동차',
  NULL, 3, 15, 350,
  'SHIPPED', 'Y',
  '40', '1000', 'seed', 'seed',
  SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_LOGS WHERE SHIP_NO = 'SH-2606-002' AND COMPANY = '40'
);
/

INSERT INTO SHIPMENT_LOGS (
  SHIP_NO, SHIP_DATE, SHIP_TIME,
  VEHICLE_NO, DRIVER_NAME, DESTINATION, CUSTOMER,
  SHIP_ORDER_NO, PALLET_COUNT, BOX_COUNT, TOTAL_QTY,
  STATUS, ERP_SYNC_YN,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
)
SELECT
  'SH-2606-003', DATE '2026-06-12', TIMESTAMP '2026-06-12 10:15:00',
  '서울78다9012', '이운전', '현대모비스 아산공장', '현대모비스',
  'SO-2606-003', 1, 5, 50,
  'SHIPPED', 'N',
  '40', '1000', 'seed', 'seed',
  SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SHIPMENT_LOGS WHERE SHIP_NO = 'SH-2606-003' AND COMPANY = '40'
);
/

COMMIT;
/
