BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS ADD (AUDIT_ID_NEW VARCHAR2(30))';
  EXECUTE IMMEDIATE 'UPDATE AUDIT_FINDINGS SET AUDIT_ID_NEW = TO_CHAR(AUDIT_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS DROP CONSTRAINT PK_AUDIT_FINDINGS';
  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS DROP COLUMN AUDIT_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS RENAME COLUMN AUDIT_ID_NEW TO AUDIT_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS MODIFY (AUDIT_ID NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS ADD CONSTRAINT PK_AUDIT_FINDINGS PRIMARY KEY (AUDIT_ID, FINDING_NO)';

  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS ADD (CAPA_ID_NEW VARCHAR2(30))';
  EXECUTE IMMEDIATE 'UPDATE AUDIT_FINDINGS SET CAPA_ID_NEW = TO_CHAR(CAPA_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS DROP COLUMN CAPA_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_FINDINGS RENAME COLUMN CAPA_ID_NEW TO CAPA_ID';

  EXECUTE IMMEDIATE 'ALTER TABLE CAPA_ACTIONS ADD (CAPA_ID_NEW VARCHAR2(30))';
  EXECUTE IMMEDIATE 'UPDATE CAPA_ACTIONS SET CAPA_ID_NEW = TO_CHAR(CAPA_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE CAPA_ACTIONS DROP CONSTRAINT PK_CAPA_ACTIONS';
  EXECUTE IMMEDIATE 'ALTER TABLE CAPA_ACTIONS DROP COLUMN CAPA_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE CAPA_ACTIONS RENAME COLUMN CAPA_ID_NEW TO CAPA_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE CAPA_ACTIONS MODIFY (CAPA_ID NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE CAPA_ACTIONS ADD CONSTRAINT PK_CAPA_ACTIONS PRIMARY KEY (CAPA_ID, SEQ)';

  EXECUTE IMMEDIATE 'ALTER TABLE CONTROL_PLAN_ITEMS ADD (CONTROL_PLAN_ID_NEW VARCHAR2(30))';
  EXECUTE IMMEDIATE 'UPDATE CONTROL_PLAN_ITEMS SET CONTROL_PLAN_ID_NEW = TO_CHAR(CONTROL_PLAN_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE CONTROL_PLAN_ITEMS DROP CONSTRAINT PK_CONTROL_PLAN_ITEMS';
  EXECUTE IMMEDIATE 'ALTER TABLE CONTROL_PLAN_ITEMS DROP COLUMN CONTROL_PLAN_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE CONTROL_PLAN_ITEMS RENAME COLUMN CONTROL_PLAN_ID_NEW TO CONTROL_PLAN_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE CONTROL_PLAN_ITEMS MODIFY (CONTROL_PLAN_ID NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE CONTROL_PLAN_ITEMS ADD CONSTRAINT PK_CONTROL_PLAN_ITEMS PRIMARY KEY (CONTROL_PLAN_ID, SEQ)';

  EXECUTE IMMEDIATE 'ALTER TABLE FAI_ITEMS ADD (FAI_ID_NEW VARCHAR2(30))';
  EXECUTE IMMEDIATE 'UPDATE FAI_ITEMS SET FAI_ID_NEW = TO_CHAR(FAI_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE FAI_ITEMS DROP CONSTRAINT PK_FAI_ITEMS';
  EXECUTE IMMEDIATE 'ALTER TABLE FAI_ITEMS DROP COLUMN FAI_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE FAI_ITEMS RENAME COLUMN FAI_ID_NEW TO FAI_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE FAI_ITEMS MODIFY (FAI_ID NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE FAI_ITEMS ADD CONSTRAINT PK_FAI_ITEMS PRIMARY KEY (FAI_ID, SEQ)';

  EXECUTE IMMEDIATE 'ALTER TABLE FG_LABELS ADD (INSPECT_RESULT_ID_NEW VARCHAR2(30))';
  EXECUTE IMMEDIATE 'UPDATE FG_LABELS SET INSPECT_RESULT_ID_NEW = TO_CHAR(INSPECT_RESULT_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE FG_LABELS DROP COLUMN INSPECT_RESULT_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE FG_LABELS RENAME COLUMN INSPECT_RESULT_ID_NEW TO INSPECT_RESULT_ID';

  EXECUTE IMMEDIATE 'ALTER TABLE LABEL_PRINT_LOGS ADD (TEMPLATE_ID_NEW VARCHAR2(36))';
  EXECUTE IMMEDIATE 'UPDATE LABEL_PRINT_LOGS SET TEMPLATE_ID_NEW = TEMPLATE_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE LABEL_PRINT_LOGS DROP COLUMN TEMPLATE_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE LABEL_PRINT_LOGS RENAME COLUMN TEMPLATE_ID_NEW TO TEMPLATE_ID';

  EXECUTE IMMEDIATE 'ALTER TABLE PM_PLAN_ITEMS ADD (PM_PLAN_ID_NEW VARCHAR2(50))';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_PLAN_ITEMS DROP CONSTRAINT PK_PM_PLAN_ITEMS';
  EXECUTE IMMEDIATE 'UPDATE PM_PLAN_ITEMS SET PM_PLAN_ID_NEW = RAWTOHEX(PM_PLAN_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_PLAN_ITEMS DROP COLUMN PM_PLAN_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_PLAN_ITEMS RENAME COLUMN PM_PLAN_ID_NEW TO PM_PLAN_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_PLAN_ITEMS MODIFY (PM_PLAN_ID NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_PLAN_ITEMS ADD CONSTRAINT PK_PM_PLAN_ITEMS PRIMARY KEY (PM_PLAN_ID, SEQ)';

  EXECUTE IMMEDIATE 'ALTER TABLE PM_WORK_ORDERS ADD (PM_PLAN_ID_NEW VARCHAR2(50))';
  EXECUTE IMMEDIATE 'UPDATE PM_WORK_ORDERS SET PM_PLAN_ID_NEW = RAWTOHEX(PM_PLAN_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_WORK_ORDERS DROP COLUMN PM_PLAN_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_WORK_ORDERS RENAME COLUMN PM_PLAN_ID_NEW TO PM_PLAN_ID';

  EXECUTE IMMEDIATE 'ALTER TABLE PM_WO_RESULTS ADD (PM_PLAN_ITEM_ID_NEW NUMBER)';
  EXECUTE IMMEDIATE 'UPDATE PM_WO_RESULTS SET PM_PLAN_ITEM_ID_NEW = TO_NUMBER(RAWTOHEX(PM_PLAN_ITEM_ID))';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_WO_RESULTS DROP COLUMN PM_PLAN_ITEM_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE PM_WO_RESULTS RENAME COLUMN PM_PLAN_ITEM_ID_NEW TO PM_PLAN_ITEM_ID';

  EXECUTE IMMEDIATE 'ALTER TABLE SPC_DATA ADD (CHART_ID_NEW VARCHAR2(30))';
  EXECUTE IMMEDIATE 'UPDATE SPC_DATA SET CHART_ID_NEW = TO_CHAR(CHART_ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE SPC_DATA DROP CONSTRAINT PK_SPC_DATA';
  EXECUTE IMMEDIATE 'ALTER TABLE SPC_DATA DROP COLUMN CHART_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE SPC_DATA RENAME COLUMN CHART_ID_NEW TO CHART_ID';
  EXECUTE IMMEDIATE 'ALTER TABLE SPC_DATA MODIFY (CHART_ID NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE SPC_DATA ADD CONSTRAINT PK_SPC_DATA PRIMARY KEY (CHART_ID, SAMPLE_DATE, SEQ)';
END;
/
