-- 실적입력(수작업)/실적입력(가공) 화면 제거에 따른 메뉴 연관 데이터 정리
-- 대상 메뉴 코드: PROD_INPUT_MANUAL, PROD_INPUT_MACHINE
-- MENU_CATEGORY_ITEMS / PDA_ROLE_MENU / USER_AUTHS 에는 해당 행이 없었고,
-- ROLE_MENU_PERMISSIONS 에만 MANAGER/OPERATOR × 2코드 (COMPANY='40', PLANT_CD='1000') 4행 존재.

DELETE FROM ROLE_MENU_PERMISSIONS
 WHERE MENU_CODE IN ('PROD_INPUT_MANUAL', 'PROD_INPUT_MACHINE');

-- 잔여 흔적 정리(멱등): 다른 사이트/스코프에 남아있을 수 있는 메뉴 항목도 제거
DELETE FROM MENU_CATEGORY_ITEMS
 WHERE MENU_CODE IN ('PROD_INPUT_MANUAL', 'PROD_INPUT_MACHINE');

DELETE FROM PDA_ROLE_MENU
 WHERE MENU_CODE IN ('PROD_INPUT_MANUAL', 'PROD_INPUT_MACHINE');

COMMIT;
