-- 2026-10-03: 사용자별 메뉴 즐겨찾기 + 1단계 폴더
-- 헤더 즐겨찾기 드롭다운 / 사이드바 ★ 토글이 사용한다. 테넌트 키는 ORGANIZATION_ID, 사용자는 ISYS_USERS.USER_ID.
-- 블록 구분자는 '/' 한 줄이다. 재실행해도 이미 있는 객체는 건너뛴다.

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'USER_MENU_FAVORITE_FOLDERS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE USER_MENU_FAVORITE_FOLDERS (
      ID              NUMBER(15,0)        NOT NULL,
      ORGANIZATION_ID NUMBER              NOT NULL,
      USER_ID         VARCHAR2(20)        NOT NULL,
      NAME            VARCHAR2(100 CHAR)  NOT NULL,
      SORT_ORDER      NUMBER(15,0)        NOT NULL,
      CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_MENU_FAVORITE_FOLDER PRIMARY KEY (ID),
      CONSTRAINT UK_MENU_FAV_FOLDER_OWNER UNIQUE (ORGANIZATION_ID, USER_ID, ID),
      CONSTRAINT CK_MENU_FAV_FOLDER_NAME CHECK (TRIM(NAME) IS NOT NULL)
    )';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_MENU_FAVORITE_FOLDER';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_MENU_FAVORITE_FOLDER START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'USER_MENU_FAVORITES';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE USER_MENU_FAVORITES (
      ORGANIZATION_ID NUMBER         NOT NULL,
      USER_ID         VARCHAR2(20)   NOT NULL,
      MENU_CODE       VARCHAR2(100)  NOT NULL,
      SORT_ORDER      NUMBER(10,0)   DEFAULT 0 NOT NULL,
      FOLDER_ID       NUMBER(15,0),
      CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY      VARCHAR2(50)   NOT NULL,
      UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_BY      VARCHAR2(50)   NOT NULL,
      CONSTRAINT PK_USER_MENU_FAVORITES PRIMARY KEY (ORGANIZATION_ID, USER_ID, MENU_CODE),
      CONSTRAINT FK_MENU_FAV_FOLDER_OWNER FOREIGN KEY (ORGANIZATION_ID, USER_ID, FOLDER_ID)
        REFERENCES USER_MENU_FAVORITE_FOLDERS (ORGANIZATION_ID, USER_ID, ID)
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_UMF_USER ON USER_MENU_FAVORITES (ORGANIZATION_ID, USER_ID, SORT_ORDER)';
  END IF;
END;
/
COMMENT ON TABLE USER_MENU_FAVORITE_FOLDERS IS '사용자별 메뉴 즐겨찾기 폴더 (1단계)'
/
COMMENT ON COLUMN USER_MENU_FAVORITE_FOLDERS.ID IS '폴더 ID (SEQ_MENU_FAVORITE_FOLDER)'
/
COMMENT ON COLUMN USER_MENU_FAVORITE_FOLDERS.ORGANIZATION_ID IS '조직 ID (테넌트 키)'
/
COMMENT ON COLUMN USER_MENU_FAVORITE_FOLDERS.USER_ID IS '사용자 ID (ISYS_USERS.USER_ID)'
/
COMMENT ON COLUMN USER_MENU_FAVORITE_FOLDERS.NAME IS '사용자 지정 폴더명'
/
COMMENT ON COLUMN USER_MENU_FAVORITE_FOLDERS.SORT_ORDER IS '폴더 표시 순서'
/
COMMENT ON TABLE USER_MENU_FAVORITES IS '사용자별 메뉴 즐겨찾기'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.ORGANIZATION_ID IS '조직 ID (테넌트 키)'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.USER_ID IS '사용자 ID (ISYS_USERS.USER_ID)'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.MENU_CODE IS '메뉴 코드 (menuConfig leaf)'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.SORT_ORDER IS '즐겨찾기 표시 순서'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.FOLDER_ID IS '즐겨찾기 폴더 ID (NULL: 폴더 밖)'
/
