-- 조립 실적입력(PROD_INPUT_ASSEMBLY) 메뉴 DB 시드
-- 신규 leaf: PROD_INPUT_ASSEMBLY / path /production/input-assembly / labelKey menu.production.inputAssembly
-- 형제 PROD_KITTING(SORT_ORDER=36) 바로 다음인 SORT_ORDER=37로 배치.
-- 멀티테넌시 정본: COMPANY=40, PLANT_CD='1000'. 멱등 MERGE(ON = MENU_CODE+COMPANY+PLANT_CD). add-only.

-- 1) 메뉴 아이템 등록
MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'PROD_INPUT_ASSEMBLY' AS MENU_CODE,
         'PRODUCTION'          AS CATEGORY_CODE,
         37                    AS SORT_ORDER,
         '40'                  AS COMPANY,
         '1000'                AS PLANT_CD
  FROM dual
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD,
          CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD,
          SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');

-- 2) RBAC 권한 등록 (형제 PROD_KITTING과 동일: MANAGER/OPERATOR CAN_ACCESS='Y')
MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER'  AS ROLE_CODE, 'PROD_INPUT_ASSEMBLY' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
  UNION ALL
  SELECT 'OPERATOR' AS ROLE_CODE, 'PROD_INPUT_ASSEMBLY' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD);
