BEGIN
  MERGE INTO EQUIP_MASTERS t
  USING (
    SELECT
      'EQ-' || p.PROCESS_CODE || '-' || LPAD(lv.N, 2, '0') AS EQUIP_CODE,
      p.PROCESS_NAME || ' 설비 #' || lv.N AS EQUIP_NAME,
      CASE
        WHEN p.PROCESS_CATEGORY = 'TERMINAL' THEN 'AUTO_CRIMP'
        WHEN p.PROCESS_CATEGORY = 'INSPECTION' THEN 'TESTER'
        WHEN p.PROCESS_CATEGORY = 'ASSEMBLY' THEN 'HOUSING'
        WHEN p.PROCESS_CATEGORY = 'WIRE' AND INSTR(p.PROCESS_CODE, 'CUT') > 0 THEN 'SINGLE_CUT'
        ELSE 'OTHER'
      END AS EQUIP_TYPE,
      'SEED-' || REPLACE(p.PROCESS_CODE, '-', '') || '-' || LPAD(lv.N, 2, '0') AS MODEL_NAME,
      'HANES-SIM' AS MAKER,
      CASE
        WHEN p.PROCESS_CATEGORY = 'WIRE' THEN 'LINE-01'
        WHEN p.PROCESS_CATEGORY = 'TERMINAL' THEN 'LINE-02'
        WHEN p.PROCESS_CATEGORY = 'ASSEMBLY' OR p.PROCESS_CATEGORY IS NULL THEN 'LINE-03'
        WHEN p.PROCESS_CATEGORY = 'HEAT' THEN 'LINE-04'
        WHEN p.PROCESS_CATEGORY = 'INSPECTION' THEN 'LINE-05'
        ELSE 'LINE-99'
      END AS LINE_CODE,
      p.PROCESS_CODE,
      DATE '2026-06-11' AS INSTALL_DATE,
      p.COMPANY,
      p.PLANT_CD
    FROM PROCESS_MASTERS p
    JOIN (
      SELECT LEVEL AS N
      FROM DUAL
      CONNECT BY LEVEL <= 2
    ) lv
      ON lv.N <= CASE
        WHEN p.PROCESS_CATEGORY IN ('WIRE', 'TERMINAL', 'INSPECTION') THEN 2
        ELSE 1
      END
    WHERE p.COMPANY = '40'
      AND p.PLANT_CD = '1000'
      AND p.USE_YN = 'Y'
  ) s
  ON (t.EQUIP_CODE = s.EQUIP_CODE)
  WHEN MATCHED THEN UPDATE SET
    t.EQUIP_NAME = s.EQUIP_NAME,
    t.EQUIP_TYPE = s.EQUIP_TYPE,
    t.MODEL_NAME = s.MODEL_NAME,
    t.MAKER = s.MAKER,
    t.LINE_CODE = s.LINE_CODE,
    t.PROCESS_CODE = s.PROCESS_CODE,
    t.INSTALL_DATE = s.INSTALL_DATE,
    t.STATUS = 'NORMAL',
    t.USE_YN = 'Y',
    t.COMPANY = s.COMPANY,
    t.PLANT_CD = s.PLANT_CD,
    t.UPDATED_BY = 'codex',
    t.UPDATED_AT = SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT (
    EQUIP_CODE,
    EQUIP_NAME,
    EQUIP_TYPE,
    MODEL_NAME,
    MAKER,
    LINE_CODE,
    PROCESS_CODE,
    INSTALL_DATE,
    STATUS,
    USE_YN,
    COMPANY,
    PLANT_CD,
    CREATED_BY,
    UPDATED_BY,
    CREATED_AT,
    UPDATED_AT
  ) VALUES (
    s.EQUIP_CODE,
    s.EQUIP_NAME,
    s.EQUIP_TYPE,
    s.MODEL_NAME,
    s.MAKER,
    s.LINE_CODE,
    s.PROCESS_CODE,
    s.INSTALL_DATE,
    'NORMAL',
    'Y',
    s.COMPANY,
    s.PLANT_CD,
    'codex',
    'codex',
    SYSTIMESTAMP,
    SYSTIMESTAMP
  );

  MERGE INTO PROCESS_EQUIPMENTS t
  USING (
    SELECT
      p.COMPANY,
      p.PLANT_CD,
      p.PROCESS_CODE,
      'EQ-' || p.PROCESS_CODE || '-' || LPAD(lv.N, 2, '0') AS EQUIP_CODE
    FROM PROCESS_MASTERS p
    JOIN (
      SELECT LEVEL AS N
      FROM DUAL
      CONNECT BY LEVEL <= 2
    ) lv
      ON lv.N <= CASE
        WHEN p.PROCESS_CATEGORY IN ('WIRE', 'TERMINAL', 'INSPECTION') THEN 2
        ELSE 1
      END
    WHERE p.COMPANY = '40'
      AND p.PLANT_CD = '1000'
      AND p.USE_YN = 'Y'
  ) s
  ON (
    t.COMPANY = s.COMPANY
    AND t.PLANT_CD = s.PLANT_CD
    AND t.PROCESS_CODE = s.PROCESS_CODE
    AND t.EQUIP_CODE = s.EQUIP_CODE
  )
  WHEN MATCHED THEN UPDATE SET
    t.USE_YN = 'Y',
    t.UPDATED_BY = 'codex',
    t.UPDATED_AT = SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT (
    COMPANY,
    PLANT_CD,
    PROCESS_CODE,
    EQUIP_CODE,
    USE_YN,
    CREATED_BY,
    UPDATED_BY,
    CREATED_AT,
    UPDATED_AT
  ) VALUES (
    s.COMPANY,
    s.PLANT_CD,
    s.PROCESS_CODE,
    s.EQUIP_CODE,
    'Y',
    'codex',
    'codex',
    SYSTIMESTAMP,
    SYSTIMESTAMP
  );

  COMMIT;
END;
/
