DECLARE
  -- 생산월력 IP_ 모델 보강 (멱등)
  -- 설계: docs/specs/2026-07-14-work-calendar-ip-model-design.md
  -- 대상: IP_PRODUCT_COMPANY_CALENDAR, IP_PRODUCT_LINE_CALENDAR, IP_SHIFT_TIME_MASTER
  -- HOLIDAY_YN은 F_GET_DELIVERY_DATE가 읽으므로 삭제하지 않고 DAY_TYPE의 미러로 유지한다.
  PROCEDURE add_column(p_table VARCHAR2, p_column VARCHAR2, p_ddl VARCHAR2) IS
    l_cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_cnt FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = UPPER(p_table) AND COLUMN_NAME = UPPER(p_column);
    IF l_cnt = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_ddl || ')';
    END IF;
  END;

  PROCEDURE add_constraint(p_table VARCHAR2, p_name VARCHAR2, p_ddl VARCHAR2) IS
    l_cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_cnt FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = UPPER(p_table) AND CONSTRAINT_NAME = UPPER(p_name);
    IF l_cnt = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD CONSTRAINT ' || p_name || ' ' || p_ddl;
    END IF;
  END;

  PROCEDURE force_not_null(p_table VARCHAR2, p_column VARCHAR2) IS
    l_nullable VARCHAR2(1);
  BEGIN
    SELECT NULLABLE INTO l_nullable FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = UPPER(p_table) AND COLUMN_NAME = UPPER(p_column);
    IF l_nullable = 'Y' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' MODIFY (' || p_column || ' NOT NULL)';
    END IF;
  END;
BEGIN
  -- 1) 전사 월력
  add_column('IP_PRODUCT_COMPANY_CALENDAR', 'DAY_TYPE',     'DAY_TYPE VARCHAR2(20) DEFAULT ''WORK'' NOT NULL');
  add_column('IP_PRODUCT_COMPANY_CALENDAR', 'OFF_REASON',   'OFF_REASON VARCHAR2(20)');
  add_column('IP_PRODUCT_COMPANY_CALENDAR', 'WORK_MINUTES', 'WORK_MINUTES NUMBER(5) DEFAULT 0 NOT NULL');
  add_column('IP_PRODUCT_COMPANY_CALENDAR', 'OT_MINUTES',   'OT_MINUTES NUMBER(5) DEFAULT 0 NOT NULL');
  add_column('IP_PRODUCT_COMPANY_CALENDAR', 'CONFIRM_YN',   'CONFIRM_YN VARCHAR2(1) DEFAULT ''N'' NOT NULL');
  add_constraint('IP_PRODUCT_COMPANY_CALENDAR', 'CK_IPCC_DAY_TYPE',
    'CHECK (DAY_TYPE IN (''WORK'',''OFF'',''HALF'',''SPECIAL''))');
  add_constraint('IP_PRODUCT_COMPANY_CALENDAR', 'CK_IPCC_HOLIDAY_SYNC',
    'CHECK ((DAY_TYPE = ''OFF'' AND HOLIDAY_YN = ''Y'') OR (DAY_TYPE <> ''OFF'' AND HOLIDAY_YN = ''N''))');
  add_constraint('IP_PRODUCT_COMPANY_CALENDAR', 'CK_IPCC_CONFIRM_YN',
    'CHECK (CONFIRM_YN IN (''Y'',''N''))');

  -- 2) 라인 예외 월력
  add_column('IP_PRODUCT_LINE_CALENDAR', 'DAY_TYPE',     'DAY_TYPE VARCHAR2(20) DEFAULT ''WORK'' NOT NULL');
  add_column('IP_PRODUCT_LINE_CALENDAR', 'OFF_REASON',   'OFF_REASON VARCHAR2(20)');
  add_column('IP_PRODUCT_LINE_CALENDAR', 'WORK_MINUTES', 'WORK_MINUTES NUMBER(5) DEFAULT 0 NOT NULL');
  add_column('IP_PRODUCT_LINE_CALENDAR', 'OT_MINUTES',   'OT_MINUTES NUMBER(5) DEFAULT 0 NOT NULL');
  add_column('IP_PRODUCT_LINE_CALENDAR', 'CONFIRM_YN',   'CONFIRM_YN VARCHAR2(1) DEFAULT ''N'' NOT NULL');
  add_constraint('IP_PRODUCT_LINE_CALENDAR', 'CK_IPLC_DAY_TYPE',
    'CHECK (DAY_TYPE IN (''WORK'',''OFF'',''HALF'',''SPECIAL''))');
  add_constraint('IP_PRODUCT_LINE_CALENDAR', 'CK_IPLC_HOLIDAY_SYNC',
    'CHECK ((DAY_TYPE = ''OFF'' AND HOLIDAY_YN = ''Y'') OR (DAY_TYPE <> ''OFF'' AND HOLIDAY_YN = ''N''))');
  add_constraint('IP_PRODUCT_LINE_CALENDAR', 'CK_IPLC_CONFIRM_YN',
    'CHECK (CONFIRM_YN IN (''Y'',''N''))');

  -- 3) 교대시간 마스터 - PK가 없어 먼저 정상화
  force_not_null('IP_SHIFT_TIME_MASTER', 'ORGANIZATION_ID');
  force_not_null('IP_SHIFT_TIME_MASTER', 'DATESET');
  add_column('IP_SHIFT_TIME_MASTER', 'DAY_BREAK_MINUTES',   'DAY_BREAK_MINUTES NUMBER(4) DEFAULT 0 NOT NULL');
  add_column('IP_SHIFT_TIME_MASTER', 'NIGHT_BREAK_MINUTES', 'NIGHT_BREAK_MINUTES NUMBER(4) DEFAULT 0 NOT NULL');
  add_constraint('IP_SHIFT_TIME_MASTER', 'PK_IP_SHIFT_TIME_MASTER',
    'PRIMARY KEY (ORGANIZATION_ID, DATESET)');
END;
/
