-- 2026-06-16 공통코드 전면 정합화 (유형 A 값추가 + 유형 B/D 그룹 신설)
-- 배경: ComCodeBadge/Select가 참조하는 그룹/코드와 실데이터가 불일치해 배지 raw 표시·드롭다운 빈값 다발.
--   - 유형 A: 기존 그룹에 실데이터 값 누락 → 값 추가
--   - 유형 B/D: 그룹 자체가 COM_CODES에 부재(IATF 시드가 폐기 plant로 작성돼 미적용) → 신설
-- 코드/한글명 출처: 기존 시드 SQL(scripts/migration/add_iatf_comcodes.sql, add_iatf_phase2_comcodes.sql),
--   ko.json comCode 블록, 도메인 DTO/서비스 상태흐름, JSHANES 실데이터 distinct.
-- PK=(GROUP_CODE,DETAIL_CODE). MERGE로 재실행 안전. 사이트: JSHANES (COMPANY=40, PLANT_CD=1000)
-- 유형 C(프론트 groupCode 오타 CON_CATEGORY→CONSUMABLE_CATEGORY, JOB_STATUS→JOB_ORDER_STATUS)는 코드 커밋에서 별도 처리.

MERGE INTO COM_CODES t
USING (
  -- ===== 유형 A: 기존 그룹에 누락 값 추가 =====
  SELECT 'EQUIP_STATUS' GROUP_CODE, 'INTERLOCK' DETAIL_CODE, '인터록' CODE_NAME, 4 SORT_ORDER FROM DUAL UNION ALL
  SELECT 'ISSUE_STATUS','APPROVED','승인',4 FROM DUAL UNION ALL
  SELECT 'PARTNER_TYPE','MFG','제조사',3 FROM DUAL UNION ALL
  SELECT 'RECEIVE_STATUS','DONE','입고완료',5 FROM DUAL UNION ALL
  SELECT 'ARRIVAL_RESULT_STATUS','DONE','완료',6 FROM DUAL UNION ALL
  SELECT 'ARRIVAL_PO_TYPE','PO','발주',3 FROM DUAL UNION ALL
  -- ===== 유형 B/D: 신설 그룹 =====
  -- 변경관리
  SELECT 'CHANGE_TYPE','MAN','인력변경',1 FROM DUAL UNION ALL
  SELECT 'CHANGE_TYPE','MACHINE','설비변경',2 FROM DUAL UNION ALL
  SELECT 'CHANGE_TYPE','MATERIAL','자재변경',3 FROM DUAL UNION ALL
  SELECT 'CHANGE_TYPE','METHOD','방법변경',4 FROM DUAL UNION ALL
  SELECT 'CHANGE_PRIORITY','HIGH','긴급',1 FROM DUAL UNION ALL
  SELECT 'CHANGE_PRIORITY','MEDIUM','보통',2 FROM DUAL UNION ALL
  SELECT 'CHANGE_PRIORITY','LOW','낮음',3 FROM DUAL UNION ALL
  SELECT 'CHANGE_STATUS','DRAFT','초안',1 FROM DUAL UNION ALL
  SELECT 'CHANGE_STATUS','SUBMITTED','제출',2 FROM DUAL UNION ALL
  SELECT 'CHANGE_STATUS','REVIEWING','검토중',3 FROM DUAL UNION ALL
  SELECT 'CHANGE_STATUS','APPROVED','승인',4 FROM DUAL UNION ALL
  SELECT 'CHANGE_STATUS','REJECTED','반려',5 FROM DUAL UNION ALL
  SELECT 'CHANGE_STATUS','IN_PROGRESS','진행중',6 FROM DUAL UNION ALL
  SELECT 'CHANGE_STATUS','COMPLETED','완료',7 FROM DUAL UNION ALL
  SELECT 'CHANGE_STATUS','CLOSED','종결',8 FROM DUAL UNION ALL
  -- MSA 교정
  SELECT 'CAL_TYPE','INTERNAL','자체교정',1 FROM DUAL UNION ALL
  SELECT 'CAL_TYPE','EXTERNAL','외부교정',2 FROM DUAL UNION ALL
  SELECT 'CAL_RESULT','PASS','합격',1 FROM DUAL UNION ALL
  SELECT 'CAL_RESULT','FAIL','불합격',2 FROM DUAL UNION ALL
  SELECT 'CAL_RESULT','CONDITIONAL','조건부합격',3 FROM DUAL UNION ALL
  -- 월간생산계획
  SELECT 'PROD_PLAN_STATUS','DRAFT','초안',1 FROM DUAL UNION ALL
  SELECT 'PROD_PLAN_STATUS','CONFIRMED','확정',2 FROM DUAL UNION ALL
  SELECT 'PROD_PLAN_STATUS','CLOSED','마감',3 FROM DUAL UNION ALL
  -- 금형 유형
  SELECT 'MOLD_TYPE','INJECTION','사출금형',1 FROM DUAL UNION ALL
  SELECT 'MOLD_TYPE','PRESS','프레스금형',2 FROM DUAL UNION ALL
  SELECT 'MOLD_TYPE','CRIMPING','크림핑금형',3 FROM DUAL UNION ALL
  SELECT 'MOLD_TYPE','OTHER','기타',4 FROM DUAL UNION ALL
  -- 소모품 운용상태
  SELECT 'CONSUMABLE_OPER_STATUS','WAREHOUSE','창고대기',1 FROM DUAL UNION ALL
  SELECT 'CONSUMABLE_OPER_STATUS','MOUNTED','장착중',2 FROM DUAL UNION ALL
  SELECT 'CONSUMABLE_OPER_STATUS','REPAIR','수리중',3 FROM DUAL UNION ALL
  -- 소모품 수명상태
  SELECT 'CONSUMABLE_LIFE_STATUS','NORMAL','정상',1 FROM DUAL UNION ALL
  SELECT 'CONSUMABLE_LIFE_STATUS','WARNING','주의',2 FROM DUAL UNION ALL
  SELECT 'CONSUMABLE_LIFE_STATUS','REPLACE','교체필요',3 FROM DUAL UNION ALL
  -- 제품 홀드 상태
  SELECT 'PRODUCT_HOLD_STATUS','NORMAL','정상',1 FROM DUAL UNION ALL
  SELECT 'PRODUCT_HOLD_STATUS','HOLD','홀드',2 FROM DUAL UNION ALL
  -- CAPA
  SELECT 'CAPA_TYPE','CORRECTIVE','시정조치',1 FROM DUAL UNION ALL
  SELECT 'CAPA_TYPE','PREVENTIVE','예방조치',2 FROM DUAL UNION ALL
  SELECT 'CAPA_SOURCE_TYPE','DEFECT','불량',1 FROM DUAL UNION ALL
  SELECT 'CAPA_SOURCE_TYPE','COMPLAINT','고객클레임',2 FROM DUAL UNION ALL
  SELECT 'CAPA_SOURCE_TYPE','AUDIT','감사',3 FROM DUAL UNION ALL
  SELECT 'CAPA_SOURCE_TYPE','REWORK','재작업',4 FROM DUAL UNION ALL
  SELECT 'CAPA_STATUS','OPEN','접수',1 FROM DUAL UNION ALL
  SELECT 'CAPA_STATUS','ANALYZING','원인분석중',2 FROM DUAL UNION ALL
  SELECT 'CAPA_STATUS','ACTION_PLANNED','조치계획',3 FROM DUAL UNION ALL
  SELECT 'CAPA_STATUS','IN_PROGRESS','조치진행',4 FROM DUAL UNION ALL
  SELECT 'CAPA_STATUS','VERIFYING','검증중',5 FROM DUAL UNION ALL
  SELECT 'CAPA_STATUS','CLOSED','종결',6 FROM DUAL UNION ALL
  SELECT 'CAPA_ACTION_STATUS','PENDING','대기',1 FROM DUAL UNION ALL
  SELECT 'CAPA_ACTION_STATUS','IN_PROGRESS','진행중',2 FROM DUAL UNION ALL
  SELECT 'CAPA_ACTION_STATUS','DONE','완료',3 FROM DUAL UNION ALL
  -- 고객클레임
  SELECT 'COMPLAINT_TYPE','QUALITY','품질불량',1 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_TYPE','DELIVERY','납기지연',2 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_TYPE','DAMAGE','파손',3 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_URGENCY','CRITICAL','긴급',1 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_URGENCY','HIGH','높음',2 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_URGENCY','MEDIUM','보통',3 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_URGENCY','LOW','낮음',4 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_STATUS','RECEIVED','접수',1 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_STATUS','INVESTIGATING','조사중',2 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_STATUS','RESPONDING','대응중',3 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_STATUS','RESOLVED','해결',4 FROM DUAL UNION ALL
  SELECT 'COMPLAINT_STATUS','CLOSED','종결',5 FROM DUAL UNION ALL
  -- 문서관리
  SELECT 'DOC_TYPE','PROCEDURE','절차서',1 FROM DUAL UNION ALL
  SELECT 'DOC_TYPE','WI','작업표준서',2 FROM DUAL UNION ALL
  SELECT 'DOC_TYPE','FORM','양식',3 FROM DUAL UNION ALL
  SELECT 'DOC_TYPE','SPEC','규격서',4 FROM DUAL UNION ALL
  SELECT 'DOC_TYPE','DRAWING','도면',5 FROM DUAL UNION ALL
  SELECT 'DOC_TYPE','MANUAL','매뉴얼',6 FROM DUAL UNION ALL
  SELECT 'DOC_STATUS','DRAFT','작성중',1 FROM DUAL UNION ALL
  SELECT 'DOC_STATUS','REVIEW','검토중',2 FROM DUAL UNION ALL
  SELECT 'DOC_STATUS','APPROVED','승인됨',3 FROM DUAL UNION ALL
  SELECT 'DOC_STATUS','OBSOLETE','폐기',4 FROM DUAL UNION ALL
  -- 관리계획서(Control Plan)
  SELECT 'CP_PHASE','PROTOTYPE','시작품',1 FROM DUAL UNION ALL
  SELECT 'CP_PHASE','PRE_LAUNCH','양산준비',2 FROM DUAL UNION ALL
  SELECT 'CP_PHASE','PRODUCTION','양산',3 FROM DUAL UNION ALL
  SELECT 'CP_STATUS','DRAFT','작성중',1 FROM DUAL UNION ALL
  SELECT 'CP_STATUS','REVIEW','검토중',2 FROM DUAL UNION ALL
  SELECT 'CP_STATUS','APPROVED','승인됨',3 FROM DUAL UNION ALL
  SELECT 'CP_STATUS','OBSOLETE','폐기',4 FROM DUAL UNION ALL
  -- OQC 상태
  SELECT 'OQC_STATUS','PENDING','대기',1 FROM DUAL UNION ALL
  SELECT 'OQC_STATUS','IN_PROGRESS','검사중',2 FROM DUAL UNION ALL
  SELECT 'OQC_STATUS','PASS','합격',3 FROM DUAL UNION ALL
  SELECT 'OQC_STATUS','FAIL','불합격',4 FROM DUAL UNION ALL
  -- 출하지시 상태
  SELECT 'SHIP_ORDER_STATUS','DRAFT','임시저장',1 FROM DUAL UNION ALL
  SELECT 'SHIP_ORDER_STATUS','CONFIRMED','확정',2 FROM DUAL UNION ALL
  SELECT 'SHIP_ORDER_STATUS','SHIPPING','출하중',3 FROM DUAL UNION ALL
  SELECT 'SHIP_ORDER_STATUS','SHIPPED','출하완료',4 FROM DUAL UNION ALL
  SELECT 'SHIP_ORDER_STATUS','CLOSED','마감',5 FROM DUAL UNION ALL
  -- 설비 점검유형
  SELECT 'INSPECT_CHECK_TYPE','DAILY','일상점검',1 FROM DUAL UNION ALL
  SELECT 'INSPECT_CHECK_TYPE','PERIODIC','정기점검',2 FROM DUAL UNION ALL
  SELECT 'INSPECT_CHECK_TYPE','WORKER','작업자점검',3 FROM DUAL UNION ALL
  -- 설비 점검판정
  SELECT 'INSPECT_JUDGE','PASS','합격',1 FROM DUAL UNION ALL
  SELECT 'INSPECT_JUDGE','FAIL','불합격',2 FROM DUAL UNION ALL
  SELECT 'INSPECT_JUDGE','CONDITIONAL','조건부합격',3 FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE)
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES (s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y', '40', '1000', 'claude', 'claude');
/
