-- Cleanup product receive residue for BX2606260001.
-- Target: JSHANES / company 40 / plant 1000
-- Root cause row confirmed before cleanup:
--   PRODUCT_TRANSACTIONS.PTX2026062600001 = WIP_OUT / REF_TYPE=BOX / REF_ID=BX2606260001 / STATUS=DONE
-- This file removes that receive history and restores stock to the pre-receive state.

DELETE FROM PRODUCT_TRANSACTIONS
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND (
     TRANS_NO = 'PTX2026062600001'
     OR CANCEL_REF_ID = 'PTX2026062600001'
   )
/

UPDATE PRODUCT_STOCKS
   SET QTY = QTY - 5,
       AVAILABLE_QTY = GREATEST(AVAILABLE_QTY - 5, 0),
       UPDATED_BY = 'cleanup',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND WAREHOUSE_CODE = 'FG_MAIN'
   AND ITEM_CODE = 'N91H00-X9800'
   AND QTY > 5
/

DELETE FROM PRODUCT_STOCKS
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND WAREHOUSE_CODE = 'FG_MAIN'
   AND ITEM_CODE = 'N91H00-X9800'
   AND QTY <= 5
   AND RESERVED_QTY = 0
/

MERGE INTO PRODUCT_STOCKS dst
USING (
  SELECT '40' AS COMPANY,
         '1000' AS PLANT_CD,
         'WIP_MAIN' AS WAREHOUSE_CODE,
         'N91H00-X9800' AS ITEM_CODE,
         'FINISHED' AS ITEM_TYPE,
         5 AS RESTORE_QTY
    FROM DUAL
) src
ON (
  dst.COMPANY = src.COMPANY
  AND dst.PLANT_CD = src.PLANT_CD
  AND dst.WAREHOUSE_CODE = src.WAREHOUSE_CODE
  AND dst.ITEM_CODE = src.ITEM_CODE
)
WHEN NOT MATCHED THEN
  INSERT (
    COMPANY, PLANT_CD, WAREHOUSE_CODE, LOCATION_CODE, ITEM_CODE, ITEM_TYPE,
    PRD_UID, ORDER_NO, PROCESS_CODE,
    QTY, RESERVED_QTY, AVAILABLE_QTY, STATUS,
    HOLD_REASON, HOLD_AT, HOLD_BY, LAST_COUNT,
    CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT, VERSION
  ) VALUES (
    src.COMPANY, src.PLANT_CD, src.WAREHOUSE_CODE, NULL, src.ITEM_CODE, src.ITEM_TYPE,
    NULL, 'WO-SEED-N91-X9800', NULL,
    src.RESTORE_QTY, 0, src.RESTORE_QTY, 'NORMAL',
    NULL, NULL, NULL, NULL,
    'cleanup', 'cleanup', SYSTIMESTAMP, SYSTIMESTAMP, 1
  )
WHEN MATCHED THEN
  UPDATE SET
    dst.ITEM_TYPE = src.ITEM_TYPE,
    dst.QTY = CASE
      WHEN NVL(dst.AVAILABLE_QTY, 0) < src.RESTORE_QTY
      THEN NVL(dst.RESERVED_QTY, 0) + src.RESTORE_QTY
      ELSE dst.QTY
    END,
    dst.AVAILABLE_QTY = GREATEST(NVL(dst.AVAILABLE_QTY, 0), src.RESTORE_QTY),
    dst.STATUS = 'NORMAL',
    dst.UPDATED_BY = 'cleanup',
    dst.UPDATED_AT = SYSTIMESTAMP
/
