BEGIN
  /* 2026-05-27: PURCHASE_ORDER_ITEMS REL_NO 컬럼 추가 및 UK 변경
   * 기존 UK(PO_ID+LINE_NO+REV_NO) → UK(PO_ID+LINE_NO+REL_NO)
   * REL_NO: ERP Release Number (Schedule Release 구분용)
   * 멱등성: 컬럼/인덱스 이미 존재 시 SKIP
   */

  -- 1. REL_NO 컬럼 추가
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PURCHASE_ORDER_ITEMS ADD (REL_NO NUMBER)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -01430 THEN RAISE; END IF;
  END;

  -- 2. 기존 UK 삭제 (존재 시)
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX UK_PO_ITEM_LINE_REV';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -01418 THEN RAISE; END IF;
  END;

  -- 3. 새 UK 생성 (PO_ID + LINE_NO + REL_NO)
  BEGIN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_PO_ITEM_LINE_REL ON PURCHASE_ORDER_ITEMS (PO_ID, LINE_NO, REL_NO)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -00955 THEN RAISE; END IF;
  END;

  -- 4. 컬럼 코멘트
  BEGIN
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.REL_NO IS 'ERP Release Number (Schedule Release 구분)']';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -00904 THEN RAISE; END IF;
  END;

  COMMIT;
END;
/