DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'MODEL_NAME';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS ADD (MODEL_NAME VARCHAR2(100))';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.MODEL_NAME IS '차종']';
END;
/
