DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'ROUTING_PROCESSES'
    AND COLUMN_NAME = 'JOB_ORDER_YN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (JOB_ORDER_YN VARCHAR2(1) DEFAULT ''Y'' NOT NULL)';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE TABLE_NAME = 'ROUTING_PROCESSES'
    AND CONSTRAINT_NAME = 'CK_ROUTING_PROC_JOB_ORDER_YN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE ROUTING_PROCESSES ADD CONSTRAINT CK_ROUTING_PROC_JOB_ORDER_YN CHECK (JOB_ORDER_YN IN ('Y', 'N'))]';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ROUTING_PROCESSES.JOB_ORDER_YN IS '공정 작업지시 생성 여부: Y=JOB_ORDERS OPERATION 생성, N=검사/참조 공정으로 작업지시 미생성']';
END;
/
