BEGIN
  MERGE INTO MENU_CATEGORY_ITEMS t
  USING (
    SELECT 'PROD_KITTING' MENU_CODE, 'PRODUCTION' CATEGORY_CODE, 36 SORT_ORDER, '40' COMPANY, '1000' PLANT_CD FROM DUAL
  ) s
  ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
  WHEN NOT MATCHED THEN
    INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
    VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD, 'migration', 'migration');
  COMMIT;
END;
/
