-- LINE_NO NULL 백필 후 NOT NULL, (PO_ID, LINE_NO, REV_NO) UNIQUE 인덱스 추가
-- ERP 인터페이스 기준: PO 식별은 PO번호 + L/N + R/N 3키 조합

BEGIN
  -- 1. LINE_NO NULL → SEQ 백필 (ERP 연동 전 수동 입력 데이터)
  EXECUTE IMMEDIATE 'UPDATE PURCHASE_ORDER_ITEMS SET LINE_NO = SEQ WHERE LINE_NO IS NULL';

  -- 2. LINE_NO NOT NULL 제약
  EXECUTE IMMEDIATE 'ALTER TABLE PURCHASE_ORDER_ITEMS MODIFY (LINE_NO NUMBER NOT NULL)';

  -- 3. 비즈니스 식별 UNIQUE 인덱스: PO번호 + Line번호 + Release번호
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_PO_ITEM_LINE_REV ON PURCHASE_ORDER_ITEMS (PO_ID, LINE_NO, REV_NO)';
END;
/
