DECLARE
  v_count NUMBER;
  v_index_ddl CLOB;
  v_index_text VARCHAR2(32767);
  v_index_expressions VARCHAR2(4000);

  PROCEDURE assert_true(p_ok BOOLEAN, p_message VARCHAR2) IS
  BEGIN
    IF p_ok IS NULL OR NOT p_ok THEN
      RAISE_APPLICATION_ERROR(-20001, p_message);
    END IF;
  END;

  PROCEDURE assert_default(p_table VARCHAR2, p_column VARCHAR2, p_default VARCHAR2) IS
    l_xml XMLTYPE;
    l_default VARCHAR2(4000);
    l_table VARCHAR2(128);
    l_column VARCHAR2(128);
  BEGIN
    l_table := DBMS_ASSERT.SIMPLE_SQL_NAME(UPPER(p_table));
    l_column := DBMS_ASSERT.SIMPLE_SQL_NAME(UPPER(p_column));
    l_xml := DBMS_XMLGEN.GETXMLTYPE(
      'SELECT DATA_DEFAULT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = '
      || DBMS_ASSERT.ENQUOTE_LITERAL(l_table)
      || ' AND COLUMN_NAME = ' || DBMS_ASSERT.ENQUOTE_LITERAL(l_column)
    );
    SELECT XMLCAST(XMLQUERY('/ROWSET/ROW/DATA_DEFAULT/text()'
             PASSING l_xml RETURNING CONTENT) AS VARCHAR2(4000))
      INTO l_default FROM DUAL;
    assert_true(REPLACE(UPPER(TRIM(l_default)), ' ', '') = REPLACE(UPPER(p_default), ' ', ''),
      p_table || '.' || p_column || ' default mismatch');
  END;

  PROCEDURE assert_column(
    p_table VARCHAR2, p_column VARCHAR2, p_type VARCHAR2,
    p_length NUMBER, p_precision NUMBER, p_scale NUMBER, p_nullable VARCHAR2
  ) IS
    l_type USER_TAB_COLUMNS.DATA_TYPE%TYPE;
    l_length USER_TAB_COLUMNS.DATA_LENGTH%TYPE;
    l_precision USER_TAB_COLUMNS.DATA_PRECISION%TYPE;
    l_scale USER_TAB_COLUMNS.DATA_SCALE%TYPE;
    l_nullable USER_TAB_COLUMNS.NULLABLE%TYPE;
  BEGIN
    SELECT DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE
      INTO l_type, l_length, l_precision, l_scale, l_nullable
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_column;
    assert_true(l_type = p_type
      AND (p_length IS NULL OR l_length = p_length)
      AND (p_precision IS NULL OR l_precision = p_precision)
      AND (p_scale IS NULL OR l_scale = p_scale)
      AND l_nullable = p_nullable,
      p_table || '.' || p_column || ' definition mismatch');
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20002, p_table || '.' || p_column || ' is missing');
  END;

  PROCEDURE assert_fk_target(p_name VARCHAR2, p_target VARCHAR2, p_columns VARCHAR2) IS
    l_target USER_CONSTRAINTS.TABLE_NAME%TYPE;
    l_columns VARCHAR2(4000);
  BEGIN
    SELECT r.TABLE_NAME INTO l_target
      FROM USER_CONSTRAINTS f
      JOIN USER_CONSTRAINTS r ON r.CONSTRAINT_NAME = f.R_CONSTRAINT_NAME
     WHERE f.CONSTRAINT_NAME = p_name;
    SELECT LISTAGG(r.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY r.POSITION)
      INTO l_columns
      FROM USER_CONSTRAINTS f
      JOIN USER_CONS_COLUMNS r ON r.CONSTRAINT_NAME = f.R_CONSTRAINT_NAME
     WHERE f.CONSTRAINT_NAME = p_name;
    assert_true(l_target = p_target AND l_columns = p_columns, p_name || ' target mismatch');
  END;

  PROCEDURE assert_constraint(
    p_name VARCHAR2, p_table VARCHAR2, p_type VARCHAR2, p_columns VARCHAR2
  ) IS
    l_type USER_CONSTRAINTS.CONSTRAINT_TYPE%TYPE;
    l_table USER_CONSTRAINTS.TABLE_NAME%TYPE;
    l_columns VARCHAR2(4000);
  BEGIN
    SELECT CONSTRAINT_TYPE, TABLE_NAME INTO l_type, l_table
      FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = p_name;
    SELECT LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY POSITION)
      INTO l_columns FROM USER_CONS_COLUMNS WHERE CONSTRAINT_NAME = p_name;
    assert_true(l_type = p_type AND l_table = p_table AND l_columns = p_columns,
      p_name || ' definition mismatch');
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20003, p_name || ' is missing');
  END;

  PROCEDURE assert_check(p_name VARCHAR2, p_table VARCHAR2, p_text VARCHAR2) IS
    l_table USER_CONSTRAINTS.TABLE_NAME%TYPE;
    l_text USER_CONSTRAINTS.SEARCH_CONDITION_VC%TYPE;
  BEGIN
    SELECT TABLE_NAME, SEARCH_CONDITION_VC INTO l_table, l_text
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = p_name AND CONSTRAINT_TYPE = 'C';
    assert_true(l_table = p_table
      AND REGEXP_REPLACE(REPLACE(UPPER(l_text), '"', ''), '[[:space:]]+', '')
        = REGEXP_REPLACE(UPPER(p_text), '[[:space:]]+', ''),
      p_name || ' definition mismatch');
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20004, p_name || ' is missing');
  END;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'IP_ROUTING_GROUPS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE IP_ROUTING_GROUPS (
        ORGANIZATION_ID NUMBER NOT NULL,
        ROUTING_CODE VARCHAR2(50) NOT NULL,
        ITEM_CODE VARCHAR2(20) NOT NULL,
        ROUTING_NAME VARCHAR2(200) NOT NULL,
        DESCRIPTION VARCHAR2(500),
        USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        CREATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_BY VARCHAR2(50),
        UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_IP_ROUTING_GROUPS PRIMARY KEY (ORGANIZATION_ID, ROUTING_CODE),
        CONSTRAINT FK_IP_RG_ITEM FOREIGN KEY (ITEM_CODE, ORGANIZATION_ID)
          REFERENCES ID_ITEM (ITEM_CODE, ORGANIZATION_ID),
        CONSTRAINT CK_IP_RG_USE CHECK (USE_YN IN ('Y', 'N'))
      )~';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'IP_ROUTING_PROCESSES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE IP_ROUTING_PROCESSES (
        ORGANIZATION_ID NUMBER NOT NULL,
        ROUTING_CODE VARCHAR2(50) NOT NULL,
        PROCESS_SEQ NUMBER(10) NOT NULL,
        WORKSTAGE_CODE VARCHAR2(10) NOT NULL,
        EXECUTION_TYPE VARCHAR2(20) DEFAULT 'INTERNAL' NOT NULL,
        JOB_ORDER_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        SUBCON_SUPPLIER_CODE VARCHAR2(20),
        STANDARD_TIME NUMBER(10,4),
        SETUP_TIME NUMBER(10,4),
        USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        CREATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_BY VARCHAR2(50),
        UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_IP_ROUTING_PROCESSES PRIMARY KEY (ORGANIZATION_ID, ROUTING_CODE, PROCESS_SEQ),
        CONSTRAINT FK_IP_RP_GROUP FOREIGN KEY (ORGANIZATION_ID, ROUTING_CODE)
          REFERENCES IP_ROUTING_GROUPS (ORGANIZATION_ID, ROUTING_CODE),
        CONSTRAINT FK_IP_RP_STAGE FOREIGN KEY (WORKSTAGE_CODE, ORGANIZATION_ID)
          REFERENCES IP_PRODUCT_WORKSTAGE (WORKSTAGE_CODE, ORGANIZATION_ID),
        CONSTRAINT FK_IP_RP_SUPPLIER FOREIGN KEY (SUBCON_SUPPLIER_CODE, ORGANIZATION_ID)
          REFERENCES ICOM_SUPPLIER (SUPPLIER_CODE, ORGANIZATION_ID),
        CONSTRAINT CK_IP_RP_SEQ CHECK (PROCESS_SEQ > 0),
        CONSTRAINT CK_IP_RP_EXEC CHECK (EXECUTION_TYPE IN ('INTERNAL', 'SUBCON')),
        CONSTRAINT CK_IP_RP_SUPPLIER CHECK (
          (EXECUTION_TYPE = 'SUBCON' AND SUBCON_SUPPLIER_CODE IS NOT NULL) OR
          (EXECUTION_TYPE = 'INTERNAL' AND SUBCON_SUPPLIER_CODE IS NULL)
        ),
        CONSTRAINT CK_IP_RP_JOB CHECK (JOB_ORDER_YN IN ('Y', 'N')),
        CONSTRAINT CK_IP_RP_STD_TIME CHECK (STANDARD_TIME IS NULL OR STANDARD_TIME >= 0),
        CONSTRAINT CK_IP_RP_SETUP_TIME CHECK (SETUP_TIME IS NULL OR SETUP_TIME >= 0),
        CONSTRAINT CK_IP_RP_USE CHECK (USE_YN IN ('Y', 'N'))
      )~';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'IP_ROUTING_MATERIALS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE IP_ROUTING_MATERIALS (
        ORGANIZATION_ID NUMBER NOT NULL,
        ROUTING_CODE VARCHAR2(50) NOT NULL,
        PROCESS_SEQ NUMBER(10) NOT NULL,
        CHILD_ITEM_CODE VARCHAR2(20) NOT NULL,
        ALLOC_QTY NUMBER(18,6) NOT NULL,
        ISSUE_METHOD VARCHAR2(20) DEFAULT 'BACKFLUSH' NOT NULL,
        CREATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_BY VARCHAR2(50),
        UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_IP_ROUTING_MATERIALS PRIMARY KEY (ORGANIZATION_ID, ROUTING_CODE, PROCESS_SEQ, CHILD_ITEM_CODE),
        CONSTRAINT FK_IP_RM_PROCESS FOREIGN KEY (ORGANIZATION_ID, ROUTING_CODE, PROCESS_SEQ)
          REFERENCES IP_ROUTING_PROCESSES (ORGANIZATION_ID, ROUTING_CODE, PROCESS_SEQ)
          DEFERRABLE INITIALLY IMMEDIATE,
        CONSTRAINT FK_IP_RM_ITEM FOREIGN KEY (CHILD_ITEM_CODE, ORGANIZATION_ID)
          REFERENCES ID_ITEM (ITEM_CODE, ORGANIZATION_ID),
        CONSTRAINT UK_IP_RM_CHILD UNIQUE (ORGANIZATION_ID, ROUTING_CODE, CHILD_ITEM_CODE),
        CONSTRAINT CK_IP_RM_QTY CHECK (ALLOC_QTY > 0),
        CONSTRAINT CK_IP_RM_METHOD CHECK (ISSUE_METHOD IN ('BACKFLUSH', 'PRE_ISSUE'))
      )~';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'UK_IP_RG_ACTIVE_ITEM';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE UNIQUE INDEX UK_IP_RG_ACTIVE_ITEM ON IP_ROUTING_GROUPS (
        CASE USE_YN WHEN 'Y' THEN ORGANIZATION_ID END,
        CASE USE_YN WHEN 'Y' THEN ITEM_CODE END
      )~';
  END IF;

  assert_column('IP_ROUTING_GROUPS', 'ORGANIZATION_ID', 'NUMBER', NULL, NULL, NULL, 'N');
  assert_column('IP_ROUTING_GROUPS', 'ROUTING_CODE', 'VARCHAR2', 50, NULL, NULL, 'N');
  assert_column('IP_ROUTING_GROUPS', 'ITEM_CODE', 'VARCHAR2', 20, NULL, NULL, 'N');
  assert_column('IP_ROUTING_GROUPS', 'ROUTING_NAME', 'VARCHAR2', 200, NULL, NULL, 'N');
  assert_column('IP_ROUTING_GROUPS', 'DESCRIPTION', 'VARCHAR2', 500, NULL, NULL, 'Y');
  assert_column('IP_ROUTING_GROUPS', 'USE_YN', 'VARCHAR2', 1, NULL, NULL, 'N');
  assert_column('IP_ROUTING_GROUPS', 'CREATED_BY', 'VARCHAR2', 50, NULL, NULL, 'Y');
  assert_column('IP_ROUTING_GROUPS', 'CREATED_AT', 'TIMESTAMP(6)', 11, NULL, 6, 'N');
  assert_column('IP_ROUTING_GROUPS', 'UPDATED_BY', 'VARCHAR2', 50, NULL, NULL, 'Y');
  assert_column('IP_ROUTING_GROUPS', 'UPDATED_AT', 'TIMESTAMP(6)', 11, NULL, 6, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'ORGANIZATION_ID', 'NUMBER', NULL, NULL, NULL, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'ROUTING_CODE', 'VARCHAR2', 50, NULL, NULL, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'PROCESS_SEQ', 'NUMBER', NULL, 10, 0, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'WORKSTAGE_CODE', 'VARCHAR2', 10, NULL, NULL, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'EXECUTION_TYPE', 'VARCHAR2', 20, NULL, NULL, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'JOB_ORDER_YN', 'VARCHAR2', 1, NULL, NULL, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'SUBCON_SUPPLIER_CODE', 'VARCHAR2', 20, NULL, NULL, 'Y');
  assert_column('IP_ROUTING_PROCESSES', 'STANDARD_TIME', 'NUMBER', NULL, 10, 4, 'Y');
  assert_column('IP_ROUTING_PROCESSES', 'SETUP_TIME', 'NUMBER', NULL, 10, 4, 'Y');
  assert_column('IP_ROUTING_PROCESSES', 'USE_YN', 'VARCHAR2', 1, NULL, NULL, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'CREATED_BY', 'VARCHAR2', 50, NULL, NULL, 'Y');
  assert_column('IP_ROUTING_PROCESSES', 'CREATED_AT', 'TIMESTAMP(6)', 11, NULL, 6, 'N');
  assert_column('IP_ROUTING_PROCESSES', 'UPDATED_BY', 'VARCHAR2', 50, NULL, NULL, 'Y');
  assert_column('IP_ROUTING_PROCESSES', 'UPDATED_AT', 'TIMESTAMP(6)', 11, NULL, 6, 'N');
  assert_column('IP_ROUTING_MATERIALS', 'ORGANIZATION_ID', 'NUMBER', NULL, NULL, NULL, 'N');
  assert_column('IP_ROUTING_MATERIALS', 'ROUTING_CODE', 'VARCHAR2', 50, NULL, NULL, 'N');
  assert_column('IP_ROUTING_MATERIALS', 'PROCESS_SEQ', 'NUMBER', NULL, 10, 0, 'N');
  assert_column('IP_ROUTING_MATERIALS', 'CHILD_ITEM_CODE', 'VARCHAR2', 20, NULL, NULL, 'N');
  assert_column('IP_ROUTING_MATERIALS', 'ALLOC_QTY', 'NUMBER', NULL, 18, 6, 'N');
  assert_column('IP_ROUTING_MATERIALS', 'ISSUE_METHOD', 'VARCHAR2', 20, NULL, NULL, 'N');
  assert_column('IP_ROUTING_MATERIALS', 'CREATED_BY', 'VARCHAR2', 50, NULL, NULL, 'Y');
  assert_column('IP_ROUTING_MATERIALS', 'CREATED_AT', 'TIMESTAMP(6)', 11, NULL, 6, 'N');
  assert_column('IP_ROUTING_MATERIALS', 'UPDATED_BY', 'VARCHAR2', 50, NULL, NULL, 'Y');
  assert_column('IP_ROUTING_MATERIALS', 'UPDATED_AT', 'TIMESTAMP(6)', 11, NULL, 6, 'N');

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IP_ROUTING_GROUPS';
  assert_true(v_count = 10, 'IP_ROUTING_GROUPS column count mismatch');
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IP_ROUTING_PROCESSES';
  assert_true(v_count = 14, 'IP_ROUTING_PROCESSES column count mismatch');
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IP_ROUTING_MATERIALS';
  assert_true(v_count = 10, 'IP_ROUTING_MATERIALS column count mismatch');

  assert_default('IP_ROUTING_GROUPS', 'USE_YN', '''Y''');
  assert_default('IP_ROUTING_GROUPS', 'CREATED_AT', 'SYSTIMESTAMP');
  assert_default('IP_ROUTING_GROUPS', 'UPDATED_AT', 'SYSTIMESTAMP');
  assert_default('IP_ROUTING_PROCESSES', 'EXECUTION_TYPE', '''INTERNAL''');
  assert_default('IP_ROUTING_PROCESSES', 'JOB_ORDER_YN', '''Y''');
  assert_default('IP_ROUTING_PROCESSES', 'USE_YN', '''Y''');
  assert_default('IP_ROUTING_PROCESSES', 'CREATED_AT', 'SYSTIMESTAMP');
  assert_default('IP_ROUTING_PROCESSES', 'UPDATED_AT', 'SYSTIMESTAMP');
  assert_default('IP_ROUTING_MATERIALS', 'ISSUE_METHOD', '''BACKFLUSH''');
  assert_default('IP_ROUTING_MATERIALS', 'CREATED_AT', 'SYSTIMESTAMP');
  assert_default('IP_ROUTING_MATERIALS', 'UPDATED_AT', 'SYSTIMESTAMP');

  assert_constraint('PK_IP_ROUTING_GROUPS', 'IP_ROUTING_GROUPS', 'P', 'ORGANIZATION_ID,ROUTING_CODE');
  assert_constraint('FK_IP_RG_ITEM', 'IP_ROUTING_GROUPS', 'R', 'ITEM_CODE,ORGANIZATION_ID');
  assert_constraint('PK_IP_ROUTING_PROCESSES', 'IP_ROUTING_PROCESSES', 'P', 'ORGANIZATION_ID,ROUTING_CODE,PROCESS_SEQ');
  assert_constraint('FK_IP_RP_GROUP', 'IP_ROUTING_PROCESSES', 'R', 'ORGANIZATION_ID,ROUTING_CODE');
  assert_constraint('FK_IP_RP_STAGE', 'IP_ROUTING_PROCESSES', 'R', 'WORKSTAGE_CODE,ORGANIZATION_ID');
  assert_constraint('FK_IP_RP_SUPPLIER', 'IP_ROUTING_PROCESSES', 'R', 'SUBCON_SUPPLIER_CODE,ORGANIZATION_ID');
  assert_constraint('PK_IP_ROUTING_MATERIALS', 'IP_ROUTING_MATERIALS', 'P', 'ORGANIZATION_ID,ROUTING_CODE,PROCESS_SEQ,CHILD_ITEM_CODE');
  assert_constraint('FK_IP_RM_PROCESS', 'IP_ROUTING_MATERIALS', 'R', 'ORGANIZATION_ID,ROUTING_CODE,PROCESS_SEQ');
  assert_constraint('FK_IP_RM_ITEM', 'IP_ROUTING_MATERIALS', 'R', 'CHILD_ITEM_CODE,ORGANIZATION_ID');
  assert_constraint('UK_IP_RM_CHILD', 'IP_ROUTING_MATERIALS', 'U', 'ORGANIZATION_ID,ROUTING_CODE,CHILD_ITEM_CODE');
  assert_fk_target('FK_IP_RG_ITEM', 'ID_ITEM', 'ITEM_CODE,ORGANIZATION_ID');
  assert_fk_target('FK_IP_RP_GROUP', 'IP_ROUTING_GROUPS', 'ORGANIZATION_ID,ROUTING_CODE');
  assert_fk_target('FK_IP_RP_STAGE', 'IP_PRODUCT_WORKSTAGE', 'WORKSTAGE_CODE,ORGANIZATION_ID');
  assert_fk_target('FK_IP_RP_SUPPLIER', 'ICOM_SUPPLIER', 'SUPPLIER_CODE,ORGANIZATION_ID');
  assert_fk_target('FK_IP_RM_PROCESS', 'IP_ROUTING_PROCESSES', 'ORGANIZATION_ID,ROUTING_CODE,PROCESS_SEQ');
  assert_fk_target('FK_IP_RM_ITEM', 'ID_ITEM', 'ITEM_CODE,ORGANIZATION_ID');

  assert_check('CK_IP_RG_USE', 'IP_ROUTING_GROUPS', 'USE_YN IN (''Y'', ''N'')');
  assert_check('CK_IP_RP_SEQ', 'IP_ROUTING_PROCESSES', 'PROCESS_SEQ > 0');
  assert_check('CK_IP_RP_EXEC', 'IP_ROUTING_PROCESSES', 'EXECUTION_TYPE IN (''INTERNAL'', ''SUBCON'')');
  assert_check('CK_IP_RP_SUPPLIER', 'IP_ROUTING_PROCESSES', '(EXECUTION_TYPE = ''SUBCON'' AND SUBCON_SUPPLIER_CODE IS NOT NULL) OR (EXECUTION_TYPE = ''INTERNAL'' AND SUBCON_SUPPLIER_CODE IS NULL)');
  assert_check('CK_IP_RP_JOB', 'IP_ROUTING_PROCESSES', 'JOB_ORDER_YN IN (''Y'', ''N'')');
  assert_check('CK_IP_RP_STD_TIME', 'IP_ROUTING_PROCESSES', 'STANDARD_TIME IS NULL OR STANDARD_TIME >= 0');
  assert_check('CK_IP_RP_SETUP_TIME', 'IP_ROUTING_PROCESSES', 'SETUP_TIME IS NULL OR SETUP_TIME >= 0');
  assert_check('CK_IP_RP_USE', 'IP_ROUTING_PROCESSES', 'USE_YN IN (''Y'', ''N'')');
  assert_check('CK_IP_RM_QTY', 'IP_ROUTING_MATERIALS', 'ALLOC_QTY > 0');
  assert_check('CK_IP_RM_METHOD', 'IP_ROUTING_MATERIALS', 'ISSUE_METHOD IN (''BACKFLUSH'', ''PRE_ISSUE'')');

  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'FK_IP_RM_PROCESS'
     AND DEFERRABLE = 'DEFERRABLE' AND DEFERRED = 'IMMEDIATE';
  assert_true(v_count = 1, 'FK_IP_RM_PROCESS deferrability mismatch');

  SELECT COUNT(*) INTO v_count
    FROM USER_IND_COLUMNS
   WHERE INDEX_NAME = 'UK_IP_RG_ACTIVE_ITEM'
     AND TABLE_NAME = 'IP_ROUTING_GROUPS';
  assert_true(v_count = 2, 'UK_IP_RG_ACTIVE_ITEM column count mismatch');

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES
   WHERE INDEX_NAME = 'UK_IP_RG_ACTIVE_ITEM'
     AND TABLE_NAME = 'IP_ROUTING_GROUPS' AND UNIQUENESS = 'UNIQUE';
  assert_true(v_count = 1, 'UK_IP_RG_ACTIVE_ITEM properties mismatch');

  v_index_ddl := DBMS_METADATA.GET_DDL('INDEX', 'UK_IP_RG_ACTIVE_ITEM');
  v_index_text := REGEXP_REPLACE(
    REPLACE(UPPER(DBMS_LOB.SUBSTR(v_index_ddl, 32767, 1)), '"', ''),
    '[[:space:]]+', ''
  );
  v_index_expressions := REGEXP_SUBSTR(
    v_index_text, 'IP_ROUTING_GROUPS\(([^)]*)\)', 1, 1, NULL, 1
  );
  assert_true(v_index_expressions =
    'CASEUSE_YNWHEN''Y''THENORGANIZATION_IDEND,CASEUSE_YNWHEN''Y''THENITEM_CODEEND',
    'UK_IP_RG_ACTIVE_ITEM definition mismatch');
END;
/
