-- 생산월력 공통코드 시드 (멱등)
-- WORK DAY TYPE: 근무유형, DAY OFF TYPE: 휴무사유
-- 은성 공통코드 조회는 groupCode의 언더스코어를 공백으로 정규화해 CODE_TYPE과 매칭한다.
-- (구조테스트 'common code lookup normalizes column names and CODE_TYPE spacing' 참조)
-- 따라서 프론트의 groupCode "WORK_DAY_TYPE" → CODE_TYPE 'WORK DAY TYPE'.
MERGE INTO ISYS_BASECODE t
USING (
  SELECT 'WORK DAY TYPE' AS CODE_TYPE, 'WORK'    AS CODE_NAME, '근무'     AS CODE_MEAN_KOR, 'WORK'           AS CODE_MEAN_ENG, 1 AS ORGANIZATION_ID FROM DUAL UNION ALL
  SELECT 'WORK DAY TYPE', 'OFF',            '휴무',     'DAY OFF',        1 FROM DUAL UNION ALL
  SELECT 'WORK DAY TYPE', 'HALF',           '반일',     'HALF DAY',       1 FROM DUAL UNION ALL
  SELECT 'WORK DAY TYPE', 'SPECIAL',        '특근',     'SPECIAL WORK',   1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'WEEKEND',        '주말',     'WEEKEND',        1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'HOLIDAY',        '공휴일',   'PUBLIC HOLIDAY', 1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'PLANT_SHUTDOWN', '공장휴무', 'PLANT SHUTDOWN', 1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'LINE_STOP',      '라인정지', 'LINE STOP',      1 FROM DUAL
) s
ON (t.CODE_TYPE = s.CODE_TYPE AND t.CODE_NAME = s.CODE_NAME AND t.ORGANIZATION_ID = s.ORGANIZATION_ID)
WHEN NOT MATCHED THEN
  INSERT (CODE_TYPE, CODE_NAME, ORGANIZATION_ID, CODE_MEAN_KOR, CODE_MEAN_ENG, CODE_GROUP, ENTER_BY, ENTER_DATE)
  VALUES (s.CODE_TYPE, s.CODE_NAME, s.ORGANIZATION_ID, s.CODE_MEAN_KOR, s.CODE_MEAN_ENG, 'SYSTEM', 'SYSTEM', SYSDATE);
/
