-- 제품 불량창고입고(PROD_DEFECT_TRANSFER) 메뉴 DB 시드
-- 신규 leaf: PROD_DEFECT_TRANSFER / path /product/defect-transfer / labelKey menu.productMgmt.defectTransfer
-- 멀티테넌시 정본: COMPANY='40', PLANT_CD='1000'. 멱등 MERGE.

MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'PROD_DEFECT_TRANSFER' AS MENU_CODE,
         'PRODUCT_MGMT'         AS CATEGORY_CODE,
         35                     AS SORT_ORDER,
         '40'                   AS COMPANY,
         '1000'                 AS PLANT_CD
  FROM dual
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD,
          CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD,
          SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system')
/

MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER' AS ROLE_CODE, 'PROD_DEFECT_TRANSFER' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
  UNION ALL
  SELECT 'OPERATOR' AS ROLE_CODE, 'PROD_DEFECT_TRANSFER' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD)
/
