BEGIN
  /*
   * 2026-05-26: IQC005 Phase A — 제조사 거래처 시드 + RAW_MATERIAL LOT_UNIT_QTY 보강
   * PARTNER_MASTERS: PARTNER_TYPE='MFG' 5건 (한성정밀/비나마이크로/ABC Industries/대성하이텍/KH Vietnam)
   * ITEM_MASTERS: RAW_MATERIAL인데 LOT_UNIT_QTY NULL인 행에 기본값 50 적용
   */
  MERGE INTO PARTNER_MASTERS p
  USING (
    SELECT 'M001' AS PARTNER_CODE, '한성정밀' AS PARTNER_NAME FROM DUAL UNION ALL
    SELECT 'M002', '비나마이크로' FROM DUAL UNION ALL
    SELECT 'M003', 'ABC Industries' FROM DUAL UNION ALL
    SELECT 'M004', '대성하이텍' FROM DUAL UNION ALL
    SELECT 'M005', 'KH Vietnam' FROM DUAL
  ) s ON (p.PARTNER_CODE = s.PARTNER_CODE)
  WHEN MATCHED THEN UPDATE SET PARTNER_NAME = s.PARTNER_NAME, PARTNER_TYPE = 'MFG', USE_YN = 'Y'
  WHEN NOT MATCHED THEN INSERT
    (PARTNER_CODE, PARTNER_NAME, PARTNER_TYPE, USE_YN, COMPANY, PLANT_CD, CREATED_BY)
  VALUES
    (s.PARTNER_CODE, s.PARTNER_NAME, 'MFG', 'Y', '40', '1000', 'SYSTEM');

  UPDATE ITEM_MASTERS
     SET LOT_UNIT_QTY = 50
   WHERE COMPANY = '40'
     AND ITEM_TYPE = 'RAW_MATERIAL'
     AND LOT_UNIT_QTY IS NULL;

  COMMIT;
END;
/
