-- 2026-06-26 WORKER_NO → WORKER_CODE 스키마 통일
-- WORKER_MASTERS.WORKER_CODE(자연키 PK)를 참조하는 20개 트랜잭션/로그 테이블의
-- WORKER_NO 컬럼을 WORKER_CODE로 rename 하여 명명을 일치시킨다.
-- 각 문장은 '/' 로 분리되어 독립 실행된다. (적용 시점 DB는 전부 WORKER_NO 상태)
-- 재실행 시 이미 변경된 컬럼은 ORA-00904로 실패하지만 무해하다(일회성 마이그레이션).
ALTER TABLE CONSUMABLE_LOGS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE CONSUMABLE_MOUNT_LOGS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE CUSTOMS_USAGE_REPORTS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE FG_LABELS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE LABEL_PRINT_LOGS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE MAT_ARRIVALS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE MAT_ARRIVAL_TRANSACTIONS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE MAT_ISSUES RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE MAT_RECEIVINGS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE PRODUCT_TRANSACTIONS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE PROD_RESULTS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE REPAIR_LOGS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE REPAIR_ORDERS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE SG_LABELS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE STOCK_TRANSACTIONS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE STOCK_TRANSACTIONS_BAK_20260616 RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE SUBCON_DELIVERIES RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE SUBCON_RECEIVES RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE TRACE_LOGS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER TABLE WIP_MAT_TRANSACTIONS RENAME COLUMN WORKER_NO TO WORKER_CODE;
/
ALTER INDEX IDX_REPAIR_ORDERS_WORKER_NO RENAME TO IDX_REPAIR_ORDERS_WORKER_CODE;
/
