-- 반제품 샘플검사이력 시드 데이터
-- SAMPLE_INSPECT_RESULTS
-- 화면: /production/sample-inspect

-- JO-FIX-105736 (샘플 3개)
INSERT INTO SAMPLE_INSPECT_RESULTS (
  ORDER_NO, INSPECT_DATE, INSPECTOR_NAME, INSPECT_TYPE,
  SAMPLE_NO, MEASURED_VALUE, SPEC_UPPER, SPEC_LOWER, PASS_YN,
  REMARK, COMPANY, PLANT_CD
) VALUES (
  'JO-FIX-105736', TO_DATE('2026-06-12', 'YYYY-MM-DD'), '김철수', 'DIMENSION',
  1, '25.3', '26.0', '24.0', 'Y',
  NULL, '40', '1000'
)
/
INSERT INTO SAMPLE_INSPECT_RESULTS (
  ORDER_NO, INSPECT_DATE, INSPECTOR_NAME, INSPECT_TYPE,
  SAMPLE_NO, MEASURED_VALUE, SPEC_UPPER, SPEC_LOWER, PASS_YN,
  REMARK, COMPANY, PLANT_CD
) VALUES (
  'JO-FIX-105736', TO_DATE('2026-06-12', 'YYYY-MM-DD'), '김철수', 'DIMENSION',
  2, '25.7', '26.0', '24.0', 'Y',
  NULL, '40', '1000'
)
/
INSERT INTO SAMPLE_INSPECT_RESULTS (
  ORDER_NO, INSPECT_DATE, INSPECTOR_NAME, INSPECT_TYPE,
  SAMPLE_NO, MEASURED_VALUE, SPEC_UPPER, SPEC_LOWER, PASS_YN,
  REMARK, COMPANY, PLANT_CD
) VALUES (
  'JO-FIX-105736', TO_DATE('2026-06-12', 'YYYY-MM-DD'), '김철수', 'DIMENSION',
  3, '26.5', '26.0', '24.0', 'N',
  '상한 초과 — 재작업 필요', '40', '1000'
)
/

-- JO-FIX-105654 (샘플 3개)
INSERT INTO SAMPLE_INSPECT_RESULTS (
  ORDER_NO, INSPECT_DATE, INSPECTOR_NAME, INSPECT_TYPE,
  SAMPLE_NO, MEASURED_VALUE, SPEC_UPPER, SPEC_LOWER, PASS_YN,
  REMARK, COMPANY, PLANT_CD
) VALUES (
  'JO-FIX-105654', TO_DATE('2026-06-12', 'YYYY-MM-DD'), '이영희', 'APPEARANCE',
  1, NULL, NULL, NULL, 'Y',
  '외관 이상 없음', '40', '1000'
)
/
INSERT INTO SAMPLE_INSPECT_RESULTS (
  ORDER_NO, INSPECT_DATE, INSPECTOR_NAME, INSPECT_TYPE,
  SAMPLE_NO, MEASURED_VALUE, SPEC_UPPER, SPEC_LOWER, PASS_YN,
  REMARK, COMPANY, PLANT_CD
) VALUES (
  'JO-FIX-105654', TO_DATE('2026-06-12', 'YYYY-MM-DD'), '이영희', 'APPEARANCE',
  2, NULL, NULL, NULL, 'Y',
  NULL, '40', '1000'
)
/
INSERT INTO SAMPLE_INSPECT_RESULTS (
  ORDER_NO, INSPECT_DATE, INSPECTOR_NAME, INSPECT_TYPE,
  SAMPLE_NO, MEASURED_VALUE, SPEC_UPPER, SPEC_LOWER, PASS_YN,
  REMARK, COMPANY, PLANT_CD
) VALUES (
  'JO-FIX-105654', TO_DATE('2026-06-12', 'YYYY-MM-DD'), '이영희', 'APPEARANCE',
  3, NULL, NULL, NULL, 'N',
  '스크래치 발견', '40', '1000'
)
/

-- JO-20260612-375-01-01-02-01 (샘플 2개)
INSERT INTO SAMPLE_INSPECT_RESULTS (
  ORDER_NO, INSPECT_DATE, INSPECTOR_NAME, INSPECT_TYPE,
  SAMPLE_NO, MEASURED_VALUE, SPEC_UPPER, SPEC_LOWER, PASS_YN,
  REMARK, COMPANY, PLANT_CD
) VALUES (
  'JO-20260612-375-01-01-02-01', TO_DATE('2026-06-12', 'YYYY-MM-DD'), '박민준', 'WEIGHT',
  1, '120.2', '125.0', '115.0', 'Y',
  NULL, '40', '1000'
)
/
INSERT INTO SAMPLE_INSPECT_RESULTS (
  ORDER_NO, INSPECT_DATE, INSPECTOR_NAME, INSPECT_TYPE,
  SAMPLE_NO, MEASURED_VALUE, SPEC_UPPER, SPEC_LOWER, PASS_YN,
  REMARK, COMPANY, PLANT_CD
) VALUES (
  'JO-20260612-375-01-01-02-01', TO_DATE('2026-06-12', 'YYYY-MM-DD'), '박민준', 'WEIGHT',
  2, '119.8', '125.0', '115.0', 'Y',
  NULL, '40', '1000'
)
/

COMMIT
/
