-- 자재입고 스캔 실적: 거래처/제조사 부착 바코드 원본 저장
-- 적용 대상: JSHANES

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'MAT_RECEIVINGS'
     AND COLUMN_NAME = 'VENDOR_BARCODE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MAT_RECEIVINGS ADD (VENDOR_BARCODE VARCHAR2(200))';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN MAT_RECEIVINGS.VENDOR_BARCODE IS '거래처/제조사 부착 바코드 원본']';
  END IF;
END;
/
