-- HNS02 트리 + KS_ 품목 삭제 후 보존 마스터 잔존 정리 (FK 정합성 복구 포함)
-- 대상: IQC 검사기준 3종 + 관리계획 + 하네스도면. _BAK 백업은 보존.

DELETE FROM IQC_PART_SPEC_ITEMS
 WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
   OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A'));
/

DELETE FROM IQC_PART_SPECS
 WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
   OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A'));
/

DELETE FROM IQC_ITEM_MASTERS
 WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
   OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A'));
/

DELETE FROM CONTROL_PLAN_ITEMS
 WHERE CONTROL_PLAN_ID IN (
   SELECT ID FROM CONTROL_PLANS
    WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
      OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A')));
/

DELETE FROM CONTROL_PLANS
 WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
   OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A'));
/

DELETE FROM HARNESS_DRAWING_REVISIONS
 WHERE DRAWING_ID IN (
   SELECT DRAWING_ID FROM HARNESS_DRAWING_MASTERS
    WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
      OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A')));
/

DELETE FROM HARNESS_DRAWING_MASTERS
 WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
   OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A'));
/

COMMIT;
/

ALTER TABLE IQC_ITEM_MASTERS ENABLE CONSTRAINT FK_IQC_ITEM_MAS_ITEM_CODE;
/
