DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'JOB_ORDERS'
    AND COLUMN_NAME = 'ORDER_KIND';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JOB_ORDERS ADD (ORDER_KIND VARCHAR2(20) DEFAULT ''ITEM'' NOT NULL)';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'JOB_ORDERS'
    AND COLUMN_NAME = 'ROUTING_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JOB_ORDERS ADD (ROUTING_SEQ NUMBER)';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_JOB_ORDERS_KIND';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_JOB_ORDERS_KIND ON JOB_ORDERS (ORDER_KIND)';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_JOB_ORDERS_PARENT_KIND';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_JOB_ORDERS_PARENT_KIND ON JOB_ORDERS (PARENT_ID, ORDER_KIND)';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_JOB_ORDERS_ROUTING_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_JOB_ORDERS_ROUTING_SEQ ON JOB_ORDERS (ROUTING_CODE, ROUTING_SEQ)';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN JOB_ORDERS.ORDER_KIND IS '작업지시 종류: ITEM=품목/BOM 단위, OPERATION=라우팅 공정 단위']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN JOB_ORDERS.ROUTING_SEQ IS 'OPERATION 작업지시의 라우팅 공정 순번']';
END;
/
