-- SYS_CONFIGS: 검사 bypass 설정
-- CONFIG_TYPE=BOOLEAN (Y/N)
INSERT INTO SYS_CONFIGS (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, SORT_ORDER, COMPANY, PLANT_CD)
VALUES ('STRUCTURE_INSP_BYPASS', 'INSPECTION', 'N', 'BOOLEAN', '구조검사 bypass', '구조검사를 생략합니다 (Y=생략, N=사용)', 1, '40', '1000');

INSERT INTO SYS_CONFIGS (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, SORT_ORDER, COMPANY, PLANT_CD)
VALUES ('VISUAL_INSP_BYPASS', 'INSPECTION', 'N', 'BOOLEAN', '외관검사 bypass', '외관검사를 생략합니다 (Y=생략, N=사용)', 2, '40', '1000');
