-- 소모품(제품 BOM의 ITEM_TYPE='CONSUMABLE' 품목) 입하 LOT 시드
-- 목적: 자재와 동일하게 MAT_LOTS에 matUid를 부여해, 키오스크에서 바코드(matUid) 스캔 시
--       MAT_LOTS 조회로 품목(ITEM_CODE)을 알 수 있게 한다.
-- 대상: 제품 BOM에 실제 사용되는 소모품 12종 × 2개(실물) = 24 LOT
-- matUid: 'MC260616' + 5자리 일련번호 (자재는 'M...', 소모품은 'MC...'로 구분)
-- 사이트: JSHANES, COMPANY=40 / PLANT_CD=1000
INSERT INTO MAT_LOTS (
  MAT_UID, ITEM_CODE, INIT_QTY, CURRENT_QTY, RECV_DATE, VENDOR,
  IQC_STATUS, STATUS, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT
)
SELECT
  'MC260616' || LPAD(ROWNUM, 5, '0'),
  ITEM_CODE, 1, 1, SYSDATE, 'JS-TOOL',
  'PASS', 'NORMAL', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM (
  SELECT i.ITEM_CODE
  FROM ITEM_MASTERS i
  CROSS JOIN (SELECT 1 AS N FROM DUAL UNION ALL SELECT 2 FROM DUAL) d
  WHERE i.ITEM_TYPE = 'CONSUMABLE'
    AND i.COMPANY = '40'
    AND i.ITEM_CODE IN (
      'APPCT-A','APPCT-B','APPCT-SE',
      'CUTBL001','CUTBL002','CUTBL003','CUTBL004','CUTBL009',
      'JIGHD-A','JIGHD-B','JIGHD-C','JIGHD-D'
    )
  ORDER BY i.ITEM_CODE
)
/
