DECLARE
  v_box_id_count NUMBER := 0;
  v_box_no_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_box_id_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'TRACE_LOGS'
     AND COLUMN_NAME = 'BOX_ID';

  SELECT COUNT(*)
    INTO v_box_no_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'TRACE_LOGS'
     AND COLUMN_NAME = 'BOX_NO';

  IF v_box_id_count = 1 AND v_box_no_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TRACE_LOGS RENAME COLUMN BOX_ID TO BOX_NO';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN TRACE_LOGS.BOX_NO IS '박스번호 (BOX_MASTERS.BOX_NO 참조)']';
END;
/
