DROP TABLE EQUIP_INSPECT_ITEM_POOL
/
DROP TABLE EQUIP_INSPECT_ITEM_MASTERS
/
CREATE TABLE EQUIP_INSPECT_ITEM_MASTERS (
  COMPANY        VARCHAR2(50)  NOT NULL,
  PLANT_CD       VARCHAR2(50)  NOT NULL,
  ITEM_CODE      VARCHAR2(30)  NOT NULL,
  ITEM_NAME      VARCHAR2(200) NOT NULL,
  INSPECT_TYPE   VARCHAR2(20)  NOT NULL,
  EQUIP_TYPE     VARCHAR2(50),
  ITEM_TYPE      VARCHAR2(20)  DEFAULT 'VISUAL' NOT NULL,
  CRITERIA       VARCHAR2(500),
  CYCLE          VARCHAR2(20),
  UNIT           VARCHAR2(20),
  LSL_VALUE      NUMBER,
  USL_VALUE      NUMBER,
  WORKER_QR_CODE VARCHAR2(50),
  USE_YN         VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  REMARK         VARCHAR2(500),
  CREATED_BY     VARCHAR2(50),
  UPDATED_BY     VARCHAR2(50),
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_EQUIP_INSPECT_ITEM_MASTERS PRIMARY KEY (COMPANY, PLANT_CD, ITEM_CODE)
)
/
COMMENT ON TABLE EQUIP_INSPECT_ITEM_MASTERS IS '설비점검항목 기준 마스터 (설비유형별 점검항목 템플릿)'
/
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_MASTERS.EQUIP_TYPE IS '설비유형 (COM_CODES EQUIP_TYPE). 기준항목을 설비유형으로 분류'
/
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_MASTERS.WORKER_QR_CODE IS '작업자점검 QR 코드 페이로드 (INSPECT_TYPE=WORKER 항목에만 사용)'
/
CREATE TABLE EQUIP_INSPECT_ITEM_POOL (
  COMPANY      VARCHAR2(50) NOT NULL,
  PLANT_CD     VARCHAR2(50) NOT NULL,
  EQUIP_CODE   VARCHAR2(36) NOT NULL,
  ITEM_CODE    VARCHAR2(30) NOT NULL,
  INSPECT_TYPE VARCHAR2(20) NOT NULL,
  USE_YN       VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
  SORT_SEQ     NUMBER,
  CREATED_BY   VARCHAR2(50),
  UPDATED_BY   VARCHAR2(50),
  CREATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_EQUIP_INSPECT_ITEM_POOL PRIMARY KEY (COMPANY, PLANT_CD, EQUIP_CODE, ITEM_CODE, INSPECT_TYPE)
)
/
COMMENT ON TABLE EQUIP_INSPECT_ITEM_POOL IS '설비-점검항목 연결 풀 (설비코드+항목코드+점검유형 기준 등록)'
/
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_POOL.SORT_SEQ IS '표시 순서 (비PK, 정렬용)'
/
COMMIT
/
