DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_SG_LABEL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_SG_LABEL START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_PROD_GENEALOGY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PROD_GENEALOGY START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SG_LABELS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE SG_LABELS (
        SG_BARCODE VARCHAR2(30) NOT NULL,
        ITEM_CODE VARCHAR2(50) NOT NULL,
        ORDER_NO VARCHAR2(50),
        ISSUE_PROCESS_CODE VARCHAR2(50),
        CURRENT_PROCESS_CODE VARCHAR2(50),
        MOUNTED_EQUIP_CODE VARCHAR2(50),
        WAREHOUSE_CODE VARCHAR2(50),
        INIT_QTY NUMBER DEFAULT 0 NOT NULL,
        REMAIN_QTY NUMBER DEFAULT 0 NOT NULL,
        STATUS VARCHAR2(20) DEFAULT ''IN_STOCK'' NOT NULL,
        WORKER_ID VARCHAR2(50),
        ISSUED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_SG_LABELS PRIMARY KEY (SG_BARCODE),
        CONSTRAINT CK_SG_LABELS_STATUS CHECK (STATUS IN (''IN_STOCK'',''MOUNTED'',''CONSUMED'',''DEFECT''))
      )';
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SG_LABELS_ITEM ON SG_LABELS (ITEM_CODE)';
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SG_LABELS_ORDER ON SG_LABELS (ORDER_NO)';
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SG_LABELS_STATUS ON SG_LABELS (STATUS)';
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SG_LABELS_EQUIP ON SG_LABELS (MOUNTED_EQUIP_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'PRODUCT_GENEALOGY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE PRODUCT_GENEALOGY (
        GENEALOGY_ID NUMBER NOT NULL,
        PARENT_TYPE VARCHAR2(20) NOT NULL,
        PARENT_KEY VARCHAR2(50) NOT NULL,
        CHILD_TYPE VARCHAR2(20) NOT NULL,
        CHILD_KEY VARCHAR2(100) NOT NULL,
        ITEM_CODE VARCHAR2(50),
        QTY NUMBER DEFAULT 1 NOT NULL,
        PROCESS_CODE VARCHAR2(50),
        CIRCUIT_NO VARCHAR2(50),
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CREATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_PRODUCT_GENEALOGY PRIMARY KEY (GENEALOGY_ID),
        CONSTRAINT CK_PROD_GENEALOGY_PT CHECK (PARENT_TYPE IN (''FG'',''SG'')),
        CONSTRAINT CK_PROD_GENEALOGY_CT CHECK (CHILD_TYPE IN (''SG'',''MAT_LOT''))
      )';
    EXECUTE IMMEDIATE 'CREATE INDEX IX_PROD_GENEALOGY_PARENT ON PRODUCT_GENEALOGY (PARENT_KEY)';
    EXECUTE IMMEDIATE 'CREATE INDEX IX_PROD_GENEALOGY_CHILD ON PRODUCT_GENEALOGY (CHILD_KEY)';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON TABLE SG_LABELS IS '반제품 묶음 추적라벨(잔량 가닥수 보유)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SG_LABELS.INIT_QTY IS '최초 가닥수']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SG_LABELS.REMAIN_QTY IS '잔여 가닥수']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SG_LABELS.MOUNTED_EQUIP_CODE IS '장착 설비(NULL=미장착)']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE PRODUCT_GENEALOGY IS '생산 genealogy(제품→묶음→원자재 lot 재귀)']';
END;
/
