BEGIN
  EXECUTE IMMEDIATE q'[
    MERGE INTO MENU_CATEGORY_ITEMS t
    USING (
      SELECT 'PROD_WIP_STOCK' MENU_CODE, 'PRODUCTION' CATEGORY_CODE, 70 SORT_ORDER, '40' COMPANY, '1000' PLANT_CD FROM DUAL
      UNION ALL
      SELECT 'PROD_FG_STOCK' MENU_CODE, 'PRODUCTION' CATEGORY_CODE, 71 SORT_ORDER, '40' COMPANY, '1000' PLANT_CD FROM DUAL
    ) s
    ON (
      t.MENU_CODE = s.MENU_CODE
      AND t.COMPANY = s.COMPANY
      AND t.PLANT_CD = s.PLANT_CD
    )
    WHEN MATCHED THEN UPDATE SET
      t.CATEGORY_CODE = s.CATEGORY_CODE,
      t.SORT_ORDER = s.SORT_ORDER,
      t.UPDATED_AT = SYSTIMESTAMP,
      t.UPDATED_BY = 'codex'
    WHEN NOT MATCHED THEN INSERT (
      MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
    ) VALUES (
      s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD, SYSTIMESTAMP, 'codex', SYSTIMESTAMP, 'codex'
    )
  ]';

  EXECUTE IMMEDIATE q'[
    MERGE INTO ROLE_MENU_PERMISSIONS t
    USING (
      SELECT 'MANAGER' ROLE_CODE, 'PROD_FG_STOCK' MENU_CODE, '40' COMPANY, '1000' PLANT_CD FROM DUAL
      UNION ALL
      SELECT 'OPERATOR' ROLE_CODE, 'PROD_FG_STOCK' MENU_CODE, '40' COMPANY, '1000' PLANT_CD FROM DUAL
    ) s
    ON (
      t.ROLE_CODE = s.ROLE_CODE
      AND t.MENU_CODE = s.MENU_CODE
      AND t.COMPANY = s.COMPANY
      AND t.PLANT_CD = s.PLANT_CD
    )
    WHEN MATCHED THEN UPDATE SET
      t.CAN_ACCESS = 'Y',
      t.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD
    ) VALUES (
      s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD
    )
  ]';
END;
