-- Seed N91H00-X9800 default model so production order creation can expand BOM,
-- create semi-product child orders, and show equipment candidates per process.

MERGE INTO BOM_MASTERS b
  USING (
    SELECT
      COMPANY,
      PLANT_CD,
      'N91H00-X9800' AS PARENT_ITEM_CODE,
      CHILD_ITEM_CODE,
      QTY_PER,
      SEQ,
      REVISION,
      BOM_GRP,
      OPER,
      SIDE,
      ECO_NO,
      VALID_FROM,
      VALID_TO,
      'Y' AS USE_YN,
      'N91H00-X9800 기본 품목 BOM seed' AS REMARK
    FROM BOM_MASTERS
    WHERE COMPANY = '40'
      AND PLANT_CD = '1000'
      AND PARENT_ITEM_CODE = 'N91H00-X9800_1'
      AND USE_YN = 'Y'
  ) s
  ON (
    b.COMPANY = s.COMPANY
    AND b.PLANT_CD = s.PLANT_CD
    AND b.PARENT_ITEM_CODE = s.PARENT_ITEM_CODE
    AND b.CHILD_ITEM_CODE = s.CHILD_ITEM_CODE
    AND b.REVISION = s.REVISION
  )
  WHEN MATCHED THEN UPDATE SET
    b.QTY_PER = s.QTY_PER,
    b.SEQ = s.SEQ,
    b.BOM_GRP = s.BOM_GRP,
    b.OPER = s.OPER,
    b.SIDE = s.SIDE,
    b.ECO_NO = s.ECO_NO,
    b.VALID_FROM = s.VALID_FROM,
    b.VALID_TO = s.VALID_TO,
    b.USE_YN = 'Y',
    b.REMARK = s.REMARK,
    b.UPDATED_BY = 'codex',
    b.UPDATED_AT = SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT (
    COMPANY,
    PLANT_CD,
    PARENT_ITEM_CODE,
    CHILD_ITEM_CODE,
    QTY_PER,
    SEQ,
    REVISION,
    BOM_GRP,
    OPER,
    SIDE,
    ECO_NO,
    VALID_FROM,
    VALID_TO,
    USE_YN,
    REMARK,
    CREATED_BY,
    UPDATED_BY,
    CREATED_AT,
    UPDATED_AT
  ) VALUES (
    s.COMPANY,
    s.PLANT_CD,
    s.PARENT_ITEM_CODE,
    s.CHILD_ITEM_CODE,
    s.QTY_PER,
    s.SEQ,
    s.REVISION,
    s.BOM_GRP,
    s.OPER,
    s.SIDE,
    s.ECO_NO,
    s.VALID_FROM,
    s.VALID_TO,
    'Y',
    s.REMARK,
    'codex',
    'codex',
    SYSTIMESTAMP,
    SYSTIMESTAMP
  );
/

MERGE INTO ROUTING_GROUPS g
  USING (
    SELECT '40' COMPANY, '1000' PLANT_CD, 'N91H00-X9800' ROUTING_CODE, 'N91H00-X9800 조립 라우팅' ROUTING_NAME, 'N91H00-X9800' ITEM_CODE FROM DUAL
    UNION ALL SELECT '40', '1000', 'N91H00-X9800-S', 'N91H00-X9800-S 열수축 라우팅', 'N91H00-X9800-S' FROM DUAL
    UNION ALL SELECT '40', '1000', 'N91H00-X9800-S-A', 'N91H00-X9800-S-A 압착 라우팅', 'N91H00-X9800-S-A' FROM DUAL
    UNION ALL SELECT '40', '1000', 'N91H00-X9800-S-AB', 'N91H00-X9800-S-AB 육각압착 라우팅', 'N91H00-X9800-S-AB' FROM DUAL
    UNION ALL SELECT '40', '1000', 'N91H00-X9800-S-ABC', 'N91H00-X9800-S-ABC 압착준비 라우팅', 'N91H00-X9800-S-ABC' FROM DUAL
    UNION ALL SELECT '40', '1000', 'N91H00-X9800-C1', 'N91H00-X9800-C1 실드절단 라우팅', 'N91H00-X9800-C1' FROM DUAL
    UNION ALL SELECT '40', '1000', 'N91H00-X9800-C1-A', 'N91H00-X9800-C1-A 자동절단탈피 라우팅', 'N91H00-X9800-C1-A' FROM DUAL
    UNION ALL SELECT '40', '1000', 'N91H00-X9800-C2', 'N91H00-X9800-C2 실드절단 라우팅', 'N91H00-X9800-C2' FROM DUAL
    UNION ALL SELECT '40', '1000', 'N91H00-X9800-C2-A', 'N91H00-X9800-C2-A 자동절단탈피 라우팅', 'N91H00-X9800-C2-A' FROM DUAL
  ) s
  ON (g.COMPANY = s.COMPANY AND g.PLANT_CD = s.PLANT_CD AND g.ROUTING_CODE = s.ROUTING_CODE)
  WHEN MATCHED THEN UPDATE SET
    g.ROUTING_NAME = s.ROUTING_NAME,
    g.ITEM_CODE = s.ITEM_CODE,
    g.DESCRIPTION = 'N91H00-X9800 BOM 전개 작업지시 생성용 라우팅 seed',
    g.USE_YN = 'Y',
    g.UPDATED_BY = 'codex',
    g.UPDATED_AT = SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT (
    COMPANY,
    PLANT_CD,
    ROUTING_CODE,
    ROUTING_NAME,
    ITEM_CODE,
    DESCRIPTION,
    USE_YN,
    CREATED_BY,
    UPDATED_BY,
    CREATED_AT,
    UPDATED_AT
  ) VALUES (
    s.COMPANY,
    s.PLANT_CD,
    s.ROUTING_CODE,
    s.ROUTING_NAME,
    s.ITEM_CODE,
    'N91H00-X9800 BOM 전개 작업지시 생성용 라우팅 seed',
    'Y',
    'codex',
    'codex',
    SYSTIMESTAMP,
    SYSTIMESTAMP
  );
/

MERGE INTO ROUTING_PROCESSES p
  USING (
    SELECT r.COMPANY, r.PLANT_CD, r.ROUTING_CODE, r.SEQ, r.PROCESS_CODE,
           pm.PROCESS_NAME, pm.PROCESS_TYPE, r.STD_TIME
    FROM (
      SELECT '40' COMPANY, '1000' PLANT_CD, 'N91H00-X9800' ROUTING_CODE, 10 SEQ, 'MASSY' PROCESS_CODE, 30 STD_TIME FROM DUAL
      UNION ALL SELECT '40', '1000', 'N91H00-X9800-S', 10, 'TUBHT', 20 FROM DUAL
      UNION ALL SELECT '40', '1000', 'N91H00-X9800-S-A', 10, 'CRMPB', 24 FROM DUAL
      UNION ALL SELECT '40', '1000', 'N91H00-X9800-S-AB', 10, 'HEXCP', 24 FROM DUAL
      UNION ALL SELECT '40', '1000', 'N91H00-X9800-S-ABC', 10, 'HEXPR', 12 FROM DUAL
      UNION ALL SELECT '40', '1000', 'N91H00-X9800-C1', 10, 'SHDCT', 18 FROM DUAL
      UNION ALL SELECT '40', '1000', 'N91H00-X9800-C1-A', 10, 'ATCNS', 18 FROM DUAL
      UNION ALL SELECT '40', '1000', 'N91H00-X9800-C2', 1, 'SHDCT', 18 FROM DUAL
      UNION ALL SELECT '40', '1000', 'N91H00-X9800-C2-A', 10, 'ATCNS', 18 FROM DUAL
    ) r
    JOIN PROCESS_MASTERS pm
      ON pm.COMPANY = r.COMPANY
     AND pm.PLANT_CD = r.PLANT_CD
     AND pm.PROCESS_CODE = r.PROCESS_CODE
  ) s
  ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
  WHEN MATCHED THEN UPDATE SET
    p.PROCESS_CODE = s.PROCESS_CODE,
    p.PROCESS_NAME = s.PROCESS_NAME,
    p.PROCESS_TYPE = s.PROCESS_TYPE,
    p.JOB_ORDER_YN = 'Y',
    p.SAMPLE_INSPECT_YN = 'N',
    p.ISSUE_LABEL_TYPE = 'NONE',
    p.EXECUTION_TYPE = 'IN_HOUSE',
    p.STD_TIME = s.STD_TIME,
    p.USE_YN = 'Y',
    p.UPDATED_BY = 'codex',
    p.UPDATED_AT = SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT (
    COMPANY,
    PLANT_CD,
    ROUTING_CODE,
    SEQ,
    PROCESS_CODE,
    PROCESS_NAME,
    PROCESS_TYPE,
    JOB_ORDER_YN,
    SAMPLE_INSPECT_YN,
    ISSUE_LABEL_TYPE,
    EXECUTION_TYPE,
    STD_TIME,
    QC_SELF_YN,
    INSPECT_METHOD,
    DESTRUCTIVE_YN,
    SAMPLE_QTY,
    USE_YN,
    CREATED_BY,
    UPDATED_BY,
    CREATED_AT,
    UPDATED_AT
  ) VALUES (
    s.COMPANY,
    s.PLANT_CD,
    s.ROUTING_CODE,
    s.SEQ,
    s.PROCESS_CODE,
    s.PROCESS_NAME,
    s.PROCESS_TYPE,
    'Y',
    'N',
    'NONE',
    'IN_HOUSE',
    s.STD_TIME,
    'N',
    'DIRECT',
    'N',
    1,
    'Y',
    'codex',
    'codex',
    SYSTIMESTAMP,
    SYSTIMESTAMP
  );
/

MERGE INTO PROCESS_EQUIPMENTS pe
  USING (
    SELECT '40' COMPANY, '1000' PLANT_CD, 'MASSY' PROCESS_CODE, 'EQ-MASSY-01' EQUIP_CODE FROM DUAL
    UNION ALL SELECT '40', '1000', 'MASSY', 'KS_EQ_MASSY' FROM DUAL
    UNION ALL SELECT '40', '1000', 'CONAS', 'EQ-MASSY-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'CONAS', 'KS_EQ_MASSY' FROM DUAL
    UNION ALL SELECT '40', '1000', 'FINSH', 'EQ-MASSY-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'FINSH', 'KS_EQ_MASSY' FROM DUAL
    UNION ALL SELECT '40', '1000', 'SACMB', 'EQ-SASSY-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'SACMB', 'KS_EQ_MASSY' FROM DUAL
    UNION ALL SELECT '40', '1000', 'TUBHT', 'EQ-TUBHT-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'TUBHT', 'KS_EQ_TUBHT' FROM DUAL
    UNION ALL SELECT '40', '1000', 'CRMPB', 'EQ-CRMPB-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'CRMPB', 'EQ-CRMPB-02' FROM DUAL
    UNION ALL SELECT '40', '1000', 'CRMPF', 'EQ-CRMPF-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'CRMPF', 'EQ-CRMPF-02' FROM DUAL
    UNION ALL SELECT '40', '1000', 'HEXCP', 'EQ-HEXCP-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'HEXCP', 'EQ-HEXCP-02' FROM DUAL
    UNION ALL SELECT '40', '1000', 'HEXPR', 'EQ-HEXPR-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'SHDCT', 'EQ-SHDRM-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'SHDCT', 'EQ-SHDRM-02' FROM DUAL
    UNION ALL SELECT '40', '1000', 'SHDCT', 'KS_EQ_SHDRM' FROM DUAL
    UNION ALL SELECT '40', '1000', 'ATCNS', 'EQ-ATCNS-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'ATCNS', 'EQ-ATCNS-02' FROM DUAL
    UNION ALL SELECT '40', '1000', 'CRINS', 'EQ-SGINS-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'CRINS', 'KS_EQ_AINSP' FROM DUAL
    UNION ALL SELECT '40', '1000', 'SGINS', 'EQ-SGINS-01' FROM DUAL
    UNION ALL SELECT '40', '1000', 'SGINS', 'KS_EQ_AINSP' FROM DUAL
  ) s
  ON (
    pe.COMPANY = s.COMPANY
    AND pe.PLANT_CD = s.PLANT_CD
    AND pe.PROCESS_CODE = s.PROCESS_CODE
    AND pe.EQUIP_CODE = s.EQUIP_CODE
  )
  WHEN MATCHED THEN UPDATE SET
    pe.USE_YN = 'Y',
    pe.UPDATED_BY = 'codex',
    pe.UPDATED_AT = SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT (
    COMPANY,
    PLANT_CD,
    PROCESS_CODE,
    EQUIP_CODE,
    USE_YN,
    CREATED_BY,
    UPDATED_BY,
    CREATED_AT,
    UPDATED_AT
  ) VALUES (
    s.COMPANY,
    s.PLANT_CD,
    s.PROCESS_CODE,
    s.EQUIP_CODE,
    'Y',
    'codex',
    'codex',
    SYSTIMESTAMP,
    SYSTIMESTAMP
  );
/

COMMIT;
/
