BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_RESULTS DROP CONSTRAINT FK_REWORK_RES_PROC';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_RESULTS DROP CONSTRAINT PK_REWORK_RESULTS';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_PROCESSES DROP CONSTRAINT PK_REWORK_PROCESSES';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_INSPECTS DROP CONSTRAINT PK_REWORK_INSPECTS';

  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_ORDERS MODIFY (DEFECT_LOG_ID VARCHAR2(50))';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_ORDERS MODIFY (COMPANY VARCHAR2(50))';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_INSPECTS MODIFY (REWORK_ORDER_ID VARCHAR2(50))';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_INSPECTS MODIFY (COMPANY VARCHAR2(50))';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_PROCESSES MODIFY (REWORK_ORDER_ID VARCHAR2(50))';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_PROCESSES MODIFY (COMPANY VARCHAR2(50))';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_RESULTS MODIFY (REWORK_ORDER_ID VARCHAR2(50))';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_RESULTS MODIFY (COMPANY VARCHAR2(50))';

  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_INSPECTS ADD CONSTRAINT PK_REWORK_INSPECTS PRIMARY KEY (REWORK_ORDER_ID, SEQ)';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_PROCESSES ADD CONSTRAINT PK_REWORK_PROCESSES PRIMARY KEY (REWORK_ORDER_ID, PROCESS_CODE)';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_RESULTS ADD CONSTRAINT PK_REWORK_RESULTS PRIMARY KEY (REWORK_ORDER_ID, PROCESS_CODE, SEQ)';
  EXECUTE IMMEDIATE 'ALTER TABLE REWORK_RESULTS ADD CONSTRAINT FK_REWORK_RES_PROC FOREIGN KEY (REWORK_ORDER_ID, PROCESS_CODE) REFERENCES REWORK_PROCESSES (REWORK_ORDER_ID, PROCESS_CODE)';
END;
/
