-- Seed work instructions for /production/input-kiosk verification.
-- 활성 작업지시(WAITING/RUNNING)의 (품목, 공정) 조합별 작업지도서 시드.
-- HNS02C1ABCD / ATCUT 은 기존(codex) 시드를 보존하기 위해 제외한다.
-- IMAGE_URL 은 NULL — 키오스크는 이미지가 없으면 제목+내용 플레이스홀더를 표시한다.

MERGE INTO WORK_INSTRUCTIONS wi
USING (
  SELECT
    b.ITEM_CODE,
    b.PROCESS_CODE,
    'A' AS REVISION,
    b.ITEM_CODE || ' ' || b.PROCESS_NAME || ' 작업지도서' AS TITLE,
    '1. 작업지시와 품목 ' || b.ITEM_CODE || '을(를) 확인한다.' || CHR(10) ||
    '2. ' || b.PROCESS_NAME || '(' || b.PROCESS_CODE || ') 공정의 설비 상태와 투입 자재를 확인한다.' || CHR(10) ||
    '3. 작업표준에 따라 ' || b.PROCESS_NAME || '을(를) 수행하고 규격·외관을 확인한다.' || CHR(10) ||
    '4. 이상 발생 시 설비를 정지하고 작업자설비점검 및 품질 담당자에게 알린다.' AS CONTENT,
    CAST(NULL AS VARCHAR2(500)) AS IMAGE_URL,
    'Y' AS USE_YN,
    '40' AS COMPANY,
    '1000' AS PLANT_CD,
    'claude' AS CREATED_BY,
    'claude' AS UPDATED_BY
  FROM (
    SELECT 'HNS02'        AS ITEM_CODE, 'MASSY' AS PROCESS_CODE, '메인조립'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02'        AS ITEM_CODE, 'SASSY' AS PROCESS_CODE, '서브조립'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02-SCA'    AS ITEM_CODE, 'CRMPB' AS PROCESS_CODE, '양단압착'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02-SCA_1'  AS ITEM_CODE, 'STRPB' AS PROCESS_CODE, '양단탈피'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02-SCA_2'  AS ITEM_CODE, 'ATCUT' AS PROCESS_CODE, '자동절단'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C1'      AS ITEM_CODE, 'WELDR' AS PROCESS_CODE, '후단융착'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C1A'     AS ITEM_CODE, 'MTASY' AS PROCESS_CODE, '자재장착'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C1AB'    AS ITEM_CODE, 'CRMPF' AS PROCESS_CODE, '전단압착'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C1ABC'   AS ITEM_CODE, 'STRPB' AS PROCESS_CODE, '양단탈피'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C2'      AS ITEM_CODE, 'TUBHT' AS PROCESS_CODE, '튜브열처리'       AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C2A'     AS ITEM_CODE, 'CRMPR' AS PROCESS_CODE, '후단압착'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C2AB'    AS ITEM_CODE, 'HEXCP' AS PROCESS_CODE, '육각압착'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C2ABC'   AS ITEM_CODE, 'MTASY' AS PROCESS_CODE, '자재장착'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C2ABCD'  AS ITEM_CODE, 'SHDRM' AS PROCESS_CODE, '편조제거'         AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02C2ABCDE' AS ITEM_CODE, 'ATCNS' AS PROCESS_CODE, '자동절단탈피'     AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02_FA'     AS ITEM_CODE, 'TAPPN' AS PROCESS_CODE, '배판작업(테이핑)' AS PROCESS_NAME FROM DUAL UNION ALL
    SELECT 'HNS02_FB'     AS ITEM_CODE, 'SASSY' AS PROCESS_CODE, '서브조립'         AS PROCESS_NAME FROM DUAL
  ) b
) src
ON (
  wi.ITEM_CODE = src.ITEM_CODE
  AND wi.PROCESS_CODE = src.PROCESS_CODE
  AND wi.REVISION = src.REVISION
  AND wi.COMPANY = src.COMPANY
  AND wi.PLANT_CD = src.PLANT_CD
)
WHEN MATCHED THEN UPDATE SET
  wi.TITLE = src.TITLE,
  wi.CONTENT = src.CONTENT,
  wi.USE_YN = src.USE_YN,
  wi.UPDATED_BY = src.UPDATED_BY,
  wi.UPDATED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  ITEM_CODE,
  PROCESS_CODE,
  REVISION,
  TITLE,
  CONTENT,
  IMAGE_URL,
  USE_YN,
  COMPANY,
  PLANT_CD,
  CREATED_BY,
  UPDATED_BY,
  CREATED_AT,
  UPDATED_AT
) VALUES (
  src.ITEM_CODE,
  src.PROCESS_CODE,
  src.REVISION,
  src.TITLE,
  src.CONTENT,
  src.IMAGE_URL,
  src.USE_YN,
  src.COMPANY,
  src.PLANT_CD,
  src.CREATED_BY,
  src.UPDATED_BY,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);
