-- 2026-06-16 PROCESS_MASTERS 공정대분류(PROCESS_CATEGORY) 누락 2건 보완
-- CRMPB(양단압착)/MTASY(자재장착)만 PROCESS_CATEGORY 가 NULL 이라 대분류 컬럼이 '-' 로 표시됨.
-- 동일 성격 형제 공정의 대분류 관례에 맞춰 채운다.
--   - 압착 계열(CRMPF/HEXCP/CRMPR/PRC-CRIMP) → TERMINAL  ⇒ CRMPB = TERMINAL
--   - 조립 계열(AUXMT/SASSY/TAPPN/MASSY)        → ASSEMBLY ⇒ MTASY = ASSEMBLY
-- 사이트: JSHANES (COMPANY=40, PLANT_CD=1000)

UPDATE PROCESS_MASTERS SET PROCESS_CATEGORY='TERMINAL', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE='CRMPB';
/
UPDATE PROCESS_MASTERS SET PROCESS_CATEGORY='ASSEMBLY', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE='MTASY';
/
