DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'ROUTING_PROCESSES'
    AND COLUMN_NAME = 'EXECUTION_TYPE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (EXECUTION_TYPE VARCHAR2(20) DEFAULT ''IN_HOUSE'' NOT NULL)';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'ROUTING_PROCESSES'
    AND COLUMN_NAME = 'SUBCON_VENDOR_CODE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (SUBCON_VENDOR_CODE VARCHAR2(50))';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE TABLE_NAME = 'ROUTING_PROCESSES'
    AND CONSTRAINT_NAME = 'CK_ROUTING_PROC_EXEC_TYPE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE ROUTING_PROCESSES ADD CONSTRAINT CK_ROUTING_PROC_EXEC_TYPE CHECK (EXECUTION_TYPE IN ('IN_HOUSE', 'SUBCON'))]';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ROUTING_PROCESSES.EXECUTION_TYPE IS '공정 실행유형: IN_HOUSE=사내, SUBCON=외주']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ROUTING_PROCESSES.SUBCON_VENDOR_CODE IS '외주 공정 기본 외주처 코드 (VENDOR_MASTERS.VENDOR_CODE)']';
END;
/
