BEGIN
  MERGE INTO MENU_CATEGORY_ITEMS t
  USING (
    SELECT
      'SYS_ER_VIEW' MENU_CODE,
      'SYSTEM' CATEGORY_CODE,
      95 SORT_ORDER,
      '40' COMPANY,
      '1000' PLANT_CD
    FROM DUAL
  ) s
  ON (
    t.COMPANY = s.COMPANY
    AND t.PLANT_CD = s.PLANT_CD
    AND t.MENU_CODE = s.MENU_CODE
  )
  WHEN MATCHED THEN UPDATE SET
    t.CATEGORY_CODE = s.CATEGORY_CODE,
    t.SORT_ORDER = s.SORT_ORDER,
    t.UPDATED_AT = SYSTIMESTAMP,
    t.UPDATED_BY = 'codex'
  WHEN NOT MATCHED THEN INSERT
    (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES
    (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD, 'codex', 'codex');

  COMMIT;
END;
/
