-- Seed WIP product stock for /product/receive.
-- Target: JSHANES / company 40 / plant 1000
-- Scenario: receive box BX2606260001 (N91H00-X9800 qty 5) from WIP_MAIN to FG default warehouse.
-- Guard: do nothing after a normal BOX receipt/move transaction already exists for this box.

MERGE INTO PRODUCT_STOCKS dst
USING (
  SELECT '40' AS COMPANY,
         '1000' AS PLANT_CD,
         'WIP_MAIN' AS WAREHOUSE_CODE,
         'N91H00-X9800' AS ITEM_CODE,
         'FINISHED' AS ITEM_TYPE,
         5 AS SEED_QTY
    FROM DUAL
   WHERE NOT EXISTS (
     SELECT 1
       FROM PRODUCT_TRANSACTIONS t
      WHERE t.COMPANY = '40'
        AND t.PLANT_CD = '1000'
        AND t.REF_TYPE = 'BOX'
        AND t.REF_ID = 'BX2606260001'
        AND t.TRANS_TYPE IN ('WIP_OUT', 'FG_IN', 'WIP_IN')
        AND t.STATUS = 'DONE'
   )
) src
ON (
  dst.COMPANY = src.COMPANY
  AND dst.PLANT_CD = src.PLANT_CD
  AND dst.WAREHOUSE_CODE = src.WAREHOUSE_CODE
  AND dst.ITEM_CODE = src.ITEM_CODE
)
WHEN NOT MATCHED THEN
  INSERT (
    COMPANY, PLANT_CD, WAREHOUSE_CODE, LOCATION_CODE, ITEM_CODE, ITEM_TYPE,
    PRD_UID, ORDER_NO, PROCESS_CODE,
    QTY, RESERVED_QTY, AVAILABLE_QTY, STATUS,
    HOLD_REASON, HOLD_AT, HOLD_BY, LAST_COUNT,
    CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT, VERSION
  ) VALUES (
    src.COMPANY, src.PLANT_CD, src.WAREHOUSE_CODE, NULL, src.ITEM_CODE, src.ITEM_TYPE,
    NULL, 'WO-SEED-N91-X9800', NULL,
    src.SEED_QTY, 0, src.SEED_QTY, 'NORMAL',
    NULL, NULL, NULL, NULL,
    'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP, 1
  )
WHEN MATCHED THEN
  UPDATE SET
    dst.ITEM_TYPE = src.ITEM_TYPE,
    dst.QTY = CASE
      WHEN NVL(dst.AVAILABLE_QTY, 0) < src.SEED_QTY
      THEN NVL(dst.RESERVED_QTY, 0) + src.SEED_QTY
      ELSE dst.QTY
    END,
    dst.AVAILABLE_QTY = GREATEST(NVL(dst.AVAILABLE_QTY, 0), src.SEED_QTY),
    dst.STATUS = 'NORMAL',
    dst.UPDATED_BY = 'seed',
    dst.UPDATED_AT = SYSTIMESTAMP
/

MERGE INTO PRODUCT_TRANSACTIONS dst
USING (
  SELECT 'PTX-SEED-BX2606260001-WIP' AS TRANS_NO
    FROM DUAL
   WHERE NOT EXISTS (
     SELECT 1
       FROM PRODUCT_TRANSACTIONS t
      WHERE t.COMPANY = '40'
        AND t.PLANT_CD = '1000'
        AND t.REF_TYPE = 'BOX'
        AND t.REF_ID = 'BX2606260001'
        AND t.TRANS_TYPE IN ('WIP_OUT', 'FG_IN', 'WIP_IN')
        AND t.STATUS = 'DONE'
   )
) src
ON (dst.TRANS_NO = src.TRANS_NO)
WHEN NOT MATCHED THEN
  INSERT (
    TRANS_NO, TRANS_TYPE, TRANS_DATE,
    FROM_WAREHOUSE_ID, TO_WAREHOUSE_ID,
    ITEM_CODE, ITEM_TYPE, PRD_UID, ORDER_NO, PROCESS_CODE,
    QTY, UNIT_PRICE, TOTAL_AMOUNT,
    REF_TYPE, REF_ID, CANCEL_REF_ID, WORKER_CODE, ISSUE_TYPE,
    REMARK, STATUS, COMPANY, PLANT_CD,
    CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
  ) VALUES (
    src.TRANS_NO, 'WIP_IN', SYSTIMESTAMP,
    NULL, 'WIP_MAIN',
    'N91H00-X9800', 'FINISHED', NULL, 'WO-SEED-N91-X9800', NULL,
    5, NULL, NULL,
    'SEED', 'BX2606260001-WIP', NULL, NULL, NULL,
    '시드: BX2606260001 제품입고용 WIP_MAIN 재고', 'DONE', '40', '1000',
    'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
  )
/
