DECLARE
  v_cnt NUMBER;
  v_has_policy_col NUMBER;
  v_has_level_col NUMBER;
  v_has_critical_col NUMBER;
  v_has_major_col NUMBER;
  v_has_minor_col NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM USER_TABLES
   WHERE TABLE_NAME = 'IQC_AQL_POLICIES';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE IQC_AQL_POLICIES (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        POLICY_CODE VARCHAR2(50) NOT NULL,
        POLICY_NAME VARCHAR2(100) NOT NULL,
        INSPECTION_LEVEL VARCHAR2(20),
        MAJOR_AQL_CODE VARCHAR2(50),
        MINOR_AQL_CODE VARCHAR2(50),
        CRITICAL_MODE VARCHAR2(30) DEFAULT 'IMMEDIATE_FAIL' NOT NULL,
        USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        REMARK VARCHAR2(500),
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_IQC_AQL_POLICIES PRIMARY KEY (COMPANY, PLANT_CD, POLICY_CODE),
        CONSTRAINT CK_IQC_AQL_POLICIES_USE_YN CHECK (USE_YN IN ('Y', 'N')),
        CONSTRAINT CK_IQC_AQL_POLICIES_CRIT CHECK (CRITICAL_MODE IN ('IMMEDIATE_FAIL'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_has_policy_col
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'IQC_AQL_POLICY_CODE';

  IF v_has_policy_col = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS ADD (IQC_AQL_POLICY_CODE VARCHAR2(50))';
  END IF;

  SELECT COUNT(*) INTO v_has_level_col
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'INSPECTION_LEVEL';
  SELECT COUNT(*) INTO v_has_critical_col
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'AQL_CRITICAL';
  SELECT COUNT(*) INTO v_has_major_col
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'AQL_MAJOR';
  SELECT COUNT(*) INTO v_has_minor_col
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'AQL_MINOR';

  EXECUTE IMMEDIATE q'[
    INSERT INTO IQC_AQL_POLICIES (
      COMPANY, PLANT_CD, POLICY_CODE, POLICY_NAME, INSPECTION_LEVEL,
      MAJOR_AQL_CODE, MINOR_AQL_CODE, CRITICAL_MODE, USE_YN, REMARK, CREATED_BY, UPDATED_BY
    )
    SELECT s.COMPANY, s.PLANT_CD, 'AQLP-II-1.0-2.5', '기본 IQC AQL II Major 1.0 Minor 2.5', 'II',
           (SELECT MAX(a.AQL_CODE)
              FROM AQL_STANDARDS a
             WHERE a.COMPANY = s.COMPANY
               AND a.PLANT_CD = s.PLANT_CD
               AND a.INSPECTION_LEVEL = 'II'
               AND a.AQL_VALUE = 1
               AND a.USE_YN = 'Y'),
           (SELECT MAX(a.AQL_CODE)
              FROM AQL_STANDARDS a
             WHERE a.COMPANY = s.COMPANY
               AND a.PLANT_CD = s.PLANT_CD
               AND a.INSPECTION_LEVEL = 'II'
               AND a.AQL_VALUE = 2.5
               AND a.USE_YN = 'Y'),
           'IMMEDIATE_FAIL', 'Y', '품목 AQL 정책코드 전환 기본 정책', 'migration', 'migration'
      FROM (SELECT DISTINCT COMPANY, PLANT_CD FROM ITEM_MASTERS) s
     WHERE NOT EXISTS (
       SELECT 1 FROM IQC_AQL_POLICIES p
        WHERE p.COMPANY = s.COMPANY
          AND p.PLANT_CD = s.PLANT_CD
          AND p.POLICY_CODE = 'AQLP-II-1.0-2.5'
     )
  ]';

  IF v_has_level_col = 1 OR v_has_major_col = 1 OR v_has_minor_col = 1 THEN
    EXECUTE IMMEDIATE q'[
      INSERT INTO IQC_AQL_POLICIES (
        COMPANY, PLANT_CD, POLICY_CODE, POLICY_NAME, INSPECTION_LEVEL,
        MAJOR_AQL_CODE, MINOR_AQL_CODE, CRITICAL_MODE, USE_YN, REMARK, CREATED_BY, UPDATED_BY
      )
      WITH old_values AS (
        SELECT DISTINCT
               COMPANY,
               PLANT_CD,
               NVL(NULLIF(TRIM(INSPECTION_LEVEL), ''), 'II') AS LEVEL_CODE,
               AQL_MAJOR,
               AQL_MINOR,
               NVL(
                 RTRIM(RTRIM(TO_CHAR(AQL_MAJOR, 'FM9999990D999', 'NLS_NUMERIC_CHARACTERS=''.,'''), '0'), '.'),
                 'NA'
               ) AS MAJOR_TEXT,
               NVL(
                 RTRIM(RTRIM(TO_CHAR(AQL_MINOR, 'FM9999990D999', 'NLS_NUMERIC_CHARACTERS=''.,'''), '0'), '.'),
                 'NA'
               ) AS MINOR_TEXT
          FROM ITEM_MASTERS
         WHERE INSPECTION_LEVEL IS NOT NULL
            OR AQL_MAJOR IS NOT NULL
            OR AQL_MINOR IS NOT NULL
      ),
      policies AS (
        SELECT COMPANY,
               PLANT_CD,
               SUBSTR('AQLP-' || LEVEL_CODE || '-' || MAJOR_TEXT || '-' || MINOR_TEXT, 1, 50) AS POLICY_CODE,
               SUBSTR('IQC AQL ' || LEVEL_CODE || ' Major ' || MAJOR_TEXT || ' Minor ' || MINOR_TEXT, 1, 100) AS POLICY_NAME,
               LEVEL_CODE,
               AQL_MAJOR,
               AQL_MINOR
          FROM old_values
      )
      SELECT p.COMPANY,
             p.PLANT_CD,
             p.POLICY_CODE,
             p.POLICY_NAME,
             p.LEVEL_CODE,
             (SELECT MAX(a.AQL_CODE)
                FROM AQL_STANDARDS a
               WHERE a.COMPANY = p.COMPANY
                 AND a.PLANT_CD = p.PLANT_CD
                 AND a.INSPECTION_LEVEL = p.LEVEL_CODE
                 AND a.AQL_VALUE = p.AQL_MAJOR
                 AND a.USE_YN = 'Y'),
             (SELECT MAX(a.AQL_CODE)
                FROM AQL_STANDARDS a
               WHERE a.COMPANY = p.COMPANY
                 AND a.PLANT_CD = p.PLANT_CD
                 AND a.INSPECTION_LEVEL = p.LEVEL_CODE
                 AND a.AQL_VALUE = p.AQL_MINOR
                 AND a.USE_YN = 'Y'),
             'IMMEDIATE_FAIL',
             'Y',
             'ITEM_MASTERS 기존 AQL 속성에서 자동 전환',
             'migration',
             'migration'
        FROM policies p
       WHERE NOT EXISTS (
         SELECT 1 FROM IQC_AQL_POLICIES t
          WHERE t.COMPANY = p.COMPANY
            AND t.PLANT_CD = p.PLANT_CD
            AND t.POLICY_CODE = p.POLICY_CODE
       )
    ]';

    EXECUTE IMMEDIATE q'[
      UPDATE ITEM_MASTERS i
         SET IQC_AQL_POLICY_CODE = (
           SELECT SUBSTR(
                    'AQLP-' ||
                    NVL(NULLIF(TRIM(i.INSPECTION_LEVEL), ''), 'II') || '-' ||
                    NVL(RTRIM(RTRIM(TO_CHAR(i.AQL_MAJOR, 'FM9999990D999', 'NLS_NUMERIC_CHARACTERS=''.,'''), '0'), '.'), 'NA') || '-' ||
                    NVL(RTRIM(RTRIM(TO_CHAR(i.AQL_MINOR, 'FM9999990D999', 'NLS_NUMERIC_CHARACTERS=''.,'''), '0'), '.'), 'NA'),
                    1, 50
                  )
             FROM DUAL
         )
       WHERE i.IQC_AQL_POLICY_CODE IS NULL
         AND (i.INSPECTION_LEVEL IS NOT NULL OR i.AQL_MAJOR IS NOT NULL OR i.AQL_MINOR IS NOT NULL)
    ]';
  END IF;

  EXECUTE IMMEDIATE q'[
    UPDATE ITEM_MASTERS
       SET IQC_AQL_POLICY_CODE = 'AQLP-II-1.0-2.5'
     WHERE IQC_AQL_POLICY_CODE IS NULL
       AND NVL(IQC_FLAG, 'Y') = 'Y'
       AND EXISTS (
         SELECT 1 FROM IQC_AQL_POLICIES p
          WHERE p.COMPANY = ITEM_MASTERS.COMPANY
            AND p.PLANT_CD = ITEM_MASTERS.PLANT_CD
            AND p.POLICY_CODE = 'AQLP-II-1.0-2.5'
       )
  ]';

  IF v_has_level_col = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS DROP COLUMN INSPECTION_LEVEL';
  END IF;
  IF v_has_critical_col = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS DROP COLUMN AQL_CRITICAL';
  END IF;
  IF v_has_major_col = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS DROP COLUMN AQL_MAJOR';
  END IF;
  IF v_has_minor_col = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS DROP COLUMN AQL_MINOR';
  END IF;

  EXECUTE IMMEDIATE q'[
    UPDATE ITEM_MASTERS i
       SET IQC_AQL_POLICY_CODE = 'AQLP-II-1.0-2.5'
     WHERE IQC_AQL_POLICY_CODE = 'AQLP-II-1-2.5'
       AND EXISTS (
         SELECT 1 FROM IQC_AQL_POLICIES p
          WHERE p.COMPANY = i.COMPANY
            AND p.PLANT_CD = i.PLANT_CD
            AND p.POLICY_CODE = 'AQLP-II-1.0-2.5'
       )
  ]';

  EXECUTE IMMEDIATE q'[
    DELETE FROM IQC_AQL_POLICIES p
     WHERE p.POLICY_CODE = 'AQLP-II-1-2.5'
       AND NOT EXISTS (
         SELECT 1 FROM ITEM_MASTERS i
          WHERE i.COMPANY = p.COMPANY
            AND i.PLANT_CD = p.PLANT_CD
            AND i.IQC_AQL_POLICY_CODE = p.POLICY_CODE
       )
       AND EXISTS (
         SELECT 1 FROM IQC_AQL_POLICIES d
          WHERE d.COMPANY = p.COMPANY
            AND d.PLANT_CD = p.PLANT_CD
            AND d.POLICY_CODE = 'AQLP-II-1.0-2.5'
            AND d.INSPECTION_LEVEL = p.INSPECTION_LEVEL
            AND d.MAJOR_AQL_CODE = p.MAJOR_AQL_CODE
            AND d.MINOR_AQL_CODE = p.MINOR_AQL_CODE
       )
  ]';

  EXECUTE IMMEDIATE q'[
    INSERT INTO IQC_AQL_POLICIES (
      COMPANY, PLANT_CD, POLICY_CODE, POLICY_NAME, INSPECTION_LEVEL,
      MAJOR_AQL_CODE, MINOR_AQL_CODE, CRITICAL_MODE, USE_YN, REMARK, CREATED_BY, UPDATED_BY
    )
    SELECT s.COMPANY, s.PLANT_CD, s.POLICY_CODE, s.POLICY_NAME, 'II',
           s.MAJOR_AQL_CODE, s.MINOR_AQL_CODE,
           'IMMEDIATE_FAIL', 'Y', 'AQL 기준 등록값 기반 추가 정책', 'migration', 'migration'
      FROM (
        SELECT c.COMPANY, c.PLANT_CD, 'AQLP-II-1.0-4.0' AS POLICY_CODE,
               '기본 IQC AQL II Major 1.0 Minor 4.0' AS POLICY_NAME,
               'AQL-II-1.0' AS MAJOR_AQL_CODE, 'AQL-II-4.0' AS MINOR_AQL_CODE
          FROM (SELECT DISTINCT COMPANY, PLANT_CD FROM AQL_STANDARDS) c
         WHERE EXISTS (SELECT 1 FROM AQL_STANDARDS a WHERE a.COMPANY = c.COMPANY AND a.PLANT_CD = c.PLANT_CD AND a.AQL_CODE = 'AQL-II-1.0' AND a.USE_YN = 'Y')
           AND EXISTS (SELECT 1 FROM AQL_STANDARDS a WHERE a.COMPANY = c.COMPANY AND a.PLANT_CD = c.PLANT_CD AND a.AQL_CODE = 'AQL-II-4.0' AND a.USE_YN = 'Y')
        UNION ALL
        SELECT c.COMPANY, c.PLANT_CD, 'AQLP-II-2.5-4.0' AS POLICY_CODE,
               '기본 IQC AQL II Major 2.5 Minor 4.0' AS POLICY_NAME,
               'AQL-II-2.5' AS MAJOR_AQL_CODE, 'AQL-II-4.0' AS MINOR_AQL_CODE
          FROM (SELECT DISTINCT COMPANY, PLANT_CD FROM AQL_STANDARDS) c
         WHERE EXISTS (SELECT 1 FROM AQL_STANDARDS a WHERE a.COMPANY = c.COMPANY AND a.PLANT_CD = c.PLANT_CD AND a.AQL_CODE = 'AQL-II-2.5' AND a.USE_YN = 'Y')
           AND EXISTS (SELECT 1 FROM AQL_STANDARDS a WHERE a.COMPANY = c.COMPANY AND a.PLANT_CD = c.PLANT_CD AND a.AQL_CODE = 'AQL-II-4.0' AND a.USE_YN = 'Y')
      ) s
     WHERE NOT EXISTS (
       SELECT 1 FROM IQC_AQL_POLICIES p
        WHERE p.COMPANY = s.COMPANY
          AND p.PLANT_CD = s.PLANT_CD
          AND p.POLICY_CODE = s.POLICY_CODE
     )
  ]';

  EXECUTE IMMEDIATE q'[COMMENT ON TABLE IQC_AQL_POLICIES IS 'IQC AQL 정책 기준정보']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQC_AQL_POLICIES.POLICY_CODE IS 'IQC AQL 정책 코드']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQC_AQL_POLICIES.POLICY_NAME IS 'IQC AQL 정책명']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQC_AQL_POLICIES.INSPECTION_LEVEL IS '검사수준']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQC_AQL_POLICIES.MAJOR_AQL_CODE IS 'Major AQL 기준 코드']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQC_AQL_POLICIES.MINOR_AQL_CODE IS 'Minor AQL 기준 코드']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQC_AQL_POLICIES.CRITICAL_MODE IS 'Critical 불량 판정 방식']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.IQC_AQL_POLICY_CODE IS 'IQC AQL 정책 코드']';
END;
/
