BEGIN
  /*
   * 2026-05-26: IQC005 Phase A — PO 라인 메타 컬럼 신설
   * PURCHASE_ORDER_ITEMS: LINE_NO, REV_NO, LINE_STATUS
   * PURCHASE_ORDERS: USE_TYPE
   * 기존 행은 SEQ → LINE_NO, REV_NO=1, LINE_STATUS는 누적입하 비율로 계산.
   */
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PURCHASE_ORDER_ITEMS ADD (LINE_NO NUMBER)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN NULL;
      ELSE RAISE;
      END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PURCHASE_ORDER_ITEMS ADD (REV_NO NUMBER DEFAULT 1)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN NULL;
      ELSE RAISE;
      END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE PURCHASE_ORDER_ITEMS ADD (LINE_STATUS VARCHAR2(20) DEFAULT 'OPEN')]';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN NULL;
      ELSE RAISE;
      END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE PURCHASE_ORDERS ADD (USE_TYPE VARCHAR2(20) DEFAULT 'PROD')]';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN NULL;
      ELSE RAISE;
      END IF;
  END;
END;
/

BEGIN
  /* 백필 */
  UPDATE PURCHASE_ORDER_ITEMS SET LINE_NO = SEQ WHERE LINE_NO IS NULL;
  UPDATE PURCHASE_ORDER_ITEMS SET REV_NO = 1 WHERE REV_NO IS NULL;
  UPDATE PURCHASE_ORDER_ITEMS
     SET LINE_STATUS = CASE
       WHEN RECEIVED_QTY >= ORDER_QTY THEN 'CLOSE'
       WHEN RECEIVED_QTY > 0 THEN 'PARTIAL'
       ELSE 'OPEN'
     END
   WHERE LINE_STATUS IS NULL OR LINE_STATUS = 'OPEN';

  UPDATE PURCHASE_ORDERS SET USE_TYPE = 'PROD' WHERE USE_TYPE IS NULL;

  COMMIT;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.LINE_NO IS '발주 라인 번호 (IQC005 L/N)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.REV_NO IS '발주 라인 리비전 번호 (IQC005 R/N, 기본 1)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.LINE_STATUS IS '라인 상태: OPEN | PARTIAL | CLOSE']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PURCHASE_ORDERS.USE_TYPE IS '사용 구분: PROD(양산) | DEV(개발) | SAMPLE 등']';
END;
/
