-- 설비별 WIP 창고 행 삭제 (공정재고는 WIP_MAT_STOCKS 별도 테이블로 이관). WIP_MAIN(EQUIP_CODE NULL)은 보존.
DELETE FROM WAREHOUSES WHERE WAREHOUSE_TYPE='WIP' AND WAREHOUSE_CODE LIKE 'WIP\_%' ESCAPE '\' AND EQUIP_CODE IS NOT NULL;
