BEGIN
  /*
   * 2026-05-26: IQC005 Phase A — MAT_LOTS에 제조사 코드 컬럼 추가
   * 제조사 데이터는 PARTNER_MASTERS.PARTNER_TYPE='MFG' row를 참조한다.
   * 본 컬럼 추가는 idempotent (ORA-01430 catch).
   */
  EXECUTE IMMEDIATE 'ALTER TABLE MAT_LOTS ADD (MFG_PARTNER_CODE VARCHAR2(50))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; -- ORA-01430: column being added already exists
    ELSE RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN MAT_LOTS.MFG_PARTNER_CODE IS '제조사 거래처코드 (PARTNER_MASTERS.PARTNER_CODE, PARTNER_TYPE=MFG)']';
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_MAT_LOTS_MFG ON MAT_LOTS(MFG_PARTNER_CODE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; -- ORA-00955: name already used
    ELSE RAISE;
    END IF;
END;
/
