DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ITEM_MASTERS' AND COLUMN_NAME = 'INSPECTION_LEVEL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS ADD (INSPECTION_LEVEL VARCHAR2(20))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ITEM_MASTERS' AND COLUMN_NAME = 'AQL_CRITICAL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS ADD (AQL_CRITICAL NUMBER(8,3))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ITEM_MASTERS' AND COLUMN_NAME = 'AQL_MAJOR';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS ADD (AQL_MAJOR NUMBER(8,3))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ITEM_MASTERS' AND COLUMN_NAME = 'AQL_MINOR';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS ADD (AQL_MINOR NUMBER(8,3))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PARTNER_MASTERS' AND COLUMN_NAME = 'QUALITY_GRADE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PARTNER_MASTERS ADD (QUALITY_GRADE VARCHAR2(20))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PARTNER_MASTERS' AND COLUMN_NAME = 'INSPECTION_MODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE PARTNER_MASTERS ADD (INSPECTION_MODE VARCHAR2(20) DEFAULT 'NORMAL')]';
  END IF;

  EXECUTE IMMEDIATE q'[UPDATE PARTNER_MASTERS SET INSPECTION_MODE = 'NORMAL' WHERE INSPECTION_MODE IS NULL]';

  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_PARTNER_INSPECTION_MODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE PARTNER_MASTERS ADD CONSTRAINT CK_PARTNER_INSPECTION_MODE CHECK (INSPECTION_MODE IN ('TIGHTENED', 'NORMAL', 'REDUCED'))]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AQL_SAMPLING_RULES' AND COLUMN_NAME = 'CODE_LETTER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AQL_SAMPLING_RULES ADD (CODE_LETTER VARCHAR2(5))';
  END IF;

  EXECUTE IMMEDIATE q'[
    UPDATE AQL_SAMPLING_RULES SET CODE_LETTER =
      CASE LOT_QTY_FROM
        WHEN 2 THEN 'A'
        WHEN 9 THEN 'B'
        WHEN 16 THEN 'C'
        WHEN 26 THEN 'D'
        WHEN 51 THEN 'E'
        WHEN 91 THEN 'F'
        WHEN 151 THEN 'G'
        WHEN 281 THEN 'H'
        WHEN 501 THEN 'J'
        WHEN 1201 THEN 'K'
        WHEN 3201 THEN 'L'
        WHEN 10001 THEN 'M'
        WHEN 35001 THEN 'N'
        WHEN 150001 THEN 'P'
        WHEN 500001 THEN 'Q'
        ELSE CODE_LETTER
      END
    WHERE CODE_LETTER IS NULL
  ]';

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'VENDOR_CODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (VENDOR_CODE VARCHAR2(50))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'LOT_QTY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (LOT_QTY NUMBER)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_INSPECTION_LEVEL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_INSPECTION_LEVEL VARCHAR2(20))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_INSPECTION_MODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_INSPECTION_MODE VARCHAR2(20))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_SAMPLE_QTY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_SAMPLE_QTY NUMBER)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_MAJOR_CODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_MAJOR_CODE VARCHAR2(50))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_MAJOR_AC';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_MAJOR_AC NUMBER)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_MAJOR_RE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_MAJOR_RE NUMBER)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_MINOR_CODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_MINOR_CODE VARCHAR2(50))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_MINOR_AC';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_MINOR_AC NUMBER)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_MINOR_RE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_MINOR_RE NUMBER)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'DEFECT_CRITICAL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (DEFECT_CRITICAL NUMBER DEFAULT 0)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'DEFECT_MAJOR';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (DEFECT_MAJOR NUMBER DEFAULT 0)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'DEFECT_MINOR';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (DEFECT_MINOR NUMBER DEFAULT 0)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IQC_LOGS' AND COLUMN_NAME = 'AQL_JUDGE_REASON';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IQC_LOGS ADD (AQL_JUDGE_REASON VARCHAR2(500))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'VENDOR_INSPECTION_MODE_HISTORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE VENDOR_INSPECTION_MODE_HISTORY (
        SEQ NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        VENDOR_CODE VARCHAR2(50) NOT NULL,
        PREV_MODE VARCHAR2(20),
        NEW_MODE VARCHAR2(20) NOT NULL,
        REASON VARCHAR2(500),
        REF_ARRIVAL_NO VARCHAR2(100),
        REF_ITEM_CODE VARCHAR2(50),
        CHANGED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_VENDOR_INSP_MODE_HIST PRIMARY KEY (SEQ),
        CONSTRAINT CK_VENDOR_INSP_MODE_HIST CHECK (NEW_MODE IN ('TIGHTENED', 'NORMAL', 'REDUCED'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_IQC_LOGS_VENDOR_MODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IQC_LOGS_VENDOR_MODE ON IQC_LOGS (COMPANY, PLANT_CD, VENDOR_CODE, INSPECT_DATE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_VENDOR_INSP_MODE_HIST';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_VENDOR_INSP_MODE_HIST ON VENDOR_INSPECTION_MODE_HISTORY (COMPANY, PLANT_CD, VENDOR_CODE, CHANGED_AT)';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.SAMPLE_QTY IS '기본시료수. IQC 검사 시 사용할 시료량이며 AQL 산출 샘플수량과 별개']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.INSPECTION_LEVEL IS '품목 기준 AQL 검사수준']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.AQL_CRITICAL IS '품목 기준 Critical AQL. Critical 불량은 1건 이상 즉시 불합격']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.AQL_MAJOR IS '품목 기준 Major AQL']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.AQL_MINOR IS '품목 기준 Minor AQL']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PARTNER_MASTERS.QUALITY_GRADE IS '공급업체 품질등급']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PARTNER_MASTERS.INSPECTION_MODE IS '공급업체 검사강도: TIGHTENED/NORMAL/REDUCED']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_SAMPLING_RULES.CODE_LETTER IS 'ISO 2859-1 / ANSI ASQ Z1.4 코드 문자']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE VENDOR_INSPECTION_MODE_HISTORY IS '공급업체 검사강도 자동 전환 이력']';

  COMMIT;
END;
/
