DECLARE
  v_count NUMBER;
BEGIN
  -- T-HARNESS-WIRE-SPEC-SEPARATION
  -- 전선 길이/스트리핑 조건을 품목마스터에서 회로스펙/라우팅 연결로 분리한다.
  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'HARNESS_CIRCUIT_SPECS'
     AND COLUMN_NAME = 'WIRE_ITEM_CODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HARNESS_CIRCUIT_SPECS ADD WIRE_ITEM_CODE VARCHAR2(50)';
  END IF;
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN HARNESS_CIRCUIT_SPECS.WIRE_ITEM_CODE IS ''회로별 전선 BOM 품목코드''';

  SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_HARNESS_CIRCUIT_WIRE_ITEM';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_HARNESS_CIRCUIT_WIRE_ITEM ON HARNESS_CIRCUIT_SPECS (COMPANY, PLANT_CD, WIRE_ITEM_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ROUTING_MATERIALS'
     AND COLUMN_NAME = 'CIRCUIT_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_MATERIALS ADD CIRCUIT_ID NUMBER';
  END IF;
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN ROUTING_MATERIALS.CIRCUIT_ID IS ''공정 투입자재가 참조하는 회로 사양 ID''';

  SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_ROUTING_MATERIALS_CIRCUIT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ROUTING_MATERIALS_CIRCUIT ON ROUTING_MATERIALS (CIRCUIT_ID)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'FK_ROUTING_MATERIALS_CIRCUIT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_MATERIALS ADD CONSTRAINT FK_ROUTING_MATERIALS_CIRCUIT FOREIGN KEY (CIRCUIT_ID) REFERENCES HARNESS_CIRCUIT_SPECS (CIRCUIT_ID)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'LENGTH';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS DROP COLUMN LENGTH';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'STRIP_BEFORE';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS DROP COLUMN STRIP_BEFORE';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'STRIP_AFTER';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS DROP COLUMN STRIP_AFTER';
  END IF;
END;
/
