DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'DEFECT_CATEGORY_MASTERS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DEFECT_CATEGORY_MASTERS (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CATEGORY_CODE VARCHAR2(50) NOT NULL,
        CATEGORY_NAME VARCHAR2(100) NOT NULL,
        LEVEL_NO NUMBER(1) NOT NULL,
        PARENT_CATEGORY_CODE VARCHAR2(50),
        SORT_ORDER NUMBER(8) DEFAULT 0 NOT NULL,
        USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        DESCRIPTION VARCHAR2(500),
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_DEFECT_CATEGORY_MASTERS PRIMARY KEY (COMPANY, PLANT_CD, CATEGORY_CODE),
        CONSTRAINT CK_DEFECT_CATEGORY_LEVEL CHECK (LEVEL_NO IN (1, 2, 3)),
        CONSTRAINT CK_DEFECT_CATEGORY_USE_YN CHECK (USE_YN IN ('Y', 'N')),
        CONSTRAINT FK_DEFECT_CATEGORY_PARENT FOREIGN KEY (COMPANY, PLANT_CD, PARENT_CATEGORY_CODE)
          REFERENCES DEFECT_CATEGORY_MASTERS (COMPANY, PLANT_CD, CATEGORY_CODE)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'DEFECT_CODE_MASTERS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DEFECT_CODE_MASTERS (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        DEFECT_CODE VARCHAR2(50) NOT NULL,
        DEFECT_NAME VARCHAR2(100) NOT NULL,
        CATEGORY_CODE VARCHAR2(50) NOT NULL,
        DEFECT_GRADE VARCHAR2(20) NOT NULL,
        DEFECT_SCOPE VARCHAR2(30) DEFAULT 'COMMON' NOT NULL,
        DESCRIPTION VARCHAR2(500),
        SORT_ORDER NUMBER(8) DEFAULT 0 NOT NULL,
        USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_DEFECT_CODE_MASTERS PRIMARY KEY (COMPANY, PLANT_CD, DEFECT_CODE),
        CONSTRAINT CK_DEFECT_CODE_GRADE CHECK (DEFECT_GRADE IN ('CRITICAL', 'MAJOR', 'MINOR')),
        CONSTRAINT CK_DEFECT_CODE_SCOPE CHECK (DEFECT_SCOPE IN ('RAW_MATERIAL', 'PRODUCT', 'PROCESS', 'COMMON')),
        CONSTRAINT CK_DEFECT_CODE_USE_YN CHECK (USE_YN IN ('Y', 'N')),
        CONSTRAINT FK_DEFECT_CODE_CATEGORY FOREIGN KEY (COMPANY, PLANT_CD, CATEGORY_CODE)
          REFERENCES DEFECT_CATEGORY_MASTERS (COMPANY, PLANT_CD, CATEGORY_CODE)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'DEFECT_CODE_PRODUCT_TYPES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DEFECT_CODE_PRODUCT_TYPES (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        DEFECT_CODE VARCHAR2(50) NOT NULL,
        PRODUCT_TYPE VARCHAR2(50) NOT NULL,
        CREATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_DEFECT_CODE_PRODUCT_TYPES PRIMARY KEY (COMPANY, PLANT_CD, DEFECT_CODE, PRODUCT_TYPE),
        CONSTRAINT FK_DEFECT_PRODUCT_CODE FOREIGN KEY (COMPANY, PLANT_CD, DEFECT_CODE)
          REFERENCES DEFECT_CODE_MASTERS (COMPANY, PLANT_CD, DEFECT_CODE)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_DEFECT_CAT_PARENT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_DEFECT_CAT_PARENT ON DEFECT_CATEGORY_MASTERS (COMPANY, PLANT_CD, PARENT_CATEGORY_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_DEFECT_CODE_CATEGORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_DEFECT_CODE_CATEGORY ON DEFECT_CODE_MASTERS (COMPANY, PLANT_CD, CATEGORY_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_DEFECT_PRODUCT_TYPE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_DEFECT_PRODUCT_TYPE ON DEFECT_CODE_PRODUCT_TYPES (COMPANY, PLANT_CD, PRODUCT_TYPE)';
  END IF;

  EXECUTE IMMEDIATE q'[
    MERGE INTO COM_CODES d
    USING (
      WITH tenants AS (
        SELECT DISTINCT COMPANY, PLANT_CD FROM COM_CODES WHERE GROUP_CODE = 'DEFECT_TYPE'
        UNION
        SELECT '40' COMPANY, '1000' PLANT_CD FROM DUAL
        WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'DEFECT_TYPE')
      ),
      model_groups AS (
        SELECT 'LV' DETAIL_CODE, '저전압' CODE_NAME, 10 SORT_ORDER FROM DUAL UNION ALL
        SELECT 'HV', '고전압', 20 FROM DUAL
      )
      SELECT t.COMPANY, t.PLANT_CD, mg.*
      FROM tenants t CROSS JOIN model_groups mg
    ) s
    ON (
      d.COMPANY = s.COMPANY
      AND d.PLANT_CD = s.PLANT_CD
      AND d.GROUP_CODE = 'DEFECT_MODEL_GROUP'
      AND d.DETAIL_CODE = s.DETAIL_CODE
    )
    WHEN MATCHED THEN UPDATE SET
      d.CODE_NAME = s.CODE_NAME,
      d.SORT_ORDER = s.SORT_ORDER,
      d.USE_YN = 'Y',
      d.UPDATED_BY = 'migration',
      d.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN,
      COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
    ) VALUES (
      'DEFECT_MODEL_GROUP', s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y',
      s.COMPANY, s.PLANT_CD, 'migration', 'migration', SYSTIMESTAMP, SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE 'ALTER TABLE DEFECT_CATEGORY_MASTERS DISABLE CONSTRAINT FK_DEFECT_CATEGORY_PARENT';

  EXECUTE IMMEDIATE q'[
    MERGE INTO DEFECT_CATEGORY_MASTERS d
    USING (
      WITH tenants AS (
        SELECT DISTINCT COMPANY, PLANT_CD FROM COM_CODES WHERE GROUP_CODE = 'DEFECT_TYPE'
        UNION
        SELECT '40' AS COMPANY, '1000' AS PLANT_CD FROM DUAL
        WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'DEFECT_TYPE')
      ),
      stages AS (
        SELECT 'IQC' CATEGORY_CODE, 'IQC' CATEGORY_NAME, 10 SORT_ORDER FROM DUAL UNION ALL
        SELECT 'LQC', 'LQC', 20 FROM DUAL UNION ALL
        SELECT 'OQC', 'OQC', 30 FROM DUAL
      ),
      model_groups AS (
        SELECT
          c.COMPANY,
          c.PLANT_CD,
          c.DETAIL_CODE MODEL_GROUP,
          c.CODE_NAME MODEL_GROUP_NAME,
          ROW_NUMBER() OVER (PARTITION BY c.COMPANY, c.PLANT_CD ORDER BY c.SORT_ORDER, c.DETAIL_CODE) SORT_ORDER
        FROM COM_CODES c
        WHERE c.GROUP_CODE = 'DEFECT_MODEL_GROUP'
          AND c.USE_YN = 'Y'
        UNION ALL
        SELECT t.COMPANY, t.PLANT_CD, 'LV', '저전압', 10
        FROM tenants t
        WHERE NOT EXISTS (
          SELECT 1
          FROM COM_CODES c
          WHERE c.COMPANY = t.COMPANY
            AND c.PLANT_CD = t.PLANT_CD
            AND c.GROUP_CODE = 'DEFECT_MODEL_GROUP'
            AND c.USE_YN = 'Y'
            AND c.DETAIL_CODE = 'LV'
        )
        UNION ALL
        SELECT t.COMPANY, t.PLANT_CD, 'HV', '고전압', 20
        FROM tenants t
        WHERE NOT EXISTS (
          SELECT 1
          FROM COM_CODES c
          WHERE c.COMPANY = t.COMPANY
            AND c.PLANT_CD = t.PLANT_CD
            AND c.GROUP_CODE = 'DEFECT_MODEL_GROUP'
            AND c.USE_YN = 'Y'
            AND c.DETAIL_CODE = 'HV'
        )
      ),
      defect_kinds AS (
        SELECT 'FUNCTION' KIND_CODE, '기능' KIND_NAME, 10 SORT_ORDER FROM DUAL UNION ALL
        SELECT 'APPEARANCE', '외관', 20 FROM DUAL UNION ALL
        SELECT 'ETC', '기타', 30 FROM DUAL
      ),
      categories AS (
        SELECT
          t.COMPANY,
          t.PLANT_CD,
          s.CATEGORY_CODE,
          s.CATEGORY_NAME,
          1 LEVEL_NO,
          CAST(NULL AS VARCHAR2(50)) PARENT_CATEGORY_CODE,
          s.SORT_ORDER
        FROM tenants t CROSS JOIN stages s
        UNION ALL
        SELECT
          mg.COMPANY,
          mg.PLANT_CD,
          s.CATEGORY_CODE || '_' || mg.MODEL_GROUP,
          mg.MODEL_GROUP_NAME,
          2,
          s.CATEGORY_CODE,
          s.SORT_ORDER * 100 + mg.SORT_ORDER
        FROM model_groups mg CROSS JOIN stages s
        UNION ALL
        SELECT
          mg.COMPANY,
          mg.PLANT_CD,
          s.CATEGORY_CODE || '_' || mg.MODEL_GROUP || '_' || k.KIND_CODE,
          k.KIND_NAME,
          3,
          s.CATEGORY_CODE || '_' || mg.MODEL_GROUP,
          s.SORT_ORDER * 1000 + mg.SORT_ORDER * 10 + k.SORT_ORDER
        FROM model_groups mg CROSS JOIN stages s CROSS JOIN defect_kinds k
      )
      SELECT categories.*
      FROM categories
    ) s
    ON (d.COMPANY = s.COMPANY AND d.PLANT_CD = s.PLANT_CD AND d.CATEGORY_CODE = s.CATEGORY_CODE)
    WHEN NOT MATCHED THEN INSERT (
      COMPANY, PLANT_CD, CATEGORY_CODE, CATEGORY_NAME, LEVEL_NO, PARENT_CATEGORY_CODE,
      SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
    ) VALUES (
      s.COMPANY, s.PLANT_CD, s.CATEGORY_CODE, s.CATEGORY_NAME, s.LEVEL_NO, s.PARENT_CATEGORY_CODE,
      s.SORT_ORDER, 'Y', 'migration', 'migration', SYSTIMESTAMP, SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE 'ALTER TABLE DEFECT_CATEGORY_MASTERS ENABLE CONSTRAINT FK_DEFECT_CATEGORY_PARENT';

  EXECUTE IMMEDIATE q'[
    MERGE INTO DEFECT_CODE_MASTERS d
    USING (
      SELECT
        COMPANY,
        PLANT_CD,
        DETAIL_CODE AS DEFECT_CODE,
        CODE_NAME AS DEFECT_NAME,
        CASE
          WHEN DETAIL_CODE IN ('MATERIAL', 'MAT') THEN 'IQC_LV_ETC'
          WHEN DETAIL_CODE IN ('WORK', 'ASM', 'WELD') THEN 'LQC_LV_ETC'
          WHEN DETAIL_CODE = 'FUNC' THEN 'OQC_LV_FUNCTION'
          WHEN DETAIL_CODE IN ('APP', 'MARK', 'BURR', 'CRACK', 'DIM') THEN 'OQC_LV_APPEARANCE'
          ELSE 'OQC_LV_ETC'
        END AS CATEGORY_CODE,
        NVL(DEFECT_GRADE, CASE WHEN DETAIL_CODE = 'CRACK' THEN 'CRITICAL' ELSE 'MAJOR' END) AS DEFECT_GRADE,
        CASE
          WHEN DETAIL_CODE IN ('MATERIAL', 'MAT') THEN 'RAW_MATERIAL'
          WHEN DETAIL_CODE IN ('WORK', 'ASM', 'WELD') THEN 'PROCESS'
          WHEN DETAIL_CODE = 'ETC' THEN 'COMMON'
          ELSE 'PRODUCT'
        END AS DEFECT_SCOPE,
        SORT_ORDER,
        USE_YN
      FROM COM_CODES
      WHERE GROUP_CODE = 'DEFECT_TYPE'
    ) s
    ON (d.COMPANY = s.COMPANY AND d.PLANT_CD = s.PLANT_CD AND d.DEFECT_CODE = s.DEFECT_CODE)
    WHEN NOT MATCHED THEN INSERT (
      COMPANY, PLANT_CD, DEFECT_CODE, DEFECT_NAME, CATEGORY_CODE, DEFECT_GRADE, DEFECT_SCOPE,
      SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
    ) VALUES (
      s.COMPANY, s.PLANT_CD, s.DEFECT_CODE, s.DEFECT_NAME, s.CATEGORY_CODE, s.DEFECT_GRADE, s.DEFECT_SCOPE,
      s.SORT_ORDER, s.USE_YN, 'migration', 'migration', SYSTIMESTAMP, SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE q'[
    MERGE INTO DEFECT_CODE_PRODUCT_TYPES d
    USING (
      SELECT
        COMPANY,
        PLANT_CD,
        DETAIL_CODE AS DEFECT_CODE,
        'LV' AS PRODUCT_TYPE
      FROM COM_CODES
      WHERE GROUP_CODE = 'DEFECT_TYPE'
    ) s
    ON (
      d.COMPANY = s.COMPANY
      AND d.PLANT_CD = s.PLANT_CD
      AND d.DEFECT_CODE = s.DEFECT_CODE
      AND d.PRODUCT_TYPE = s.PRODUCT_TYPE
    )
    WHEN NOT MATCHED THEN INSERT (
      COMPANY, PLANT_CD, DEFECT_CODE, PRODUCT_TYPE, CREATED_BY, CREATED_AT
    ) VALUES (
      s.COMPANY, s.PLANT_CD, s.DEFECT_CODE, s.PRODUCT_TYPE, 'migration', SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE q'[
    MERGE INTO MENU_CATEGORY_ITEMS d
    USING (
      SELECT '40' COMPANY, '1000' PLANT_CD, 'QUALITY' CATEGORY_CODE, 'QC_DEFECT_CODE' MENU_CODE, 55 SORT_ORDER FROM DUAL
    ) s
    ON (d.COMPANY = s.COMPANY AND d.PLANT_CD = s.PLANT_CD AND d.MENU_CODE = s.MENU_CODE)
    WHEN NOT MATCHED THEN INSERT (
      COMPANY, PLANT_CD, CATEGORY_CODE, MENU_CODE, SORT_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
    ) VALUES (
      s.COMPANY, s.PLANT_CD, s.CATEGORY_CODE, s.MENU_CODE, s.SORT_ORDER, SYSTIMESTAMP, 'migration', SYSTIMESTAMP, 'migration'
    )
  ]';

  EXECUTE IMMEDIATE q'[COMMENT ON TABLE DEFECT_CATEGORY_MASTERS IS '불량코드 전용 3레벨 분류 마스터']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE DEFECT_CODE_MASTERS IS '불량코드 전용 마스터']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE DEFECT_CODE_PRODUCT_TYPES IS '불량코드 모델구분별 적용 매핑']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN DEFECT_CODE_PRODUCT_TYPES.PRODUCT_TYPE IS '모델구분 코드: DEFECT_MODEL_GROUP']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN DEFECT_CODE_MASTERS.DEFECT_GRADE IS 'CRITICAL/MAJOR/MINOR AQL 판정 등급']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN DEFECT_CODE_MASTERS.DEFECT_SCOPE IS 'RAW_MATERIAL/PRODUCT/PROCESS/COMMON 적용 범위']';

  COMMIT;
END;
/
