-- 공정수불(PROD_WIP_MAT_TRANS) 좌측 메뉴 DB 시드
-- 신규 leaf: PROD_WIP_MAT_TRANS / path /production/wip-material-trans / labelKey menu.production.wipMaterialTrans
-- 직전 PROD_WIP_MAT_STOCK(CATEGORY=PRODUCTION, SORT_ORDER=75) 바로 다음 SORT_ORDER=76에 배치.
-- 멀티테넌시 정본: COMPANY=40, PLANT_CD='1000'. 멱등 MERGE(ON = MENU_CODE+COMPANY+PLANT_CD). add-only.
-- MENU_PATH/MENU_NAME 컬럼은 없음(라벨/경로는 프론트 menuConfig.ts labelKey 기준).

-- 1) 메뉴 아이템 등록
MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'PROD_WIP_MAT_TRANS' AS MENU_CODE,
         'PRODUCTION'         AS CATEGORY_CODE,
         76                   AS SORT_ORDER,
         '40'                 AS COMPANY,
         '1000'               AS PLANT_CD
  FROM dual
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD,
          CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD,
          SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');

-- 2) RBAC 권한 등록 (직전 PROD_WIP_MAT_STOCK과 동일: MANAGER/OPERATOR CAN_ACCESS='Y')
MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER'  AS ROLE_CODE, 'PROD_WIP_MAT_TRANS' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
  UNION ALL
  SELECT 'OPERATOR' AS ROLE_CODE, 'PROD_WIP_MAT_TRANS' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD);
