-- FG_LABELS.STRUCTURE_YN: 구조검사 합불 컬럼 추가
-- 검사결과를 STATUS와 분리하여 생산흐름과 독립적으로 관리
ALTER TABLE FG_LABELS ADD STRUCTURE_YN VARCHAR2(1);
COMMENT ON COLUMN FG_LABELS.STRUCTURE_YN IS '구조검사 합불 (Y=합격, N=불합격, NULL=미검사)';

-- 기존 STRUCTURE_PASS/STRUCTURE_FAIL 데이터 마이그레이션
UPDATE FG_LABELS
SET STRUCTURE_YN = CASE
  WHEN STATUS = 'STRUCTURE_PASS' THEN 'Y'
  WHEN STATUS = 'STRUCTURE_FAIL' THEN 'N'
END
WHERE STATUS IN ('STRUCTURE_PASS', 'STRUCTURE_FAIL');

-- STATUS 값 정리 (STRUCTURE_PASS → ISSUED, STRUCTURE_FAIL → ISSUED)
UPDATE FG_LABELS SET STATUS = 'ISSUED'
WHERE STATUS IN ('STRUCTURE_PASS', 'STRUCTURE_FAIL')
  AND BOX_NO IS NULL;

-- 이미 박스에 담긴 경우 VISUAL_PASS로 복원
UPDATE FG_LABELS SET STATUS = 'VISUAL_PASS'
WHERE STATUS IN ('STRUCTURE_PASS', 'STRUCTURE_FAIL')
  AND BOX_NO IS NOT NULL;
