DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'EQUIP_MASTERS'
    AND COLUMN_NAME = 'CURRENT_WORKER_CODES';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_MASTERS ADD (CURRENT_WORKER_CODES VARCHAR2(1000))';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN EQUIP_MASTERS.CURRENT_WORKER_CODES IS '현재 설비에 배치된 작업자 코드 목록(콤마 구분). 표시 정보는 WORKER_MASTERS에서 재조회한다.']';
END;
/
