DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'MAT_LOTS'
     AND COLUMN_NAME = 'SPECIAL_ACCEPT_WORKER_CODE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MAT_LOTS ADD (SPECIAL_ACCEPT_WORKER_CODE VARCHAR2(50))';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN MAT_LOTS.SPECIAL_ACCEPT_WORKER_CODE IS '특채 처리 작업자 코드 (WORKER_MASTERS.WORKER_CODE 참조)']';

  SELECT COUNT(*)
    INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_MAT_LOTS_SA_WORKER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MAT_LOTS_SA_WORKER ON MAT_LOTS (COMPANY, PLANT_CD, SPECIAL_ACCEPT_WORKER_CODE)';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'FK_MAT_LOTS_SA_WORKER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MAT_LOTS ADD CONSTRAINT FK_MAT_LOTS_SA_WORKER FOREIGN KEY (COMPANY, PLANT_CD, SPECIAL_ACCEPT_WORKER_CODE) REFERENCES WORKER_MASTERS (COMPANY, PLANT_CD, WORKER_CODE)';
  END IF;
END;
/
