DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM USER_TABLES
   WHERE TABLE_NAME = 'COMM_CONFIGS';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE COMM_CONFIGS (
        CONFIG_NAME VARCHAR2(100) NOT NULL,
        COMM_TYPE VARCHAR2(50) NOT NULL,
        DESCRIPTION VARCHAR2(500),
        HOST VARCHAR2(255),
        PORT NUMBER,
        PORT_NAME VARCHAR2(50),
        BAUD_RATE NUMBER,
        DATA_BITS NUMBER,
        STOP_BITS VARCHAR2(10),
        PARITY VARCHAR2(10),
        FLOW_CONTROL VARCHAR2(20),
        LINE_ENDING VARCHAR2(10) DEFAULT ''NONE'',
        EXTRA_CONFIG CLOB,
        USE_YN VARCHAR2(1) DEFAULT ''Y'' NOT NULL,
        ORGANIZATION_ID NUMBER NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_COMM_CONFIGS PRIMARY KEY (CONFIG_NAME)
      )';

    EXECUTE IMMEDIATE 'CREATE INDEX IDX_COMM_CONFIGS_TYPE ON COMM_CONFIGS (COMM_TYPE)';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_COMM_CONFIGS_ORG ON COMM_CONFIGS (ORGANIZATION_ID)';
  END IF;
END;
/
