DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_HARNESS_DRAWING_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_HARNESS_DRAWING_ID START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_HARNESS_DRAWING_REV_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_HARNESS_DRAWING_REV_ID START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_HARNESS_CIRCUIT_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_HARNESS_CIRCUIT_ID START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'HARNESS_DRAWING_MASTERS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE HARNESS_DRAWING_MASTERS (
        DRAWING_ID NUMBER NOT NULL,
        DRAWING_NO VARCHAR2(100) NOT NULL,
        ITEM_CODE VARCHAR2(50) NOT NULL,
        ITEM_NAME VARCHAR2(200),
        ERP_ITEM_NO VARCHAR2(100),
        CUSTOMER_PART_NO VARCHAR2(100),
        REMARK VARCHAR2(1000),
        USE_YN VARCHAR2(1) DEFAULT ''Y'' NOT NULL,
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HARNESS_DRAWING_MASTERS PRIMARY KEY (DRAWING_ID),
        CONSTRAINT UK_HARNESS_DRAWING_NO UNIQUE (COMPANY, PLANT_CD, DRAWING_NO)
      )';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'HARNESS_DRAWING_REVISIONS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE HARNESS_DRAWING_REVISIONS (
        REVISION_ID NUMBER NOT NULL,
        DRAWING_ID NUMBER NOT NULL,
        REVISION_CODE VARCHAR2(20) NOT NULL,
        STATUS VARCHAR2(20) DEFAULT ''DRAFT'' NOT NULL,
        EFFECTIVE_FROM DATE,
        CHANGE_REASON VARCHAR2(1000),
        APPROVED_BY VARCHAR2(50),
        APPROVED_AT TIMESTAMP,
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HARNESS_DRAWING_REVISIONS PRIMARY KEY (REVISION_ID),
        CONSTRAINT UK_HARNESS_DRAWING_REV UNIQUE (COMPANY, PLANT_CD, DRAWING_ID, REVISION_CODE),
        CONSTRAINT CK_HARNESS_DRAWING_REV_STATUS CHECK (STATUS IN (''DRAFT'', ''APPROVED'', ''OBSOLETE'')),
        CONSTRAINT FK_HARNESS_REV_MASTER FOREIGN KEY (DRAWING_ID) REFERENCES HARNESS_DRAWING_MASTERS (DRAWING_ID)
      )';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'HARNESS_CIRCUIT_SPECS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE HARNESS_CIRCUIT_SPECS (
        CIRCUIT_ID NUMBER NOT NULL,
        REVISION_ID NUMBER NOT NULL,
        SORT_ORDER NUMBER DEFAULT 0 NOT NULL,
        CIRCUIT_NO VARCHAR2(50) NOT NULL,
        WIRE_SPEC VARCHAR2(100),
        WIRE_SIZE VARCHAR2(50),
        COLOR_CODE VARCHAR2(30),
        COLOR_NAME VARCHAR2(50),
        LENGTH_MM NUMBER(12,3),
        STRIP_A_MM NUMBER(8,3),
        STRIP_B_MM NUMBER(8,3),
        END_A_HOUSING VARCHAR2(100),
        END_A_TERMINAL VARCHAR2(100),
        CONNECTION_SYMBOL VARCHAR2(30),
        END_B_TERMINAL VARCHAR2(100),
        END_B_HOUSING VARCHAR2(100),
        TUBE_SPEC VARCHAR2(100),
        SUB_NO VARCHAR2(50),
        REMARK VARCHAR2(1000),
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HARNESS_CIRCUIT_SPECS PRIMARY KEY (CIRCUIT_ID),
        CONSTRAINT UK_HARNESS_CIRCUIT_NO UNIQUE (COMPANY, PLANT_CD, REVISION_ID, CIRCUIT_NO),
        CONSTRAINT FK_HARNESS_CIRCUIT_REV FOREIGN KEY (REVISION_ID) REFERENCES HARNESS_DRAWING_REVISIONS (REVISION_ID)
      )';
  END IF;

  MERGE INTO MENU_CATEGORY_ITEMS t
  USING (
    SELECT 'PROD_SPEC_SETUP' MENU_CODE, 'PRODUCTION' CATEGORY_CODE, 35 SORT_ORDER, '40' COMPANY, '1000' PLANT_CD FROM DUAL
  ) s
  ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
  WHEN NOT MATCHED THEN
    INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
    VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD, 'migration', 'migration');

  EXECUTE IMMEDIATE q'[COMMENT ON TABLE HARNESS_DRAWING_MASTERS IS '하네스 제품 도면 Header']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE HARNESS_DRAWING_REVISIONS IS '하네스 제품 도면 Revision']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE HARNESS_CIRCUIT_SPECS IS '하네스 제품 도면 회로별 제작 사양']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN HARNESS_CIRCUIT_SPECS.CIRCUIT_NO IS 'Circuit: 하네스 내 회로/전선 식별 번호']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN HARNESS_CIRCUIT_SPECS.STRIP_A_MM IS 'A측 피복 탈피 길이(mm)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN HARNESS_CIRCUIT_SPECS.STRIP_B_MM IS 'B측 피복 탈피 길이(mm)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN HARNESS_CIRCUIT_SPECS.END_A_HOUSING IS 'A측 터미널 삽입 하우징']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN HARNESS_CIRCUIT_SPECS.END_B_HOUSING IS 'B측 터미널 삽입 하우징']';
END;
/
