BEGIN
  UPDATE COM_CODES SET CREATED_AT = CURRENT_TIMESTAMP WHERE CREATED_AT IS NULL;
  UPDATE COM_CODES SET UPDATED_AT = CURRENT_TIMESTAMP WHERE UPDATED_AT IS NULL;
  UPDATE EQUIP_INSPECT_LOGS SET CREATED_AT = CURRENT_TIMESTAMP WHERE CREATED_AT IS NULL;
  UPDATE EQUIP_INSPECT_LOGS SET UPDATED_AT = CURRENT_TIMESTAMP WHERE UPDATED_AT IS NULL;
  UPDATE EQUIP_PROTOCOLS SET DELIMITER = ',' WHERE DELIMITER IS NULL;
  UPDATE ITEM_MASTERS SET BOX_QTY = 0 WHERE BOX_QTY IS NULL;
  UPDATE JOB_ORDERS SET CREATED_AT = CURRENT_TIMESTAMP WHERE CREATED_AT IS NULL;
  UPDATE PARTNER_MASTERS SET CREATED_AT = CURRENT_TIMESTAMP WHERE CREATED_AT IS NULL;
  UPDATE PARTNER_MASTERS SET UPDATED_AT = CURRENT_TIMESTAMP WHERE UPDATED_AT IS NULL;
  UPDATE SHIPMENT_LOGS SET CREATED_AT = CURRENT_TIMESTAMP WHERE CREATED_AT IS NULL;

  EXECUTE IMMEDIATE 'ALTER TABLE COM_CODES MODIFY (CREATED_AT NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE COM_CODES MODIFY (UPDATED_AT NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_LOGS MODIFY (CREATED_AT NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_LOGS MODIFY (UPDATED_AT NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_PROTOCOLS MODIFY (DELIMITER NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS MODIFY (BOX_QTY NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE JOB_ORDERS MODIFY (CREATED_AT NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE PARTNER_MASTERS MODIFY (CREATED_AT NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE PARTNER_MASTERS MODIFY (UPDATED_AT NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE SHIPMENT_LOGS MODIFY (CREATED_AT NOT NULL)';
END;
/
