DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ROUTING_PROCESSES' AND COLUMN_NAME = 'ISSUE_SG_LABEL_YN';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (ISSUE_SG_LABEL_YN VARCHAR2(1) DEFAULT ''N'')';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ROUTING_PROCESSES' AND COLUMN_NAME = 'ISSUE_FG_LABEL_YN';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (ISSUE_FG_LABEL_YN VARCHAR2(1) DEFAULT ''N'')';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ROUTING_PROCESSES.ISSUE_SG_LABEL_YN IS '이 공정에서 반제품 묶음 추적라벨(SG) 발행 여부 Y/N']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ROUTING_PROCESSES.ISSUE_FG_LABEL_YN IS '이 공정(서브공정)에서 제품라벨(FG) 발행 여부 Y/N']';
END;
/
