BEGIN
  /*
   * 2026-05-26: IQC005 Phase A — 자재 시리얼 & 입하실적코드 일별 시퀀스
   * 형식: VH1-RM + YYMMDD + 5자리(SEQ_MAT_SERIAL_DAILY)
   *       R + YYMMDD + 5자리(SEQ_ARRIVAL_NO_DAILY)
   * 일별 리셋은 DBMS_SCHEDULER 잡(별도 마이그레이션)에서 처리.
   */
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE SEQ_MAT_SERIAL_DAILY
    START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE ORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; -- ORA-00955: name already used
    ELSE RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE SEQ_ARRIVAL_NO_DAILY
    START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE ORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL;
    ELSE RAISE;
    END IF;
END;
/
