-- 2026-06-18 품목마스터에 색상(COLOR)·길이(LENGTH)·스트리핑 전/후(STRIP_BEFORE/STRIP_AFTER) 컬럼 추가
-- 재실행 시 이미 존재하면 ORA-01430(컬럼 중복) — 무시 가능.
ALTER TABLE ITEM_MASTERS ADD (COLOR VARCHAR2(50));
/
ALTER TABLE ITEM_MASTERS ADD (LENGTH NUMBER);
/
ALTER TABLE ITEM_MASTERS ADD (STRIP_BEFORE NUMBER, STRIP_AFTER NUMBER);
/
COMMENT ON COLUMN ITEM_MASTERS.COLOR IS '품목 색상';
/
COMMENT ON COLUMN ITEM_MASTERS.LENGTH IS '품목 길이';
/
COMMENT ON COLUMN ITEM_MASTERS.STRIP_BEFORE IS '스트리핑 전';
/
COMMENT ON COLUMN ITEM_MASTERS.STRIP_AFTER IS '스트리핑 후';
/
-- ITEM_MASTERS를 참조하는 PL/SQL이 무효화되므로 재컴파일(ORA-04068 예방)
ALTER PACKAGE PKG_DASHBOARD COMPILE BODY;
/
ALTER PROCEDURE IF_ITEM_MASTER COMPILE;
/
