DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'ITEM_MASTERS'
    AND COLUMN_NAME = 'DEFECT_MODEL_GROUP';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS ADD DEFECT_MODEL_GROUP VARCHAR2(50)';
  END IF;

  EXECUTE IMMEDIATE q'[
    MERGE INTO COM_CODES d
    USING (
      SELECT '40' COMPANY, '1000' PLANT_CD, 'LV' DETAIL_CODE, '저전압' CODE_NAME, 10 SORT_ORDER FROM DUAL UNION ALL
      SELECT '40', '1000', 'HV', '고전압', 20 FROM DUAL
    ) s
    ON (
      d.COMPANY = s.COMPANY
      AND d.PLANT_CD = s.PLANT_CD
      AND d.GROUP_CODE = 'DEFECT_MODEL_GROUP'
      AND d.DETAIL_CODE = s.DETAIL_CODE
    )
    WHEN MATCHED THEN UPDATE SET
      d.CODE_NAME = s.CODE_NAME,
      d.SORT_ORDER = s.SORT_ORDER,
      d.USE_YN = 'Y',
      d.UPDATED_BY = 'migration',
      d.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN,
      COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
    ) VALUES (
      'DEFECT_MODEL_GROUP', s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y',
      s.COMPANY, s.PLANT_CD, 'migration', 'migration', SYSTIMESTAMP, SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.DEFECT_MODEL_GROUP IS '불량코드 모델구분: LV=저전압 HV=고전압']';

  EXECUTE IMMEDIATE q'[
    UPDATE ITEM_MASTERS
       SET DEFECT_MODEL_GROUP = 'LV',
           UPDATED_BY = 'migration',
           UPDATED_AT = SYSTIMESTAMP
     WHERE COMPANY = '40'
       AND PLANT_CD = '1000'
       AND DEFECT_MODEL_GROUP IS NULL
  ]';

  COMMIT;
END;
/
