-- 2026-05-28: 엔티티-DB 불일치 수정 (audit_entity_columns.py 결과)
-- 적용 완료 (JSHANES)

-- 1. PM_WO_RESULTS: WORK_ORDER_ID(NUMBER) → WORK_ORDER_NO(VARCHAR2(20))
--    PK 재생성: (WORK_ORDER_NO, SEQ)
ALTER TABLE PM_WO_RESULTS DROP CONSTRAINT PK_PM_WO_RESULTS
/
ALTER TABLE PM_WO_RESULTS DROP COLUMN WORK_ORDER_ID
/
ALTER TABLE PM_WO_RESULTS ADD (WORK_ORDER_NO VARCHAR2(20) DEFAULT 'UNKNOWN' NOT NULL)
/
ALTER TABLE PM_WO_RESULTS MODIFY (WORK_ORDER_NO DEFAULT NULL)
/
ALTER TABLE PM_WO_RESULTS ADD CONSTRAINT PK_PM_WO_RESULTS PRIMARY KEY (WORK_ORDER_NO, SEQ)
/

-- 2. REPAIR_ORDERS 테이블 신규 생성 (repair-order.entity.ts)
CREATE TABLE REPAIR_ORDERS (
  REPAIR_DATE     DATE          NOT NULL,
  SEQ             NUMBER(10)    NOT NULL,
  STATUS          VARCHAR2(20)  DEFAULT 'RECEIVED' NOT NULL,
  FG_BARCODE      VARCHAR2(100),
  ITEM_CODE       VARCHAR2(50)  NOT NULL,
  ITEM_NAME       VARCHAR2(200),
  QTY             NUMBER(10)    DEFAULT 1 NOT NULL,
  PRD_UID         VARCHAR2(50),
  SOURCE_PROCESS  VARCHAR2(50),
  RETURN_PROCESS  VARCHAR2(50),
  REPAIR_RESULT   VARCHAR2(50),
  GENUINE_TYPE    VARCHAR2(50),
  DEFECT_TYPE     VARCHAR2(50),
  DEFECT_CAUSE    VARCHAR2(50),
  DEFECT_POSITION VARCHAR2(50),
  DISPOSITION     VARCHAR2(50),
  WORKER_ID       VARCHAR2(50),
  RECEIVED_AT     TIMESTAMP,
  COMPLETED_AT    TIMESTAMP,
  REMARK          VARCHAR2(500),
  COMPANY         VARCHAR2(50),
  PLANT_CD        VARCHAR2(50),
  CREATED_BY      VARCHAR2(50),
  UPDATED_BY      VARCHAR2(50),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_REPAIR_ORDERS PRIMARY KEY (REPAIR_DATE, SEQ)
)
/
CREATE INDEX IDX_REPAIR_ORDERS_STATUS  ON REPAIR_ORDERS (STATUS)
/
CREATE INDEX IDX_REPAIR_ORDERS_ITEM    ON REPAIR_ORDERS (ITEM_CODE)
/
CREATE INDEX IDX_REPAIR_ORDERS_BARCODE ON REPAIR_ORDERS (FG_BARCODE)
/
CREATE INDEX IDX_REPAIR_ORDERS_WORKER  ON REPAIR_ORDERS (WORKER_ID)
/

-- 3. REPAIR_USED_PARTS 테이블 신규 생성 (repair-used-part.entity.ts)
CREATE TABLE REPAIR_USED_PARTS (
  REPAIR_DATE  DATE          NOT NULL,
  SEQ          NUMBER(10)    NOT NULL,
  ITEM_CODE    VARCHAR2(50)  NOT NULL,
  ITEM_NAME    VARCHAR2(200),
  PRD_UID      VARCHAR2(50),
  QTY          NUMBER(10)    DEFAULT 1 NOT NULL,
  REMARK       VARCHAR2(500),
  COMPANY      VARCHAR2(50),
  PLANT_CD     VARCHAR2(50),
  CREATED_BY   VARCHAR2(50),
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_REPAIR_USED_PARTS PRIMARY KEY (REPAIR_DATE, SEQ, ITEM_CODE)
)
/

-- 참고: simulation-result.entity.ts의 오탐 컬럼들은
--       SIMULATION_PLANS / SIMULATION_SCHEDULES 테이블에 정상 존재 (문제 없음)
