-- N91H00 라우팅 정확화: 회신 공정명 전용 공정코드 추가 + 라우팅 교체
-- 일반압착/커넥터체결/외장재조립/최종검사 (기존 근사 매핑 대체)

-- 1) PROCESS_MASTERS 신규 공정코드
MERGE INTO PROCESS_MASTERS p USING (SELECT '40' C,'1000' PL,'GCRMP' PC FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.PL AND p.PROCESS_CODE=x.PC)
WHEN NOT MATCHED THEN INSERT (PROCESS_CODE,PROCESS_NAME,PROCESS_TYPE,SORT_ORDER,USE_YN,COMPANY,PLANT_CD,CREATED_BY) VALUES ('GCRMP','일반압착','CRIMPING',901,'Y','40','1000','claude');
/
MERGE INTO PROCESS_MASTERS p USING (SELECT '40' C,'1000' PL,'CONAS' PC FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.PL AND p.PROCESS_CODE=x.PC)
WHEN NOT MATCHED THEN INSERT (PROCESS_CODE,PROCESS_NAME,PROCESS_TYPE,SORT_ORDER,USE_YN,COMPANY,PLANT_CD,CREATED_BY) VALUES ('CONAS','커넥터체결','ASSEMBLY',902,'Y','40','1000','claude');
/
MERGE INTO PROCESS_MASTERS p USING (SELECT '40' C,'1000' PL,'EXTAS' PC FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.PL AND p.PROCESS_CODE=x.PC)
WHEN NOT MATCHED THEN INSERT (PROCESS_CODE,PROCESS_NAME,PROCESS_TYPE,SORT_ORDER,USE_YN,COMPANY,PLANT_CD,CREATED_BY) VALUES ('EXTAS','외장재조립','ASSEMBLY',903,'Y','40','1000','claude');
/
MERGE INTO PROCESS_MASTERS p USING (SELECT '40' C,'1000' PL,'FINSP' PC FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.PL AND p.PROCESS_CODE=x.PC)
WHEN NOT MATCHED THEN INSERT (PROCESS_CODE,PROCESS_NAME,PROCESS_TYPE,SORT_ORDER,USE_YN,COMPANY,PLANT_CD,CREATED_BY) VALUES ('FINSP','최종검사','INSPECTION',904,'Y','40','1000','claude');
/

-- 2) 라우팅 공정 교체 (PROCESS_CODE + PROCESS_NAME)
UPDATE ROUTING_PROCESSES SET PROCESS_CODE='GCRMP', PROCESS_NAME='일반압착', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
 WHERE COMPANY='40' AND ROUTING_CODE IN ('RT_N91H00-X9800-C1','RT_N91H00-X9800-C2') AND SEQ=50 AND PROCESS_CODE='TMCRP';
/
UPDATE ROUTING_PROCESSES SET PROCESS_CODE='CONAS', PROCESS_NAME='커넥터체결', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
 WHERE COMPANY='40' AND ROUTING_CODE='RT_N91H00-X9800' AND SEQ=40 AND PROCESS_CODE='PROTC';
/
UPDATE ROUTING_PROCESSES SET PROCESS_CODE='EXTAS', PROCESS_NAME='외장재조립', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
 WHERE COMPANY='40' AND ROUTING_CODE='RT_N91H00-X9800' AND SEQ=50 AND PROCESS_CODE='MASSY';
/
UPDATE ROUTING_PROCESSES SET PROCESS_CODE='FINSP', PROCESS_NAME='최종검사', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
 WHERE COMPANY='40' AND ROUTING_CODE='RT_N91H00-X9800' AND SEQ=70 AND PROCESS_CODE='AINSP';
/
COMMIT;
/
