-- 메뉴 카테고리 테넌트 키를 COMPANY/PLANT_CD → ORGANIZATION_ID 로 전환한다.
-- 은성전장은 단일 조직(ORGANIZATION_ID=1)이며, COMPANY는 표시용 정보로만 사용한다.
-- 대상: MENU_CATEGORIES, MENU_CATEGORY_ITEMS (이 DB에서 COMPANY+PLANT_CD를 키로 쓰는 유일한 2개 테이블)
-- 기존 데이터는 사실상 비어있어(고아 1건) 백필로 org=1 지정 후 company/plant 컬럼을 제거한다.

-- 1) child FK 먼저 제거 (부모 PK 재구성을 위해)
ALTER TABLE MENU_CATEGORY_ITEMS DROP CONSTRAINT FK_MENU_CAT_ITEM_CAT;

-- 2) MENU_CATEGORIES: ORGANIZATION_ID 추가 → 백필 → PK 재구성 → company/plant 제거
ALTER TABLE MENU_CATEGORIES ADD (ORGANIZATION_ID NUMBER);
UPDATE MENU_CATEGORIES SET ORGANIZATION_ID = 1 WHERE ORGANIZATION_ID IS NULL;
ALTER TABLE MENU_CATEGORIES MODIFY (ORGANIZATION_ID NUMBER NOT NULL);
ALTER TABLE MENU_CATEGORIES DROP PRIMARY KEY;
ALTER TABLE MENU_CATEGORIES ADD CONSTRAINT PK_MENU_CATEGORIES PRIMARY KEY (ORGANIZATION_ID, CATEGORY_CODE);
ALTER TABLE MENU_CATEGORIES DROP COLUMN COMPANY;
ALTER TABLE MENU_CATEGORIES DROP COLUMN PLANT_CD;

-- 3) MENU_CATEGORY_ITEMS: ORGANIZATION_ID 추가 → 백필 → PK 재구성 → company/plant 제거
ALTER TABLE MENU_CATEGORY_ITEMS ADD (ORGANIZATION_ID NUMBER);
UPDATE MENU_CATEGORY_ITEMS SET ORGANIZATION_ID = 1 WHERE ORGANIZATION_ID IS NULL;
ALTER TABLE MENU_CATEGORY_ITEMS MODIFY (ORGANIZATION_ID NUMBER NOT NULL);
ALTER TABLE MENU_CATEGORY_ITEMS DROP PRIMARY KEY;
ALTER TABLE MENU_CATEGORY_ITEMS ADD CONSTRAINT PK_MENU_CATEGORY_ITEMS PRIMARY KEY (ORGANIZATION_ID, MENU_CODE);
ALTER TABLE MENU_CATEGORY_ITEMS DROP COLUMN COMPANY;
ALTER TABLE MENU_CATEGORY_ITEMS DROP COLUMN PLANT_CD;

-- 4) FK 재생성 (ORGANIZATION_ID 기준)
ALTER TABLE MENU_CATEGORY_ITEMS ADD CONSTRAINT FK_MENU_CAT_ITEM_CAT
  FOREIGN KEY (ORGANIZATION_ID, CATEGORY_CODE) REFERENCES MENU_CATEGORIES (ORGANIZATION_ID, CATEGORY_CODE);
