DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'AQL_CODE_LETTER_RULES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE AQL_CODE_LETTER_RULES (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        INSPECTION_LEVEL VARCHAR2(20) NOT NULL,
        LOT_QTY_FROM NUMBER NOT NULL,
        LOT_QTY_TO NUMBER NOT NULL,
        CODE_LETTER VARCHAR2(5) NOT NULL,
        SORT_ORDER NUMBER,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_AQL_CODE_LETTER_RULES PRIMARY KEY (COMPANY, PLANT_CD, INSPECTION_LEVEL, LOT_QTY_FROM),
        CONSTRAINT CK_AQL_CODE_LETTER_RANGE CHECK (LOT_QTY_FROM <= LOT_QTY_TO)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'AQL_CODE_LETTER_SAMPLES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE AQL_CODE_LETTER_SAMPLES (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CODE_LETTER VARCHAR2(5) NOT NULL,
        SAMPLE_SIZE NUMBER NOT NULL,
        SORT_ORDER NUMBER,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_AQL_CODE_LETTER_SAMPLES PRIMARY KEY (COMPANY, PLANT_CD, CODE_LETTER)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'AQL_ACCEPTANCE_RULES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE AQL_ACCEPTANCE_RULES (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        INSPECTION_MODE VARCHAR2(20) NOT NULL,
        CODE_LETTER VARCHAR2(5) NOT NULL,
        AQL_VALUE NUMBER(8,3) NOT NULL,
        SAMPLE_CODE_LETTER VARCHAR2(5) NOT NULL,
        ACCEPT_QTY NUMBER NOT NULL,
        REJECT_QTY NUMBER NOT NULL,
        SORT_ORDER NUMBER,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_AQL_ACCEPTANCE_RULES PRIMARY KEY (COMPANY, PLANT_CD, INSPECTION_MODE, CODE_LETTER, AQL_VALUE),
        CONSTRAINT CK_AQL_ACCEPT_REJECT CHECK (REJECT_QTY > ACCEPT_QTY)
      )
    ]';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON TABLE AQL_CODE_LETTER_RULES IS 'ISO 2859-1 LOT 수량/검사수준별 Sample Size Code Letter 표']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE AQL_CODE_LETTER_SAMPLES IS 'ISO 2859-1 Code Letter별 표준 샘플수량 표']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE AQL_ACCEPTANCE_RULES IS 'ISO 2859-1 Code Letter와 AQL값별 Ac/Re 판정표']';
END;
/

MERGE INTO AQL_CODE_LETTER_SAMPLES t
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, CODE_LETTER, SAMPLE_SIZE, SORT_ORDER
  FROM (
    SELECT 'A' CODE_LETTER, 2 SAMPLE_SIZE, 1 SORT_ORDER FROM DUAL UNION ALL
    SELECT 'B', 3, 2 FROM DUAL UNION ALL
    SELECT 'C', 5, 3 FROM DUAL UNION ALL
    SELECT 'D', 8, 4 FROM DUAL UNION ALL
    SELECT 'E', 13, 5 FROM DUAL UNION ALL
    SELECT 'F', 20, 6 FROM DUAL UNION ALL
    SELECT 'G', 32, 7 FROM DUAL UNION ALL
    SELECT 'H', 50, 8 FROM DUAL UNION ALL
    SELECT 'J', 80, 9 FROM DUAL UNION ALL
    SELECT 'K', 125, 10 FROM DUAL UNION ALL
    SELECT 'L', 200, 11 FROM DUAL UNION ALL
    SELECT 'M', 315, 12 FROM DUAL UNION ALL
    SELECT 'N', 500, 13 FROM DUAL UNION ALL
    SELECT 'P', 800, 14 FROM DUAL UNION ALL
    SELECT 'Q', 1250, 15 FROM DUAL UNION ALL
    SELECT 'R', 2000, 16 FROM DUAL
  )
) x
ON (t.COMPANY = x.COMPANY AND t.PLANT_CD = x.PLANT_CD AND t.CODE_LETTER = x.CODE_LETTER)
WHEN MATCHED THEN UPDATE SET t.SAMPLE_SIZE = x.SAMPLE_SIZE, t.SORT_ORDER = x.SORT_ORDER, t.UPDATED_BY = 'codex', t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, CODE_LETTER, SAMPLE_SIZE, SORT_ORDER, CREATED_BY)
VALUES (x.COMPANY, x.PLANT_CD, x.CODE_LETTER, x.SAMPLE_SIZE, x.SORT_ORDER, 'codex');
/

MERGE INTO AQL_CODE_LETTER_RULES t
USING (
  WITH lot_rows AS (
    SELECT 2 F, 8 T, 1 O, 'A' L_I, 'A' L_II, 'B' L_III, 'A' L_S1, 'A' L_S2, 'A' L_S3, 'A' L_S4 FROM DUAL UNION ALL
    SELECT 9, 15, 2, 'A','B','C','A','A','A','A' FROM DUAL UNION ALL
    SELECT 16, 25, 3, 'B','C','D','A','A','B','B' FROM DUAL UNION ALL
    SELECT 26, 50, 4, 'C','D','E','A','B','B','C' FROM DUAL UNION ALL
    SELECT 51, 90, 5, 'C','E','F','B','B','C','C' FROM DUAL UNION ALL
    SELECT 91, 150, 6, 'D','F','G','B','B','C','D' FROM DUAL UNION ALL
    SELECT 151, 280, 7, 'E','G','H','B','C','D','E' FROM DUAL UNION ALL
    SELECT 281, 500, 8, 'F','H','J','B','C','D','E' FROM DUAL UNION ALL
    SELECT 501, 1200, 9, 'G','J','K','C','C','E','F' FROM DUAL UNION ALL
    SELECT 1201, 3200, 10, 'H','K','L','C','D','E','G' FROM DUAL UNION ALL
    SELECT 3201, 10000, 11, 'J','L','M','C','D','F','G' FROM DUAL UNION ALL
    SELECT 10001, 35000, 12, 'K','M','N','C','D','F','H' FROM DUAL UNION ALL
    SELECT 35001, 150000, 13, 'L','N','P','D','E','G','J' FROM DUAL UNION ALL
    SELECT 150001, 500000, 14, 'M','P','Q','D','E','G','J' FROM DUAL UNION ALL
    SELECT 500001, 999999999, 15, 'N','Q','R','D','E','H','K' FROM DUAL
  )
  SELECT '40' COMPANY, '1000' PLANT_CD, INSPECTION_LEVEL, F LOT_QTY_FROM, T LOT_QTY_TO, CODE_LETTER, O SORT_ORDER
  FROM lot_rows
  UNPIVOT (CODE_LETTER FOR INSPECTION_LEVEL IN (
    L_I AS 'I', L_II AS 'II', L_III AS 'III', L_S1 AS 'S1', L_S2 AS 'S2', L_S3 AS 'S3', L_S4 AS 'S4'
  ))
) x
ON (t.COMPANY = x.COMPANY AND t.PLANT_CD = x.PLANT_CD AND t.INSPECTION_LEVEL = x.INSPECTION_LEVEL AND t.LOT_QTY_FROM = x.LOT_QTY_FROM)
WHEN MATCHED THEN UPDATE SET t.LOT_QTY_TO = x.LOT_QTY_TO, t.CODE_LETTER = x.CODE_LETTER, t.SORT_ORDER = x.SORT_ORDER, t.UPDATED_BY = 'codex', t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, INSPECTION_LEVEL, LOT_QTY_FROM, LOT_QTY_TO, CODE_LETTER, SORT_ORDER, CREATED_BY)
VALUES (x.COMPANY, x.PLANT_CD, x.INSPECTION_LEVEL, x.LOT_QTY_FROM, x.LOT_QTY_TO, x.CODE_LETTER, x.SORT_ORDER, 'codex');
/

MERGE INTO AQL_ACCEPTANCE_RULES t
USING (
  SELECT r.COMPANY,
         r.PLANT_CD,
         'NORMAL' INSPECTION_MODE,
         r.CODE_LETTER,
         s.AQL_VALUE,
         MIN(sm.CODE_LETTER) KEEP (DENSE_RANK FIRST ORDER BY ABS(sm.SAMPLE_SIZE - r.SAMPLE_SIZE), sm.SORT_ORDER) SAMPLE_CODE_LETTER,
         MIN(r.ACCEPT_QTY) ACCEPT_QTY,
         MIN(r.REJECT_QTY) REJECT_QTY,
         MIN(sm.SORT_ORDER) SORT_ORDER
    FROM AQL_SAMPLING_RULES r
    JOIN AQL_STANDARDS s
      ON s.COMPANY = r.COMPANY
     AND s.PLANT_CD = r.PLANT_CD
     AND s.AQL_CODE = r.AQL_CODE
    JOIN AQL_CODE_LETTER_SAMPLES sm
      ON sm.COMPANY = r.COMPANY
     AND sm.PLANT_CD = r.PLANT_CD
   WHERE r.COMPANY = '40'
     AND r.PLANT_CD = '1000'
     AND r.CODE_LETTER IS NOT NULL
     AND s.AQL_VALUE IS NOT NULL
   GROUP BY r.COMPANY, r.PLANT_CD, r.CODE_LETTER, s.AQL_VALUE
) x
ON (t.COMPANY = x.COMPANY AND t.PLANT_CD = x.PLANT_CD AND t.INSPECTION_MODE = x.INSPECTION_MODE AND t.CODE_LETTER = x.CODE_LETTER AND t.AQL_VALUE = x.AQL_VALUE)
WHEN MATCHED THEN UPDATE SET t.SAMPLE_CODE_LETTER = x.SAMPLE_CODE_LETTER, t.ACCEPT_QTY = x.ACCEPT_QTY, t.REJECT_QTY = x.REJECT_QTY, t.SORT_ORDER = x.SORT_ORDER, t.UPDATED_BY = 'codex', t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, INSPECTION_MODE, CODE_LETTER, AQL_VALUE, SAMPLE_CODE_LETTER, ACCEPT_QTY, REJECT_QTY, SORT_ORDER, CREATED_BY)
VALUES (x.COMPANY, x.PLANT_CD, x.INSPECTION_MODE, x.CODE_LETTER, x.AQL_VALUE, x.SAMPLE_CODE_LETTER, x.ACCEPT_QTY, x.REJECT_QTY, x.SORT_ORDER, 'codex');
/

UPDATE AQL_ACCEPTANCE_RULES
   SET SAMPLE_CODE_LETTER = 'J',
       ACCEPT_QTY = 0,
       REJECT_QTY = 1,
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND INSPECTION_MODE = 'NORMAL'
   AND AQL_VALUE = 0.015
   AND CODE_LETTER IN ('A', 'B', 'C', 'D');
/

UPDATE AQL_ACCEPTANCE_RULES
   SET SAMPLE_CODE_LETTER = CASE
         WHEN CODE_LETTER IN ('A','B','C','D','E','F','G','H','J','K') THEN 'K'
         ELSE CODE_LETTER
       END,
       ACCEPT_QTY = 0,
       REJECT_QTY = 1,
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND INSPECTION_MODE = 'NORMAL'
   AND AQL_VALUE = 0.01;
/

COMMIT;
/
