-- 구조검사 메뉴 등록 (INSP_STRUCTURE)
-- 검사관리(INSPECTION) 카테고리 첫 번째(5)에 배치.
-- 경로/라벨은 프론트 menuConfig(INSP_STRUCTURE -> /inspection/structure, menu.inspection.structure).

INSERT ALL
  WHEN menu_missing = 1 THEN
    INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
    VALUES ('INSP_STRUCTURE', 'INSPECTION', 5, '40', '1000', 'system', 'system')
  WHEN manager_missing = 1 THEN
    INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
    VALUES ('MANAGER', 'INSP_STRUCTURE', 'Y', '40', '1000')
  WHEN operator_missing = 1 THEN
    INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
    VALUES ('OPERATOR', 'INSP_STRUCTURE', 'Y', '40', '1000')
SELECT
  CASE WHEN NOT EXISTS (
    SELECT 1 FROM MENU_CATEGORY_ITEMS
    WHERE MENU_CODE = 'INSP_STRUCTURE'
      AND COMPANY = '40'
      AND PLANT_CD = '1000'
  ) THEN 1 ELSE 0 END AS menu_missing,
  CASE WHEN NOT EXISTS (
    SELECT 1 FROM ROLE_MENU_PERMISSIONS
    WHERE ROLE_CODE = 'MANAGER'
      AND MENU_CODE = 'INSP_STRUCTURE'
      AND COMPANY = '40'
      AND PLANT_CD = '1000'
  ) THEN 1 ELSE 0 END AS manager_missing,
  CASE WHEN NOT EXISTS (
    SELECT 1 FROM ROLE_MENU_PERMISSIONS
    WHERE ROLE_CODE = 'OPERATOR'
      AND MENU_CODE = 'INSP_STRUCTURE'
      AND COMPANY = '40'
      AND PLANT_CD = '1000'
  ) THEN 1 ELSE 0 END AS operator_missing
FROM DUAL;
