DECLARE
  -- 작업지도서 테이블을 신규 운영 환경에도 멱등 배포한다.
  -- 기존 JSIDC 테이블은 COMPANY/PLANT_CD 계약을 유지하면서 ORGANIZATION_ID를 보정한다.
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'WORK_INSTRUCTIONS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE WORK_INSTRUCTIONS (
        ITEM_CODE       VARCHAR2(50) NOT NULL,
        PROCESS_CODE    VARCHAR2(50) NOT NULL,
        TITLE           VARCHAR2(255) NOT NULL,
        CONTENT         CLOB,
        IMAGE_URL       VARCHAR2(500),
        REVISION        VARCHAR2(20) DEFAULT 'A' NOT NULL,
        USE_YN          VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        CREATED_AT      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
        COMPANY         VARCHAR2(50) DEFAULT '40' NOT NULL,
        PLANT_CD        VARCHAR2(50) DEFAULT '1000' NOT NULL,
        CREATED_BY      VARCHAR2(50),
        UPDATED_BY      VARCHAR2(50),
        ORGANIZATION_ID NUMBER DEFAULT 1 NOT NULL,
        CONSTRAINT PK_WORK_INSTRUCTIONS PRIMARY KEY (ITEM_CODE, PROCESS_CODE, REVISION)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'WORK_INSTRUCTIONS' AND COLUMN_NAME = 'ORGANIZATION_ID';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE WORK_INSTRUCTIONS ADD (ORGANIZATION_ID NUMBER DEFAULT 1 NOT NULL)';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'WORK_INSTRUCTIONS' AND COLUMN_NAME = 'COMPANY' AND DATA_DEFAULT IS NOT NULL;
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE WORK_INSTRUCTIONS MODIFY (COMPANY DEFAULT ''40'')';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'WORK_INSTRUCTIONS' AND COLUMN_NAME = 'PLANT_CD' AND DATA_DEFAULT IS NOT NULL;
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE WORK_INSTRUCTIONS MODIFY (PLANT_CD DEFAULT ''1000'')';
  END IF;
END;
