BEGIN
  EXECUTE IMMEDIATE q'[
    COMMENT ON COLUMN ITEM_MASTERS.ITEM_TYPE IS
      '품목유형 [공통코드:ITEM_TYPE] (RAW_MATERIAL/SEMI_PRODUCT/FINISHED/CONSUMABLE)'
  ]';

  UPDATE COM_CODES
     SET USE_YN = 'N',
         UPDATED_AT = SYSTIMESTAMP
   WHERE GROUP_CODE = 'PART_TYPE'
     AND USE_YN = 'Y';

  COMMIT;
END;
