DECLARE
  -- 생산월력 일자편집 '라인 추가 운영' 자식 테이블 (멱등)
  -- LINE_CODE     = 월력 소유자. '*'는 전사(형제 테이블 IP_PRODUCT_CALENDAR_SHIFT/_BREAK와 동일)
  -- RUN_LINE_CODE = 추가 운영 대상 라인(IP_PRODUCT_LINE). 소유자와 의미가 달라 컬럼을 분리한다
  -- RUN_SEQ       = 행 순번. 같은 라인을 오전/야간처럼 여러 구간으로 등록할 수 있게 한다
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'IP_PRODUCT_CALENDAR_LINE_RUN';
  IF n = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE IP_PRODUCT_CALENDAR_LINE_RUN (
        PLAN_DATE         DATE          NOT NULL,
        ORGANIZATION_ID   NUMBER        NOT NULL,
        LINE_CODE         VARCHAR2(20)  DEFAULT ''*'' NOT NULL,
        RUN_SEQ           NUMBER        NOT NULL,
        RUN_LINE_CODE     VARCHAR2(20)  NOT NULL,
        START_TIME        VARCHAR2(8)   NOT NULL,
        END_TIME          VARCHAR2(8)   NOT NULL,
        ENTER_BY          VARCHAR2(20)  NOT NULL,
        ENTER_DATE        DATE          NOT NULL,
        LAST_MODIFY_BY    VARCHAR2(20),
        LAST_MODIFY_DATE  DATE,
        CONSTRAINT XPKIP_PRODUCT_CALENDAR_LINE_RUN
          PRIMARY KEY (PLAN_DATE, ORGANIZATION_ID, LINE_CODE, RUN_SEQ)
      )';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE IP_PRODUCT_CALENDAR_LINE_RUN IS ''생산월력 일자별 라인 추가 운영. LINE_CODE=''''*''''는 전사 월력''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.LINE_CODE IS ''월력 소유자. ''''*''''=전사''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.RUN_SEQ IS ''행 순번. 같은 라인 복수 구간 등록용''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.RUN_LINE_CODE IS ''추가 운영 라인(IP_PRODUCT_LINE)''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.START_TIME IS ''가동 시작 HH:MM''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN IP_PRODUCT_CALENDAR_LINE_RUN.END_TIME IS ''가동 종료 HH:MM. 시작보다 이르면 자정 넘김''';
  END IF;
END;
