DECLARE
  v_user_email_cols NUMBER := 0;
  v_email_cols NUMBER := 0;
  v_exists NUMBER := 0;
  v_orphans NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_user_email_cols
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ACTIVITY_LOGS'
     AND COLUMN_NAME = 'USER_EMAIL';

  SELECT COUNT(*)
    INTO v_email_cols
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ACTIVITY_LOGS'
     AND COLUMN_NAME = 'EMAIL';

  IF v_user_email_cols = 1 AND v_email_cols = 1 THEN
    RAISE_APPLICATION_ERROR(-20001, 'ACTIVITY_LOGS has both USER_EMAIL and EMAIL columns');
  END IF;

  SELECT COUNT(*)
    INTO v_exists
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'FK_ACTIVITY_LOGS_USER_EMAIL'
     AND TABLE_NAME = 'ACTIVITY_LOGS';

  IF v_exists = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ACTIVITY_LOGS DROP CONSTRAINT FK_ACTIVITY_LOGS_USER_EMAIL';
  END IF;

  IF v_user_email_cols = 1 AND v_email_cols = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ACTIVITY_LOGS RENAME COLUMN USER_EMAIL TO EMAIL';
  END IF;

  EXECUTE IMMEDIATE '
    SELECT COUNT(*)
      FROM ACTIVITY_LOGS al
      LEFT JOIN USERS u ON u.EMAIL = al.EMAIL
     WHERE al.EMAIL IS NOT NULL
       AND u.EMAIL IS NULL'
    INTO v_orphans;

  IF v_orphans > 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'ACTIVITY_LOGS.EMAIL orphan rows exist: ' || v_orphans);
  END IF;

  SELECT COUNT(*)
    INTO v_exists
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'FK_ACTIVITY_LOGS_EMAIL'
     AND TABLE_NAME = 'ACTIVITY_LOGS';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      ALTER TABLE ACTIVITY_LOGS
      ADD CONSTRAINT FK_ACTIVITY_LOGS_EMAIL
      FOREIGN KEY (EMAIL)
      REFERENCES USERS (EMAIL)
      ENABLE VALIDATE';
  END IF;
END;
/
