DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'COM_CODES'
    AND COLUMN_NAME = 'DEFECT_GRADE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE COM_CODES ADD (DEFECT_GRADE VARCHAR2(20))';
  END IF;

  EXECUTE IMMEDIATE q'[
    UPDATE COM_CODES
       SET DEFECT_GRADE =
         CASE DETAIL_CODE
           WHEN 'CRACK' THEN 'CRITICAL'
           WHEN 'APP' THEN 'MINOR'
           WHEN 'MARK' THEN 'MINOR'
           WHEN 'BURR' THEN 'MINOR'
           WHEN 'ETC' THEN 'MINOR'
           ELSE 'MAJOR'
         END
     WHERE GROUP_CODE = 'DEFECT_TYPE'
       AND DEFECT_GRADE IS NULL
  ]';

  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE TABLE_NAME = 'COM_CODES'
    AND CONSTRAINT_NAME = 'CK_COM_CODES_DEFECT_GRADE_VAL';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE COM_CODES ADD CONSTRAINT CK_COM_CODES_DEFECT_GRADE_VAL
      CHECK (DEFECT_GRADE IS NULL OR DEFECT_GRADE IN ('CRITICAL', 'MAJOR', 'MINOR'))
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE TABLE_NAME = 'COM_CODES'
    AND CONSTRAINT_NAME = 'CK_COM_CODES_DEFECT_GRADE_REQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE COM_CODES ADD CONSTRAINT CK_COM_CODES_DEFECT_GRADE_REQ
      CHECK (GROUP_CODE <> 'DEFECT_TYPE' OR DEFECT_GRADE IS NOT NULL)
    ]';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN COM_CODES.DEFECT_GRADE IS '불량코드 등급. DEFECT_TYPE 그룹은 CRITICAL/MAJOR/MINOR 필수']';

  COMMIT;
END;
/
