-- 팔레트출하 메뉴(SHIP_PALLET_SHIP) 등록
-- /shipping/pallet-ship 경로, menu.shipping.palletShip 라벨

INSERT ALL
  WHEN menu_missing = 1 THEN
    INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
    VALUES ('SHIP_PALLET_SHIP', 'SHIPPING', 80, '40', '1000', 'system', 'system')
  WHEN manager_missing = 1 THEN
    INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
    VALUES ('MANAGER', 'SHIP_PALLET_SHIP', 'Y', '40', '1000')
  WHEN operator_missing = 1 THEN
    INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
    VALUES ('OPERATOR', 'SHIP_PALLET_SHIP', 'Y', '40', '1000')
  WHEN viewer_missing = 1 THEN
    INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
    VALUES ('VIEWER', 'SHIP_PALLET_SHIP', 'Y', '40', '1000')
SELECT
  CASE WHEN NOT EXISTS (
    SELECT 1 FROM MENU_CATEGORY_ITEMS
    WHERE MENU_CODE = 'SHIP_PALLET_SHIP'
      AND COMPANY = '40'
      AND PLANT_CD = '1000'
  ) THEN 1 ELSE 0 END AS menu_missing,
  CASE WHEN NOT EXISTS (
    SELECT 1 FROM ROLE_MENU_PERMISSIONS
    WHERE ROLE_CODE = 'MANAGER'
      AND MENU_CODE = 'SHIP_PALLET_SHIP'
      AND COMPANY = '40'
      AND PLANT_CD = '1000'
  ) THEN 1 ELSE 0 END AS manager_missing,
  CASE WHEN NOT EXISTS (
    SELECT 1 FROM ROLE_MENU_PERMISSIONS
    WHERE ROLE_CODE = 'OPERATOR'
      AND MENU_CODE = 'SHIP_PALLET_SHIP'
      AND COMPANY = '40'
      AND PLANT_CD = '1000'
  ) THEN 1 ELSE 0 END AS operator_missing,
  CASE WHEN NOT EXISTS (
    SELECT 1 FROM ROLE_MENU_PERMISSIONS
    WHERE ROLE_CODE = 'VIEWER'
      AND MENU_CODE = 'SHIP_PALLET_SHIP'
      AND COMPANY = '40'
      AND PLANT_CD = '1000'
  ) THEN 1 ELSE 0 END AS viewer_missing
FROM DUAL
