DECLARE
  v_cnt NUMBER;
BEGIN
  -- 리뉴얼 Phase 4: PRODUCT_STOCKS를 품목+창고 수량으로 일원화(PRD_UID를 PK에서 제거).
  -- 시리얼 추적은 FG_LABELS/SG_LABELS가 담당. 적용 시 테이블이 비어있어야 안전(테스트데이터 정리 승인됨).

  -- 기존 PK 제거
  SELECT COUNT(*) INTO v_cnt FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='PRODUCT_STOCKS' AND CONSTRAINT_NAME='PK_PRODUCT_STOCKS' AND CONSTRAINT_TYPE='P';
  IF v_cnt = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS DROP CONSTRAINT PK_PRODUCT_STOCKS';
  END IF;

  -- PRD_UID NULL 허용 (과도기 — 컬럼 물리 drop은 안정 후 별도 마이그레이션)
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS MODIFY (PRD_UID NULL)';
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  -- 신규 PK: (COMPANY, PLANT_CD, WAREHOUSE_CODE, ITEM_CODE)
  SELECT COUNT(*) INTO v_cnt FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='PRODUCT_STOCKS' AND CONSTRAINT_NAME='PK_PRODUCT_STOCKS' AND CONSTRAINT_TYPE='P';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS ADD CONSTRAINT PK_PRODUCT_STOCKS PRIMARY KEY (COMPANY, PLANT_CD, WAREHOUSE_CODE, ITEM_CODE)';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PRODUCT_STOCKS.PRD_UID IS '(폐기 예정) 시리얼 추적은 FG_LABELS/SG_LABELS, 재고는 품목+창고 수량. NULL 허용 과도기']';
  COMMIT;
END;
/
