DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EQUIP_INSPECT_ITEM_MASTERS'
     AND COLUMN_NAME = 'IMAGE_URL';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_ITEM_MASTERS ADD (IMAGE_URL VARCHAR2(500))';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN EQUIP_INSPECT_ITEM_MASTERS.IMAGE_URL IS '점검항목 사진 파일 URL (/uploads/equip-inspect-items/...)']';
END;
/
