-- 품목마스터 마킹 문구 컬럼 추가
-- 적용 대상: JSHANES

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'ITEM_MASTERS'
     AND COLUMN_NAME = 'MARKING_TEXT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS ADD (MARKING_TEXT VARCHAR2(100))';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.MARKING_TEXT IS '마킹 문구']';
  END IF;
END;
/
