-- 소모품 관리 방향 전환: 제품 BOM에서 소모품 제거 + 소모품-설비-모델 매핑 테이블 신설
-- 배경: 소모품을 제품 BOM/자재로 통합하던 방식을 폐기하고,
--       기존 소모품 관리 기능(CONSUMABLE_MASTERS/STOCKS, mount, 사용횟수)을 활용한다.
--       키오스크는 신설 매핑(모델+설비→소모품)으로 필요 소모품을 조회하고,
--       conUid 바코드 스캔으로 실제 롯트를 장착, 생산실적 시 사용횟수를 차감한다.
-- 사이트: JSHANES, COMPANY=40 / PLANT_CD=1000

-- 1) BOM 소모품 백업 (복원용) — 기존 존재 시 무시
CREATE TABLE BOM_MASTERS_CONSUMABLE_BAK AS
SELECT * FROM BOM_MASTERS
WHERE COMPANY = '40'
  AND CHILD_ITEM_CODE IN (
    'APPCT-A','APPCT-B','APPCT-SE',
    'CUTBL001','CUTBL002','CUTBL003','CUTBL004','CUTBL009',
    'JIGHD-A','JIGHD-B','JIGHD-C','JIGHD-D'
  )
/

-- 2) 제품 BOM에서 소모품 자식 제거
DELETE FROM BOM_MASTERS
WHERE COMPANY = '40'
  AND CHILD_ITEM_CODE IN (
    'APPCT-A','APPCT-B','APPCT-SE',
    'CUTBL001','CUTBL002','CUTBL003','CUTBL004','CUTBL009',
    'JIGHD-A','JIGHD-B','JIGHD-C','JIGHD-D'
  )
/

-- 3) 통합 잔재 제거: 소모품을 자재로 입하했던 재고/롯트
DELETE FROM MAT_STOCKS WHERE MAT_UID LIKE 'MC260616%'
/
DELETE FROM MAT_LOTS WHERE MAT_UID LIKE 'MC260616%'
/

-- 4) 소모품-설비-모델 매핑 테이블 신설
--    PK: 모델(제품 ITEM_CODE) + 설비(EQUIP_CODE) + 소모품(CONSUMABLE_CODE)
--    USAGE_PER_UNIT: 단위 생산당 소모 타수(사용횟수)
CREATE TABLE CONSUMABLE_USAGE_MAP (
  COMPANY           VARCHAR2(50) NOT NULL,
  PLANT_CD          VARCHAR2(50) NOT NULL,
  PRODUCT_ITEM_CODE VARCHAR2(50) NOT NULL,
  EQUIP_CODE        VARCHAR2(50) NOT NULL,
  CONSUMABLE_CODE   VARCHAR2(50) NOT NULL,
  USAGE_PER_UNIT    NUMBER DEFAULT 1 NOT NULL,
  USE_YN            VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  REMARK            VARCHAR2(500),
  CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CONSUMABLE_USAGE_MAP PRIMARY KEY (COMPANY, PLANT_CD, PRODUCT_ITEM_CODE, EQUIP_CODE, CONSUMABLE_CODE)
)
/
