-- 생산월력 일자편집 재구성 — 공통코드 보강 + 교대조/비작업 자식 테이블 (멱등)
-- 1) WORK DAY TYPE / DAY OFF TYPE / BREAK TYPE 코드 시드
-- 2) IP_PRODUCT_CALENDAR_SHIFT : 일자 x 교대조 시작~종료
-- 3) IP_PRODUCT_CALENDAR_BREAK : 일자 x 비작업분류 분
-- LINE_CODE '*' = 전사(부모 IP_PRODUCT_COMPANY_CALENDAR), 그 외 = 라인 예외.
MERGE INTO ISYS_BASECODE t
USING (
  SELECT 'WORK DAY TYPE' AS CODE_TYPE, 'WORK'    AS CODE_NAME, '정상'         AS CODE_MEAN_KOR, 'NORMAL'          AS CODE_MEAN_ENG, 1 AS ORGANIZATION_ID FROM DUAL UNION ALL
  SELECT 'WORK DAY TYPE', 'OFF',     '휴무',         'DAY OFF',        1 FROM DUAL UNION ALL
  SELECT 'WORK DAY TYPE', 'HALF',    '임시조정',     'TEMP ADJUST',    1 FROM DUAL UNION ALL
  SELECT 'WORK DAY TYPE', 'SPECIAL', '공휴일(특근)', 'HOLIDAY WORK',   1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'WEEKEND', '주말',         'WEEKEND',        1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'HOLIDAY', '공휴일',       'PUBLIC HOLIDAY', 1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'ANNIV',   '사내기념일',   'ANNIVERSARY',    1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'EVENT',   '행사',         'EVENT',          1 FROM DUAL UNION ALL
  SELECT 'DAY OFF TYPE',  'EDU',     '교육',         'EDUCATION',      1 FROM DUAL UNION ALL
  SELECT 'BREAK TYPE',    'REST',    '휴게시간',     'REST',           1 FROM DUAL UNION ALL
  SELECT 'BREAK TYPE',    'MEAL',    '식사시간',     'MEAL',           1 FROM DUAL
) s
ON (t.CODE_TYPE = s.CODE_TYPE AND t.CODE_NAME = s.CODE_NAME AND t.ORGANIZATION_ID = s.ORGANIZATION_ID)
WHEN MATCHED THEN
  UPDATE SET t.CODE_MEAN_KOR = s.CODE_MEAN_KOR, t.CODE_MEAN_ENG = s.CODE_MEAN_ENG
WHEN NOT MATCHED THEN
  INSERT (CODE_TYPE, CODE_NAME, ORGANIZATION_ID, CODE_MEAN_KOR, CODE_MEAN_ENG, CODE_GROUP, ENTER_BY, ENTER_DATE)
  VALUES (s.CODE_TYPE, s.CODE_NAME, s.ORGANIZATION_ID, s.CODE_MEAN_KOR, s.CODE_MEAN_ENG, 'SYSTEM', 'SYSTEM', SYSDATE)
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'IP_PRODUCT_CALENDAR_SHIFT';
  IF n = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE IP_PRODUCT_CALENDAR_SHIFT (
        PLAN_DATE         DATE          NOT NULL,
        ORGANIZATION_ID   NUMBER        NOT NULL,
        LINE_CODE         VARCHAR2(20)  DEFAULT ''*'' NOT NULL,
        SHIFT_CODE        VARCHAR2(10)  NOT NULL,
        START_TIME        VARCHAR2(8)   NOT NULL,
        END_TIME          VARCHAR2(8)   NOT NULL,
        ENTER_BY          VARCHAR2(20)  NOT NULL,
        ENTER_DATE        DATE          NOT NULL,
        LAST_MODIFY_BY    VARCHAR2(20),
        LAST_MODIFY_DATE  DATE,
        CONSTRAINT XPKIP_PRODUCT_CALENDAR_SHIFT
          PRIMARY KEY (PLAN_DATE, ORGANIZATION_ID, LINE_CODE, SHIFT_CODE)
      )';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE IP_PRODUCT_CALENDAR_SHIFT IS ''생산월력 일자별 교대조 작업시간. LINE_CODE=''''*''''는 전사''';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'IP_PRODUCT_CALENDAR_BREAK';
  IF n = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE IP_PRODUCT_CALENDAR_BREAK (
        PLAN_DATE         DATE          NOT NULL,
        ORGANIZATION_ID   NUMBER        NOT NULL,
        LINE_CODE         VARCHAR2(20)  DEFAULT ''*'' NOT NULL,
        BREAK_TYPE        VARCHAR2(20)  NOT NULL,
        BREAK_MINUTES     NUMBER        DEFAULT 0 NOT NULL,
        ENTER_BY          VARCHAR2(20)  NOT NULL,
        ENTER_DATE        DATE          NOT NULL,
        LAST_MODIFY_BY    VARCHAR2(20),
        LAST_MODIFY_DATE  DATE,
        CONSTRAINT XPKIP_PRODUCT_CALENDAR_BREAK
          PRIMARY KEY (PLAN_DATE, ORGANIZATION_ID, LINE_CODE, BREAK_TYPE)
      )';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE IP_PRODUCT_CALENDAR_BREAK IS ''생산월력 일자별 비작업(휴게/식사) 시간. LINE_CODE=''''*''''는 전사''';
  END IF;
END;
/
