DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'PRODUCT_STOCKS'
     AND COLUMN_NAME = 'QUALITY_STATUS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS ADD (QUALITY_STATUS VARCHAR2(20) DEFAULT ''GOOD'' NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'PRODUCT_TRANSACTIONS'
     AND COLUMN_NAME = 'QUALITY_STATUS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_TRANSACTIONS ADD (QUALITY_STATUS VARCHAR2(20) DEFAULT ''GOOD'' NOT NULL)';
  END IF;
END;
/

UPDATE PRODUCT_STOCKS
   SET QUALITY_STATUS = 'GOOD'
 WHERE QUALITY_STATUS IS NULL;
/

UPDATE PRODUCT_TRANSACTIONS
   SET QUALITY_STATUS = 'GOOD'
 WHERE QUALITY_STATUS IS NULL;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'PRODUCT_STOCKS'
     AND CONSTRAINT_NAME = 'CK_PRODUCT_STOCKS_QUALITY_STATUS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS ADD CONSTRAINT CK_PRODUCT_STOCKS_QUALITY_STATUS CHECK (QUALITY_STATUS IN (''GOOD'', ''DEFECT''))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'PRODUCT_TRANSACTIONS'
     AND CONSTRAINT_NAME = 'CK_PRODUCT_TX_QUALITY_STATUS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_TRANSACTIONS ADD CONSTRAINT CK_PRODUCT_TX_QUALITY_STATUS CHECK (QUALITY_STATUS IN (''GOOD'', ''DEFECT''))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_pk_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONS_COLUMNS
   WHERE TABLE_NAME = 'PRODUCT_STOCKS'
     AND CONSTRAINT_NAME = 'PK_PRODUCT_STOCKS'
     AND COLUMN_NAME = 'QUALITY_STATUS';

  IF v_count = 0 THEN
    SELECT COUNT(*)
      INTO v_pk_count
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'PRODUCT_STOCKS'
       AND CONSTRAINT_NAME = 'PK_PRODUCT_STOCKS';

    IF v_pk_count > 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS DROP CONSTRAINT PK_PRODUCT_STOCKS';
    END IF;

    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS ADD CONSTRAINT PK_PRODUCT_STOCKS PRIMARY KEY (COMPANY, PLANT_CD, WAREHOUSE_CODE, ITEM_CODE, QUALITY_STATUS)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_PROD_STK_QUALITY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PROD_STK_QUALITY ON PRODUCT_STOCKS (QUALITY_STATUS)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_PROD_TX_QUALITY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PROD_TX_QUALITY ON PRODUCT_TRANSACTIONS (QUALITY_STATUS)';
  END IF;
END;
/
