-- AQL 표준 추가: 검사수준 I · AQL 0.01 (ISO 2859-1 보통검사 1회 샘플링, 화살표 적용)
-- resolve-iqc-items 404 해결: 검사항목이 I/0.01을 참조하나 표준 부재였음.
-- AQL 0.010 유효 플랜: sample 125 Ac0/Re1. LOT보다 샘플수가 크거나 같으면 전수검사로 해석한다.

MERGE INTO AQL_STANDARDS s
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'AQL-I-0.01' AQL_CODE FROM DUAL) x
ON (s.COMPANY=x.COMPANY AND s.PLANT_CD=x.PLANT_CD AND s.AQL_CODE=x.AQL_CODE)
WHEN MATCHED THEN UPDATE SET s.INSPECTION_LEVEL='I', s.AQL_VALUE=0.01, s.USE_YN='Y', s.UPDATED_BY='claude', s.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,AQL_NAME,INSPECTION_LEVEL,AQL_VALUE,USE_YN,REMARK,CREATED_BY)
VALUES ('40','1000','AQL-I-0.01','검사수준 I · AQL 0.01','I',0.01,'Y','ISO 2859-1 보통검사 1회 샘플링','claude');
/

-- 샘플링 규칙 15구간 (전 구간 Ac0/Re1, sample은 화살표 적용)
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 2 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',2,8,125,0,1,1,'A','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 9 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',9,15,125,0,1,2,'A','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 16 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',16,25,125,0,1,3,'B','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 26 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',26,50,125,0,1,4,'C','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 51 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',51,90,125,0,1,5,'C','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 91 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',91,150,125,0,1,6,'D','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 151 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',151,280,125,0,1,7,'E','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 281 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',281,500,125,0,1,8,'F','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 501 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',501,1200,125,0,1,9,'G','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 1201 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',1201,3200,125,0,1,10,'H','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 3201 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',3201,10000,125,0,1,11,'J','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 10001 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',10001,35000,125,0,1,12,'K','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 35001 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',35001,150000,200,0,1,13,'L','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 150001 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',150001,500000,315,0,1,14,'M','claude');
/
MERGE INTO AQL_SAMPLING_RULES r USING (SELECT '40' C,'1000' P,'AQL-I-0.01' A, 500001 F FROM DUAL) x ON (r.COMPANY=x.C AND r.PLANT_CD=x.P AND r.AQL_CODE=x.A AND r.LOT_QTY_FROM=x.F)
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,AQL_CODE,LOT_QTY_FROM,LOT_QTY_TO,SAMPLE_SIZE,ACCEPT_QTY,REJECT_QTY,SORT_ORDER,CODE_LETTER,CREATED_BY) VALUES ('40','1000','AQL-I-0.01',500001,999999999,500,0,1,15,'N','claude');
/
COMMIT;
/
