DECLARE
  v_count NUMBER;
BEGIN
  -- T-KIOSK-EQUIP-INSPECT-WORKDAY-ORDER
  -- 설비일일점검은 조업일(WORK_DATE), 작업자설비점검은 작업지시(ORDER_NO) 기준으로 이력을 유지한다.
  -- oracle_connector.py --execute-file은 '/' 라인으로 블록을 분리하고,
  -- PL/SQL 블록은 파일 블록이 DECLARE/BEGIN으로 시작해야 END 세미콜론을 보존한다.

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EQUIP_INSPECT_LOGS'
     AND COLUMN_NAME = 'ORDER_NO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_LOGS ADD (ORDER_NO VARCHAR2(50))';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EQUIP_INSPECT_LOGS'
     AND COLUMN_NAME = 'WORK_DATE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_LOGS ADD (WORK_DATE DATE)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EQUIP_INSPECT_LOGS'
     AND COLUMN_NAME = 'INSPECT_AT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_LOGS ADD (INSPECT_AT TIMESTAMP DEFAULT SYSTIMESTAMP)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EQUIP_INSPECT_LOGS'
     AND COLUMN_NAME = 'OP_WINDOW_START_AT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_LOGS ADD (OP_WINDOW_START_AT TIMESTAMP)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EQUIP_INSPECT_LOGS'
     AND COLUMN_NAME = 'OP_WINDOW_END_AT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_LOGS ADD (OP_WINDOW_END_AT TIMESTAMP)';
  END IF;

  EXECUTE IMMEDIATE q'[
    UPDATE EQUIP_INSPECT_LOGS
       SET WORK_DATE = TRUNC(INSPECT_DATE),
           INSPECT_AT = COALESCE(INSPECT_AT, CAST(INSPECT_DATE AS TIMESTAMP))
     WHERE WORK_DATE IS NULL
        OR INSPECT_AT IS NULL
  ]';

  SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_EQUIP_INSPECT_WORK_DATE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_EQUIP_INSPECT_WORK_DATE ON EQUIP_INSPECT_LOGS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, WORK_DATE)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_EQUIP_INSPECT_ORDER_NO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_EQUIP_INSPECT_ORDER_NO ON EQUIP_INSPECT_LOGS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, ORDER_NO)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'UX_EQUIP_INSPECT_DAILY_WORK';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE UNIQUE INDEX UX_EQUIP_INSPECT_DAILY_WORK
      ON EQUIP_INSPECT_LOGS (
        CASE WHEN INSPECT_TYPE = 'DAILY' THEN COMPANY END,
        CASE WHEN INSPECT_TYPE = 'DAILY' THEN PLANT_CD END,
        CASE WHEN INSPECT_TYPE = 'DAILY' THEN EQUIP_CODE END,
        CASE WHEN INSPECT_TYPE = 'DAILY' THEN WORK_DATE END
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'UX_EQUIP_INSPECT_WORKER_ORDER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE UNIQUE INDEX UX_EQUIP_INSPECT_WORKER_ORDER
      ON EQUIP_INSPECT_LOGS (
        CASE WHEN INSPECT_TYPE = 'WORKER' THEN COMPANY END,
        CASE WHEN INSPECT_TYPE = 'WORKER' THEN PLANT_CD END,
        CASE WHEN INSPECT_TYPE = 'WORKER' THEN EQUIP_CODE END,
        CASE WHEN INSPECT_TYPE = 'WORKER' THEN ORDER_NO END
      )
    ]';
  END IF;

  COMMIT;
END;
/
