DECLARE
  FUNCTION column_exists(p_table_name VARCHAR2, p_column_name VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = UPPER(p_table_name)
       AND COLUMN_NAME = UPPER(p_column_name);
    RETURN v_count > 0;
  END;
BEGIN
  IF column_exists('PURCHASE_ORDERS', 'PARTNER_ID') AND NOT column_exists('PURCHASE_ORDERS', 'PARTNER_CODE') THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PURCHASE_ORDERS RENAME COLUMN PARTNER_ID TO PARTNER_CODE';
  ELSIF column_exists('PURCHASE_ORDERS', 'PARTNER_ID') AND column_exists('PURCHASE_ORDERS', 'PARTNER_CODE') THEN
    RAISE_APPLICATION_ERROR(-20001, 'PURCHASE_ORDERS has both PARTNER_ID and PARTNER_CODE columns.');
  END IF;

  IF column_exists('PURCHASE_ORDERS', 'PARTNER_CODE') THEN
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PURCHASE_ORDERS.PARTNER_CODE IS '거래처코드 (PARTNER_MASTERS.PARTNER_CODE)']';
  END IF;
END;
/
