DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'IP_PRODUCT_WORKSTAGE_LINE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE IP_PRODUCT_WORKSTAGE_LINE (
        ORGANIZATION_ID NUMBER NOT NULL,
        WORKSTAGE_CODE VARCHAR2(10) NOT NULL,
        WORKSTAGE_TYPE VARCHAR2(1) NOT NULL,
        LINE_CODE VARCHAR2(20) NOT NULL,
        ENTER_BY VARCHAR2(20),
        ENTER_DATE DATE DEFAULT SYSDATE NOT NULL,
        LAST_MODIFY_BY VARCHAR2(20),
        LAST_MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_IP_PRODUCT_WORKSTAGE_LINE
          PRIMARY KEY (ORGANIZATION_ID, WORKSTAGE_CODE, WORKSTAGE_TYPE, LINE_CODE),
        CONSTRAINT FK_IP_PWL_WORKSTAGE
          FOREIGN KEY (WORKSTAGE_CODE, ORGANIZATION_ID)
          REFERENCES IP_PRODUCT_WORKSTAGE (WORKSTAGE_CODE, ORGANIZATION_ID),
        CONSTRAINT FK_IP_PWL_LINE
          FOREIGN KEY (LINE_CODE, ORGANIZATION_ID)
          REFERENCES IP_PRODUCT_LINE (LINE_CODE, ORGANIZATION_ID)
      )~';
  END IF;
END;
/
MERGE INTO IP_PRODUCT_LINE target
USING (SELECT '21' LINE_CODE, 1 ORGANIZATION_ID, '성능검사기' LINE_NAME,
              'W' LINE_DIVISION, 'FIXED' LINE_PRODUCT_DIVISION,
              'N' LINE_STATUS, 'N' ACTIVE_YN FROM DUAL) source
ON (target.LINE_CODE = source.LINE_CODE AND target.ORGANIZATION_ID = source.ORGANIZATION_ID)
WHEN NOT MATCHED THEN INSERT (
  LINE_CODE, ORGANIZATION_ID, LINE_NAME, LINE_DIVISION,
  LINE_PRODUCT_DIVISION, LINE_STATUS, ACTIVE_YN, ENTER_BY, ENTER_DATE
) VALUES (
  source.LINE_CODE, source.ORGANIZATION_ID, source.LINE_NAME, source.LINE_DIVISION,
  source.LINE_PRODUCT_DIVISION, source.LINE_STATUS, source.ACTIVE_YN, 'CODEX', SYSDATE
);
/
MERGE INTO IP_PRODUCT_LINE target
USING (SELECT '22' LINE_CODE, 1 ORGANIZATION_ID, 'COATING MACHINE' LINE_NAME,
              'W' LINE_DIVISION, 'FIXED' LINE_PRODUCT_DIVISION,
              'N' LINE_STATUS, 'N' ACTIVE_YN FROM DUAL) source
ON (target.LINE_CODE = source.LINE_CODE AND target.ORGANIZATION_ID = source.ORGANIZATION_ID)
WHEN NOT MATCHED THEN INSERT (
  LINE_CODE, ORGANIZATION_ID, LINE_NAME, LINE_DIVISION,
  LINE_PRODUCT_DIVISION, LINE_STATUS, ACTIVE_YN, ENTER_BY, ENTER_DATE
) VALUES (
  source.LINE_CODE, source.ORGANIZATION_ID, source.LINE_NAME, source.LINE_DIVISION,
  source.LINE_PRODUCT_DIVISION, source.LINE_STATUS, source.ACTIVE_YN, 'CODEX', SYSDATE
);
/
MERGE INTO IP_PRODUCT_LINE target
USING (SELECT '23' LINE_CODE, 1 ORGANIZATION_ID, 'JETTING MACHINE' LINE_NAME,
              'W' LINE_DIVISION, 'FIXED' LINE_PRODUCT_DIVISION,
              'N' LINE_STATUS, 'N' ACTIVE_YN FROM DUAL) source
ON (target.LINE_CODE = source.LINE_CODE AND target.ORGANIZATION_ID = source.ORGANIZATION_ID)
WHEN NOT MATCHED THEN INSERT (
  LINE_CODE, ORGANIZATION_ID, LINE_NAME, LINE_DIVISION,
  LINE_PRODUCT_DIVISION, LINE_STATUS, ACTIVE_YN, ENTER_BY, ENTER_DATE
) VALUES (
  source.LINE_CODE, source.ORGANIZATION_ID, source.LINE_NAME, source.LINE_DIVISION,
  source.LINE_PRODUCT_DIVISION, source.LINE_STATUS, source.ACTIVE_YN, 'CODEX', SYSDATE
);
/
MERGE INTO IP_PRODUCT_LINE target
USING (SELECT '24' LINE_CODE, 1 ORGANIZATION_ID, 'ROUTER' LINE_NAME,
              'W' LINE_DIVISION, 'FIXED' LINE_PRODUCT_DIVISION,
              'N' LINE_STATUS, 'N' ACTIVE_YN FROM DUAL) source
ON (target.LINE_CODE = source.LINE_CODE AND target.ORGANIZATION_ID = source.ORGANIZATION_ID)
WHEN NOT MATCHED THEN INSERT (
  LINE_CODE, ORGANIZATION_ID, LINE_NAME, LINE_DIVISION,
  LINE_PRODUCT_DIVISION, LINE_STATUS, ACTIVE_YN, ENTER_BY, ENTER_DATE
) VALUES (
  source.LINE_CODE, source.ORGANIZATION_ID, source.LINE_NAME, source.LINE_DIVISION,
  source.LINE_PRODUCT_DIVISION, source.LINE_STATUS, source.ACTIVE_YN, 'CODEX', SYSDATE
);
/

