-- 잔존 정리 2차: 하네스 도면 체인(회로스펙→리비전→도면) + CONTROL_PLAN_ITEMS 고아

DELETE FROM HARNESS_CIRCUIT_SPECS
 WHERE REVISION_ID IN (
   SELECT REVISION_ID FROM HARNESS_DRAWING_REVISIONS WHERE DRAWING_ID IN (
     SELECT DRAWING_ID FROM HARNESS_DRAWING_MASTERS
      WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
        OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A'))));
/

DELETE FROM HARNESS_DRAWING_REVISIONS
 WHERE DRAWING_ID IN (
   SELECT DRAWING_ID FROM HARNESS_DRAWING_MASTERS
    WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
      OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A')));
/

DELETE FROM HARNESS_DRAWING_MASTERS
 WHERE COMPANY = '40' AND (ITEM_CODE LIKE 'HNS02%' OR ITEM_CODE LIKE 'KS\_%' ESCAPE '\'
   OR ITEM_CODE IN ('CBL-A','CBL-B','CBL-SE','CNTR001','CSH001','HLD-01','HSG0001','NFT-A','PHDL001','RSL-A','RSL-B','RSL-T','TMN-A','TMN-B','TMN-C','TMN-SE1','TP0001','TUB-A'));
/

DELETE FROM CONTROL_PLAN_ITEMS
 WHERE CONTROL_PLAN_ID NOT IN (SELECT PLAN_NO FROM CONTROL_PLANS WHERE PLAN_NO IS NOT NULL);
/

COMMIT;
/
