-- EQUIP_INSPECT_ITEM_POOL 시드 — TESTER 설비 점검항목 연결
-- 설비 10종 × TESTER 항목 5종 = 50건
-- COMPANY='40', PLANT_CD='1000'

-- ── EQ-AINSP-01 통합검사 설비 #1 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-01','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-01','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-01','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-01','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-01','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-AINSP-02 통합검사 설비 #2 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-02','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-02','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-02','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-02','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-AINSP-02','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-OINSP-01 외관검사 설비 #1 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-01','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-01','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-01','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-01','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-01','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-OINSP-02 외관검사 설비 #2 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-02','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-02','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-02','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-02','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-OINSP-02','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-PRC-TEST-01 도통검사 설비 #1 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-01','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-01','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-01','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-01','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-01','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-PRC-TEST-02 도통검사 설비 #2 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-02','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-02','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-02','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-02','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-PRC-TEST-02','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-TEST-01 도통검사기 #1 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-01','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-01','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-01','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-01','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-01','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-TEST-02 도통검사기 #2 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-02','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-02','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-02','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-02','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TEST-02','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-TINSP-01 단자검사 설비 #1 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-01','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-01','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-01','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-01','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-01','EI-TST-PM1','PM','Y',1)
/

-- ── EQ-TINSP-02 단자검사 설비 #2 ──
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-02','EI-TST-001','DAILY','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-02','EI-TST-002','DAILY','Y',2)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-02','EI-TST-003','DAILY','Y',3)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-02','EI-TST-P01','PERIODIC','Y',1)
/
INSERT INTO EQUIP_INSPECT_ITEM_POOL (COMPANY,PLANT_CD,EQUIP_CODE,ITEM_CODE,INSPECT_TYPE,USE_YN,SORT_SEQ) VALUES ('40','1000','EQ-TINSP-02','EI-TST-PM1','PM','Y',1)
/
