-- 2026-06-18 검사기(TESTER) 소모품 매핑 샘플 시드
-- 통전검사 실적 화면에서 검사기를 선택하면 (품목 + 검사기) 기준으로 소모품이 조회된다.
-- 기존 매핑은 생산설비(절단/크림프 등) 위주라 검사기 매핑이 거의 없어 데모용 매핑을 추가한다.
-- 소모품: CM-JG-CT1(통전검사 치구 A), CM-JG-CT2(통전검사 치구 B) — ACTIVE 롯트 보유.
-- PK: (COMPANY, PLANT_CD, PRODUCT_ITEM_CODE, EQUIP_CODE, CONSUMABLE_CODE). 재실행 안전(NOT EXISTS).

INSERT INTO CONSUMABLE_USAGE_MAP (COMPANY, PLANT_CD, PRODUCT_ITEM_CODE, EQUIP_CODE, CONSUMABLE_CODE, USAGE_PER_UNIT, USE_YN, CREATED_AT, UPDATED_AT)
SELECT '40','1000','HNS02C1ABCD','EQ-TEST-01','CM-JG-CT1',1,'Y',SYSTIMESTAMP,SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONSUMABLE_USAGE_MAP WHERE COMPANY='40' AND PLANT_CD='1000' AND PRODUCT_ITEM_CODE='HNS02C1ABCD' AND EQUIP_CODE='EQ-TEST-01' AND CONSUMABLE_CODE='CM-JG-CT1');
/
INSERT INTO CONSUMABLE_USAGE_MAP (COMPANY, PLANT_CD, PRODUCT_ITEM_CODE, EQUIP_CODE, CONSUMABLE_CODE, USAGE_PER_UNIT, USE_YN, CREATED_AT, UPDATED_AT)
SELECT '40','1000','HNS02C1ABCD','EQ-TEST-01','CM-JG-CT2',1,'Y',SYSTIMESTAMP,SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONSUMABLE_USAGE_MAP WHERE COMPANY='40' AND PLANT_CD='1000' AND PRODUCT_ITEM_CODE='HNS02C1ABCD' AND EQUIP_CODE='EQ-TEST-01' AND CONSUMABLE_CODE='CM-JG-CT2');
/
INSERT INTO CONSUMABLE_USAGE_MAP (COMPANY, PLANT_CD, PRODUCT_ITEM_CODE, EQUIP_CODE, CONSUMABLE_CODE, USAGE_PER_UNIT, USE_YN, CREATED_AT, UPDATED_AT)
SELECT '40','1000','HNS02C1ABCD','EQ-AINSP-01','CM-JG-CT1',1,'Y',SYSTIMESTAMP,SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONSUMABLE_USAGE_MAP WHERE COMPANY='40' AND PLANT_CD='1000' AND PRODUCT_ITEM_CODE='HNS02C1ABCD' AND EQUIP_CODE='EQ-AINSP-01' AND CONSUMABLE_CODE='CM-JG-CT1');
/
INSERT INTO CONSUMABLE_USAGE_MAP (COMPANY, PLANT_CD, PRODUCT_ITEM_CODE, EQUIP_CODE, CONSUMABLE_CODE, USAGE_PER_UNIT, USE_YN, CREATED_AT, UPDATED_AT)
SELECT '40','1000','HNS02','EQ-TEST-01','CM-JG-CT1',1,'Y',SYSTIMESTAMP,SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONSUMABLE_USAGE_MAP WHERE COMPANY='40' AND PLANT_CD='1000' AND PRODUCT_ITEM_CODE='HNS02' AND EQUIP_CODE='EQ-TEST-01' AND CONSUMABLE_CODE='CM-JG-CT1');
/
INSERT INTO CONSUMABLE_USAGE_MAP (COMPANY, PLANT_CD, PRODUCT_ITEM_CODE, EQUIP_CODE, CONSUMABLE_CODE, USAGE_PER_UNIT, USE_YN, CREATED_AT, UPDATED_AT)
SELECT '40','1000','HNS02','EQ-AINSP-01','CM-JG-CT2',1,'Y',SYSTIMESTAMP,SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONSUMABLE_USAGE_MAP WHERE COMPANY='40' AND PLANT_CD='1000' AND PRODUCT_ITEM_CODE='HNS02' AND EQUIP_CODE='EQ-AINSP-01' AND CONSUMABLE_CODE='CM-JG-CT2');
/
COMMIT;
/
