-- 특채처리 메뉴 등록 (QC_CONCESSION)
-- 사이드바는 MENU_CATEGORY_ITEMS(CATEGORY_CODE) 기준으로 렌더링되며
-- QC_IQC(IQC, MATERIAL/50)와 MAT_RECEIVE(입고, MATERIAL/60) 사이(55)에 배치한다.
-- 경로/라벨은 프론트 menuConfig(QC_CONCESSION → /material/concession, menu.material.concession)에서 매핑.

-- 메뉴 항목 (CREATED_BY/UPDATED_BY NOT NULL)
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'QC_CONCESSION', 'MATERIAL', 55, '40', '1000', 'system', 'system' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM MENU_CATEGORY_ITEMS WHERE MENU_CODE='QC_CONCESSION' AND COMPANY='40' AND PLANT_CD='1000'
);

-- 권한 (QC_IQC와 동일: MANAGER, OPERATOR)
INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'MANAGER', 'QC_CONCESSION', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='MANAGER' AND MENU_CODE='QC_CONCESSION' AND COMPANY='40' AND PLANT_CD='1000'
);

INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'OPERATOR', 'QC_CONCESSION', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='OPERATOR' AND MENU_CODE='QC_CONCESSION' AND COMPANY='40' AND PLANT_CD='1000'
);
