BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_MAPS MODIFY (STD_TIME NUMBER(12,4))';
  EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_MAPS MODIFY (SETUP_TIME NUMBER(12,4))';
  EXECUTE IMMEDIATE 'ALTER TABLE PROD_RESULTS MODIFY (CYCLE_TIME NUMBER(12,4))';
  EXECUTE IMMEDIATE 'ALTER TABLE SUBCON_ORDERS MODIFY (UNIT_PRICE NUMBER(14,4))';
END;
/
