-- =====================================================================
-- 2026-10-07 제품(완제품) 실사 · 재고조정 · 월마감 테이블 4개 + 시퀀스 1개
--
-- 제품 재고(IP_PRODUCT_FG_INVENTORY)는 박스(PACK) 바코드 한 줄 = 재고 한 행이고 수량은 박스 안 PCS 다.
-- 자재(271·272·274)·공정(공정실사)과 같은 흐름으로 맞춘다:
--   실사 시작(장부 고정) → 박스 바코드 스캔·엑셀 → 일괄 조정 → 월마감
--
-- 조정은 입고(IP_PRODUCT_FG_RECEIPT)·출고(IP_PRODUCT_FG_ISSUE)에 넣지 않는다.
--   그 두 표는 판매실적·납품 뷰(IP_PRODUCT_DELIVERY_*_V)·출하 화면이 읽어서 조정이 매출로 섞인다.
--   그래서 재고(IP_PRODUCT_FG_INVENTORY)를 직접 고치고, 조정 한 건을 IP_PRODUCT_FG_ADJUST 에 남긴다.
--   월마감은 기초 + 입고 − 출고 + 조정 = 기말 (수량만 — 제품에는 원가가 없다).
-- 사용처: apps/backend/src/modules/inventory-query/fg-stocktake.service.ts, fg-close.service.ts
-- =====================================================================

CREATE TABLE IP_PRODUCT_FG_INV_CHECK (
  CHECK_YYYYMM      VARCHAR2(6)   NOT NULL,
  BARCODE           VARCHAR2(100) NOT NULL,
  LOCATION_CODE     VARCHAR2(10)  NOT NULL,
  ORGANIZATION_ID   NUMBER        NOT NULL,
  PACK_TYPE         VARCHAR2(2),
  MODEL_NAME        VARCHAR2(100),
  MODEL_SUFFIX      VARCHAR2(50),
  ITEM_CODE         VARCHAR2(20),
  INVENTORY_QTY     NUMBER        DEFAULT 0 NOT NULL,
  CHECK_QTY         NUMBER        DEFAULT 0 NOT NULL,
  SCANNED_YN        VARCHAR2(1)   DEFAULT 'N' NOT NULL,
  COMMENTS          VARCHAR2(1000),
  ENTER_DATE        DATE,
  ENTER_BY          VARCHAR2(20),
  LAST_MODIFY_DATE  DATE,
  LAST_MODIFY_BY    VARCHAR2(20),
  CONSTRAINT PK_IP_PRODUCT_FG_INV_CHECK PRIMARY KEY (CHECK_YYYYMM, BARCODE, LOCATION_CODE, ORGANIZATION_ID)
)
/
COMMENT ON TABLE IP_PRODUCT_FG_INV_CHECK IS '제품 실사표 — 실사 시작 때 제품재고(≠0)를 장부로 고정하고 스캔 수량을 채운다'
/
COMMENT ON COLUMN IP_PRODUCT_FG_INV_CHECK.INVENTORY_QTY IS '장부 수량 (실사 시작 시점의 박스 수량, PCS)'
/
COMMENT ON COLUMN IP_PRODUCT_FG_INV_CHECK.CHECK_QTY IS '실사 수량 (스캔·엑셀로 센 박스 수량, 안 센 박스는 0)'
/
COMMENT ON COLUMN IP_PRODUCT_FG_INV_CHECK.SCANNED_YN IS '스캔·엑셀로 센 박스 Y / 안 센 박스 N'
/

CREATE TABLE IP_PRODUCT_FG_ADJUST (
  ADJUST_DATE       DATE          NOT NULL,
  ADJUST_SEQUENCE   NUMBER        NOT NULL,
  ORGANIZATION_ID   NUMBER        NOT NULL,
  CHECK_YYYYMM      VARCHAR2(6)   NOT NULL,
  BARCODE           VARCHAR2(100) NOT NULL,
  LOCATION_CODE     VARCHAR2(10)  NOT NULL,
  PACK_TYPE         VARCHAR2(2),
  MODEL_NAME        VARCHAR2(100),
  MODEL_SUFFIX      VARCHAR2(50),
  ITEM_CODE         VARCHAR2(20),
  ADJUST_QTY        NUMBER        NOT NULL,
  COMMENTS          VARCHAR2(200),
  ENTER_DATE        DATE,
  ENTER_BY          VARCHAR2(20),
  CONSTRAINT PK_IP_PRODUCT_FG_ADJUST PRIMARY KEY (ADJUST_DATE, ADJUST_SEQUENCE)
)
/
CREATE INDEX IX_IP_PRODUCT_FG_ADJUST_01 ON IP_PRODUCT_FG_ADJUST (CHECK_YYYYMM, ORGANIZATION_ID, BARCODE)
/
COMMENT ON TABLE IP_PRODUCT_FG_ADJUST IS '제품 재고조정 수불 — 실사 차이를 재고에 반영한 한 건씩 (입출고 표와 분리)'
/
COMMENT ON COLUMN IP_PRODUCT_FG_ADJUST.ADJUST_DATE IS '조정 날짜 (실사월의 마지막 날)'
/
COMMENT ON COLUMN IP_PRODUCT_FG_ADJUST.ADJUST_QTY IS '조정 수량 (실사 − 장부. 남음 +, 모자람 −. 재고에 그대로 더한다)'
/

CREATE SEQUENCE SEQ_FG_ADJUST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE TABLE IP_PRODUCT_FG_INV_CLOSE (
  CLOSE_YYYYMM        VARCHAR2(6)   NOT NULL,
  MODEL_NAME          VARCHAR2(100) NOT NULL,
  MODEL_SUFFIX        VARCHAR2(50)  NOT NULL,
  ORGANIZATION_ID     NUMBER        NOT NULL,
  ITEM_CODE           VARCHAR2(20),
  LAST_INVENTORY_QTY  NUMBER        DEFAULT 0,
  MM_RECEIPT_QTY      NUMBER        DEFAULT 0,
  MM_ISSUE_QTY        NUMBER        DEFAULT 0,
  MM_ADJUST_QTY       NUMBER        DEFAULT 0,
  MM_INVENTORY_QTY    NUMBER        DEFAULT 0,
  ENTER_DATE          DATE,
  ENTER_BY            VARCHAR2(20),
  CONSTRAINT PK_IP_PRODUCT_FG_INV_CLOSE PRIMARY KEY (CLOSE_YYYYMM, MODEL_NAME, MODEL_SUFFIX, ORGANIZATION_ID)
)
/
COMMENT ON TABLE IP_PRODUCT_FG_INV_CLOSE IS '제품 재고 월마감 — 모델 단위 기초 + 입고 − 출고 + 조정 = 기말 (수량)'
/
COMMENT ON COLUMN IP_PRODUCT_FG_INV_CLOSE.MM_ISSUE_QTY IS '출고 수량 (출고 − 출고취소)'
/
COMMENT ON COLUMN IP_PRODUCT_FG_INV_CLOSE.MM_ADJUST_QTY IS '재고조정 수량 (실사 차이. 남음 +, 모자람 −)'
/

CREATE TABLE IP_PRODUCT_FG_INV_CLOSE_MONTH (
  CLOSE_YYYYMM      VARCHAR2(6) NOT NULL,
  ORGANIZATION_ID   NUMBER      NOT NULL,
  CLOSE_YN          VARCHAR2(1) DEFAULT 'N' NOT NULL,
  LAST_CLOSE_DATE   DATE,
  ENTER_DATE        DATE,
  ENTER_BY          VARCHAR2(20),
  LAST_MODIFY_DATE  DATE,
  LAST_MODIFY_BY    VARCHAR2(20),
  CONSTRAINT PK_IP_PRODUCT_FG_INV_CLOSE_MM PRIMARY KEY (CLOSE_YYYYMM, ORGANIZATION_ID)
)
/
COMMENT ON TABLE IP_PRODUCT_FG_INV_CLOSE_MONTH IS '제품 재고 마감월 표시 — 자재 마감(ISYS_INVENTORY_CLOSE_DATE)과 따로 닫는다'
/

-- 되돌리기
-- DROP TABLE IP_PRODUCT_FG_INV_CLOSE_MONTH;
-- DROP TABLE IP_PRODUCT_FG_INV_CLOSE;
-- DROP SEQUENCE SEQ_FG_ADJUST_SEQ;
-- DROP TABLE IP_PRODUCT_FG_ADJUST;
-- DROP TABLE IP_PRODUCT_FG_INV_CHECK;
