-- N91H00-X9800 라우팅 (BOM + 회신 시트 공정 기준). MERGE 멱등.

MERGE INTO ROUTING_GROUPS g USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R FROM DUAL) x ON (g.COMPANY=x.C AND g.PLANT_CD=x.P AND g.ROUTING_CODE=x.R)
WHEN MATCHED THEN UPDATE SET g.ROUTING_NAME='N91H00-X9800 완제품 라우팅', g.ITEM_CODE='N91H00-X9800', g.USE_YN='Y', g.UPDATED_BY='claude', g.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,ROUTING_NAME,ITEM_CODE,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800','N91H00-X9800 완제품 라우팅','N91H00-X9800','Y','claude');
/
MERGE INTO ROUTING_GROUPS g USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R FROM DUAL) x ON (g.COMPANY=x.C AND g.PLANT_CD=x.P AND g.ROUTING_CODE=x.R)
WHEN MATCHED THEN UPDATE SET g.ROUTING_NAME='N91H00-X9800-C1 (1번 케이블) 라우팅', g.ITEM_CODE='N91H00-X9800-C1', g.USE_YN='Y', g.UPDATED_BY='claude', g.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,ROUTING_NAME,ITEM_CODE,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1','N91H00-X9800-C1 (1번 케이블) 라우팅','N91H00-X9800-C1','Y','claude');
/
MERGE INTO ROUTING_GROUPS g USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R FROM DUAL) x ON (g.COMPANY=x.C AND g.PLANT_CD=x.P AND g.ROUTING_CODE=x.R)
WHEN MATCHED THEN UPDATE SET g.ROUTING_NAME='N91H00-X9800-C2 (2번 케이블) 라우팅', g.ITEM_CODE='N91H00-X9800-C2', g.USE_YN='Y', g.UPDATED_BY='claude', g.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,ROUTING_NAME,ITEM_CODE,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2','N91H00-X9800-C2 (2번 케이블) 라우팅','N91H00-X9800-C2','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,10 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='ATCNS', p.PROCESS_NAME='자동절단탈피', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',10,'ATCNS','자동절단탈피','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,20 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='SHDCT', p.PROCESS_NAME='실드절단', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',20,'SHDCT','실드절단','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='HEXPR', p.PROCESS_NAME='압착준비(육각)', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'HEXPR','압착준비(육각)','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,40 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='HEXCP', p.PROCESS_NAME='육각압착', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',40,'HEXCP','육각압착','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,50 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='TMCRP', p.PROCESS_NAME='단자압착', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='Y', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='Y', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',50,'TMCRP','단자압착','N','Y','N','Y','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,10 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='ATCNS', p.PROCESS_NAME='자동절단탈피', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',10,'ATCNS','자동절단탈피','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,20 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='SHDCT', p.PROCESS_NAME='실드절단', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',20,'SHDCT','실드절단','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,30 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='HEXPR', p.PROCESS_NAME='압착준비(육각)', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',30,'HEXPR','압착준비(육각)','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,40 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='HEXCP', p.PROCESS_NAME='육각압착', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',40,'HEXCP','육각압착','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,50 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='TMCRP', p.PROCESS_NAME='단자압착', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='Y', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='Y', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',50,'TMCRP','단자압착','N','Y','N','Y','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,10 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='TUBHT', p.PROCESS_NAME='열수축', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',10,'TUBHT','열수축','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,20 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='SGINS', p.PROCESS_NAME='반제품검사', p.SAMPLE_INSPECT_YN='Y', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',20,'SGINS','반제품검사','Y','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,30 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='MATPR', p.PROCESS_NAME='조립자재준비', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',30,'MATPR','조립자재준비','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,40 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='PROTC', p.PROCESS_NAME='프로텍트체결', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',40,'PROTC','프로텍트체결','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,50 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='MASSY', p.PROCESS_NAME='조립', p.SAMPLE_INSPECT_YN='N', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',50,'MASSY','조립','N','N','N','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,60 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='CIINS', p.PROCESS_NAME='회로검사', p.SAMPLE_INSPECT_YN='Y', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='Y', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',60,'CIINS','회로검사','Y','N','Y','N','Y','claude');
/
MERGE INTO ROUTING_PROCESSES p USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,70 S FROM DUAL) x ON (p.COMPANY=x.C AND p.PLANT_CD=x.P AND p.ROUTING_CODE=x.R AND p.SEQ=x.S)
WHEN MATCHED THEN UPDATE SET p.PROCESS_CODE='AINSP', p.PROCESS_NAME='통합검사', p.SAMPLE_INSPECT_YN='Y', p.ISSUE_SG_LABEL_YN='N', p.ISSUE_FG_LABEL_YN='N', p.DESTRUCTIVE_YN='N', p.UPDATED_BY='claude', p.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,PROCESS_CODE,PROCESS_NAME,SAMPLE_INSPECT_YN,ISSUE_SG_LABEL_YN,ISSUE_FG_LABEL_YN,DESTRUCTIVE_YN,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',70,'AINSP','통합검사','Y','N','N','N','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,10 S,'1SH21A7A09' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=670, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',10,'1SH21A7A09',670,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S,'STEVC73840' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'STEVC73840',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S,'RTEBW002MA' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'RTEBW002MA',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S,'SKEG176167' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'SKEG176167',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S,'CRSKEB6167' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'CRSKEB6167',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S,'CRRKEB6167' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'CRRKEB6167',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S,'HTEAVCW002MA' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'HTEAVCW002MA',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S,'CRRTEB3840' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'CRRTEB3840',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,30 S,'CRSTEB3840' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',30,'CRSTEB3840',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,50 S,'TKEG1WFSCD' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',50,'TKEG1WFSCD',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,50 S,'VSFT1-201' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',50,'VSFT1-201',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,50 S,'DLMLS6-3-3' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',50,'DLMLS6-3-3',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C1' R,50 S,'EKEESNATBC' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C1',50,'EKEESNATBC',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,10 S,'1SH21A7A09' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=785, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',10,'1SH21A7A09',785,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,30 S,'STEVC73840' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',30,'STEVC73840',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,30 S,'RTEBW002MA' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',30,'RTEBW002MA',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,30 S,'SKEG176167' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',30,'SKEG176167',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,30 S,'CRSKEB6167' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',30,'CRSKEB6167',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,30 S,'CRRKEB6167' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',30,'CRRKEB6167',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,30 S,'CRRTEB3840' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',30,'CRRTEB3840',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,30 S,'CRSTEB3840' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',30,'CRSTEB3840',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800-C2' R,50 S,'TKEG1WFSCD' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800-C2',50,'TKEG1WFSCD',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,10 S,'VSFT1-201' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',10,'VSFT1-201',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,20 S,'N91H00-X9800-C1' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',20,'N91H00-X9800-C1',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,20 S,'N91H00-X9800-C2' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',20,'N91H00-X9800-C2',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,30 S,'6TBE11A000' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=345, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',30,'6TBE11A000',345,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,40 S,'HKEAN1W002FA' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',40,'HKEAN1W002FA',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,40 S,'RKEAW002F4' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',40,'RKEAW002F4',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,50 S,'6TPH1A0190' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1330, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',50,'6TPH1A0190',1330,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,50 S,'NBC3-5L' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=2, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',50,'NBC3-5L',2,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,50 S,'LB04201250' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',50,'LB04201250',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,60 S,'LB08802520' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=1, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',60,'LB08802520',1,'BACKFLUSH','Y','claude');
/
MERGE INTO ROUTING_MATERIALS m USING (SELECT '40' C,'1000' P,'RT_N91H00-X9800' R,60 S,'RIBON-7' CH FROM DUAL) x ON (m.COMPANY=x.C AND m.PLANT_CD=x.P AND m.ROUTING_CODE=x.R AND m.SEQ=x.S AND m.CHILD_ITEM_CODE=x.CH)
WHEN MATCHED THEN UPDATE SET m.ALLOC_QTY=94, m.USE_YN='Y', m.UPDATED_BY='claude', m.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (COMPANY,PLANT_CD,ROUTING_CODE,SEQ,CHILD_ITEM_CODE,ALLOC_QTY,ISSUE_METHOD,USE_YN,CREATED_BY) VALUES ('40','1000','RT_N91H00-X9800',60,'RIBON-7',94,'BACKFLUSH','Y','claude');
/
COMMIT;
/
