-- 공정생품검사(SELF_INSPECT_ITEMS) 시드 — 실 라우팅 공정코드 17종 기준
-- 기존 PRC-* 데모 코드와 단절된 문제 해결: ROUTING_PROCESSES 가 쓰는 실 코드에 검사항목 등록.
-- 측정형(MEASURE)은 LSL/USL/UNIT 예시값 포함, 판정형(VISUAL)은 규격 없음.
-- 자연키(COMPANY,PLANT_CD,PROCESS_CODE,ITEM_NAME) WHERE NOT EXISTS → 재실행 안전. 사이트: JSHANES(40/1000)
-- 생성: scripts/seed_self_inspect_real_processes.py (동일 데이터)

-- ATCUT
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'ATCUT', '전선 절단 길이 측정', '도면 기준 100±2mm', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', 'mm', 98, 102, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='ATCUT' AND ITEM_NAME='전선 절단 길이 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'ATCUT', '절단면 상태 확인', '단면 직각, 심선 손상 없을 것', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='ATCUT' AND ITEM_NAME='절단면 상태 확인'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'ATCUT', '전선 색상·규격 확인', '작업지시 지정 색상·단면적 일치', 'DIRECT', 'FIRST', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='ATCUT' AND ITEM_NAME='전선 색상·규격 확인'
);
/
-- ATCNS
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'ATCNS', '전선 절단 길이 측정', '도면 기준 100±2mm', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', 'mm', 98, 102, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='ATCNS' AND ITEM_NAME='전선 절단 길이 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'ATCNS', '탈피 길이 측정', '도면 기준 6±0.5mm', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'MEASURE', 'mm', 5.5, 6.5, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='ATCNS' AND ITEM_NAME='탈피 길이 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'ATCNS', '심선 단선 여부 확인', '심선 가닥 100% 유지', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='ATCNS' AND ITEM_NAME='심선 단선 여부 확인'
);
/
-- STRPB
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'STRPB', '탈피 길이 측정', '도면 기준 6±0.5mm', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', 'mm', 5.5, 6.5, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='STRPB' AND ITEM_NAME='탈피 길이 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'STRPB', '절연체 손상 여부', '탈피 인접 피복 손상 없을 것', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='STRPB' AND ITEM_NAME='절연체 손상 여부'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'STRPB', '심선 단선 여부', '심선 가닥 100% 유지', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='STRPB' AND ITEM_NAME='심선 단선 여부'
);
/
-- SHDRM
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'SHDRM', '편조 제거 길이 측정', '도면 기준 10±1mm', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', 'mm', 9, 11, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='SHDRM' AND ITEM_NAME='편조 제거 길이 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'SHDRM', '심선·편조 손상 여부', '심선/편조 찍힘·손상 없을 것', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='SHDRM' AND ITEM_NAME='심선·편조 손상 여부'
);
/
-- CRMPF
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPF', '압착 높이(CH) 측정', '도면 기준 1.20±0.05mm', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', 'mm', 1.15, 1.25, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPF' AND ITEM_NAME='압착 높이(CH) 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPF', '압착 폭(CW) 측정', '도면 기준 2.00±0.10mm', 'DIRECT', 'FIRST', 0,
       2, 'Y', 'MEASURE', 'mm', 1.9, 2.1, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPF' AND ITEM_NAME='압착 폭(CW) 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPF', '인장강도 시험 (Pull test)', '규격 이상 하중에서 단선 없을 것', 'DELEGATE', 'FIRST', 1,
       3, 'Y', 'MEASURE', 'N', 60, NULL, 3,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPF' AND ITEM_NAME='인장강도 시험 (Pull test)'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPF', '압착 단면 검사 (CS)', '단면 원형, 절연체·도체 비율 기준 내', 'DELEGATE', 'FIRST', 1,
       4, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPF' AND ITEM_NAME='압착 단면 검사 (CS)'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPF', '절연체 손상 여부', '절연 피복 찍힘·손상 없을 것', 'DIRECT', 'FIRST,MID,LAST', 0,
       5, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPF' AND ITEM_NAME='절연체 손상 여부'
);
/
-- CRMPR
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPR', '압착 높이(CH) 측정', '도면 기준 1.20±0.05mm', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', 'mm', 1.15, 1.25, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPR' AND ITEM_NAME='압착 높이(CH) 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPR', '인장강도 시험 (Pull test)', '규격 이상 하중에서 단선 없을 것', 'DELEGATE', 'FIRST', 1,
       2, 'Y', 'MEASURE', 'N', 60, NULL, 3,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPR' AND ITEM_NAME='인장강도 시험 (Pull test)'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPR', '압착 단면 검사 (CS)', '단면 원형, 절연체·도체 비율 기준 내', 'DELEGATE', 'FIRST', 1,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPR' AND ITEM_NAME='압착 단면 검사 (CS)'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'CRMPR', '절연체 손상 여부', '절연 피복 찍힘·손상 없을 것', 'DIRECT', 'FIRST,MID,LAST', 0,
       4, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='CRMPR' AND ITEM_NAME='절연체 손상 여부'
);
/
-- HEXCP
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'HEXCP', '대변 거리(육각) 측정', '도면 기준 7.2±0.2mm', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', 'mm', 7.0, 7.4, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='HEXCP' AND ITEM_NAME='대변 거리(육각) 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'HEXCP', '인장강도 시험 (Pull test)', '규격 이상 하중에서 단선 없을 것', 'DELEGATE', 'FIRST', 1,
       2, 'Y', 'MEASURE', 'N', 120, NULL, 3,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='HEXCP' AND ITEM_NAME='인장강도 시험 (Pull test)'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'HEXCP', '압착부 크랙 여부', '압착부 균열·크랙 없을 것', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='HEXCP' AND ITEM_NAME='압착부 크랙 여부'
);
/
-- WELDR
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'WELDR', '융착부 인장강도', '규격 이상 하중에서 분리 없을 것', 'DELEGATE', 'FIRST', 1,
       1, 'Y', 'MEASURE', 'N', 80, NULL, 3,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='WELDR' AND ITEM_NAME='융착부 인장강도'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'WELDR', '융착 높이 측정', '도면 기준 1.5±0.2mm', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'MEASURE', 'mm', 1.3, 1.7, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='WELDR' AND ITEM_NAME='융착 높이 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'WELDR', '융착부 외관 확인', '융착부 박리·기공 없을 것', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='WELDR' AND ITEM_NAME='융착부 외관 확인'
);
/
-- TUBHT
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TUBHT', '열처리 온도', '수축 적정 온도 120~180℃', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', '℃', 120, 180, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TUBHT' AND ITEM_NAME='열처리 온도'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TUBHT', '튜브 위치·길이', '도면 기준 20±2mm', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'MEASURE', 'mm', 18, 22, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TUBHT' AND ITEM_NAME='튜브 위치·길이'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TUBHT', '튜브 수축 상태', '수축 균일, 들뜸·터짐 없을 것', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TUBHT' AND ITEM_NAME='튜브 수축 상태'
);
/
-- MTASY
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'MTASY', '부품 장착 위치 확인', '도면 지정 위치에 장착', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='MTASY' AND ITEM_NAME='부품 장착 위치 확인'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'MTASY', '체결 토크 측정', '규격 토크 2.0±0.2N·m', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'MEASURE', 'N·m', 1.8, 2.2, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='MTASY' AND ITEM_NAME='체결 토크 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'MTASY', '부품 누락 여부', 'BOM 기준 부품 누락 없을 것', 'DIRECT', 'FIRST,MID,LAST', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='MTASY' AND ITEM_NAME='부품 누락 여부'
);
/
-- AUXMT
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'AUXMT', '부자재 누락 여부', '도면 지정 부자재 누락 없을 것', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='AUXMT' AND ITEM_NAME='부자재 누락 여부'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'AUXMT', '클립 간격 측정', '도면 기준 50±5mm', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'MEASURE', 'mm', 45, 55, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='AUXMT' AND ITEM_NAME='클립 간격 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'AUXMT', '클립·밴드 체결 상태', '고정류 체결 견고, 이탈 없을 것', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='AUXMT' AND ITEM_NAME='클립·밴드 체결 상태'
);
/
-- SASSY
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'SASSY', '커넥터 체결 상태', '딸깍 체결, 불완전 체결 없을 것', 'DIRECT', 'FIRST,MID,LAST', 0,
       1, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='SASSY' AND ITEM_NAME='커넥터 체결 상태'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'SASSY', '전선 배열 순서 확인', '회로도 기준 핀 배열 일치', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='SASSY' AND ITEM_NAME='전선 배열 순서 확인'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'SASSY', '서브조립 길이 측정', '도면 기준 300±5mm', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'MEASURE', 'mm', 295, 305, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='SASSY' AND ITEM_NAME='서브조립 길이 측정'
);
/
-- MASSY
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'MASSY', '커넥터 체결 상태', '딸깍 체결, 불완전 체결 없을 것', 'DIRECT', 'FIRST,MID,LAST', 0,
       1, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='MASSY' AND ITEM_NAME='커넥터 체결 상태'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'MASSY', '회로 배열 확인', '회로도 기준 결선 일치', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='MASSY' AND ITEM_NAME='회로 배열 확인'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'MASSY', '전장(전체 길이) 측정', '도면 기준 500±5mm', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'MEASURE', 'mm', 495, 505, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='MASSY' AND ITEM_NAME='전장(전체 길이) 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'MASSY', '도통 검사', '전체 회로 도통 OK, 오결선 없을 것', 'DELEGATE', 'FIRST', 0,
       4, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='MASSY' AND ITEM_NAME='도통 검사'
);
/
-- TAPPN
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TAPPN', '테이핑 피치 확인', '테이프 겹침 1/2 이상, 빈틈 없을 것', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TAPPN' AND ITEM_NAME='테이핑 피치 확인'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TAPPN', '분기점 위치 측정', '도면 기준 150±5mm', 'DIRECT', 'FIRST,MID', 0,
       2, 'Y', 'MEASURE', 'mm', 145, 155, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TAPPN' AND ITEM_NAME='분기점 위치 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TAPPN', '테이프 종류·색상 확인', '작업지시 지정 테이프 사용', 'DIRECT', 'FIRST', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TAPPN' AND ITEM_NAME='테이프 종류·색상 확인'
);
/
-- TINSP
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TINSP', '단자 삽입력 측정', '규격 삽입력 10~40N', 'DIRECT', 'FIRST,MID', 0,
       1, 'Y', 'MEASURE', 'N', 10, 40, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TINSP' AND ITEM_NAME='단자 삽입력 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TINSP', '단자 정위치(걸림) 확인', '단자 풀백 없이 정위치 걸림', 'DIRECT', 'FIRST,MID,LAST', 0,
       2, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TINSP' AND ITEM_NAME='단자 정위치(걸림) 확인'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'TINSP', '단자 휨·변형 여부', '단자 휨·변형·손상 없을 것', 'DIRECT', 'FIRST,MID', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='TINSP' AND ITEM_NAME='단자 휨·변형 여부'
);
/
-- OINSP
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'OINSP', '외관 손상 확인', '찍힘·긁힘·오염 없을 것', 'DIRECT', 'FIRST,MID,LAST', 0,
       1, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='OINSP' AND ITEM_NAME='외관 손상 확인'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'OINSP', '라벨 부착 상태', '품번·Lot·수량 정확, 오부착 없을 것', 'DIRECT', 'FIRST,LAST', 0,
       2, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='OINSP' AND ITEM_NAME='라벨 부착 상태'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'OINSP', '전선 색상·규격 확인', '작업지시 지정 색상·규격 일치', 'DIRECT', 'FIRST', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='OINSP' AND ITEM_NAME='전선 색상·규격 확인'
);
/
-- AINSP
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'AINSP', '도통 검사', '전체 회로 도통 OK, 오결선 없을 것', 'DELEGATE', 'FIRST', 0,
       1, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='AINSP' AND ITEM_NAME='도통 검사'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'AINSP', '절연 저항 측정', '500V 인가 시 1MΩ 이상', 'DELEGATE', 'FIRST', 0,
       2, 'Y', 'MEASURE', 'MΩ', 1, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='AINSP' AND ITEM_NAME='절연 저항 측정'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'AINSP', '내전압 시험', '1000V 1분 인가 시 절연 파괴 없을 것', 'DELEGATE', 'FIRST', 0,
       3, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='AINSP' AND ITEM_NAME='내전압 시험'
);
/
INSERT INTO SELF_INSPECT_ITEMS
  (ID, PROCESS_CODE, ITEM_NAME, STANDARD, INSPECT_METHOD, TIMING, IS_DESTRUCTIVE,
   SORT_ORDER, USE_YN, ITEM_TYPE, UNIT, LSL_VALUE, USL_VALUE, SAMPLE_COUNT,
   COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT SYS_GUID(), 'AINSP', '최종 외관 확인', '찍힘·긁힘·오염 없을 것', 'DIRECT', 'LAST', 0,
       4, 'Y', 'VISUAL', NULL, NULL, NULL, 1,
       '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM SELF_INSPECT_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000'
    AND PROCESS_CODE='AINSP' AND ITEM_NAME='최종 외관 확인'
);
/

COMMIT;
/
