-- 품목마스터 속성 채움: 제품유형/차종/모델구분/리비전 (빈 값만, 기존값 보존 NVL)
-- 차종=OV(Usage Vehicle), 모델구분=HV(고전압 하네스), 리비전=A
UPDATE ITEM_MASTERS SET
  REV = NVL(REV, 'A'),
  MODEL_NAME = NVL(MODEL_NAME, 'OV'),
  DEFECT_MODEL_GROUP = NVL(DEFECT_MODEL_GROUP, 'HV'),
  PRODUCT_TYPE = NVL(PRODUCT_TYPE, CASE
    WHEN ITEM_TYPE = 'FINISHED' THEN 'HARNESS'
    WHEN ITEM_TYPE = 'SEMI_PRODUCT' THEN 'SUB_ASSY'
    WHEN ITEM_NAME IN ('WIRE', 'B/CABLE') THEN 'WIRE'
    WHEN ITEM_NAME = 'TUBE' THEN 'TUBE'
    WHEN ITEM_NAME = 'TAPE' THEN 'TAPE'
    WHEN ITEM_NAME IN ('TML', 'EARTH TML') THEN 'TERMINAL'
    WHEN ITEM_NAME = 'HSG' THEN 'HOUSING'
    WHEN ITEM_NAME IN ('LABEL', 'RIBBON') THEN 'LABEL'
    WHEN ITEM_NAME = 'RET' THEN 'HOLDER'
    WHEN ITEM_NAME = 'SEAL' THEN 'SEAL'
    WHEN ITEM_NAME IN ('CRIMP RING', 'CRIMP SHILED', 'CRIMP SHIELD') THEN 'SHIELD'
    ELSE 'HARNESS' END),
  UPDATED_BY = 'claude',
  UPDATED_AT = SYSTIMESTAMP
WHERE COMPANY = '40';
/
COMMIT;
/
