-- 2026-05-28: ROUTING_PROCESSES 검사 관련 컬럼 추가
-- QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (QC_SELF_YN VARCHAR2(1) DEFAULT ''N'' NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (INSPECT_METHOD VARCHAR2(20) DEFAULT ''DIRECT'' NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (DESTRUCTIVE_YN VARCHAR2(1) DEFAULT ''N'' NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE ROUTING_PROCESSES ADD (SAMPLE_QTY NUMBER DEFAULT 1 NULL)';
END;
/
