-- ============================================================================
-- 2026-06-16 공정재고 전용 테이블 (설비 단위 재공품 재고)
--   WIP_MAT_STOCKS       : 설비(EQUIP_CODE)별 공정재고 현재고
--   WIP_MAT_TRANSACTIONS : 공정재고 가산/차감 거래원장
--   SEQ_WIP_TX           : 공정 거래번호(WIP_TX) 채번 시퀀스
-- 원자재재고(MAT_STOCKS)·원자재 수불(STOCK_TRANSACTIONS)과 완전 분리.
-- 각 DDL 문은 슬래시(/)로 구분.
-- ============================================================================

CREATE TABLE WIP_MAT_STOCKS (
  COMPANY        VARCHAR2(50)  NOT NULL,
  PLANT_CD       VARCHAR2(50)  NOT NULL,
  EQUIP_CODE     VARCHAR2(50)  NOT NULL,
  ITEM_CODE      VARCHAR2(50)  NOT NULL,
  MAT_UID        VARCHAR2(100) NOT NULL,
  QTY            NUMBER        DEFAULT 0 NOT NULL,
  AVAILABLE_QTY  NUMBER        DEFAULT 0 NOT NULL,
  RESERVED_QTY   NUMBER        DEFAULT 0 NOT NULL,
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_WIP_MAT_STOCKS PRIMARY KEY (COMPANY, PLANT_CD, EQUIP_CODE, ITEM_CODE, MAT_UID)
)
/
CREATE INDEX IX_WIP_MAT_STOCKS_EQUIP ON WIP_MAT_STOCKS (EQUIP_CODE)
/
CREATE INDEX IX_WIP_MAT_STOCKS_ITEM ON WIP_MAT_STOCKS (ITEM_CODE)
/
CREATE TABLE WIP_MAT_TRANSACTIONS (
  TRANS_NO          VARCHAR2(50)  NOT NULL,
  TRANS_TYPE        VARCHAR2(50)  NOT NULL,
  EQUIP_CODE        VARCHAR2(50)  NOT NULL,
  ITEM_CODE         VARCHAR2(50)  NOT NULL,
  MAT_UID           VARCHAR2(100) NOT NULL,
  QTY               NUMBER        NOT NULL,
  FROM_WAREHOUSE_ID VARCHAR2(50),
  ORDER_NO          VARCHAR2(50),
  REF_TYPE          VARCHAR2(50),
  REF_ID            VARCHAR2(100),
  CANCEL_REF_ID     VARCHAR2(50),
  STATUS            VARCHAR2(20)  DEFAULT 'DONE' NOT NULL,
  REMARK            VARCHAR2(500),
  WORKER_ID         VARCHAR2(50),
  COMPANY           VARCHAR2(50)  NOT NULL,
  PLANT_CD          VARCHAR2(50)  NOT NULL,
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_WIP_MAT_TRANSACTIONS PRIMARY KEY (TRANS_NO)
)
/
CREATE INDEX IX_WIP_MAT_TX_EQUIP ON WIP_MAT_TRANSACTIONS (EQUIP_CODE, ITEM_CODE)
/
CREATE INDEX IX_WIP_MAT_TX_REF ON WIP_MAT_TRANSACTIONS (REF_TYPE, REF_ID)
/
CREATE SEQUENCE SEQ_WIP_TX START WITH 1 INCREMENT BY 1 NOCACHE
/
