-- =====================================================================
-- 2026-06-11  품목관리 제품유형(PRODUCT_TYPE) 공통코드 그룹 시드
-- 배경: /master/part 제품유형 드롭다운/컬럼이 프론트 하드코딩(PRODUCT_TYPE_VALUES)으로만
--       동작하고 COM_CODES에 PRODUCT_TYPE 그룹이 없어 코드마스터와 불일치.
-- 코드값은 @harness/shared PRODUCT_TYPE_VALUES 16종과 동일(백엔드 DTO IsIn 검증과 정합).
-- 멱등 실행(존재 시 갱신)
-- 대상: JSHANES (company=40 / plant=1000)
-- =====================================================================

MERGE INTO COM_CODES t
USING (
  SELECT 'PRODUCT_TYPE' AS GROUP_CODE, 'HARNESS' AS DETAIL_CODE, '하네스' AS CODE_NAME, 1 AS SORT_ORDER, '40' AS COMPANY, '1000' AS PLANT_CD FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'MODEL', '모델/판매코드', 2, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'SUB_ASSY', '서브조립', 3, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'WIRE', '전선/케이블', 4, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'TERMINAL', '터미널', 5, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'CONNECTOR', '커넥터', 6, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'HOLDER', '홀더', 7, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'SEAL', '씰/고무', 8, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'SHIELD', '쉴드/클램프', 9, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'TAPE', '테이프', 10, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'TUBE', '튜브', 11, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'HOUSING', '하우징', 12, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'LABEL', '라벨', 13, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'CLIP', '클립', 14, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'ELECTRIC', '전장부품', 15, '40', '1000' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TYPE', 'GROMMET', '그로멧', 16, '40', '1000' FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME = s.CODE_NAME, t.SORT_ORDER = s.SORT_ORDER, t.USE_YN = 'Y'
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY)
  VALUES (s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y', s.COMPANY, s.PLANT_CD, 'SYSTEM')
/
COMMIT
/
