-- 기타출고 메뉴 등록 (MAT_ISSUE_OTHER)
-- 출고관리(양산, MAT_ISSUE, MATERIAL/90) 다음(95)에 배치.
-- 경로/라벨은 프론트 menuConfig(MAT_ISSUE_OTHER → /material/issue-other, menu.material.issueOther).

-- 메뉴 항목
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'MAT_ISSUE_OTHER', 'MATERIAL', 95, '40', '1000', 'system', 'system' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM MENU_CATEGORY_ITEMS WHERE MENU_CODE='MAT_ISSUE_OTHER' AND COMPANY='40' AND PLANT_CD='1000'
);
/

-- 권한 (MAT_ISSUE와 동일: MANAGER)
INSERT INTO ROLE_MENU_PERMISSIONS (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
SELECT 'MANAGER', 'MAT_ISSUE_OTHER', 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM ROLE_MENU_PERMISSIONS WHERE ROLE_CODE='MANAGER' AND MENU_CODE='MAT_ISSUE_OTHER' AND COMPANY='40' AND PLANT_CD='1000'
);
/
