DECLARE
  v_original_count NUMBER := 0;
  v_cancel_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_original_count
    FROM PRODUCT_TRANSACTIONS
   WHERE COMPANY = '40'
     AND PLANT_CD = '1000'
     AND TRANS_NO = 'PTX2026062600004'
     AND TRANS_TYPE = 'FG_OUT'
     AND REF_TYPE = 'SHIP_ORDER'
     AND REF_ID = 'SH2606260006';

  SELECT COUNT(*)
    INTO v_cancel_count
    FROM PRODUCT_TRANSACTIONS
   WHERE COMPANY = '40'
     AND PLANT_CD = '1000'
     AND TRANS_NO = 'PTX2026062600005'
     AND TRANS_TYPE = 'FG_OUT_CANCEL'
     AND REF_ID = 'SH2606260006';

  IF v_original_count = 1 AND v_cancel_count = 1 THEN
    UPDATE PRODUCT_TRANSACTIONS
       SET STATUS = 'CANCELED',
           UPDATED_BY = COALESCE(UPDATED_BY, 'codex'),
           UPDATED_AT = SYSTIMESTAMP
     WHERE COMPANY = '40'
       AND PLANT_CD = '1000'
       AND TRANS_NO = 'PTX2026062600004'
       AND STATUS = 'DONE';

    UPDATE PRODUCT_TRANSACTIONS
       SET CANCEL_REF_ID = 'PTX2026062600004',
           UPDATED_BY = COALESCE(UPDATED_BY, 'codex'),
           UPDATED_AT = SYSTIMESTAMP
     WHERE COMPANY = '40'
       AND PLANT_CD = '1000'
       AND TRANS_NO = 'PTX2026062600005'
       AND CANCEL_REF_ID IS NULL;
  END IF;

  COMMIT;
END;
/
