-- 2026-06-16 PROCESS_TYPE 공통코드 확장 + PROCESS_MASTERS 공정유형 재분류
-- 배경: PROCESS_MASTERS.PROCESS_TYPE 에 공통코드 그룹 PROCESS_TYPE 에 없는 'PRODUCTION'(20건)이
--       저장되어 있어 /master/process 배지가 raw 코드로 표시되고 수정 모달 드롭다운에서 선택 불가.
-- 조치: 누락 공정유형 4종(탈피/융착/열처리/편조제거)을 공통코드에 추가하고,
--       22개 공정을 실제 공정 성격에 맞는 유형으로 정규화.
-- 사이트: JSHANES (COMPANY=40, PLANT_CD=1000)

-- 1) 공통코드 PROCESS_TYPE 신규 4종 (재실행 안전: NOT EXISTS 가드)
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_TYPE','STRIPPING','탈피',6,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_TYPE' AND DETAIL_CODE='STRIPPING');
/
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_TYPE','WELDING','융착',7,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_TYPE' AND DETAIL_CODE='WELDING');
/
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_TYPE','HEAT','열처리',8,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_TYPE' AND DETAIL_CODE='HEAT');
/
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_TYPE','SHIELD','편조제거',9,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_TYPE' AND DETAIL_CODE='SHIELD');
/

-- 2) PROCESS_MASTERS 공정유형 재분류 (유형별 일괄 UPDATE)
-- 절단: 자동절단/자동절단탈피/절단
UPDATE PROCESS_MASTERS SET PROCESS_TYPE='CUTTING', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE IN ('ATCUT','ATCNS','PRC-CUT');
/
-- 탈피: 양단탈피/탈피
UPDATE PROCESS_MASTERS SET PROCESS_TYPE='STRIPPING', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE IN ('STRPB','PRC-STRIP');
/
-- 압착: 양단/전단/육각/후단/압착
UPDATE PROCESS_MASTERS SET PROCESS_TYPE='CRIMPING', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE IN ('CRMPB','CRMPF','HEXCP','CRMPR','PRC-CRIMP');
/
-- 융착: 후단융착
UPDATE PROCESS_MASTERS SET PROCESS_TYPE='WELDING', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE IN ('WELDR');
/
-- 편조제거
UPDATE PROCESS_MASTERS SET PROCESS_TYPE='SHIELD', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE IN ('SHDRM');
/
-- 열처리: 튜브열처리
UPDATE PROCESS_MASTERS SET PROCESS_TYPE='HEAT', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE IN ('TUBHT');
/
-- 조립: 자재장착/부자재장착/서브조립/배판작업/조립
UPDATE PROCESS_MASTERS SET PROCESS_TYPE='ASSEMBLY', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE IN ('MTASY','AUXMT','SASSY','TAPPN','MASSY');
/
-- 검사: 단자검사/통합검사/외관검사/도통검사
UPDATE PROCESS_MASTERS SET PROCESS_TYPE='INSPECTION', UPDATED_BY='claude', UPDATED_AT=SYSTIMESTAMP
WHERE PROCESS_CODE IN ('TINSP','AINSP','OINSP','PRC-TEST');
/
