BEGIN
  UPDATE ROUTING_PROCESSES SET ISSUE_SG_LABEL_YN = 'Y'
   WHERE ROUTING_CODE = 'HNS02_FA' AND PROCESS_CODE = 'TAPPN' AND COMPANY = '40' AND PLANT_CD = '1000';
  UPDATE ROUTING_PROCESSES SET ISSUE_FG_LABEL_YN = 'Y'
   WHERE ROUTING_CODE = 'RT-HNS02' AND PROCESS_CODE = 'SASSY' AND COMPANY = '40' AND PLANT_CD = '1000';
  COMMIT;
END;
/
