-- =====================================================================
-- 2026-06-10  워크플로우 공통코드/엔티티 정리
-- 1. JUDGE_YN 공통코드 그룹 추가 (Y=합격, N=불합격)
-- 2. INSPECT_TYPE 그룹에 INITIAL/RETEST 추가
-- 3. IQC_LOGS 컬럼 코멘트 정리 (PASS/FAIL 직접 명시)
-- 대상: JSHANES (company=40 / plant=1000)
-- =====================================================================

-- 1) JUDGE_YN 공통코드 등록 (멱등)
MERGE INTO COM_CODES t
USING (
  SELECT 'JUDGE_YN' AS GROUP_CODE, 'Y' AS DETAIL_CODE, '합격' AS CODE_NAME,
         1 AS SORT_ORDER, 'Y' AS USE_YN,
         '40' AS COMPANY, '1000' AS PLANT_CD FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME = s.CODE_NAME, t.SORT_ORDER = s.SORT_ORDER, t.USE_YN = s.USE_YN
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY)
  VALUES (s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, s.USE_YN, s.COMPANY, s.PLANT_CD, 'SYSTEM');
/

MERGE INTO COM_CODES t
USING (
  SELECT 'JUDGE_YN' AS GROUP_CODE, 'N' AS DETAIL_CODE, '불합격' AS CODE_NAME,
         2 AS SORT_ORDER, 'Y' AS USE_YN,
         '40' AS COMPANY, '1000' AS PLANT_CD FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME = s.CODE_NAME, t.SORT_ORDER = s.SORT_ORDER, t.USE_YN = s.USE_YN
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY)
  VALUES (s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, s.USE_YN, s.COMPANY, s.PLANT_CD, 'SYSTEM');
/

-- 2) INSPECT_TYPE 그룹에 INITIAL/RETEST 추가 (기존 4건 + 신규 2건)
MERGE INTO COM_CODES t
USING (
  SELECT 'INSPECT_TYPE' AS GROUP_CODE, 'INITIAL' AS DETAIL_CODE, '초기검사' AS CODE_NAME,
         5 AS SORT_ORDER, 'Y' AS USE_YN,
         '40' AS COMPANY, '1000' AS PLANT_CD FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME = s.CODE_NAME, t.SORT_ORDER = s.SORT_ORDER, t.USE_YN = s.USE_YN
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY)
  VALUES (s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, s.USE_YN, s.COMPANY, s.PLANT_CD, 'SYSTEM');
/

MERGE INTO COM_CODES t
USING (
  SELECT 'INSPECT_TYPE' AS GROUP_CODE, 'RETEST' AS DETAIL_CODE, '재검사' AS CODE_NAME,
         6 AS SORT_ORDER, 'Y' AS USE_YN,
         '40' AS COMPANY, '1000' AS PLANT_CD FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME = s.CODE_NAME, t.SORT_ORDER = s.SORT_ORDER, t.USE_YN = s.USE_YN
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY)
  VALUES (s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, s.USE_YN, s.COMPANY, s.PLANT_CD, 'SYSTEM');
/

-- 3) IQC_LOGS 컬럼 코멘트 정리 (기존 JUDGE_YN 참조 → PASS/FAIL 직접 명시)
COMMENT ON COLUMN IQC_LOGS.RESULT IS '검사결과 (PASS=합격, FAIL=불합격)';
/

COMMENT ON COLUMN IQC_LOGS.INSPECT_TYPE IS '검사유형 (INITIAL=초기검사, RETEST=재검사, CONTINUITY=도통, INSULATION=절연, HI_POT=내압, VISUAL=외관)';
/

COMMIT;
/
