-- 불량창고입고 화면 테스트 seed
-- 목적: /product/defect-transfer 등록 패널에서 공정 WIP 불량 제품재고 후보가 보이도록 한다.
-- 대상 DB: JSHANES, COMPANY='40', PLANT_CD='1000'
-- 재실행 시 같은 수량으로 복원된다.

MERGE INTO PRODUCT_STOCKS t
USING (
  SELECT
    '40' AS COMPANY,
    '1000' AS PLANT_CD,
    'SFG_WIP' AS WAREHOUSE_CODE,
    'N91H00-X9800-C1' AS ITEM_CODE,
    'SEMI_PRODUCT' AS ITEM_TYPE,
    'DEFECT' AS QUALITY_STATUS,
    8 AS QTY
  FROM dual
) s
ON (
  t.COMPANY = s.COMPANY
  AND t.PLANT_CD = s.PLANT_CD
  AND t.WAREHOUSE_CODE = s.WAREHOUSE_CODE
  AND t.ITEM_CODE = s.ITEM_CODE
  AND t.QUALITY_STATUS = s.QUALITY_STATUS
)
WHEN MATCHED THEN
  UPDATE SET
    t.ITEM_TYPE = s.ITEM_TYPE,
    t.QTY = s.QTY,
    t.RESERVED_QTY = 0,
    t.AVAILABLE_QTY = s.QTY,
    t.STATUS = 'NORMAL',
    t.UPDATED_AT = SYSTIMESTAMP,
    t.UPDATED_BY = 'test-seed'
WHEN NOT MATCHED THEN
  INSERT (
    WAREHOUSE_CODE, ITEM_CODE, ITEM_TYPE, QUALITY_STATUS,
    QTY, RESERVED_QTY, AVAILABLE_QTY, STATUS,
    COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, VERSION
  )
  VALUES (
    s.WAREHOUSE_CODE, s.ITEM_CODE, s.ITEM_TYPE, s.QUALITY_STATUS,
    s.QTY, 0, s.QTY, 'NORMAL',
    s.COMPANY, s.PLANT_CD, SYSTIMESTAMP, 'test-seed', SYSTIMESTAMP, 'test-seed', 1
  )
/

MERGE INTO PRODUCT_STOCKS t
USING (
  SELECT
    '40' AS COMPANY,
    '1000' AS PLANT_CD,
    'FG_WIP' AS WAREHOUSE_CODE,
    'N91H00-X9800' AS ITEM_CODE,
    'FINISHED' AS ITEM_TYPE,
    'DEFECT' AS QUALITY_STATUS,
    5 AS QTY
  FROM dual
) s
ON (
  t.COMPANY = s.COMPANY
  AND t.PLANT_CD = s.PLANT_CD
  AND t.WAREHOUSE_CODE = s.WAREHOUSE_CODE
  AND t.ITEM_CODE = s.ITEM_CODE
  AND t.QUALITY_STATUS = s.QUALITY_STATUS
)
WHEN MATCHED THEN
  UPDATE SET
    t.ITEM_TYPE = s.ITEM_TYPE,
    t.QTY = s.QTY,
    t.RESERVED_QTY = 0,
    t.AVAILABLE_QTY = s.QTY,
    t.STATUS = 'NORMAL',
    t.UPDATED_AT = SYSTIMESTAMP,
    t.UPDATED_BY = 'test-seed'
WHEN NOT MATCHED THEN
  INSERT (
    WAREHOUSE_CODE, ITEM_CODE, ITEM_TYPE, QUALITY_STATUS,
    QTY, RESERVED_QTY, AVAILABLE_QTY, STATUS,
    COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, VERSION
  )
  VALUES (
    s.WAREHOUSE_CODE, s.ITEM_CODE, s.ITEM_TYPE, s.QUALITY_STATUS,
    s.QTY, 0, s.QTY, 'NORMAL',
    s.COMPANY, s.PLANT_CD, SYSTIMESTAMP, 'test-seed', SYSTIMESTAMP, 'test-seed', 1
  )
/
