DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'DEFECT_CATEGORY_MASTERS';
  IF v_count = 0 THEN
    RETURN;
  END IF;

  EXECUTE IMMEDIATE 'ALTER TABLE DEFECT_CATEGORY_MASTERS DISABLE CONSTRAINT FK_DEFECT_CATEGORY_PARENT';

  EXECUTE IMMEDIATE q'[
    MERGE INTO COM_CODES d
    USING (
      WITH tenants AS (
        SELECT DISTINCT COMPANY, PLANT_CD FROM DEFECT_CATEGORY_MASTERS
        UNION
        SELECT '40' COMPANY, '1000' PLANT_CD FROM DUAL
      ),
      model_groups AS (
        SELECT 'LV' DETAIL_CODE, '저전압' CODE_NAME, 10 SORT_ORDER FROM DUAL UNION ALL
        SELECT 'HV', '고전압', 20 FROM DUAL
      )
      SELECT t.COMPANY, t.PLANT_CD, mg.*
      FROM tenants t CROSS JOIN model_groups mg
    ) s
    ON (
      d.COMPANY = s.COMPANY
      AND d.PLANT_CD = s.PLANT_CD
      AND d.GROUP_CODE = 'DEFECT_MODEL_GROUP'
      AND d.DETAIL_CODE = s.DETAIL_CODE
    )
    WHEN MATCHED THEN UPDATE SET
      d.CODE_NAME = s.CODE_NAME,
      d.SORT_ORDER = s.SORT_ORDER,
      d.USE_YN = 'Y',
      d.UPDATED_BY = 'migration',
      d.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN,
      COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
    ) VALUES (
      'DEFECT_MODEL_GROUP', s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y',
      s.COMPANY, s.PLANT_CD, 'migration', 'migration', SYSTIMESTAMP, SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE q'[
    MERGE INTO DEFECT_CATEGORY_MASTERS d
    USING (
      WITH tenants AS (
        SELECT DISTINCT COMPANY, PLANT_CD FROM DEFECT_CATEGORY_MASTERS
        UNION
        SELECT '40' COMPANY, '1000' PLANT_CD FROM DUAL
      ),
      stages AS (
        SELECT 'IQC' CATEGORY_CODE, 'IQC' CATEGORY_NAME, 10 SORT_ORDER FROM DUAL UNION ALL
        SELECT 'LQC', 'LQC', 20 FROM DUAL UNION ALL
        SELECT 'OQC', 'OQC', 30 FROM DUAL
      ),
      model_groups AS (
        SELECT
          c.COMPANY,
          c.PLANT_CD,
          c.DETAIL_CODE MODEL_GROUP,
          c.CODE_NAME MODEL_GROUP_NAME,
          ROW_NUMBER() OVER (PARTITION BY c.COMPANY, c.PLANT_CD ORDER BY c.SORT_ORDER, c.DETAIL_CODE) SORT_ORDER
        FROM COM_CODES c
        WHERE c.GROUP_CODE = 'DEFECT_MODEL_GROUP'
          AND c.USE_YN = 'Y'
        UNION ALL
        SELECT t.COMPANY, t.PLANT_CD, 'LV', '저전압', 10
        FROM tenants t
        WHERE NOT EXISTS (
          SELECT 1
          FROM COM_CODES c
          WHERE c.COMPANY = t.COMPANY
            AND c.PLANT_CD = t.PLANT_CD
            AND c.GROUP_CODE = 'DEFECT_MODEL_GROUP'
            AND c.USE_YN = 'Y'
            AND c.DETAIL_CODE = 'LV'
        )
        UNION ALL
        SELECT t.COMPANY, t.PLANT_CD, 'HV', '고전압', 20
        FROM tenants t
        WHERE NOT EXISTS (
          SELECT 1
          FROM COM_CODES c
          WHERE c.COMPANY = t.COMPANY
            AND c.PLANT_CD = t.PLANT_CD
            AND c.GROUP_CODE = 'DEFECT_MODEL_GROUP'
            AND c.USE_YN = 'Y'
            AND c.DETAIL_CODE = 'HV'
        )
      ),
      defect_kinds AS (
        SELECT 'FUNCTION' KIND_CODE, '기능' KIND_NAME, 10 SORT_ORDER FROM DUAL UNION ALL
        SELECT 'APPEARANCE', '외관', 20 FROM DUAL UNION ALL
        SELECT 'ETC', '기타', 30 FROM DUAL
      ),
      categories AS (
        SELECT
          t.COMPANY,
          t.PLANT_CD,
          s.CATEGORY_CODE,
          s.CATEGORY_NAME,
          1 LEVEL_NO,
          CAST(NULL AS VARCHAR2(50)) PARENT_CATEGORY_CODE,
          s.SORT_ORDER
        FROM tenants t CROSS JOIN stages s
        UNION ALL
        SELECT
          mg.COMPANY,
          mg.PLANT_CD,
          s.CATEGORY_CODE || '_' || mg.MODEL_GROUP,
          mg.MODEL_GROUP_NAME,
          2,
          s.CATEGORY_CODE,
          s.SORT_ORDER * 100 + mg.SORT_ORDER
        FROM model_groups mg CROSS JOIN stages s
        UNION ALL
        SELECT
          mg.COMPANY,
          mg.PLANT_CD,
          s.CATEGORY_CODE || '_' || mg.MODEL_GROUP || '_' || k.KIND_CODE,
          k.KIND_NAME,
          3,
          s.CATEGORY_CODE || '_' || mg.MODEL_GROUP,
          s.SORT_ORDER * 1000 + mg.SORT_ORDER * 10 + k.SORT_ORDER
        FROM model_groups mg CROSS JOIN stages s CROSS JOIN defect_kinds k
      )
      SELECT * FROM categories
    ) s
    ON (d.COMPANY = s.COMPANY AND d.PLANT_CD = s.PLANT_CD AND d.CATEGORY_CODE = s.CATEGORY_CODE)
    WHEN MATCHED THEN UPDATE SET
      d.CATEGORY_NAME = s.CATEGORY_NAME,
      d.LEVEL_NO = s.LEVEL_NO,
      d.PARENT_CATEGORY_CODE = s.PARENT_CATEGORY_CODE,
      d.SORT_ORDER = s.SORT_ORDER,
      d.USE_YN = 'Y',
      d.UPDATED_BY = 'migration',
      d.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      COMPANY, PLANT_CD, CATEGORY_CODE, CATEGORY_NAME, LEVEL_NO, PARENT_CATEGORY_CODE,
      SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
    ) VALUES (
      s.COMPANY, s.PLANT_CD, s.CATEGORY_CODE, s.CATEGORY_NAME, s.LEVEL_NO, s.PARENT_CATEGORY_CODE,
      s.SORT_ORDER, 'Y', 'migration', 'migration', SYSTIMESTAMP, SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE 'ALTER TABLE DEFECT_CATEGORY_MASTERS ENABLE CONSTRAINT FK_DEFECT_CATEGORY_PARENT';

  UPDATE DEFECT_CODE_MASTERS
     SET CATEGORY_CODE = CASE
           WHEN DEFECT_CODE IN ('MATERIAL', 'MAT') THEN 'IQC_LV_ETC'
           WHEN DEFECT_CODE IN ('WORK', 'ASM', 'WELD') THEN 'LQC_LV_ETC'
           WHEN DEFECT_CODE = 'FUNC' THEN 'OQC_LV_FUNCTION'
           WHEN DEFECT_CODE IN ('APP', 'MARK', 'BURR', 'CRACK', 'DIM') THEN 'OQC_LV_APPEARANCE'
           ELSE 'OQC_LV_ETC'
         END,
         DEFECT_SCOPE = CASE
           WHEN DEFECT_CODE IN ('MATERIAL', 'MAT') THEN 'RAW_MATERIAL'
           WHEN DEFECT_CODE IN ('WORK', 'ASM', 'WELD') THEN 'PROCESS'
           WHEN DEFECT_CODE = 'ETC' THEN 'COMMON'
           ELSE 'PRODUCT'
         END,
         UPDATED_BY = 'migration',
         UPDATED_AT = SYSTIMESTAMP
   WHERE COMPANY = '40'
     AND PLANT_CD = '1000';

  DELETE FROM DEFECT_CODE_PRODUCT_TYPES
   WHERE COMPANY = '40'
     AND PLANT_CD = '1000'
     AND PRODUCT_TYPE NOT IN (
       SELECT DETAIL_CODE
       FROM COM_CODES
       WHERE GROUP_CODE = 'DEFECT_MODEL_GROUP'
         AND COMPANY = '40'
         AND PLANT_CD = '1000'
     );

  MERGE INTO DEFECT_CODE_PRODUCT_TYPES d
  USING (
    SELECT
      COMPANY,
      PLANT_CD,
      DEFECT_CODE,
      'LV' AS PRODUCT_TYPE
    FROM DEFECT_CODE_MASTERS
    WHERE COMPANY = '40'
      AND PLANT_CD = '1000'
  ) s
  ON (
    d.COMPANY = s.COMPANY
    AND d.PLANT_CD = s.PLANT_CD
    AND d.DEFECT_CODE = s.DEFECT_CODE
    AND d.PRODUCT_TYPE = s.PRODUCT_TYPE
  )
  WHEN NOT MATCHED THEN INSERT (
    COMPANY, PLANT_CD, DEFECT_CODE, PRODUCT_TYPE, CREATED_BY, CREATED_AT
  ) VALUES (
    s.COMPANY, s.PLANT_CD, s.DEFECT_CODE, s.PRODUCT_TYPE, 'migration', SYSTIMESTAMP
  );

  EXECUTE IMMEDIATE q'[COMMENT ON TABLE DEFECT_CODE_PRODUCT_TYPES IS '불량코드 모델구분별 적용 매핑']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN DEFECT_CODE_PRODUCT_TYPES.PRODUCT_TYPE IS '모델구분 코드: DEFECT_MODEL_GROUP']';

  UPDATE DEFECT_CATEGORY_MASTERS
     SET USE_YN = 'N',
         UPDATED_BY = 'migration',
         UPDATED_AT = SYSTIMESTAMP
   WHERE COMPANY = '40'
     AND PLANT_CD = '1000'
     AND CATEGORY_CODE IN (
       'APPEARANCE', 'FUNCTION', 'PROCESS', 'MATERIAL', 'ETC',
       'APP_RAW', 'APP_PRODUCT', 'FUNC_PRODUCT', 'PROC_WORK', 'MAT_RAW', 'ETC_COMMON',
       'APP_RAW_WIRE', 'APP_PRODUCT_FINISH', 'FUNC_PRODUCT_ELEC', 'PROC_ASSEMBLY',
       'PROC_WELD', 'MAT_RAW_QUALITY', 'ETC_COMMON_ETC',
       'IQC_HARNESS', 'LQC_HARNESS', 'OQC_HARNESS', 'IQC_WIRE',
       'IQC_HARNESS_FUNCTION', 'IQC_HARNESS_APPEARANCE', 'IQC_HARNESS_ETC',
       'LQC_HARNESS_FUNCTION', 'LQC_HARNESS_APPEARANCE', 'LQC_HARNESS_ETC',
       'OQC_HARNESS_FUNCTION', 'OQC_HARNESS_APPEARANCE', 'OQC_HARNESS_ETC',
       'IQC_WIRE_FUNCTION', 'IQC_WIRE_APPEARANCE', 'IQC_WIRE_ETC'
     );

  UPDATE DEFECT_CATEGORY_MASTERS
     SET USE_YN = 'N',
         UPDATED_BY = 'migration',
         UPDATED_AT = SYSTIMESTAMP
   WHERE COMPANY = '40'
     AND PLANT_CD = '1000'
     AND USE_YN = 'Y'
     AND LEVEL_NO IN (2, 3)
     AND (
       PARENT_CATEGORY_CODE IN ('IQC', 'LQC', 'OQC')
       OR PARENT_CATEGORY_CODE LIKE 'IQC_%'
       OR PARENT_CATEGORY_CODE LIKE 'LQC_%'
       OR PARENT_CATEGORY_CODE LIKE 'OQC_%'
     )
     AND CATEGORY_CODE NOT IN (
       'IQC_LV', 'IQC_HV',
       'LQC_LV', 'LQC_HV',
       'OQC_LV', 'OQC_HV',
       'IQC_LV_FUNCTION', 'IQC_LV_APPEARANCE', 'IQC_LV_ETC',
       'IQC_HV_FUNCTION', 'IQC_HV_APPEARANCE', 'IQC_HV_ETC',
       'LQC_LV_FUNCTION', 'LQC_LV_APPEARANCE', 'LQC_LV_ETC',
       'LQC_HV_FUNCTION', 'LQC_HV_APPEARANCE', 'LQC_HV_ETC',
       'OQC_LV_FUNCTION', 'OQC_LV_APPEARANCE', 'OQC_LV_ETC',
       'OQC_HV_FUNCTION', 'OQC_HV_APPEARANCE', 'OQC_HV_ETC'
     );

  COMMIT;
END;
/
