-- WAREHOUSES에 설비코드 컬럼 추가 (설비단위 공정창고용)
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE WAREHOUSES ADD (EQUIP_CODE VARCHAR2(50))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF; -- ORA-01430: 이미 존재 시 무시
END;
/
