-- Routing-based N91 comparison model.
-- BOM shape: FINISHED N91H00-X9800-R -> one SEMI_PRODUCT N91H00-X9800-R-S -> raw materials.
-- Lower production stages are represented by ROUTING_PROCESSES.JOB_ORDER_YN, while material demand remains visible under the SEMI_PRODUCT BOM.

MERGE INTO ITEM_MASTERS i
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'N91H00-X9800-R' ITEM_CODE, 'N91H00-X9800-R 라우팅기준 완제품' ITEM_NAME,
         'N91H00-X9800-R' PART_NO, 'FINISHED' ITEM_TYPE, 'HARNESS' PRODUCT_TYPE, 'EA' UNIT
  FROM DUAL
) s
ON (i.COMPANY = s.COMPANY AND i.PLANT_CD = s.PLANT_CD AND i.ITEM_CODE = s.ITEM_CODE)
WHEN MATCHED THEN UPDATE SET
  i.ITEM_NAME = s.ITEM_NAME,
  i.PART_NO = s.PART_NO,
  i.ITEM_TYPE = s.ITEM_TYPE,
  i.PRODUCT_TYPE = s.PRODUCT_TYPE,
  i.UNIT = s.UNIT,
  i.USE_YN = 'Y',
  i.UPDATED_BY = 'codex',
  i.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, PART_NO, ITEM_TYPE, PRODUCT_TYPE, UNIT,
  LEAD_TIME, SAFETY_STOCK, BOX_QTY, IQC_FLAG, TACT_TIME, EXPIRY_DATE, USE_YN,
  CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ITEM_CODE, s.ITEM_NAME, s.PART_NO, s.ITEM_TYPE, s.PRODUCT_TYPE, s.UNIT,
  0, 0, 10, 'N', 0, 0, 'Y',
  'codex', 'codex'
);

MERGE INTO ITEM_MASTERS i
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'N91H00-X9800-R-S' ITEM_CODE, 'N91H00-X9800-R-S 라우팅기준 반제품' ITEM_NAME,
         'N91H00-X9800-R-S' PART_NO, 'SEMI_PRODUCT' ITEM_TYPE, 'SUB_ASSY' PRODUCT_TYPE, 'EA' UNIT
  FROM DUAL
) s
ON (i.COMPANY = s.COMPANY AND i.PLANT_CD = s.PLANT_CD AND i.ITEM_CODE = s.ITEM_CODE)
WHEN MATCHED THEN UPDATE SET
  i.ITEM_NAME = s.ITEM_NAME,
  i.PART_NO = s.PART_NO,
  i.ITEM_TYPE = s.ITEM_TYPE,
  i.PRODUCT_TYPE = s.PRODUCT_TYPE,
  i.UNIT = s.UNIT,
  i.USE_YN = 'Y',
  i.UPDATED_BY = 'codex',
  i.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, PART_NO, ITEM_TYPE, PRODUCT_TYPE, UNIT,
  LEAD_TIME, SAFETY_STOCK, BOX_QTY, IQC_FLAG, TACT_TIME, EXPIRY_DATE, USE_YN,
  CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ITEM_CODE, s.ITEM_NAME, s.PART_NO, s.ITEM_TYPE, s.PRODUCT_TYPE, s.UNIT,
  0, 0, 10, 'N', 0, 0, 'Y',
  'codex', 'codex'
);

MERGE INTO BOM_MASTERS b
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'N91H00-X9800-R' PARENT_ITEM_CODE, 'N91H00-X9800-R-S' CHILD_ITEM_CODE,
         1 QTY_PER, 10 SEQ, 'A' REVISION
  FROM DUAL
) s
ON (
  b.COMPANY = s.COMPANY
  AND b.PLANT_CD = s.PLANT_CD
  AND b.PARENT_ITEM_CODE = s.PARENT_ITEM_CODE
  AND b.CHILD_ITEM_CODE = s.CHILD_ITEM_CODE
  AND b.REVISION = s.REVISION
)
WHEN MATCHED THEN UPDATE SET
  b.QTY_PER = s.QTY_PER,
  b.SEQ = s.SEQ,
  b.VALID_FROM = DATE '2026-06-28',
  b.VALID_TO = DATE '2099-12-31',
  b.USE_YN = 'Y',
  b.REMARK = '라우팅 기준 비교모델: 완제품 BOM은 반제품 1개를 보유',
  b.UPDATED_BY = 'codex',
  b.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, PARENT_ITEM_CODE, CHILD_ITEM_CODE, QTY_PER, SEQ, REVISION, VALID_FROM, VALID_TO, USE_YN, REMARK, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.PARENT_ITEM_CODE, s.CHILD_ITEM_CODE, s.QTY_PER, s.SEQ, s.REVISION, DATE '2026-06-28', DATE '2099-12-31', 'Y',
  '라우팅 기준 비교모델: 완제품 BOM은 반제품 1개를 보유', 'codex', 'codex'
);

MERGE INTO BOM_MASTERS b
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'N91H00-X9800-R-S' PARENT_ITEM_CODE, '1SH21A7A09' CHILD_ITEM_CODE,
         0.72 QTY_PER, 10 SEQ, 'A' REVISION, 'ATCNS' OPER FROM DUAL
  UNION ALL SELECT '40','1000','N91H00-X9800-R-S','TKEG1WFSCD',2,20,'A','CRMPF' FROM DUAL
  UNION ALL SELECT '40','1000','N91H00-X9800-R-S','EKEESNATBC',1,30,'A','CRMPF' FROM DUAL
  UNION ALL SELECT '40','1000','N91H00-X9800-R-S','HTEAVCW002MA',1,40,'A','CONAS' FROM DUAL
  UNION ALL SELECT '40','1000','N91H00-X9800-R-S','RTEBW002MA',1,50,'A','CONAS' FROM DUAL
  UNION ALL SELECT '40','1000','N91H00-X9800-R-S','VSFT1-201',2,60,'A','SACMB' FROM DUAL
  UNION ALL SELECT '40','1000','N91H00-X9800-R-S','6TPP210190',1.2,70,'A','SACMB' FROM DUAL
) s
ON (
  b.COMPANY = s.COMPANY
  AND b.PLANT_CD = s.PLANT_CD
  AND b.PARENT_ITEM_CODE = s.PARENT_ITEM_CODE
  AND b.CHILD_ITEM_CODE = s.CHILD_ITEM_CODE
  AND b.REVISION = s.REVISION
)
WHEN MATCHED THEN UPDATE SET
  b.QTY_PER = s.QTY_PER,
  b.SEQ = s.SEQ,
  b.OPER = s.OPER,
  b.VALID_FROM = DATE '2026-06-28',
  b.VALID_TO = DATE '2099-12-31',
  b.USE_YN = 'Y',
  b.REMARK = '라우팅 기준 반제품 BOM 자재',
  b.UPDATED_BY = 'codex',
  b.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, PARENT_ITEM_CODE, CHILD_ITEM_CODE, QTY_PER, SEQ, REVISION, OPER, VALID_FROM, VALID_TO, USE_YN, REMARK, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.PARENT_ITEM_CODE, s.CHILD_ITEM_CODE, s.QTY_PER, s.SEQ, s.REVISION, s.OPER, DATE '2026-06-28', DATE '2099-12-31', 'Y',
  '라우팅 기준 반제품 BOM 자재', 'codex', 'codex'
);

MERGE INTO ROUTING_GROUPS g
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R' ROUTING_CODE,
         'N91H00-X9800-R 완제품 라우팅' ROUTING_NAME, 'N91H00-X9800-R' ITEM_CODE
  FROM DUAL
) s
ON (g.COMPANY = s.COMPANY AND g.PLANT_CD = s.PLANT_CD AND g.ROUTING_CODE = s.ROUTING_CODE)
WHEN MATCHED THEN UPDATE SET
  g.ROUTING_NAME = s.ROUTING_NAME,
  g.ITEM_CODE = s.ITEM_CODE,
  g.DESCRIPTION = '라우팅 기준 비교모델 완제품 라우팅',
  g.USE_YN = 'Y',
  g.UPDATED_BY = 'codex',
  g.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, ROUTING_NAME, ITEM_CODE, DESCRIPTION, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.ROUTING_NAME, s.ITEM_CODE, '라우팅 기준 비교모델 완제품 라우팅', 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_GROUPS g
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R-S' ROUTING_CODE,
         'N91H00-X9800-R-S 반제품 라우팅' ROUTING_NAME, 'N91H00-X9800-R-S' ITEM_CODE
  FROM DUAL
) s
ON (g.COMPANY = s.COMPANY AND g.PLANT_CD = s.PLANT_CD AND g.ROUTING_CODE = s.ROUTING_CODE)
WHEN MATCHED THEN UPDATE SET
  g.ROUTING_NAME = s.ROUTING_NAME,
  g.ITEM_CODE = s.ITEM_CODE,
  g.DESCRIPTION = '하위 반제품 단계를 BOM이 아닌 라우팅 작업지시로 표현',
  g.USE_YN = 'Y',
  g.UPDATED_BY = 'codex',
  g.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, ROUTING_NAME, ITEM_CODE, DESCRIPTION, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.ROUTING_NAME, s.ITEM_CODE, '하위 반제품 단계를 BOM이 아닌 라우팅 작업지시로 표현', 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R' ROUTING_CODE, 10 SEQ,
         'CONAS' PROCESS_CODE, '커넥터체결' PROCESS_NAME, 'ASSEMBLY' PROCESS_TYPE, 'Y' JOB_ORDER_YN,
         'N' SAMPLE_INSPECT_YN, 'NONE' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 30 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'N', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R' ROUTING_CODE, 20 SEQ,
         'FINSP' PROCESS_CODE, '최종검사' PROCESS_NAME, 'INSPECTION' PROCESS_TYPE, 'N' JOB_ORDER_YN,
         'Y' SAMPLE_INSPECT_YN, 'NONE' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 20 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'Y', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R' ROUTING_CODE, 30 SEQ,
         'FINSH' PROCESS_CODE, '마무리' PROCESS_NAME, 'ASSEMBLY' PROCESS_TYPE, 'Y' JOB_ORDER_YN,
         'N' SAMPLE_INSPECT_YN, 'FG' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 25 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'N', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R-S' ROUTING_CODE, 10 SEQ,
         'ATCNS' PROCESS_CODE, '자동절단탈피' PROCESS_NAME, 'CUTTING' PROCESS_TYPE, 'Y' JOB_ORDER_YN,
         'N' SAMPLE_INSPECT_YN, 'NONE' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 18 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'N', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R-S' ROUTING_CODE, 20 SEQ,
         'CRMPF' PROCESS_CODE, '전단압착' PROCESS_NAME, 'CRIMPING' PROCESS_TYPE, 'Y' JOB_ORDER_YN,
         'N' SAMPLE_INSPECT_YN, 'NONE' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 24 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'N', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R-S' ROUTING_CODE, 30 SEQ,
         'CRINS' PROCESS_CODE, '절압물검사' PROCESS_NAME, 'INSPECTION' PROCESS_TYPE, 'N' JOB_ORDER_YN,
         'Y' SAMPLE_INSPECT_YN, 'NONE' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 12 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'Y', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R-S' ROUTING_CODE, 40 SEQ,
         'CONAS' PROCESS_CODE, '커넥터체결' PROCESS_NAME, 'ASSEMBLY' PROCESS_TYPE, 'Y' JOB_ORDER_YN,
         'N' SAMPLE_INSPECT_YN, 'NONE' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 30 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'N', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R-S' ROUTING_CODE, 50 SEQ,
         'SGINS' PROCESS_CODE, '반제품검사' PROCESS_NAME, 'INSPECTION' PROCESS_TYPE, 'N' JOB_ORDER_YN,
         'Y' SAMPLE_INSPECT_YN, 'NONE' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 15 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'Y', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_PROCESSES p
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R-S' ROUTING_CODE, 60 SEQ,
         'SACMB' PROCESS_CODE, '반제품조합' PROCESS_NAME, 'ASSEMBLY' PROCESS_TYPE, 'Y' JOB_ORDER_YN,
         'N' SAMPLE_INSPECT_YN, 'SG' ISSUE_LABEL_TYPE, 'IN_HOUSE' EXECUTION_TYPE, 35 STD_TIME
  FROM DUAL
) s
ON (p.COMPANY = s.COMPANY AND p.PLANT_CD = s.PLANT_CD AND p.ROUTING_CODE = s.ROUTING_CODE AND p.SEQ = s.SEQ)
WHEN MATCHED THEN UPDATE SET
  p.PROCESS_CODE = s.PROCESS_CODE, p.PROCESS_NAME = s.PROCESS_NAME, p.PROCESS_TYPE = s.PROCESS_TYPE,
  p.JOB_ORDER_YN = s.JOB_ORDER_YN, p.SAMPLE_INSPECT_YN = s.SAMPLE_INSPECT_YN, p.ISSUE_LABEL_TYPE = s.ISSUE_LABEL_TYPE,
  p.EXECUTION_TYPE = s.EXECUTION_TYPE, p.STD_TIME = s.STD_TIME, p.USE_YN = 'Y',
  p.UPDATED_BY = 'codex', p.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE,
  JOB_ORDER_YN, SAMPLE_INSPECT_YN, ISSUE_LABEL_TYPE, EXECUTION_TYPE, STD_TIME,
  QC_SELF_YN, INSPECT_METHOD, DESTRUCTIVE_YN, SAMPLE_QTY, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.PROCESS_CODE, s.PROCESS_NAME, s.PROCESS_TYPE,
  s.JOB_ORDER_YN, s.SAMPLE_INSPECT_YN, s.ISSUE_LABEL_TYPE, s.EXECUTION_TYPE, s.STD_TIME,
  'N', 'DIRECT', 'N', 1, 'Y', 'codex', 'codex'
);

MERGE INTO ROUTING_MATERIALS m
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'RT_N91H00-X9800-R-S' ROUTING_CODE, 10 SEQ, '1SH21A7A09' CHILD_ITEM_CODE, 0.72 ALLOC_QTY, 'BACKFLUSH' ISSUE_METHOD FROM DUAL
  UNION ALL SELECT '40','1000','RT_N91H00-X9800-R-S',20,'TKEG1WFSCD',2,'BACKFLUSH' FROM DUAL
  UNION ALL SELECT '40','1000','RT_N91H00-X9800-R-S',20,'EKEESNATBC',1,'BACKFLUSH' FROM DUAL
  UNION ALL SELECT '40','1000','RT_N91H00-X9800-R-S',40,'HTEAVCW002MA',1,'BACKFLUSH' FROM DUAL
  UNION ALL SELECT '40','1000','RT_N91H00-X9800-R-S',40,'RTEBW002MA',1,'BACKFLUSH' FROM DUAL
  UNION ALL SELECT '40','1000','RT_N91H00-X9800-R-S',60,'VSFT1-201',2,'BACKFLUSH' FROM DUAL
  UNION ALL SELECT '40','1000','RT_N91H00-X9800-R-S',60,'6TPP210190',1.2,'BACKFLUSH' FROM DUAL
) s
ON (
  m.COMPANY = s.COMPANY
  AND m.PLANT_CD = s.PLANT_CD
  AND m.ROUTING_CODE = s.ROUTING_CODE
  AND m.SEQ = s.SEQ
  AND m.CHILD_ITEM_CODE = s.CHILD_ITEM_CODE
)
WHEN MATCHED THEN UPDATE SET
  m.ALLOC_QTY = s.ALLOC_QTY,
  m.ISSUE_METHOD = s.ISSUE_METHOD,
  m.USE_YN = 'Y',
  m.UPDATED_BY = 'codex',
  m.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ROUTING_CODE, SEQ, CHILD_ITEM_CODE, ALLOC_QTY, ISSUE_METHOD, USE_YN, CREATED_BY, UPDATED_BY
) VALUES (
  s.COMPANY, s.PLANT_CD, s.ROUTING_CODE, s.SEQ, s.CHILD_ITEM_CODE, s.ALLOC_QTY, s.ISSUE_METHOD, 'Y', 'codex', 'codex'
);

COMMIT;
