DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'AQL_STANDARDS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE AQL_STANDARDS (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        AQL_CODE VARCHAR2(50) NOT NULL,
        AQL_NAME VARCHAR2(100) NOT NULL,
        INSPECTION_LEVEL VARCHAR2(20),
        AQL_VALUE NUMBER(8,3),
        USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        REMARK VARCHAR2(500),
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_AQL_STANDARDS PRIMARY KEY (COMPANY, PLANT_CD, AQL_CODE),
        CONSTRAINT CK_AQL_STANDARDS_USE_YN CHECK (USE_YN IN ('Y', 'N'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'AQL_SAMPLING_RULES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE AQL_SAMPLING_RULES (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        AQL_CODE VARCHAR2(50) NOT NULL,
        LOT_QTY_FROM NUMBER NOT NULL,
        LOT_QTY_TO NUMBER NOT NULL,
        SAMPLE_SIZE NUMBER NOT NULL,
        ACCEPT_QTY NUMBER NOT NULL,
        REJECT_QTY NUMBER NOT NULL,
        SORT_ORDER NUMBER,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_AQL_SAMPLING_RULES PRIMARY KEY (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM),
        CONSTRAINT FK_AQL_RULES_STANDARD FOREIGN KEY (COMPANY, PLANT_CD, AQL_CODE)
          REFERENCES AQL_STANDARDS (COMPANY, PLANT_CD, AQL_CODE) ON DELETE CASCADE,
        CONSTRAINT CK_AQL_RULES_RANGE CHECK (LOT_QTY_FROM <= LOT_QTY_TO),
        CONSTRAINT CK_AQL_RULES_ACCEPT_REJECT CHECK (REJECT_QTY > ACCEPT_QTY)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_AQL_RULES_LOOKUP';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_AQL_RULES_LOOKUP ON AQL_SAMPLING_RULES (COMPANY, PLANT_CD, AQL_CODE, LOT_QTY_FROM, LOT_QTY_TO)';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON TABLE AQL_STANDARDS IS 'AQL 기준 헤더']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE AQL_SAMPLING_RULES IS 'AQL LOT 수량별 sampling rule']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_STANDARDS.AQL_CODE IS 'AQL 코드']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_STANDARDS.AQL_NAME IS 'AQL 명칭']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_STANDARDS.INSPECTION_LEVEL IS '검사수준']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_STANDARDS.AQL_VALUE IS 'AQL 값']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_SAMPLING_RULES.LOT_QTY_FROM IS 'LOT 수량 From']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_SAMPLING_RULES.LOT_QTY_TO IS 'LOT 수량 To']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_SAMPLING_RULES.SAMPLE_SIZE IS '시료수']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_SAMPLING_RULES.ACCEPT_QTY IS '합격 허용수 Ac']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN AQL_SAMPLING_RULES.REJECT_QTY IS '불합격 판정수 Re']';

  COMMIT;
END;
/
