MERGE INTO COM_CODES t
USING (
  SELECT 'EQUIP_TYPE' AS GROUP_CODE,
         'COMMON' AS DETAIL_CODE,
         '공통' AS CODE_NAME,
         '설비유형 공통 점검항목' AS CODE_DESC,
         0 AS SORT_ORDER,
         'Y' AS USE_YN,
         'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200' AS ATTR1,
         'Common' AS ATTR3,
         '40' AS COMPANY,
         '1000' AS PLANT_CD
    FROM DUAL
) s
ON (
  t.COMPANY = s.COMPANY
  AND t.PLANT_CD = s.PLANT_CD
  AND t.GROUP_CODE = s.GROUP_CODE
  AND t.DETAIL_CODE = s.DETAIL_CODE
)
WHEN MATCHED THEN UPDATE SET
  t.CODE_NAME = s.CODE_NAME,
  t.CODE_DESC = s.CODE_DESC,
  t.SORT_ORDER = s.SORT_ORDER,
  t.USE_YN = s.USE_YN,
  t.ATTR1 = s.ATTR1,
  t.ATTR3 = s.ATTR3,
  t.UPDATED_BY = 'codex',
  t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  GROUP_CODE,
  DETAIL_CODE,
  PARENT_CODE,
  CODE_NAME,
  CODE_DESC,
  SORT_ORDER,
  USE_YN,
  ATTR1,
  ATTR2,
  ATTR3,
  COMPANY,
  PLANT_CD,
  CREATED_BY,
  UPDATED_BY,
  CREATED_AT,
  UPDATED_AT
) VALUES (
  s.GROUP_CODE,
  s.DETAIL_CODE,
  NULL,
  s.CODE_NAME,
  s.CODE_DESC,
  s.SORT_ORDER,
  s.USE_YN,
  s.ATTR1,
  NULL,
  s.ATTR3,
  s.COMPANY,
  s.PLANT_CD,
  'codex',
  'codex',
  SYSTIMESTAMP,
  SYSTIMESTAMP
);
/

UPDATE EQUIP_INSPECT_ITEM_MASTERS
   SET EQUIP_TYPE = 'COMMON',
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND EQUIP_TYPE IS NULL
   AND (ITEM_CODE LIKE 'EI-CMN-%' OR ITEM_CODE LIKE 'EI-WRK-%');
/

UPDATE EQUIP_INSPECT_ITEM_MASTERS
   SET CYCLE = CASE
                 WHEN INSPECT_TYPE = 'PERIODIC' THEN 'MONTHLY'
                 ELSE 'DAILY'
               END,
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND CYCLE IS NULL;
/

UPDATE EQUIP_INSPECT_ITEM_MASTERS
   SET UNIT = 'mm',
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND ITEM_CODE IN ('EI-ATC-003', 'EI-ATC-P01')
   AND UNIT IS NULL;
/

UPDATE EQUIP_INSPECT_ITEM_MASTERS
   SET UNIT = 'mm',
       LSL_VALUE = -0.5,
       USL_VALUE = 0.5,
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND ITEM_CODE = 'EI-SCT-001';
/

UPDATE EQUIP_INSPECT_ITEM_MASTERS
   SET UNIT = 'mm',
       LSL_VALUE = -0.3,
       USL_VALUE = 0.3,
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND ITEM_CODE = 'EI-SCT-003';
/

UPDATE EQUIP_INSPECT_ITEM_MASTERS
   SET UNIT = '°C',
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND ITEM_CODE IN ('EI-PKG-001', 'EI-SLD-001')
   AND UNIT IS NULL;
/

UPDATE EQUIP_INSPECT_ITEM_MASTERS
   SET UNIT = 'Ω',
       LSL_VALUE = 0,
       USL_VALUE = 0.1,
       UPDATED_BY = 'codex',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40'
   AND PLANT_CD = '1000'
   AND ITEM_CODE = 'EI-TST-002';
/

COMMIT;
/
