-- 2026-06-16 PROCESS_CATEGORY(공정 대분류) 공통코드 그룹 신설
-- 배경: /master/process 의 공정대분류 드롭다운이 프론트 하드코딩(ASSY/INSP/CUTTING/WELDING/PACKING)이라
--       실제 데이터(WIRE/TERMINAL/ASSEMBLY/INSPECTION/HEAT)와 전혀 맞지 않아 수정 모달에서 선택값이 안 잡힘.
-- 조치: 실데이터 5종을 공통코드 그룹 PROCESS_CATEGORY 로 등록하고, 프론트는 useComCodeOptions 로 전환.
-- 사이트: JSHANES (COMPANY=40, PLANT_CD=1000)

INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_CATEGORY','WIRE','전선',1,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_CATEGORY' AND DETAIL_CODE='WIRE');
/
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_CATEGORY','TERMINAL','단자',2,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_CATEGORY' AND DETAIL_CODE='TERMINAL');
/
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_CATEGORY','ASSEMBLY','조립',3,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_CATEGORY' AND DETAIL_CODE='ASSEMBLY');
/
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_CATEGORY','INSPECTION','검사',4,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_CATEGORY' AND DETAIL_CODE='INSPECTION');
/
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
SELECT 'PROCESS_CATEGORY','HEAT','열처리',5,'Y','40','1000','claude','claude' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_CATEGORY' AND DETAIL_CODE='HEAT');
/
