-- 출하취소: 박스↔출하지시 연결 + 출하시각 + 취소이력 채번 시퀀스
-- Site: JSHANES (40/1000)

ALTER TABLE BOX_MASTERS ADD (
  SHIP_ORDER_NO VARCHAR2(50),
  SHIPPED_AT    TIMESTAMP
)
/
CREATE INDEX IX_BOX_SHIP_ORDER ON BOX_MASTERS (SHIP_ORDER_NO)
/
-- 취소이력(SHIPPING_RETURNS) 자동 채번 (전역 시퀀스, 일별 리셋 없음)
CREATE SEQUENCE SEQ_SHIP_RETURN START WITH 1 INCREMENT BY 1 NOCACHE
/
-- 백필 1: 팔레트출하 박스 — 팔레트의 출하지시/출하시각 상속 (정확)
UPDATE BOX_MASTERS b
SET (b.SHIP_ORDER_NO, b.SHIPPED_AT) = (
  SELECT p.SHIP_ORDER_NO, p.SHIPPED_TIME
  FROM PALLET_MASTERS p
  WHERE p.PALLET_NO = b.PALLET_NO
)
WHERE b.PALLET_NO IS NOT NULL
  AND b.STATUS = 'SHIPPED'
  AND EXISTS (SELECT 1 FROM PALLET_MASTERS p WHERE p.PALLET_NO = b.PALLET_NO AND p.SHIP_ORDER_NO IS NOT NULL)
/
-- 백필 2: 박스출하 과거분 — 거래 remark '출하지시 박스출하:{boxNo}' 역파싱 (best-effort, 일회성)
UPDATE BOX_MASTERS b
SET b.SHIP_ORDER_NO = (
  SELECT MAX(t.REF_ID)
  FROM PRODUCT_TRANSACTIONS t
  WHERE t.REF_TYPE = 'SHIP_ORDER'
    AND t.TRANS_TYPE = 'FG_OUT'
    AND t.STATUS = 'DONE'
    AND t.REMARK = '출하지시 박스출하:' || b.BOX_NO
)
WHERE b.PALLET_NO IS NULL
  AND b.STATUS = 'SHIPPED'
  AND b.SHIP_ORDER_NO IS NULL
/
COMMIT
/
