DECLARE
  v_cnt NUMBER;
BEGIN
  -- PACK_UNIT(팔레트 구성 단위)을 VARCHAR2 → NUMBER로 변경. (현재 전 행 NULL이라 직접 변환 안전)
  SELECT COUNT(*) INTO v_cnt FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='ITEM_MASTERS' AND COLUMN_NAME='PACK_UNIT' AND DATA_TYPE='VARCHAR2';
  IF v_cnt = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITEM_MASTERS MODIFY (PACK_UNIT NUMBER)';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITEM_MASTERS.PACK_UNIT IS '팔레트 구성 단위(팔레트당 박스 수)']';
END;
/
