-- 2026-09-25_material_reference_tables.sql
-- part.service.ts(품목 삭제 참조검사) / inventory-freeze.guard.ts 가 raw SQL 로 참조하는 6개 테이블을 만든다 (멱등).
-- 구조 출처: 이전 임시 개발서버에 있던 동일 테이블 정의를 그대로 옮겼다.
-- 변경점 1: part.service.ts 가 ORGANIZATION_ID 로 필터하므로 COMPANY/PLANT_CD -> ORGANIZATION_ID 로 대체했다.
--          PHYSICAL_INV_SESSIONS 만 가드가 COMPANY/PLANT_CD 를 쓰므로 원형을 유지한다.
-- 변경점 2: DATA_DEFAULT 는 LONG 이라 조회에서 제외했고, NOT NULL 감사컬럼에만 SYSTIMESTAMP 기본값을 준다.
DECLARE
  PROCEDURE ddl_if_absent(p_name VARCHAR2, p_sql VARCHAR2) IS
    n NUMBER;
  BEGIN
    SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = p_name;
    IF n = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  ddl_if_absent('BOM_MASTERS', q'~CREATE TABLE "BOM_MASTERS" (
  "PARENT_ITEM_CODE" VARCHAR2(50) NOT NULL,
  "CHILD_ITEM_CODE" VARCHAR2(50) NOT NULL,
  "QTY_PER" NUMBER(10,4) NOT NULL,
  "SEQ" NUMBER NOT NULL,
  "REVISION" VARCHAR2(10) NOT NULL,
  "BOM_GRP" VARCHAR2(50),
  "OPER" VARCHAR2(50),
  "SIDE" VARCHAR2(10),
  "ECO_NO" VARCHAR2(50),
  "VALID_FROM" DATE,
  "VALID_TO" DATE,
  "REMARK" VARCHAR2(1000),
  "USE_YN" VARCHAR2(1) NOT NULL,
  "ORGANIZATION_ID" NUMBER DEFAULT 1 NOT NULL,
  "CREATED_BY" VARCHAR2(50),
  "UPDATED_BY" VARCHAR2(50),
  "CREATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "UPDATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT "PK_BOM_MASTERS" PRIMARY KEY ("ORGANIZATION_ID", "PARENT_ITEM_CODE", "CHILD_ITEM_CODE", "REVISION")
)~');
  ddl_if_absent('MAT_ARRIVALS', q'~CREATE TABLE "MAT_ARRIVALS" (
  "ARRIVAL_NO" VARCHAR2(50) NOT NULL,
  "INVOICE_NO" VARCHAR2(100),
  "PO_ID" VARCHAR2(50),
  "PO_ITEM_ID" VARCHAR2(50),
  "PO_NO" VARCHAR2(50),
  "VENDOR_CODE" VARCHAR2(50) NOT NULL,
  "VENDOR_NAME" VARCHAR2(200) NOT NULL,
  "ITEM_CODE" VARCHAR2(50) NOT NULL,
  "QTY" NUMBER(10,0) NOT NULL,
  "WAREHOUSE_CODE" VARCHAR2(50) NOT NULL,
  "ARRIVAL_DATE" TIMESTAMP(6) NOT NULL,
  "ARRIVAL_TYPE" VARCHAR2(20) NOT NULL,
  "WORKER_CODE" VARCHAR2(50),
  "REMARK" VARCHAR2(500),
  "STATUS" VARCHAR2(20) NOT NULL,
  "ORGANIZATION_ID" NUMBER DEFAULT 1 NOT NULL,
  "CREATED_BY" VARCHAR2(50),
  "UPDATED_BY" VARCHAR2(50),
  "CREATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "UPDATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "SEQ" NUMBER NOT NULL,
  "IQC_STATUS" VARCHAR2(20) NOT NULL,
  "SUP_UID" VARCHAR2(50),
  CONSTRAINT "PK_MAT_ARRIVALS" PRIMARY KEY ("ARRIVAL_NO", "SEQ")
)~');
  ddl_if_absent('MAT_LOTS', q'~CREATE TABLE "MAT_LOTS" (
  "MAT_UID" VARCHAR2(50) NOT NULL,
  "ITEM_CODE" VARCHAR2(50) NOT NULL,
  "INIT_QTY" NUMBER NOT NULL,
  "CURRENT_QTY" NUMBER NOT NULL,
  "RECV_DATE" DATE,
  "EXPIRE_DATE" DATE,
  "ORIGIN" VARCHAR2(100),
  "VENDOR" VARCHAR2(100) NOT NULL,
  "INVOICE_NO" VARCHAR2(100),
  "PO_NO" VARCHAR2(50),
  "IQC_STATUS" VARCHAR2(20) NOT NULL,
  "STATUS" VARCHAR2(20) NOT NULL,
  "ORGANIZATION_ID" NUMBER DEFAULT 1 NOT NULL,
  "CREATED_BY" VARCHAR2(50),
  "UPDATED_BY" VARCHAR2(50),
  "CREATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "UPDATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "MANUFACTURE_DATE" DATE,
  "ARRIVAL_NO" VARCHAR2(50),
  "ARRIVAL_SEQ" NUMBER,
  "MFG_PARTNER_CODE" VARCHAR2(50),
  "SPECIAL_ACCEPT_YN" VARCHAR2(1) NOT NULL,
  CONSTRAINT "PK_MAT_LOTS" PRIMARY KEY ("MAT_UID")
)~');
  ddl_if_absent('MAT_RECEIVINGS', q'~CREATE TABLE "MAT_RECEIVINGS" (
  "RECEIVE_NO" VARCHAR2(50) NOT NULL,
  "MAT_UID" VARCHAR2(50) NOT NULL,
  "ITEM_CODE" VARCHAR2(50) NOT NULL,
  "QTY" NUMBER(10,0) NOT NULL,
  "WAREHOUSE_CODE" VARCHAR2(50) NOT NULL,
  "RECEIVE_DATE" TIMESTAMP(6) NOT NULL,
  "WORKER_CODE" VARCHAR2(50),
  "REMARK" VARCHAR2(500),
  "STATUS" VARCHAR2(20) NOT NULL,
  "ORGANIZATION_ID" NUMBER DEFAULT 1 NOT NULL,
  "CREATED_BY" VARCHAR2(50),
  "CREATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "UPDATED_BY" VARCHAR2(50),
  "UPDATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "SEQ" NUMBER NOT NULL,
  "ARRIVAL_NO" VARCHAR2(50),
  "ARRIVAL_SEQ" NUMBER,
  "VENDOR_BARCODE" VARCHAR2(200),
  CONSTRAINT "PK_MAT_RECEIVINGS" PRIMARY KEY ("RECEIVE_NO", "SEQ")
)~');
  ddl_if_absent('PHYSICAL_INV_SESSIONS', q'~CREATE TABLE "PHYSICAL_INV_SESSIONS" (
  "INV_TYPE" VARCHAR2(20) NOT NULL,
  "STATUS" VARCHAR2(20) NOT NULL,
  "WAREHOUSE_CODE" VARCHAR2(50),
  "COMPANY" VARCHAR2(50) NOT NULL,
  "PLANT_CD" VARCHAR2(50) NOT NULL,
  "STARTED_BY" VARCHAR2(50),
  "COMPLETED_BY" VARCHAR2(50),
  "COMPLETED_AT" TIMESTAMP(6),
  "REMARK" VARCHAR2(500),
  "CREATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "UPDATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "SESSION_DATE" DATE NOT NULL,
  "SEQ" NUMBER(5,0) NOT NULL,
  "COUNT_MONTH" VARCHAR2(7) NOT NULL,
  CONSTRAINT "PK_PHYSICAL_INV_SESSIONS" PRIMARY KEY ("SESSION_DATE", "SEQ")
)~');
  ddl_if_absent('PROD_PLANS', q'~CREATE TABLE "PROD_PLANS" (
  "PLAN_NO" VARCHAR2(50) NOT NULL,
  "PLAN_MONTH" VARCHAR2(7) NOT NULL,
  "ITEM_CODE" VARCHAR2(50) NOT NULL,
  "ITEM_TYPE" VARCHAR2(10) NOT NULL,
  "PLAN_QTY" NUMBER(10,0) NOT NULL,
  "ORDER_QTY" NUMBER(10,0) NOT NULL,
  "CUSTOMER" VARCHAR2(50),
  "LINE_CODE" VARCHAR2(255),
  "PRIORITY" NUMBER(10,0) NOT NULL,
  "STATUS" VARCHAR2(20) NOT NULL,
  "REMARK" VARCHAR2(500),
  "ORGANIZATION_ID" NUMBER DEFAULT 1 NOT NULL,
  "CREATED_BY" VARCHAR2(50),
  "UPDATED_BY" VARCHAR2(50),
  "CREATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "UPDATED_AT" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT "PK_PROD_PLANS" PRIMARY KEY ("PLAN_NO")
)~');
END;
/
