BEGIN
  -- 유수명자재 메뉴 복구
  -- 원인: MAT_SHELF_LIFE_REINSPECT / MAT_SHELF_LIFE_HISTORY가 MENU_CATEGORY_ITEMS에서 빠지면
  --       menuConfig에는 존재해도 사이드바와 메뉴관리 미배치 목록에서 보이지 않는다.
  MERGE INTO MENU_CATEGORY_ITEMS t
  USING (
    SELECT 'MAT_SHELF_LIFE' MENU_CODE, 'MATERIAL' CATEGORY_CODE, 170 SORT_ORDER FROM DUAL UNION ALL
    SELECT 'MAT_SHELF_LIFE_REINSPECT', 'MATERIAL', 180 FROM DUAL UNION ALL
    SELECT 'MAT_SHELF_LIFE_HISTORY', 'MATERIAL', 190 FROM DUAL
  ) s
  ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.MENU_CODE = s.MENU_CODE)
  WHEN MATCHED THEN UPDATE SET
    t.CATEGORY_CODE = s.CATEGORY_CODE,
    t.SORT_ORDER = s.SORT_ORDER,
    t.UPDATED_AT = SYSTIMESTAMP,
    t.UPDATED_BY = 'codex'
  WHEN NOT MATCHED THEN INSERT
    (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES
    (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, '40', '1000', 'codex', 'codex');

  MERGE INTO ROLE_MENU_PERMISSIONS t
  USING (
    SELECT 'MANAGER' ROLE_CODE, 'MAT_SHELF_LIFE' MENU_CODE FROM DUAL UNION ALL
    SELECT 'MANAGER', 'MAT_SHELF_LIFE_REINSPECT' FROM DUAL UNION ALL
    SELECT 'MANAGER', 'MAT_SHELF_LIFE_HISTORY' FROM DUAL
  ) s
  ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE)
  WHEN MATCHED THEN UPDATE SET
    t.CAN_ACCESS = 'Y',
    t.UPDATED_AT = SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT
    (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
  VALUES
    (s.ROLE_CODE, s.MENU_CODE, 'Y', '40', '1000');

  COMMIT;
END;
/
