DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'SUBCON_ORDERS'
    AND COLUMN_NAME = 'JOB_ORDER_NO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SUBCON_ORDERS ADD (JOB_ORDER_NO VARCHAR2(50))';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'SUBCON_ORDERS'
    AND COLUMN_NAME = 'ROUTING_CODE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SUBCON_ORDERS ADD (ROUTING_CODE VARCHAR2(50))';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'SUBCON_ORDERS'
    AND COLUMN_NAME = 'PROCESS_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SUBCON_ORDERS ADD (PROCESS_SEQ NUMBER(10))';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'SUBCON_ORDERS'
    AND COLUMN_NAME = 'PROCESS_CODE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SUBCON_ORDERS ADD (PROCESS_CODE VARCHAR2(50))';
  END IF;

  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SUBCON_ORDERS.JOB_ORDER_NO IS '외주발주가 연결된 작업지시번호']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SUBCON_ORDERS.ROUTING_CODE IS '외주발주가 연결된 라우팅 코드']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SUBCON_ORDERS.PROCESS_SEQ IS '외주발주가 연결된 라우팅 공정 순번']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SUBCON_ORDERS.PROCESS_CODE IS '외주발주가 연결된 공정 코드']';
END;
/
