-- 2026-09-25_hanes_legacy_entity_tables.sql
-- 은성 DB에 없던 TypeORM 엔티티 매핑 테이블 18개와 부속 인덱스를 생성한다 (멱등).
-- 근거: apps/backend/src/entities/*.entity.ts 의 @Entity/@Column 메타데이터에서 DDL 을 생성했다.
-- USERS 는 제외한다: 정본 사용자 테이블은 ISYS_USERS 이고 동명 HANES 잔재가 혼동을 준다.
DECLARE
  PROCEDURE ddl_if_absent(p_kind VARCHAR2, p_name VARCHAR2, p_sql VARCHAR2) IS
    n NUMBER;
  BEGIN
    IF p_kind = 'TABLE' THEN
      SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = p_name;
    ELSE
      SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = p_name;
    END IF;
    IF n = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  ddl_if_absent('TABLE', 'VENDOR_BARCODE_MAPPINGS', q'~CREATE TABLE "VENDOR_BARCODE_MAPPINGS" (
  "VENDOR_BARCODE" varchar2(200) NOT NULL,
  "ITEM_CODE" varchar2(50) NOT NULL,
  "ITEM_NAME" varchar2(100),
  "VENDOR_CODE" varchar2(50) NOT NULL,
  "VENDOR_NAME" varchar2(100),
  "MAPPING_RULE" varchar2(200),
  "MATCH_TYPE" varchar2(20) DEFAULT 'EXACT' NOT NULL,
  "REMARK" varchar2(500),
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_VENDOR_BARCODE_MAPPINGS" PRIMARY KEY ("VENDOR_BARCODE")
)~');
  ddl_if_absent('INDEX', 'IDX_dcebeef40fde05bffefad7b102', q'~CREATE INDEX "IDX_dcebeef40fde05bffefad7b102" ON "VENDOR_BARCODE_MAPPINGS" ("VENDOR_CODE")~');
  ddl_if_absent('INDEX', 'IDX_e8273f3fc662fb3f349deb23a9', q'~CREATE INDEX "IDX_e8273f3fc662fb3f349deb23a9" ON "VENDOR_BARCODE_MAPPINGS" ("ITEM_CODE")~');
  ddl_if_absent('TABLE', 'TRAINING_PLANS', q'~CREATE TABLE "TRAINING_PLANS" (
  "PLAN_NO" varchar2(50) NOT NULL,
  "TITLE" varchar2(200) NOT NULL,
  "TRAINING_TYPE" varchar2(30) NOT NULL,
  "TARGET_ROLE" varchar2(100),
  "INSTRUCTOR" varchar2(100),
  "SCHEDULED_DATE" timestamp,
  "DURATION" int,
  "MAX_PARTICIPANTS" int,
  "STATUS" varchar2(20) DEFAULT 'PLANNED' NOT NULL,
  "DESCRIPTION" varchar2(2000),
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_TRAINING_PLANS" PRIMARY KEY ("PLAN_NO")
)~');
  ddl_if_absent('TABLE', 'TRAINING_RESULTS', q'~CREATE TABLE "TRAINING_RESULTS" (
  "PLAN_NO" varchar2(50) NOT NULL,
  "WORKER_CODE" varchar2(50) NOT NULL,
  "WORKER_NAME" varchar2(100) NOT NULL,
  "ATTEND_DATE" timestamp,
  "SCORE" int,
  "PASSED" number DEFAULT 0 NOT NULL,
  "CERTIFICATE_NO" varchar2(100),
  "VALID_UNTIL" timestamp,
  "REMARK" varchar2(500),
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_TRAINING_RESULTS" PRIMARY KEY ("PLAN_NO", "WORKER_CODE")
)~');
  ddl_if_absent('INDEX', 'IDX_13f4311af2deba0f68923438a4', q'~CREATE INDEX "IDX_13f4311af2deba0f68923438a4" ON "TRAINING_RESULTS" ("WORKER_CODE")~');
  ddl_if_absent('TABLE', 'PROCESS_QUALITY_CONDITIONS', q'~CREATE TABLE "PROCESS_QUALITY_CONDITIONS" (
  "ORGANIZATION_ID" number NOT NULL,
  "ROUTING_CODE" varchar2(50) NOT NULL,
  "SEQ" int NOT NULL,
  "CONDITION_SEQ" int NOT NULL,
  "CONDITION_CODE" varchar2(50),
  "MIN_VALUE" decimal(10,2),
  "MAX_VALUE" decimal(10,2),
  "UNIT" varchar2(20),
  "EQUIP_INTERFACE_YN" varchar2(1) DEFAULT 'N' NOT NULL,
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_PROCESS_QUALITY_CONDITIONS" PRIMARY KEY ("ORGANIZATION_ID", "ROUTING_CODE", "SEQ", "CONDITION_SEQ")
)~');
  ddl_if_absent('INDEX', 'IDX_002846650f4c214476bd70baf6', q'~CREATE INDEX "IDX_002846650f4c214476bd70baf6" ON "PROCESS_QUALITY_CONDITIONS" ("ROUTING_CODE", "SEQ")~');
  ddl_if_absent('TABLE', 'PROCESS_MAPS', q'~CREATE TABLE "PROCESS_MAPS" (
  "ITEM_CODE" varchar2(50) NOT NULL,
  "SEQ" int NOT NULL,
  "PROCESS_CODE" varchar2(255) NOT NULL,
  "PROCESS_NAME" varchar2(255) NOT NULL,
  "PROCESS_TYPE" varchar2(255),
  "EQUIP_TYPE" varchar2(255),
  "STD_TIME" decimal(10,4),
  "SETUP_TIME" decimal(10,4),
  "WIRE_LENGTH" decimal(10,2),
  "STRIP_LENGTH" decimal(10,2),
  "CRIMP_HEIGHT" decimal(10,3),
  "CRIMP_WIDTH" decimal(10,3),
  "WELD_CONDITION" varchar2(500),
  "PROCESS_PARAMS" varchar2(2000),
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_PROCESS_MAPS" PRIMARY KEY ("ITEM_CODE", "SEQ")
)~');
  ddl_if_absent('INDEX', 'IDX_67d8a4817a25f9f794af5fd8e4', q'~CREATE INDEX "IDX_67d8a4817a25f9f794af5fd8e4" ON "PROCESS_MAPS" ("PROCESS_TYPE")~');
  ddl_if_absent('INDEX', 'IDX_9b1018aefc3ab301781803d560', q'~CREATE INDEX "IDX_9b1018aefc3ab301781803d560" ON "PROCESS_MAPS" ("ITEM_CODE")~');
  ddl_if_absent('TABLE', 'PDA_ROLE_MENU', q'~CREATE TABLE "PDA_ROLE_MENU" (
  "ORGANIZATION_ID" number NOT NULL,
  "PDA_ROLE_CODE" varchar2(50) NOT NULL,
  "MENU_CODE" varchar2(50) NOT NULL,
  "IS_ACTIVE" char(1) DEFAULT 'Y' NOT NULL,
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_PDA_ROLE_MENU" PRIMARY KEY ("ORGANIZATION_ID", "PDA_ROLE_CODE", "MENU_CODE")
)~');
  ddl_if_absent('TABLE', 'PDA_ROLE', q'~CREATE TABLE "PDA_ROLE" (
  "ORGANIZATION_ID" number NOT NULL,
  "CODE" varchar2(50) NOT NULL,
  "NAME" varchar2(100) NOT NULL,
  "DESCRIPTION" varchar2(500),
  "IS_ACTIVE" char(1) DEFAULT 'Y' NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_PDA_ROLE" PRIMARY KEY ("ORGANIZATION_ID", "CODE")
)~');
  ddl_if_absent('TABLE', 'PLANTS', q'~CREATE TABLE "PLANTS" (
  "PLANT_CODE" varchar2(50) NOT NULL,
  "SHOP_CODE" varchar2(50) DEFAULT '-' NOT NULL,
  "LINE_CODE" varchar2(50) DEFAULT '-' NOT NULL,
  "CELL_CODE" varchar2(50) DEFAULT '-' NOT NULL,
  "COMPANY" varchar2(50) NOT NULL,
  "PLANT_CD" varchar2(50) NOT NULL,
  "PLANT_NAME" varchar2(200) NOT NULL,
  "PLANT_TYPE" varchar2(50),
  "SORT_ORDER" number DEFAULT 0 NOT NULL,
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_PLANTS" PRIMARY KEY ("PLANT_CODE", "SHOP_CODE", "LINE_CODE", "CELL_CODE")
)~');
  ddl_if_absent('INDEX', 'IDX_f11050a187eb206f1b644bedff', q'~CREATE INDEX "IDX_f11050a187eb206f1b644bedff" ON "PLANTS" ("PLANT_TYPE")~');
  ddl_if_absent('TABLE', 'MODEL_SUFFIXES', q'~CREATE TABLE "MODEL_SUFFIXES" (
  "MODEL_CODE" varchar2(100) NOT NULL,
  "SUFFIX_CODE" varchar2(50) NOT NULL,
  "SUFFIX_NAME" varchar2(200) NOT NULL,
  "CUSTOMER" varchar2(100),
  "REMARK" varchar2(500),
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_MODEL_SUFFIXES" PRIMARY KEY ("MODEL_CODE", "SUFFIX_CODE")
)~');
  ddl_if_absent('TABLE', 'MAT_STOCKS', q'~CREATE TABLE "MAT_STOCKS" (
  "ORGANIZATION_ID" number NOT NULL,
  "WAREHOUSE_CODE" varchar2(50) NOT NULL,
  "ITEM_CODE" varchar2(50) NOT NULL,
  "MAT_UID" varchar2(50) NOT NULL,
  "LOCATION_CODE" varchar2(50),
  "QTY" int DEFAULT 0 NOT NULL,
  "RESERVED_QTY" int DEFAULT 0 NOT NULL,
  "AVAILABLE_QTY" int DEFAULT 0 NOT NULL,
  "LAST_COUNT" timestamp,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_MAT_STOCKS" PRIMARY KEY ("ORGANIZATION_ID", "WAREHOUSE_CODE", "ITEM_CODE", "MAT_UID")
)~');
  ddl_if_absent('INDEX', 'IDX_5d781517623044aaf394256b82', q'~CREATE INDEX "IDX_5d781517623044aaf394256b82" ON "MAT_STOCKS" ("ITEM_CODE")~');
  ddl_if_absent('INDEX', 'IDX_c7f0c6e9d296826c1593ea2147', q'~CREATE INDEX "IDX_c7f0c6e9d296826c1593ea2147" ON "MAT_STOCKS" ("WAREHOUSE_CODE")~');
  ddl_if_absent('TABLE', 'IMPR_REQUESTS', q'~CREATE TABLE "IMPR_REQUESTS" (
  "IMPR_ID" varchar2(36) NOT NULL,
  "PAGE_URL" varchar2(500) NOT NULL,
  "ELEMENT_TEXT" varchar2(1000),
  "ELEMENT_TAG" varchar2(100),
  "DESCRIPTION" varchar2(2000) NOT NULL,
  "SCREENSHOT" clob,
  "STATUS" varchar2(20) DEFAULT 'PENDING' NOT NULL,
  "REQUESTER_ID" varchar2(100) NOT NULL,
  "REQUESTER_NM" varchar2(200),
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_IMPR_REQUESTS" PRIMARY KEY ("IMPR_ID")
)~');
  ddl_if_absent('INDEX', 'IDX_2fa5336c7591d19f3a9f43a243', q'~CREATE INDEX "IDX_2fa5336c7591d19f3a9f43a243" ON "IMPR_REQUESTS" ("ORGANIZATION_ID")~');
  ddl_if_absent('INDEX', 'IDX_99241b0d89c74667902f9ffd05', q'~CREATE INDEX "IDX_99241b0d89c74667902f9ffd05" ON "IMPR_REQUESTS" ("STATUS")~');
  ddl_if_absent('TABLE', 'HARNESS_CIRCUIT_SPECS', q'~CREATE TABLE "HARNESS_CIRCUIT_SPECS" (
  "CIRCUIT_ID" number NOT NULL,
  "REVISION_ID" number NOT NULL,
  "SORT_ORDER" number DEFAULT 0 NOT NULL,
  "CIRCUIT_NO" varchar2(50) NOT NULL,
  "WIRE_SPEC" varchar2(100),
  "WIRE_ITEM_CODE" varchar2(50),
  "WIRE_SIZE" varchar2(50),
  "COLOR_CODE" varchar2(30),
  "COLOR_NAME" varchar2(50),
  "LENGTH_MM" number(12,3),
  "STRIP_A_MM" number(8,3),
  "STRIP_B_MM" number(8,3),
  "END_A_HOUSING" varchar2(100),
  "END_A_TERMINAL" varchar2(100),
  "CONNECTION_SYMBOL" varchar2(30),
  "END_B_TERMINAL" varchar2(100),
  "END_B_HOUSING" varchar2(100),
  "TUBE_SPEC" varchar2(100),
  "SUB_NO" varchar2(50),
  "REMARK" varchar2(1000),
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_HARNESS_CIRCUIT_SPECS" PRIMARY KEY ("CIRCUIT_ID")
)~');
  ddl_if_absent('INDEX', 'IDX_9f94ae0fcfa1d6bf450e1f51c9', q'~CREATE UNIQUE INDEX "IDX_9f94ae0fcfa1d6bf450e1f51c9" ON "HARNESS_CIRCUIT_SPECS" ("ORGANIZATION_ID", "REVISION_ID", "CIRCUIT_NO")~');
  ddl_if_absent('INDEX', 'IDX_e463f737ca3f215d2fe8f857f8', q'~CREATE INDEX "IDX_e463f737ca3f215d2fe8f857f8" ON "HARNESS_CIRCUIT_SPECS" ("ORGANIZATION_ID", "REVISION_ID", "SORT_ORDER")~');
  ddl_if_absent('TABLE', 'FILE_ATTACHMENTS', q'~CREATE TABLE "FILE_ATTACHMENTS" (
  "ATTACHMENT_ID" number GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "BUSINESS_TYPE" varchar2(50) NOT NULL,
  "REF_KEY" varchar2(100),
  "FILE_YEAR" varchar2(4) NOT NULL,
  "ORIGINAL_NAME" varchar2(300) NOT NULL,
  "STORED_NAME" varchar2(300) NOT NULL,
  "FILE_PATH" varchar2(500) NOT NULL,
  "FILE_URL" varchar2(600) NOT NULL,
  "FILE_SIZE" number,
  "MIME_TYPE" varchar2(200),
  "DEL_YN" varchar2(1) DEFAULT 'N' NOT NULL,
  "CREATED_BY" varchar2(50),
  "CREATED_AT" date DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_FILE_ATTACHMENTS" PRIMARY KEY ("ATTACHMENT_ID")
)~');
  ddl_if_absent('TABLE', 'EQUIP_BOM_ITEMS', q'~CREATE TABLE "EQUIP_BOM_ITEMS" (
  "EQUIP_CODE" varchar2(50) NOT NULL,
  "BOM_ITEM_CODE" varchar2(50) NOT NULL,
  "BOM_ITEM_NAME" varchar2(200) NOT NULL,
  "ITEM_TYPE" varchar2(20) DEFAULT 'PART' NOT NULL,
  "SPEC" varchar2(200),
  "MAKER" varchar2(100),
  "UNIT" varchar2(20) DEFAULT 'EA' NOT NULL,
  "UNIT_PRICE" decimal(12,2),
  "REPLACEMENT_CYCLE" number,
  "STOCK_QTY" float DEFAULT 0 NOT NULL,
  "SAFETY_STOCK" int DEFAULT 0 NOT NULL,
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_EQUIP_BOM_ITEMS" PRIMARY KEY ("EQUIP_CODE", "BOM_ITEM_CODE")
)~');
  ddl_if_absent('INDEX', 'IDX_e1e8c5dcf62bf8225289b58619', q'~CREATE INDEX "IDX_e1e8c5dcf62bf8225289b58619" ON "EQUIP_BOM_ITEMS" ("USE_YN")~');
  ddl_if_absent('INDEX', 'IDX_85f1f2589ede3f264e8b91818a', q'~CREATE INDEX "IDX_85f1f2589ede3f264e8b91818a" ON "EQUIP_BOM_ITEMS" ("ITEM_TYPE")~');
  ddl_if_absent('TABLE', 'EQUIP_BOM_RELS', q'~CREATE TABLE "EQUIP_BOM_RELS" (
  "EQUIP_CODE" varchar2(50) NOT NULL,
  "BOM_ITEM_CODE" varchar2(50) NOT NULL,
  "QUANTITY" float DEFAULT 1 NOT NULL,
  "INSTALL_DATE" date,
  "EXPIRE_DATE" date,
  "REMARK" varchar2(500),
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "ORGANIZATION_ID" number NOT NULL,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_EQUIP_BOM_RELS" PRIMARY KEY ("EQUIP_CODE", "BOM_ITEM_CODE")
)~');
  ddl_if_absent('INDEX', 'IDX_1d53395cc62825871c6f06ef09', q'~CREATE INDEX "IDX_1d53395cc62825871c6f06ef09" ON "EQUIP_BOM_RELS" ("USE_YN")~');
  ddl_if_absent('TABLE', 'EQUIP_INSPECT_ITEM_MASTERS', q'~CREATE TABLE "EQUIP_INSPECT_ITEM_MASTERS" (
  "ORGANIZATION_ID" number NOT NULL,
  "ITEM_CODE" varchar2(30) NOT NULL,
  "ITEM_NAME" varchar2(200) NOT NULL,
  "INSPECT_TYPE" varchar2(20) NOT NULL,
  "EQUIP_TYPE" varchar2(50),
  "ITEM_TYPE" varchar2(20) DEFAULT 'VISUAL' NOT NULL,
  "CRITERIA" varchar2(500),
  "CYCLE" varchar2(20) NOT NULL,
  "UNIT" varchar2(20),
  "LSL_VALUE" number,
  "USL_VALUE" number,
  "WORKER_QR_CODE" varchar2(50),
  "IMAGE_URL" varchar2(500),
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "REMARK" varchar2(500),
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_EQUIP_INSPECT_ITEM_MASTERS" PRIMARY KEY ("ORGANIZATION_ID", "ITEM_CODE")
)~');
  ddl_if_absent('TABLE', 'EQUIP_INSPECT_ITEM_POOL', q'~CREATE TABLE "EQUIP_INSPECT_ITEM_POOL" (
  "ORGANIZATION_ID" number NOT NULL,
  "EQUIP_CODE" varchar2(36) NOT NULL,
  "ITEM_CODE" varchar2(30) NOT NULL,
  "INSPECT_TYPE" varchar2(20) NOT NULL,
  "USE_YN" varchar2(1) DEFAULT 'Y' NOT NULL,
  "SORT_SEQ" number,
  "CREATED_BY" varchar2(50),
  "UPDATED_BY" varchar2(50),
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_EQUIP_INSPECT_ITEM_POOL" PRIMARY KEY ("ORGANIZATION_ID", "EQUIP_CODE", "ITEM_CODE", "INSPECT_TYPE")
)~');
  ddl_if_absent('TABLE', 'ACTIVITY_LOGS', q'~CREATE TABLE "ACTIVITY_LOGS" (
  "ACTIVITY_DATE" date DEFAULT SYSDATE NOT NULL,
  "SEQ" int DEFAULT 1 NOT NULL,
  "EMAIL" varchar2(255) NOT NULL,
  "NAME" varchar2(255),
  "ACTIVITY_TYPE" varchar2(50) NOT NULL,
  "PAGE_PATH" varchar2(500),
  "PAGE_NAME" varchar2(200),
  "IP_ADDRESS" varchar2(50),
  "USER_AGENT" varchar2(500),
  "DEVICE_TYPE" varchar2(20),
  "COMPANY" varchar2(50) NOT NULL,
  "PLANT_CD" varchar2(50) NOT NULL,
  "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT "PK_ACTIVITY_LOGS" PRIMARY KEY ("ACTIVITY_DATE", "SEQ")
)~');
  ddl_if_absent('INDEX', 'IDX_650d8a606ed8e0e2cac0d45642', q'~CREATE INDEX "IDX_650d8a606ed8e0e2cac0d45642" ON "ACTIVITY_LOGS" ("CREATED_AT")~');
  ddl_if_absent('INDEX', 'IDX_fc1957f6a980e7faf2d4ca80e6', q'~CREATE INDEX "IDX_fc1957f6a980e7faf2d4ca80e6" ON "ACTIVITY_LOGS" ("ACTIVITY_TYPE")~');
  ddl_if_absent('INDEX', 'IDX_0b11ca2aee42ecc5336c4beb41', q'~CREATE INDEX "IDX_0b11ca2aee42ecc5336c4beb41" ON "ACTIVITY_LOGS" ("EMAIL")~');
END;
/
