import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { resolve } from 'node:path';

const migrationPath = resolve(
  import.meta.dirname,
  '2026-09-25_hanes_legacy_entity_tables.sql',
);
const source = readFileSync(migrationPath, 'utf8');
const compact = source.replace(/\s+/g, ' ').trim();

/**
 * @Entity 매핑이 있는데 은성 DB 에 없던 테이블 목록. 이 파일이 정본이다.
 * USERS 는 의도적으로 없다 — 사용자 정본은 ISYS_USERS 다.
 */
const TABLES = [
  'ACTIVITY_LOGS', 'EQUIP_BOM_ITEMS', 'EQUIP_BOM_RELS', 'EQUIP_INSPECT_ITEM_MASTERS',
  'EQUIP_INSPECT_ITEM_POOL', 'FILE_ATTACHMENTS', 'HARNESS_CIRCUIT_SPECS', 'IMPR_REQUESTS',
  'MAT_STOCKS', 'MODEL_SUFFIXES', 'PDA_ROLE', 'PDA_ROLE_MENU', 'PLANTS', 'PROCESS_MAPS',
  'PROCESS_QUALITY_CONDITIONS', 'TRAINING_PLANS', 'TRAINING_RESULTS',
  'VENDOR_BARCODE_MAPPINGS',
];

test('migration creates every missing entity table exactly once', () => {
  assert.match(source, /^-- 2026-09-25_hanes_legacy_entity_tables\.sql/);
  for (const table of TABLES) {
    const creates = compact.match(new RegExp(`CREATE TABLE "${table}" \\(`, 'g')) ?? [];
    assert.equal(creates.length, 1, `${table} CREATE 문이 1개가 아니다`);
  }
});

test('every DDL statement is guarded so the migration is idempotent', () => {
  const guarded = compact.match(/ddl_if_absent\('(TABLE|INDEX)', '[A-Za-z0-9_]+', q'~/g) ?? [];
  const statements = compact.match(/q'~CREATE /g) ?? [];
  assert.equal(guarded.length, statements.length, '가드 없이 실행되는 DDL 이 있다');
  assert.match(compact, /IF p_kind = 'TABLE' THEN SELECT COUNT\(\*\) INTO n FROM USER_TABLES/);
  assert.match(compact, /ELSE SELECT COUNT\(\*\) INTO n FROM USER_INDEXES/);
});

test('USERS 는 만들지 않는다 — 사용자 정본은 ISYS_USERS 다', () => {
  assert.doesNotMatch(compact, /CREATE TABLE "USERS"/);
  assert.doesNotMatch(compact, /ON "USERS"/);
});

test('FILE_ATTACHMENTS keeps the generated primary key its entity declares', () => {
  assert.match(compact, /"ATTACHMENT_ID" number GENERATED BY DEFAULT AS IDENTITY NOT NULL/);
  assert.match(compact, /CONSTRAINT "PK_FILE_ATTACHMENTS" PRIMARY KEY \("ATTACHMENT_ID"\)/);
});
