DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'IP_PRODUCT_LINE'
     AND COLUMN_NAME = 'PROCESS_CODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IP_PRODUCT_LINE ADD PROCESS_CODE VARCHAR2(20)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'IP_PRODUCT_LINE'
     AND COLUMN_NAME = 'RESOURCE_TYPE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IP_PRODUCT_LINE ADD RESOURCE_TYPE VARCHAR2(20)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'IP_PRODUCT_LINE'
     AND COLUMN_NAME = 'PARENT_LINE_CODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IP_PRODUCT_LINE ADD PARENT_LINE_CODE VARCHAR2(20)';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'IP_PRODUCT_LINE'
     AND CONSTRAINT_NAME = 'CK_IP_PROD_LINE_PROCESS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IP_PRODUCT_LINE ADD CONSTRAINT CK_IP_PROD_LINE_PROCESS CHECK (PROCESS_CODE IS NULL OR PROCESS_CODE IN (''SMT'', ''ASSY''))';
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'IP_PRODUCT_LINE'
     AND CONSTRAINT_NAME = 'CK_IP_PROD_LINE_RESOURCE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IP_PRODUCT_LINE ADD CONSTRAINT CK_IP_PROD_LINE_RESOURCE CHECK (RESOURCE_TYPE IS NULL OR RESOURCE_TYPE IN (''LINE'', ''CELL''))';
  END IF;
END;
/
