FUNCTION "F_CHECK_ITEM_LOT_BLOCKING" (
   p_material_mfs IN VARCHAR2)
   RETURN NUMBER
IS
   lvi_count   NUMBER;
BEGIN
   BEGIN
      SELECT COUNT (*)
        INTO LVI_COUNT
        FROM IM_ITEM_INVENTORY_HOLD
       WHERE     MATERIAL_MFS = P_MATERIAL_MFS
             AND INVENTORY_STATUS = 'H'
             AND ORGANIZATION_ID = 1;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         RETURN 0;
   END;

   RETURN NVL (LVI_COUNT, 0);
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END F_CHECK_ITEM_LOT_BLOCKING;