FUNCTION F_GET_PCB_FIRST_MARKING_BY_BOXNO 
(
  P_BOX_NO IN VARCHAR2 
) RETURN DATE AS 


LVDT_MARKING_DATE DATE ;
BEGIN
 
     SELECT MIN(TO_DATE(DATESET, 'YYYY/MM/DD HH24:MI:SS')) INTO LVDT_MARKING_DATE
      FROM IQ_MACHINE_INSPECT_DATA_MK
     WHERE RUN_NO = ( SELECT max(RUN_NO)  FROM IP_PRODUCT_2D_BARCODE WHERE BOX_NO = P_BOX_NO ) ;

  RETURN NVL(LVDT_MARKING_DATE , SYSDATE - 1000 ) ;
  
  EXCEPTION WHEN OTHERS THEN 
       RETURN NVL(LVDT_MARKING_DATE , SYSDATE - 1000 ) ;
       
END F_GET_PCB_FIRST_MARKING_BY_BOXNO;