FUNCTION "F_GET_PACK_BARCODE_BY_PID" 
(
  P_PID IN VARCHAR2 
) RETURN VARCHAR2 AS 


LVS_PACK_BARCODE VARCHAR2(100) ;
BEGIN

    SELECT PACK_BARCODE 
      INTO LVS_PACK_BARCODE 
      FROM IP_PRODUCT_PACK_SERIAL WHERE BARCODE = P_PID ;
    
  RETURN LVS_PACK_BARCODE;
  
  EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        RETURN  'NOTFOUND' ;
    WHEN OTHERS THEN 
    
     RAISE_APPLICATION_ERROR( -20003 , SQLERRM ) ;
     RETURN  '*' ;
    
END F_GET_PACK_BARCODE_BY_PID;