FUNCTION "F_GET_MASTER_MODEL_NAME" 
(
  P_MODEL_NAME IN VARCHAR2  , P_ORG IN NUMBER 
) RETURN VARCHAR2 AS 
LVS_MODEL_NAME VARCHAR2(30) ;
BEGIN
 
    SELECT MASTER_MODEL_NAME 
      INTO LVS_MODEL_NAME 
     FROM IP_PRODUCT_MODEL_MASTER 
    WHERE MODEL_NAME = P_MODEL_NAME 
      AND ORGANIZATION_ID = P_ORG  ;
      
      IF LVS_MODEL_NAME = '' OR LVS_MODEL_NAME IS NULL THEN 
      
        LVS_MODEL_NAME := 'NOTFOUND' ; --P_MODEL_NAME ;
        
      END IF ;
      
      RETURN LVS_MODEL_NAME ;
EXCEPTION WHEN OTHERS THEN 
RETURN P_MODEL_NAME ;
END F_GET_MASTER_MODEL_NAME;