FUNCTION F_GET_COLUMN_COMMENTS 
(
  P_COLUMN_NAME IN VARCHAR2 
) RETURN VARCHAR2 AS 

LVS_RETURN VARCHAR2(200) ;
BEGIN

  SELECT KOREA_TEXT INTO LVS_RETURN  FROM ISYS_DUAL_LANGUAGE
  WHERE UPPER(ENGLISH_TEXT)   = UPPER(REPLACE ( P_COLUMN_NAME , '_' , ' ' )) 
   AND ROWNUM = 1 ;

  RETURN LVS_RETURN ;
END F_GET_COLUMN_COMMENTS;