FUNCTION "F_GET_LOT_QTY_FROM_DB" (
   p_barcode IN VARCHAR2)
   RETURN NUMBER 
IS
   lvs_return   NUMBER ;
BEGIN
   SELECT DECODE (NVL (NEW_SCAN_QTY, 0), 0, SCAN_QTY, NEW_SCAN_QTY)
     INTO lvs_return
     FROM IM_ITEM_RECEIPT_BARCODE
    WHERE LOT_NO = F_GET_LOT_NO_FROM_BARCODE (p_barcode);

   RETURN lvs_return;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      RETURN 0;
   WHEN OTHERS
   THEN
      RETURN 0;
END;