FUNCTION "F_GET_ALPHABET_NUMBER" 
(
  P_PARAM IN VARCHAR2 
) RETURN VARCHAR2 AS 
BEGIN

IF P_PARAM = 'A' THEN 
RETURN  '1' ;
ELSIF P_PARAM = 'B' THEN 
RETURN  '2' ;
ELSIF P_PARAM = 'C' THEN 
RETURN  '3' ;
ELSIF P_PARAM = 'D' THEN 
RETURN  '4' ;
ELSIF P_PARAM = 'E' THEN 
RETURN  '5' ;
ELSIF P_PARAM = 'F' THEN 
RETURN  '6' ;
ELSIF P_PARAM = 'G' THEN 
RETURN  '7' ;
ELSIF P_PARAM = 'H' THEN 
RETURN  '8' ;
ELSIF P_PARAM = 'I' THEN 
RETURN  '9' ;
ELSIF P_PARAM = 'J' THEN 
RETURN  '10' ;
ELSIF P_PARAM = 'K' THEN 
RETURN  '11' ;
ELSIF P_PARAM = 'L' THEN 
RETURN  '12' ;
ELSIF P_PARAM = 'M' THEN 
RETURN  '13' ;
ELSIF P_PARAM = 'N' THEN 
RETURN  '14' ;
ELSIF P_PARAM = 'O' THEN 
RETURN  '15' ;
ELSIF P_PARAM = 'P' THEN 
RETURN  '16' ;
ELSIF P_PARAM = 'Q' THEN 
RETURN  '17' ;
ELSIF P_PARAM = 'R' THEN 
RETURN  '18' ;
ELSIF P_PARAM = 'S' THEN 
RETURN  '19' ;
ELSIF P_PARAM = 'T' THEN 
RETURN  '20' ;
ELSIF P_PARAM = 'U' THEN 
RETURN  '21' ;
ELSIF P_PARAM = 'V' THEN 
RETURN  '22' ;
ELSIF P_PARAM = 'W' THEN 
RETURN  '23' ;
ELSIF P_PARAM = 'X' THEN 
RETURN  '24' ;
ELSIF P_PARAM = 'Y' THEN 
RETURN  '25' ;
ELSIF P_PARAM = 'Z' THEN 
RETURN  '26' ;
ELSE 
RETURN P_PARAM ;
END IF ;

       

END F_GET_ALPHABET_NUMBER;