FUNCTION "F_GET_INVENTORY_TYPE" 
(
  P_MATERIAL_MFS IN VARCHAR2 
) RETURN VARCHAR2 AS 


LVS_TYPE VARCHAR2(10) ;
BEGIN

  BEGIN 
  
  SELECT INVENTORY_TYPE INTO LVS_TYPE 
   FROM IM_ITEM_RECEIPT_BARCODE
   WHERE LOT_NO = P_MATERIAL_MFS ;
   
   EXCEPTION WHEN NO_DATA_FOUND THEN 
      RETURN 'P' ;
   END ;
   
 RETURN NVL(LVS_TYPE ,'P' ) ; -- 디폴트 양산 자재 

END F_GET_INVENTORY_TYPE;