FUNCTION F_GET_RUN_LINE_ACTUAL_QTY
(
  P_RUN_NO  IN VARCHAR2, 
  P_LINE    IN VARCHAR2,
  P_ORG     IN NUMBER 
) RETURN NUMBER AS 


LVL_RETURN NUMBER ;

BEGIN

  LVL_RETURN := 0;
  
    SELECT COUNT(DISTINCT a.PID) 
        INTO LVL_RETURN
     FROM IQ_MACHINE_INSPECT_DATA_AOI a
    WHERE a.PID IN ( SELECT b.SERIAL_NO FROM IP_PRODUCT_2D_BARCODE b WHERE b.RUN_NO = P_RUN_NO ) ;

--  SELECT SUM(PRODUCT_ACTUAL_QTY)
--        INTO LVL_RETURN
--     FROM IP_PRODUCT_SENSOR_ACTUAL
--    WHERE LINE_CODE = P_LINE 
--      AND RUN_NO = P_RUN_NO ;
  
--  ------------------------------------------------------------
--  -- Route 상 io_type = 'C' 생산완성실적으로 집계
--  ------------------------------------------------------------
--   SELECT NVL(SUM(IO_QTY),0)   --COUNT(*) 
--     INTO LVL_RETURN 
--     FROM IP_PRODUCT_WORKSTAGE_IO
--    WHERE LINE_CODE       = P_LINE
--      AND RUN_NO          = P_RUN_NO 
--      AND WORKSTAGE_CODE  = F_GET_WORKSTAGE_CODE_4_LINE(P_LINE, 'C')
--      AND ORGANIZATION_ID = P_ORG;
   
  RETURN LVL_RETURN;
  
  
EXCEPTION 
   WHEN NO_DATA_FOUND THEN 
        RETURN 0 ;
    
END F_GET_RUN_LINE_ACTUAL_QTY;