FUNCTION "F_GET_MESSAGE_TEXT" 
  ( P_MSG_ID IN VARCHAR2 ,P_LANGUAGE IN VARCHAR2)
  RETURN  VARCHAR2 IS

-- ---------   ------  -------------------------------------------
   LVS_TEXT                 VARCHAR2(100);

BEGIN

    SELECT DECODE( P_LANGUAGE , 'E' , DETAIL_ENG , 'C' , DETAIL_LOC , 'K' , DETAIL_KOR )
     INTO LVS_TEXT
     FROM ISYS_AUDIT_MESSAGE_CODE
     WHERE MSG_ID = P_MSG_ID ;

    RETURN LVS_TEXT ;
EXCEPTION
   WHEN OTHERS  THEN
       RAISE_APPLICATION_ERROR ( -20003 , SQLERRM )  ;
END;