FUNCTION "F_GET_PRODUCT_INVENTORY_CYCLE" (
   P_CUSTOMER IN VARCHAR2)
   RETURN NUMBER
IS
   LVI_INVENTORY   NUMBER;
   LVI_SHIPPING    NUMBER;
BEGIN
   SELECT COUNT (*)
     INTO LVI_INVENTORY
     FROM IP_PRODUCT_2D_BARCODE
    WHERE SHIPPING_DEFICIT = '1' ;

   SELECT COUNT (*) / 30
     INTO LVI_SHIPPING
     FROM IP_PRODUCT_2D_BARCODE
    WHERE SHIPPING_DATE >= SYSDATE - 30 AND SHIPPING_DEFICIT = '3';

   RETURN ROUND (LVI_INVENTORY / LVI_SHIPPING, 1);
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
     RETURN 0;
   WHEN OTHERS
   THEN
      RAISE_APPLICATION_ERROR (-20003, SQLERRM);
END F_GET_PRODUCT_INVENTORY_CYCLE;