FUNCTION "F_GET_MAT_ON_FEEDER_QTY" (
   P_ITEM_CODE   IN VARCHAR2,
   P_ORG         IN NUMBER)
   RETURN NUMBER
IS
   LVL_QTY   NUMBER;

BEGIN
   SELECT SUM (FEEDING_QTY)
     INTO LVL_QTY
     FROM IB_PRODUCT_PLANDATA
    WHERE     CHIPNAME = P_ITEM_CODE
          AND ACTIVE_YN = 'Y'
          AND ORGANIZATION_ID = P_ORG;

   RETURN NVL (LVL_QTY, 0);
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      RETURN 0;
   WHEN OTHERS
   THEN
      -- Consider logging the error and then re-raise
      RAISE_APPLICATION_ERROR (-20003, SQLERRM);
END ;