FUNCTION "F_GET_MAT_UNFEEDING_QTY" (
   P_LINE_CODE        IN VARCHAR2,
   P_MODEL_NAME      IN VARCHAR2,
   P_ITEM_CODE       IN VARCHAR2,
   P_LOCATION_CODE   IN VARCHAR,
   P_FEEDER_SHAFT    IN VARCHAR2,
   P_FEEDER_GROUP_NO IN VARCHAR2 )
   RETURN NUMBER
IS

LVL_RETURN NUMBER ;
BEGIN

   SELECT SUM (SCAN_QTY)
     INTO LVL_RETURN
     FROM IM_ITEM_RECEIPT_BARCODE
    WHERE     ITEM_CODE = P_ITEM_CODE
          AND LINE_CODE = P_LINE_CODE
          AND FEEDING_MODEL = P_MODEL_NAME
          AND LOCATION_CODE = P_LOCATION_CODE
          AND FEEDER_SHAFT = P_FEEDER_SHAFT
          AND ISSUE_COMPARE_YN = 'Y'
          AND NVL (FEEDING_YN, 'N') = 'N'
          AND NVL(FEEDING_GROUP_NO , '*') = P_FEEDER_GROUP_NO ;

   RETURN NVL (LVL_RETURN, 0);
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      RETURN 0;
   WHEN OTHERS
   THEN
      RETURN 0;
END;