FUNCTION "F_GET_MONTHYLY_POINT_4_KPI" ( P_LINE_CODE IN VARCHAR2 ) RETURN NUMBER IS

BEGIN

   RETURN 97.5 ;
   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       RETURN 0;
     WHEN OTHERS THEN

       RAISE_APPLICATION_ERROR( -20003 , SQLERRM );
END ;