FUNCTION "F_GET_FEEDER_FEEDING_QTY" (
     P_LINE_CODE       IN VARCHAR2,
   P_MODEL_NAME      IN VARCHAR2,
   P_LOCATION_CODE   IN VARCHAR2,
   P_PCB_ITEM        IN VARCHAR2)
   RETURN NUMBER
IS
   LVL_RETURN   NUMBER;
BEGIN
   LVL_RETURN := 0;

   SELECT SUM (NVL (FEEDING_QTY, 0))
     INTO LVL_RETURN
     FROM IB_PRODUCT_PLANDATA
    WHERE     LINE_CODE = P_LINE_CODE
          AND MODEL_NAME = P_MODEL_NAME
          AND LOCATION_CODE = P_LOCATION_CODE
          AND PCB_ITEM = P_PCB_ITEM
          AND ACTIVE_YN = 'Y';


   RETURN LVL_RETURN;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      RETURN 0;
   WHEN OTHERS
   THEN
      RAISE_APPLICATION_ERROR (-20003, SQLERRM);
      RETURN 0;
END;