FUNCTION F_GET_JIG_VALUE_QTY 
(
  P_LOT_NO IN VARCHAR2 ,
  P_TYPE VARCHAR2 
) RETURN NUMBER AS 

LVL_HIT_VALUE NUMBER ;
LVL_BREAK_VALUE NUMBER ;
BEGIN

   SELECT NVL(HIT_VALUE,0) , NVL(BREAK_VALUE,0)
     INTO LVL_HIT_VALUE , LVL_BREAK_VALUE 
      FROM IMCN_JIG 
      WHERE jig_lot_no = P_LOT_NO ;
      
      
      IF P_TYPE = 'BREAK' THEN 
        RETURN LVL_BREAK_VALUE ;
      ELSE
          RETURN LVL_HIT_VALUE ;
      END IF  ;


END F_GET_JIG_VALUE_QTY;