TRIGGER "INFINITY21_JSMES"."TRG_IMCN_JIG_SQUEZE_CHECK_INS"
 BEFORE INSERT ON IMCN_JIG_SQUEZE_CHECK
 FOR EACH ROW
DECLARE

BEGIN
   
   IF (:NEW.JIG_CHECK_STATUS = 'R' AND :NEW.HIT_VALUE >= :NEW.BREAK_VALUE ) THEN

       UPDATE IMCN_JIG
          SET HIT_VALUE = 0,
              USE_STATUS = 'U'
        WHERE JIG_CODE        = :NEW.JIG_CODE
          AND JIG_LOT_NO      = :NEW.JIG_LOT_NO
          AND JIG_TYPE        = 'S'
          AND ORGANIZATION_ID = 1;

   END IF;
   
EXCEPTION
    WHEN OTHERS THEN
         raise_application_error (-20003, SQLERRM);

END;
