TRIGGER "INFINITY21_JSMES"."TRGIP_PRODUCT_LINE_TARGET_UPD" 
   BEFORE UPDATE
   ON IP_PRODUCT_LINE_TARGET
   FOR EACH ROW
DECLARE
   LVF_ST      NUMBER;

   LVDT_DATE   DATE;
BEGIN

   -- 2016/09/05 SHS, ？？？？ð？？？ ？？？？？？ - ？？？ð？ ？？？ð？ ？？ ？？？？？？ ？？？？？？
   :NEW.WORKING_HOUR := (NVL(:NEW.WORKING_END_DATE,  SYSDATE) - NVL(:NEW.WORKING_START_DATE, SYSDATE)) * 24;


EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;