TRIGGER "INFINITY21_JSMES"."TRGIP_PRODUCT_WORK_QC_INS" 
BEFORE INSERT ON IP_PRODUCT_WORK_QC 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
BEGIN
  
    IF :NEW.RECEIPT_DEFICIT  = '1' THEN 
    
      UPDATE IQ_PRODUCT_WQC SET REPAIR_RECEIPT_DEFICIT = '1' , REPAIR_DATE = SYSDATE 
      WHERE SERIAL_NO = :NEW.SERIAL_NO ;
      
    END IF ;
  
END;