-- 코멘트 없는 운영 테이블에 한글 테이블 코멘트 보강 (AI text-to-SQL 카탈로그 정확도 향상)
-- 대상: 컬럼 구조로 용도가 식별되는 운영 테이블. 권한/백업/마이그레이션 테이블 제외.
-- 실행: oracle-db execute-file ('/' 구분 개별 DDL)
COMMENT ON TABLE ACTIVITY_LOGS IS '사용자 활동 로그(페이지 접근 이력)';
/
COMMENT ON TABLE AUDIT_FINDINGS IS '내부심사 부적합 사항(발견사항)';
/
COMMENT ON TABLE AUDIT_PLANS IS '내부심사 계획';
/
COMMENT ON TABLE CALIBRATION_LOGS IS '계측기 교정 이력';
/
COMMENT ON TABLE CAPA_ACTIONS IS 'CAPA(시정 예방조치) 조치 항목';
/
COMMENT ON TABLE CAPA_REQUESTS IS 'CAPA(시정 예방조치) 요청';
/
COMMENT ON TABLE CHANGE_ORDERS IS '변경관리(설계 공정 변경) 요청';
/
COMMENT ON TABLE CONSUMABLE_STOCKS IS '소모품 재고(시리얼 단위)';
/
COMMENT ON TABLE CONSUMABLE_USAGE_MAP IS '소모품 사용 정의(품목 설비별 사용량)';
/
COMMENT ON TABLE CONTROL_PLANS IS '관리계획서(Control Plan)';
/
COMMENT ON TABLE CONTROL_PLAN_ITEMS IS '관리계획서 상세 항목';
/
COMMENT ON TABLE CUSTOMER_COMPLAINTS IS '고객 불만(클레임)';
/
COMMENT ON TABLE DOCUMENT_MASTERS IS '문서 마스터(문서관리)';
/
COMMENT ON TABLE EQUIP_CONDITION_RULES IS '설비 상태감시 규칙(센서 임계값)';
/
COMMENT ON TABLE EQUIP_INSPECT_ITEM_POOL IS '설비 점검 항목 풀';
/
COMMENT ON TABLE EQUIP_PROTOCOLS IS '설비 통신 프로토콜 정의';
/
COMMENT ON TABLE FAI_ITEMS IS '초도품검사(FAI) 측정 항목';
/
COMMENT ON TABLE FAI_REQUESTS IS '초도품검사(FAI) 요청';
/
COMMENT ON TABLE FG_LABELS IS '완제품 라벨(시리얼 바코드)';
/
COMMENT ON TABLE GAUGE_MASTERS IS '게이지(측정기) 마스터';
/
COMMENT ON TABLE IMPR_REQUESTS IS '화면 개선요청';
/
COMMENT ON TABLE IQC_TEMPLATES IS '수입검사(IQC) 템플릿';
/
COMMENT ON TABLE IQC_TEMPLATE_ITEMS IS '수입검사(IQC) 템플릿 항목';
/
COMMENT ON TABLE JOB_MATERIAL_LOTS IS '작업지시 투입 자재 로트';
/
COMMENT ON TABLE MAT_ARRIVAL_STOCKS IS '자재 입하 재고';
/
COMMENT ON TABLE MAT_ARRIVAL_TRANSACTIONS IS '자재 입하 트랜잭션';
/
COMMENT ON TABLE MOLD_MASTERS IS '금형 마스터';
/
COMMENT ON TABLE MOLD_USAGE_LOGS IS '금형 사용 이력(쇼트 수)';
/
COMMENT ON TABLE PHYSICAL_INV_COUNT_DETAILS IS '재고 실사 상세(품목별 실사 수량)';
/
COMMENT ON TABLE PHYSICAL_INV_SESSIONS IS '재고 실사 세션';
/
COMMENT ON TABLE PPAP_SUBMISSIONS IS 'PPAP 제출(양산부품 승인)';
/
COMMENT ON TABLE PROCESS_CAPAS IS '공정 생산능력(CAPA) 정의';
/
COMMENT ON TABLE PROCESS_EQUIPMENTS IS '공정-설비 매핑';
/
COMMENT ON TABLE PROCESS_QUALITY_CONDITIONS IS '공정 품질조건(관리 항목 규격)';
/
COMMENT ON TABLE PRODUCT_STOCKS IS '제품 재고(수량)';
/
COMMENT ON TABLE PRODUCT_TRANSACTIONS IS '제품 입출고 트랜잭션';
/
COMMENT ON TABLE PROD_PLANS IS '생산계획(월 단위)';
/
COMMENT ON TABLE REPAIR_ORDERS IS '수리 지시';
/
COMMENT ON TABLE REPAIR_USED_PARTS IS '수리 사용 부품';
/
COMMENT ON TABLE REWORK_INSPECTS IS '재작업 검사';
/
COMMENT ON TABLE REWORK_ORDERS IS '재작업 지시';
/
COMMENT ON TABLE REWORK_PROCESSES IS '재작업 공정';
/
COMMENT ON TABLE REWORK_RESULTS IS '재작업 실적';
/
COMMENT ON TABLE ROUTING_GROUPS IS '라우팅(공정순서) 그룹';
/
COMMENT ON TABLE ROUTING_MATERIALS IS '라우팅 투입 자재(BOM)';
/
COMMENT ON TABLE ROUTING_PROCESSES IS '라우팅 공정 순서';
/
COMMENT ON TABLE SAMPLE_INSPECT_RESULTS IS '샘플 검사 결과(측정값)';
/
COMMENT ON TABLE SCHEDULER_JOBS IS '스케줄러 작업 정의';
/
COMMENT ON TABLE SCHEDULER_LOGS IS '스케줄러 실행 로그';
/
COMMENT ON TABLE SCHEDULER_NOTIFICATIONS IS '스케줄러 알림';
/
COMMENT ON TABLE SELF_INSPECT_ITEMS IS '자주검사 항목';
/
COMMENT ON TABLE SELF_INSPECT_RESULTS IS '자주검사 결과';
/
COMMENT ON TABLE SENSOR_DATA_LOGS IS '설비 센서 데이터 로그';
/
COMMENT ON TABLE SEQ_RULES IS '채번 규칙(문서번호 생성)';
/
COMMENT ON TABLE SHIFT_PATTERNS IS '근무 교대 패턴';
/
COMMENT ON TABLE SIMULATION_HEADERS IS '생산 시뮬레이션 헤더';
/
COMMENT ON TABLE SIMULATION_PLANS IS '생산 시뮬레이션 계획';
/
COMMENT ON TABLE SIMULATION_SCHEDULES IS '생산 시뮬레이션 일정';
/
COMMENT ON TABLE SPC_CHARTS IS 'SPC 관리도 정의';
/
COMMENT ON TABLE SPC_DATA IS 'SPC 측정 데이터';
/
COMMENT ON TABLE TRAINING_PLANS IS '교육 계획';
/
COMMENT ON TABLE TRAINING_RESULTS IS '교육 결과(수료)';
/
COMMENT ON TABLE WIP_MAT_STOCKS IS '재공 자재 재고(설비 장착분)';
/
COMMENT ON TABLE WIP_MAT_TRANSACTIONS IS '재공 자재 트랜잭션';
/
COMMENT ON TABLE WORK_CALENDARS IS '작업 캘린더(연 공정 단위)';
/
COMMENT ON TABLE WORK_CALENDAR_DAYS IS '작업 캘린더 일자별 근무';
/
