"use client";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import toast from "react-hot-toast";
import { Edit2,Plus,RefreshCw,Search,Trash2 } from "lucide-react";
import { Button,Card,CardContent,ConfirmModal,Input,Modal } from "@/components/ui";
import PartSelect from "@/components/shared/PartSelect";
import ProcessSelect from "@/components/shared/ProcessSelect";
import SupplierSelect from "@/components/shared/SupplierSelect";
import api from "@/services/api";
import type{RoutingGroupItem,RoutingProcessItem,SelectedProcess}from"../types";
type Props={selectedProcess:SelectedProcess|null;onSelectProcess:(v:SelectedProcess|null)=>void};
const emptyGroup:{routingCode:string;itemCode:string;routingName:string;description:string;useYn:"Y"|"N"}={routingCode:"",itemCode:"",routingName:"",description:"",useYn:"Y"};
const emptyProcess={seq:"10",workstageCode:"",executionType:"INTERNAL" as "INTERNAL"|"SUBCON",jobOrderYn:"Y" as "Y"|"N",subconSupplierCode:"",standardTime:"",setupTime:"",useYn:"Y" as "Y"|"N"};
export default function RoutingGroupManager({selectedProcess,onSelectProcess}:Props){
 const requestGeneration=useRef(0),requestController=useRef<AbortController|null>(null),groupRequestGeneration=useRef(0),groupRequestController=useRef<AbortController|null>(null),targetRef=useRef<string|null>(null);
 const[groups,setGroups]=useState<RoutingGroupItem[]>([]),[processes,setProcesses]=useState<RoutingProcessItem[]>([]);const[selected,setSelected]=useState<RoutingGroupItem|null>(null);const[search,setSearch]=useState("");const[loading,setLoading]=useState(false);const[groupOpen,setGroupOpen]=useState(false),[processOpen,setProcessOpen]=useState(false);const[editingGroup,setEditingGroup]=useState<RoutingGroupItem|null>(null),[editingProcess,setEditingProcess]=useState<RoutingProcessItem|null>(null);const[groupForm,setGroupForm]=useState(emptyGroup),[processForm,setProcessForm]=useState(emptyProcess);const[deleteGroup,setDeleteGroup]=useState<RoutingGroupItem|null>(null),[deleteProcess,setDeleteProcess]=useState<RoutingProcessItem|null>(null);
 targetRef.current=selected?.routingCode??null;
 const loadGroups=useCallback(async()=>{groupRequestController.current?.abort();const controller=new AbortController();groupRequestController.current=controller;const generation=++groupRequestGeneration.current;setLoading(true);try{const r=await api.get("/master/routing-groups",{params:{search:search||undefined,limit:5000},signal:controller.signal});if(generation!==groupRequestGeneration.current)return;const rows=r.data?.data??[];setGroups(rows);setSelected(p=>p&&rows.some((x:RoutingGroupItem)=>x.routingCode===p.routingCode)?p:rows[0]??null)}catch(error:unknown){if(!controller.signal.aborted)toast.error("라우팅 조회 중 오류가 발생했습니다.")}finally{if(generation===groupRequestGeneration.current)setLoading(false)}},[search]);
 const loadProcesses=useCallback(async()=>{requestController.current?.abort();const controller=new AbortController();requestController.current=controller;const generation=++requestGeneration.current;setProcesses([]);onSelectProcess(null);if(!selected)return;try{const r=await api.get(`/master/routing-groups/${selected.routingCode}/processes`,{signal:controller.signal});if(generation !== requestGeneration.current)return;const rows=r.data?.data??[];setProcesses(rows);const current=rows[0];onSelectProcess(current?{routingCode:selected.routingCode,routingName:selected.routingName,seq:current.seq,workstageCode:current.workstageCode,workstageName:current.workstageName??current.workstageCode}:null)}catch(error:unknown){if(!controller.signal.aborted&&generation===requestGeneration.current)toast.error("공정 조회 중 오류가 발생했습니다.")}},[onSelectProcess,selected]);
 useEffect(()=>{void loadGroups();return()=>groupRequestController.current?.abort()},[loadGroups]);useEffect(()=>{void loadProcesses();return()=>requestController.current?.abort()},[loadProcesses]);
 const nextSeq=useMemo(()=>String((processes.length?Math.max(...processes.map(p=>p.seq)):0)+10),[processes]);
 const saveGroup=async()=>{if(!groupForm.routingCode.trim()||!groupForm.itemCode||!groupForm.routingName.trim())return;try{const body={routingName:groupForm.routingName.trim(),description:groupForm.description||undefined,useYn:groupForm.useYn};if(editingGroup)await api.put(`/master/routing-groups/${editingGroup.routingCode}`,body);else await api.post("/master/routing-groups",{...body,routingCode:groupForm.routingCode.trim(),itemCode:groupForm.itemCode});setGroupOpen(false);toast.success("저장되었습니다.");await loadGroups()}catch{toast.error("저장 중 오류가 발생했습니다.")}};
 const saveProcess=async()=>{if(!selected||!processForm.workstageCode)return;const target=selected.routingCode;const body={seq:Number(processForm.seq),workstageCode:processForm.workstageCode,executionType:processForm.executionType,jobOrderYn:processForm.jobOrderYn,subconSupplierCode:processForm.executionType==="SUBCON"?processForm.subconSupplierCode||undefined:undefined,standardTime:processForm.standardTime===""?undefined:Number(processForm.standardTime),setupTime:processForm.setupTime===""?undefined:Number(processForm.setupTime),useYn:processForm.useYn};try{if(editingProcess)await api.put(`/master/routing-groups/${target}/processes/${editingProcess.seq}`,body);else await api.post(`/master/routing-groups/${target}/processes`,body);if(target!==targetRef.current)return;setProcessOpen(false);toast.success("저장되었습니다.");await loadProcesses()}catch{if(target===targetRef.current)toast.error("저장 중 오류가 발생했습니다.")}};
 const confirmDeleteGroup=async()=>{if(!deleteGroup)return;try{await api.delete(`/master/routing-groups/${deleteGroup.routingCode}`);setDeleteGroup(null);toast.success("삭제되었습니다.");await loadGroups()}catch{toast.error("하위 공정을 먼저 삭제해야 합니다.")}};const confirmDeleteProcess=async()=>{if(!selected||!deleteProcess)return;try{await api.delete(`/master/routing-groups/${selected.routingCode}/processes/${deleteProcess.seq}`);setDeleteProcess(null);toast.success("삭제되었습니다.");await loadProcesses()}catch{toast.error("연결 자재를 먼저 삭제해야 합니다.")}};
 return <div className="grid h-full min-h-0 grid-cols-5 gap-3"><Card padding="none" className="col-span-2 min-h-0"><CardContent className="flex h-full flex-col p-3"><div className="flex gap-2"><Input value={search} onChange={e=>setSearch(e.target.value)} leftIcon={<Search className="h-4 w-4"/>}/><Button size="sm" onClick={()=>{setEditingGroup(null);setGroupForm(emptyGroup);setGroupOpen(true)}}><Plus className="h-4 w-4"/></Button></div><div className="mt-3 flex-1 overflow-auto">{loading?<RefreshCw className="m-auto animate-spin"/>:groups.map(g=><div key={g.routingCode} onClick={()=>setSelected(g)} className={`mb-1 flex cursor-pointer items-center gap-2 rounded p-2 text-xs ${selected?.routingCode===g.routingCode?"bg-primary text-white":"hover:bg-surface-hover"}`}><div className="min-w-0 flex-1"><b>{g.routingName}</b><div>{g.routingCode} · {g.itemCode}{g.itemName?` ${g.itemName}`:""}</div></div><button onClick={e=>{e.stopPropagation();setEditingGroup(g);setGroupForm({...g,description:g.description??""});setGroupOpen(true)}}><Edit2 className="h-3.5 w-3.5"/></button><button onClick={e=>{e.stopPropagation();setDeleteGroup(g)}}><Trash2 className="h-3.5 w-3.5 text-red-500"/></button></div>)}</div></CardContent></Card><Card padding="none" className="col-span-3 min-h-0"><CardContent className="flex h-full flex-col p-0"><div className="flex items-center justify-between border-b p-3"><b>{selected?.routingName??"공정 구성"}</b><Button size="sm" disabled={!selected} onClick={()=>{setEditingProcess(null);setProcessForm({...emptyProcess,seq:nextSeq});setProcessOpen(true)}}><Plus className="mr-1 h-4 w-4"/>공정</Button></div><div className="flex-1 overflow-auto"><table className="w-full text-xs"><thead><tr><th>순번</th><th>공정</th><th>구분</th><th>작업지시</th><th>사용</th><th/></tr></thead><tbody>{processes.map(p=><tr key={p.seq} onClick={()=>onSelectProcess({routingCode:p.routingCode,routingName:selected?.routingName??"",seq:p.seq,workstageCode:p.workstageCode,workstageName:p.workstageName??p.workstageCode})} className={`cursor-pointer border-t text-center ${selectedProcess?.seq===p.seq?"bg-primary/10":""}`}><td>{p.seq}</td><td className="py-2 text-left">{p.workstageName??p.workstageCode}<small className="ml-1">[{p.workstageCode}]</small></td><td>{p.executionType==="SUBCON"?"외주":"내작"}</td><td>{p.jobOrderYn}</td><td>{p.useYn}</td><td><button onClick={e=>{e.stopPropagation();setEditingProcess(p);setProcessForm({seq:String(p.seq),workstageCode:p.workstageCode,executionType:p.executionType,jobOrderYn:p.jobOrderYn,subconSupplierCode:p.subconSupplierCode??"",standardTime:p.standardTime==null?"":String(p.standardTime),setupTime:p.setupTime==null?"":String(p.setupTime),useYn:p.useYn});setProcessOpen(true)}}><Edit2 className="h-3.5 w-3.5"/></button><button onClick={e=>{e.stopPropagation();setDeleteProcess(p)}}><Trash2 className="h-3.5 w-3.5 text-red-500"/></button></td></tr>)}</tbody></table></div></CardContent></Card>
 <Modal isOpen={groupOpen} onClose={()=>setGroupOpen(false)} title={editingGroup?"라우팅 수정":"라우팅 등록"}><div className="space-y-3"><Input label="라우팅 코드" value={groupForm.routingCode} disabled={!!editingGroup} onChange={e=>setGroupForm(f=>({...f,routingCode:e.target.value}))}/><PartSelect label="품목" value={groupForm.itemCode} onChange={v=>setGroupForm(f=>({...f,itemCode:v}))} disabled={!!editingGroup} fullWidth/><Input label="라우팅명" value={groupForm.routingName} onChange={e=>setGroupForm(f=>({...f,routingName:e.target.value}))}/><Input label="설명" value={groupForm.description} onChange={e=>setGroupForm(f=>({...f,description:e.target.value}))}/><label><input type="checkbox" checked={groupForm.useYn==="Y"} onChange={e=>setGroupForm(f=>({...f,useYn:e.target.checked?"Y":"N"}))}/> 사용</label></div><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setGroupOpen(false)}>취소</Button><Button onClick={saveGroup}>저장</Button></div></Modal>
 <Modal isOpen={processOpen} onClose={()=>setProcessOpen(false)} title={editingProcess?"공정 수정":"공정 등록"}><div className="grid grid-cols-2 gap-3"><Input label="순번" type="number" value={processForm.seq} disabled={!!editingProcess} onChange={e=>setProcessForm(f=>({...f,seq:e.target.value}))}/><ProcessSelect label="공정" value={processForm.workstageCode} onChange={v=>setProcessForm(f=>({...f,workstageCode:v}))} fullWidth/><label>실행유형<select className="mt-1 h-10 w-full border bg-surface" value={processForm.executionType} onChange={e=>setProcessForm(f=>({...f,executionType:e.target.value as "INTERNAL"|"SUBCON",subconSupplierCode:e.target.value==="SUBCON"?f.subconSupplierCode:""}))}><option value="INTERNAL">내작</option><option value="SUBCON">외주</option></select></label><SupplierSelect label="외주 공급처" value={processForm.subconSupplierCode} onChange={v=>setProcessForm(f=>({...f,subconSupplierCode:v}))} disabled={processForm.executionType!=="SUBCON"} fullWidth/><Input label="표준시간" type="number" min="0" value={processForm.standardTime} onChange={e=>setProcessForm(f=>({...f,standardTime:e.target.value}))}/><Input label="준비시간" type="number" min="0" value={processForm.setupTime} onChange={e=>setProcessForm(f=>({...f,setupTime:e.target.value}))}/><label><input type="checkbox" checked={processForm.jobOrderYn==="Y"} onChange={e=>setProcessForm(f=>({...f,jobOrderYn:e.target.checked?"Y":"N"}))}/> 작업지시 생성</label><label><input type="checkbox" checked={processForm.useYn==="Y"} onChange={e=>setProcessForm(f=>({...f,useYn:e.target.checked?"Y":"N"}))}/> 사용</label></div><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setProcessOpen(false)}>취소</Button><Button onClick={saveProcess}>저장</Button></div></Modal><ConfirmModal isOpen={!!deleteGroup} onClose={()=>setDeleteGroup(null)} onConfirm={confirmDeleteGroup} title="라우팅 삭제" message="라우팅을 삭제하시겠습니까?" variant="danger"/><ConfirmModal isOpen={!!deleteProcess} onClose={()=>setDeleteProcess(null)} onConfirm={confirmDeleteProcess} title="공정 삭제" message="공정을 삭제하시겠습니까?" variant="danger"/></div>}
