import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const read = (path) => fs.readFileSync(path, "utf8");

const forbiddenRoutes = [
  "/system/pda-roles",
  "/system/comm-config",
  "/interface/dashboard",
  "/interface/log",
  "/interface/manual",
  "/consumables/master",
  "/consumables/label",
  "/consumables/receiving",
  "/consumables/issuing",
  "/consumables/stock",
  "/consumables/life",
  "/consumables/mount",
  "/master/vendor-barcode",
  "/inventory/stock",
  "/inventory/product-physical-inv",
  "/inventory/product-physical-inv-history",
  "/inventory/product-hold",
  "/master/iqc-item",
  "/master/iqc-part-spec",
  "/material/iqc",
  "/material/iqc-history",
  "/material/concession",
  "/production/monthly-plan",
  "/production/simulation",
  "/production/specification-setup",
  "/production/subprocess-kitting",
  "/production/input-assembly",
  "/production/order",
  "/production/result",
  "/production/order-result",
  "/production/progress",
  "/production/input-kiosk",
  "/production/input-inspect",
  "/production/input-equip",
  "/production/result-summary",
  "/production/wip-stock",
  "/production/fg-stock",
  "/production/wip-material-stock",
  "/production/wip-material-trans",
  "/production/repair",
  "/production/pack-result",
  "/production/sample-inspect",
  "/system/training",
  "/quality/aql",
  "/quality/audit",
  "/quality/capa",
  "/quality/change-control",
  "/quality/complaint",
  "/quality/control-plan",
  "/quality/defect",
  "/quality/defect-code",
  "/quality/fai",
  "/quality/inspect",
  "/quality/oqc",
  "/quality/oqc-history",
  "/quality/ppap",
  "/quality/request-inspect",
  "/quality/rework",
  "/quality/rework-history",
  "/quality/rework-inspect",
  "/quality/self-inspect-history",
  "/quality/spc",
  "/quality/trace",
  "/shipping/pack",
  "/shipping/order",
  "/shipping/box-stock",
  "/shipping/confirm",
  "/shipping/pallet",
  "/shipping/pallet-ship",
  "/shipping/history",
  "/shipping/return",
  "/shipping/customer-po",
  "/shipping/customer-po-status",
  "/product/receive",
  "/product/receipt-cancel",
  "/product/issue",
  "/product/issue-cancel",
  "/product/defect-transfer",
];

const forbiddenCodes = [
  "SYS_PDA_ROLE",
  "SYS_COMM",
  "IF_DASHBOARD",
  "IF_LOG",
  "IF_MANUAL",
  "INTERFACE",
  "CONS_MASTER",
  "CONS_LABEL",
  "CONS_RECEIVING",
  "CONS_ISSUING",
  "CONS_STOCK",
  "CONS_LIFE",
  "CONS_MOUNT",
  "CONSUMABLES",
  "MST_VENDOR_BARCODE",
  "PRODUCT_INVENTORY",
  "INV_PRODUCT_STOCK",
  "INV_PRODUCT_PHYSICAL_INV",
  "INV_PRODUCT_PHYSICAL_INV_HISTORY",
  "PROD_HOLD",
  "PRODUCTION",
  "PROD_MONTHLY_PLAN",
  "PROD_SIMULATION",
  "PROD_SPEC_SETUP",
  "PROD_KITTING",
  "PROD_INPUT_ASSEMBLY",
  "PROD_ORDER",
  "PROD_RESULT",
  "PROD_ORDER_RESULT",
  "PROD_PROGRESS",
  "PROD_INPUT_KIOSK",
  "PROD_INPUT_INSPECT",
  "PROD_INPUT_EQUIP",
  "PROD_RESULT_SUMMARY",
  "PROD_WIP_STOCK",
  "PROD_FG_STOCK",
  "PROD_WIP_MAT_STOCK",
  "PROD_WIP_MAT_TRANS",
  "PROD_REPAIR",
  "SHIP_PACK_RESULT",
  "PROD_SAMPLE_INSPECT",
  "QUALITY",
  "QC_IQC_ITEM",
  "QC_IQC_PART_SPEC",
  "QC_AQL",
  "QC_IQC",
  "QC_IQC_HISTORY",
  "QC_CONCESSION",
  "QC_DEFECT",
  "QC_DEFECT_CODE",
  "QC_REWORK_INSPECT",
  "QC_INSPECT",
  "QC_REQUEST_INSPECT",
  "QC_SELF_INSPECT_HISTORY",
  "QC_SAMPLE_INSPECT",
  "QC_OQC",
  "QC_OQC_HISTORY",
  "QC_TRACE",
  "QC_CHANGE",
  "QC_COMPLAINT",
  "QC_CAPA",
  "QC_FAI",
  "QC_PPAP",
  "QC_SPC",
  "QC_CONTROL_PLAN",
  "QC_AUDIT",
  "QC_REWORK",
  "QC_REWORK_HISTORY",
  "SYS_TRAINING",
  "SHIPPING",
  "SHIP_PACK",
  "SHIP_ORDER",
  "SHIP_BOX_STOCK",
  "SHIP_CONFIRM",
  "SHIP_PALLET",
  "SHIP_PALLET_SHIP",
  "SHIP_HISTORY",
  "SHIP_RETURN",
  "SHIP_CUST_PO",
  "SHIP_CUST_PO_STATUS",
  "PROD_RECEIVE",
  "PROD_RECEIPT_CANCEL",
  "PROD_ISSUE",
  "PROD_ISSUE_CANCEL",
  "PROD_DEFECT_TRANSFER",
];

const deletedRouteDirs = [
  "apps/frontend/src/app/(authenticated)/system/pda-roles",
  "apps/frontend/src/app/(authenticated)/system/comm-config",
  "apps/frontend/src/app/(authenticated)/interface",
  "apps/frontend/src/app/(authenticated)/consumables",
  "apps/frontend/src/app/(authenticated)/master/vendor-barcode",
  "apps/frontend/src/app/(authenticated)/inventory/stock",
  "apps/frontend/src/app/(authenticated)/inventory/product-physical-inv",
  "apps/frontend/src/app/(authenticated)/inventory/product-physical-inv-history",
  "apps/frontend/src/app/(authenticated)/inventory/product-hold",
  "apps/frontend/src/app/(authenticated)/quality",
  "apps/frontend/src/app/(authenticated)/master/iqc-item",
  "apps/frontend/src/app/(authenticated)/master/iqc-part-spec",
  "apps/frontend/src/app/(authenticated)/material/iqc",
  "apps/frontend/src/app/(authenticated)/material/iqc-history",
  "apps/frontend/src/app/(authenticated)/material/concession",
  "apps/frontend/src/app/(authenticated)/production",
  "apps/frontend/src/app/(authenticated)/system/training",
  "apps/frontend/src/app/(authenticated)/shipping",
  "apps/frontend/src/app/(authenticated)/product",
  "apps/backend/src/modules/ai-page-tools/registry/vendor-barcode-tools.provider.ts",
];

const deletedRegistryFiles = [
  "apps/frontend/src/components/layout/page-registries/system__pda-roles.generated.ts",
  "apps/frontend/src/components/layout/page-registries/system__comm-config.generated.ts",
  "apps/frontend/src/components/layout/page-registries/interface__dashboard.generated.ts",
  "apps/frontend/src/components/layout/page-registries/interface__log.generated.ts",
  "apps/frontend/src/components/layout/page-registries/interface__manual.generated.ts",
  "apps/frontend/src/components/layout/page-registries/consumables__master.generated.ts",
  "apps/frontend/src/components/layout/page-registries/consumables__label.generated.ts",
  "apps/frontend/src/components/layout/page-registries/consumables__receiving.generated.ts",
  "apps/frontend/src/components/layout/page-registries/consumables__issuing.generated.ts",
  "apps/frontend/src/components/layout/page-registries/consumables__stock.generated.ts",
  "apps/frontend/src/components/layout/page-registries/consumables__life.generated.ts",
  "apps/frontend/src/components/layout/page-registries/consumables__mount.generated.ts",
  "apps/frontend/src/components/layout/page-registries/master__vendor-barcode.generated.ts",
  "apps/frontend/src/components/layout/page-registries/inventory__stock.generated.ts",
  "apps/frontend/src/components/layout/page-registries/inventory__product-physical-inv.generated.ts",
  "apps/frontend/src/components/layout/page-registries/inventory__product-physical-inv-history.generated.ts",
  "apps/frontend/src/components/layout/page-registries/inventory__product-hold.generated.ts",
  "apps/frontend/src/components/layout/page-registries/master__iqc-item.generated.ts",
  "apps/frontend/src/components/layout/page-registries/master__iqc-part-spec.generated.ts",
  "apps/frontend/src/components/layout/page-registries/material__concession.generated.ts",
  "apps/frontend/src/components/layout/page-registries/material__iqc.generated.ts",
  "apps/frontend/src/components/layout/page-registries/material__iqc-history.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__monthly-plan.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__simulation.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__specification-setup.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__subprocess-kitting.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__input-assembly.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__order.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__result.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__order-result.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__progress.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__input-kiosk.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__input-inspect.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__input-equip.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__result-summary.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__wip-stock.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__fg-stock.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__wip-material-stock.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__wip-material-trans.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__repair.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__pack-result.generated.ts",
  "apps/frontend/src/components/layout/page-registries/production__sample-inspect.generated.ts",
  "apps/frontend/src/components/layout/page-registries/system__training.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__aql.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__audit.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__capa.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__change-control.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__complaint.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__control-plan.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__defect.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__defect-code.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__fai.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__inspect.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__oqc.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__oqc-history.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__ppap.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__request-inspect.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__rework.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__rework-history.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__rework-inspect.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__self-inspect-history.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__spc.generated.ts",
  "apps/frontend/src/components/layout/page-registries/quality__trace.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__pack.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__order.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__box-stock.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__confirm.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__pallet.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__pallet-ship.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__history.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__return.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__customer-po.generated.ts",
  "apps/frontend/src/components/layout/page-registries/shipping__customer-po-status.generated.ts",
  "apps/frontend/src/components/layout/page-registries/product__receive.generated.ts",
  "apps/frontend/src/components/layout/page-registries/product__receipt-cancel.generated.ts",
  "apps/frontend/src/components/layout/page-registries/product__issue.generated.ts",
  "apps/frontend/src/components/layout/page-registries/product__issue-cancel.generated.ts",
  "apps/frontend/src/components/layout/page-registries/product__defect-transfer.generated.ts",
];

test("삭제된 메뉴 페이지는 메뉴, 기본 카테고리, 레지스트리에 남지 않는다", () => {
  const routeSources = [
    "apps/frontend/src/config/menuConfig.ts",
    "apps/backend/src/modules/menu-categories/utils/menu-code-validator.ts",
    "apps/backend/src/modules/menu-categories/utils/default-menu-category-layout.ts",
    "apps/backend/src/seeds/menu-config.json",
    "apps/frontend/src/components/layout/pageRegistry.generated.ts",
    "apps/frontend/src/config/workflowConfig.ts",
    "apps/frontend/src/config/workflowMap.ts",
    "apps/frontend/public/help/manifest.json",
    "packages/shared/src/constants/menu.ts",
    "apps/backend/src/modules/ai-page-tools/ai-page-tools.module.ts",
  ].map((path) => [path, read(path)]);

  const codeSources = routeSources.filter(([path]) => ![
    "apps/frontend/src/config/workflowConfig.ts",
    "apps/frontend/src/config/workflowMap.ts",
  ].includes(path));

  for (const [path, source] of routeSources) {
    for (const route of forbiddenRoutes) {
      assert.equal(source.includes(route), false, `${path} must not reference deleted route ${route}`);
    }
  }

  for (const [path, source] of codeSources) {
    for (const code of forbiddenCodes) {
      assert.equal(source.includes(code), false, `${path} must not reference deleted menu code ${code}`);
    }
  }
});

test("삭제된 메뉴 페이지의 라우트 폴더와 생성 레지스트리 파일은 존재하지 않는다", () => {
  for (const path of [...deletedRouteDirs, ...deletedRegistryFiles]) {
    assert.equal(fs.existsSync(path), false, `${path} must be deleted`);
  }
});

test("은성 메뉴 상위 구조는 지정된 6개 카테고리만 사용한다", () => {
  const source = read("apps/frontend/src/config/menuConfig.ts");
  const menuArray = source.slice(source.indexOf("export const menuConfig"));
  const topLevelCodes = [...menuArray.matchAll(/^  \{\r?\n    code: "([^"]+)"/gm)].map((match) => match[1]);

  assert.deepEqual(topLevelCodes, [
    "MASTER",
    "OEE",
    "MATERIAL",
    "PROCESS_TRANSACTION",
    "PRODUCT_MGMT",
    "OUTSOURCING",
  ]);
});
