import { existsSync, readdirSync, readFileSync } from 'fs';
import { join } from 'path';

const oeeScriptRoot = join(__dirname, '../../../../../oracle_db_scripts/oee');
const deploymentManifestPath = join(oeeScriptRoot, 'deployment-manifest.json');
const routineDeploymentFiles = [
  '01_tables.sql',
  '03_tables_ext.sql',
  '07_mobile_prerequisites.sql',
  '12_resource_management_contract.sql',
  '04_view_plan_time.sql',
  '05_view_live.sql',
  '06_proc_build_summary.sql',
];
const manualCleanupFiles = [
  'manual/08_cleanup_legacy_oee_plants.sql',
  'manual/10_cleanup_unapproved_oee_resources.sql',
];
const manualBootstrapFiles = ['manual/09_bootstrap_dashboard_resources.sql'];
const protectedMasterTables = new Set([
  'IP_PRODUCT_WORKSTAGE',
  'IP_PRODUCT_LINE',
  'IMCN_MACHINE',
  'IP_PRODUCT_ST_MASTER',
  'IS_PRODUCT_SALE_PRICE',
  'IM_ITEM_UNIT_PRICE',
]);

function collectOeeSqlFiles(directory: string): string[] {
  if (!existsSync(directory)) {
    return [];
  }

  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const filePath = join(directory, entry.name);
    if (entry.isDirectory()) {
      return collectOeeSqlFiles(filePath);
    }
    return entry.isFile() && filePath.endsWith('.sql') ? [filePath] : [];
  });
}

function stripSqlComments(source: string): string {
  return source.replace(/--[^\r\n]*/g, ' ').replace(/\/\*[\s\S]*?\*\//g, ' ');
}

function extractTargets(source: string, operation: 'write' | 'read'): string[] {
  const keyword = operation === 'write'
    ? '(?:INSERT\\s+INTO|UPDATE(?!\\s+SET\\b)|DELETE\\s+FROM|MERGE\\s+INTO)'
    : '(?:FROM|JOIN)';
  const identifier = '(?:"([^"]+)"|([A-Z0-9_$#]+))';
  const pattern = new RegExp(
    `\\b${keyword}\\s+(?:${identifier}\\s*\\.\\s*)?${identifier}`,
    'gi',
  );

  return [...stripSqlComments(source).matchAll(pattern)].map((match) =>
    (match[3] ?? match[4]).toUpperCase(),
  );
}

describe('OEE MOBILE prerequisite DDL', () => {
  const source = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/07_mobile_prerequisites.sql'),
    'utf8',
  );
  const resourceBootstrap = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/manual/09_bootstrap_dashboard_resources.sql'),
    'utf8',
  );
  const resourceContract = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/12_resource_management_contract.sql'),
    'utf8',
  );
  const legacyPlantCleanup = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/manual/08_cleanup_legacy_oee_plants.sql'),
    'utf8',
  );
  const unapprovedResourceCleanup = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/manual/10_cleanup_unapproved_oee_resources.sql'),
    'utf8',
  );
  const baseTables = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/01_tables.sql'),
    'utf8',
  );
  const extendedTables = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/03_tables_ext.sql'),
    'utf8',
  );
  const planView = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/04_view_plan_time.sql'),
    'utf8',
  );
  const liveView = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/05_view_live.sql'),
    'utf8',
  );
  const summaryProcedure = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/06_proc_build_summary.sql'),
    'utf8',
  );

  it('contains the event contract and guarded Oracle objects', () => {
    expect(source.trimStart()).toMatch(/^DECLARE\b/);
    expect(source).toContain('CREATE TABLE OEE_DOWNTIME_EVENT');
    expect(source).toContain('EVENT_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY');
    expect(source).toContain('UQ_OEE_DTE_START_REQ UNIQUE (ORGANIZATION_ID, START_REQUEST_ID)');
    expect(source).not.toContain('UQ_OEE_DTE_END_REQ UNIQUE (ORGANIZATION_ID, END_REQUEST_ID)');
    expect(source).toContain('CREATE UNIQUE INDEX UX_OEE_DTE_END_REQ');
    expect(source).toContain('CASE WHEN END_REQUEST_ID IS NOT NULL THEN ORGANIZATION_ID END');
    expect(source).toContain('CASE WHEN END_REQUEST_ID IS NOT NULL THEN END_REQUEST_ID END');
    expect(source).toContain('CREATE UNIQUE INDEX UX_OEE_DTE_OPEN');
    expect(source).toContain('CASE WHEN END_TIME IS NULL THEN ORGANIZATION_ID END');
    expect(source).toContain('CK_OEE_DTE_RESOURCE');
    expect(source).toContain('CK_OEE_DTE_PROCESS');
    expect(source).toContain('CK_OEE_DTE_WORK_SEGMENT');
    expect(source).toMatch(/USER_TABLES/);
    expect(source).toMatch(/USER_CONSTRAINTS/);
    expect(source).toMatch(/USER_INDEXES/);
    expect(source.split(/\r?\n/).filter((line) => line.trim() === '/').length).toBeGreaterThan(1);
  });

  it('keeps the fixed resource projection as a manual bootstrap only', () => {
    expect(resourceBootstrap).toContain('One-time bootstrap only');
    expect(resourceBootstrap).toContain('IP_PRODUCT_LINE');
    expect(resourceBootstrap).not.toContain('PLANTS');
    expect(resourceBootstrap).not.toContain('PROD2');
  });

  it('enforces one managed OEE resource per organization and line', () => {
    expect(resourceContract.trimStart()).toMatch(/^DECLARE\b/);
    expect(resourceContract).toContain('REF_CODE NOT NULL');
    expect(resourceContract).toContain('ORGANIZATION_ID, REF_CODE');
    expect(resourceContract).toContain('CK_OEE_RESOURCE_PROCESS');
    expect(resourceContract).toContain('CK_OEE_RESOURCE_TYPE');
    expect(resourceContract).toContain('CK_OEE_RESOURCE_USE');
    expect(baseTables).toContain("RESOURCE_TYPE IN ('LINE', 'CELL')");
    expect(baseTables).toContain('OEE_RESOURCE (ORGANIZATION_ID, REF_CODE)');
  });

  it('only deletes the exact legacy OEE PLANTS seed hierarchy', () => {
    expect(legacyPlantCleanup.trimStart()).toMatch(/^BEGIN\b/);
    expect(legacyPlantCleanup).toContain('DELETE FROM PLANTS');
    expect(legacyPlantCleanup).toContain("CREATED_BY = 'SYSTEM'");
    expect(legacyPlantCleanup).toContain("LINE_CODE = 'PROD2'");
    expect(legacyPlantCleanup).not.toMatch(/\b(?:INSERT|MERGE|UPDATE)\b/);
  });

  it('guards cleanup of the unapproved 50-64 OEE projection and exact verification event', () => {
    expect(unapprovedResourceCleanup.trimStart()).toMatch(/^DECLARE\b/);
    expect(unapprovedResourceCleanup).toContain('EVENT_ID = 22');
    expect(unapprovedResourceCleanup).toContain('START_REQUEST_ID');
    expect(unapprovedResourceCleanup).toContain('END_REQUEST_ID');
    expect(unapprovedResourceCleanup).toContain('RAISE_APPLICATION_ERROR');
    expect(unapprovedResourceCleanup).toContain("REF_CODE BETWEEN '50' AND '64'");
    expect(unapprovedResourceCleanup).not.toMatch(/DELETE FROM IP_PRODUCT_LINE/);
  });

  it('deploys the dashboard schema as guarded A-J objects without temporary shift seeds', () => {
    expect(baseTables.trimStart()).toMatch(/^DECLARE\b/);
    expect(extendedTables.trimStart()).toMatch(/^DECLARE\b/);
    expect(baseTables).toContain("SHIFT IN ('A','B','C','D','E','F','G','H','I','J')");
    expect(extendedTables).toContain("SHIFT IN ('A','B','C','D','E','F','G','H','I','J')");
    expect(extendedTables).not.toContain('INSERT INTO OEE_WORKTIME_RANGE');
    expect(extendedTables).not.toMatch(/'DAY'|'NIGHT'/);
  });

  it('builds live OEE from the real A-J worktime and mobile downtime sources', () => {
    expect(planView).toContain('ICOM_WORKTIME_RANGES');
    expect(planView).not.toContain('OEE_WORKTIME_RANGE');
    expect(planView).toContain('WORK_TYPE AS SHIFT');
    expect(planView).toContain("LENGTH(TRIM(START_TIME)) = 4");
    expect(planView).toContain("TRIM(START_TIME) || '00'");
    expect(planView).toContain("r.PROCESS_CODE IN ('SMT', 'ASSY')");
    expect(planView).toContain("r.RESOURCE_TYPE IN ('LINE', 'CELL')");
    expect(liveView).toContain('OEE_DOWNTIME_EVENT');
    expect(liveView).not.toContain('OEE_OPERATION_LOG');
    expect(liveView).toContain('SEGMENT_START_TIME');
    expect(liveView).toContain('SEGMENT_END_TIME');
    expect(liveView).not.toContain("pt.WORK_DATE = TRUNC(SYSDATE - (8.5 / 24))");
    expect(summaryProcedure.trimStart()).toMatch(/^BEGIN\b/);
    expect(summaryProcedure).toContain('CREATE OR REPLACE NONEDITIONABLE PROCEDURE');
  });

  it('keeps routine deployment separate from manual cleanup and the removed production2 seed', () => {
    expect(existsSync(deploymentManifestPath)).toBe(true);
    expect(existsSync(join(oeeScriptRoot, manualCleanupFiles[0]))).toBe(true);
    expect(existsSync(join(oeeScriptRoot, manualCleanupFiles[1]))).toBe(true);
    expect(existsSync(join(oeeScriptRoot, '08_cleanup_legacy_oee_plants.sql'))).toBe(false);
    expect(existsSync(join(oeeScriptRoot, '10_cleanup_unapproved_oee_resources.sql'))).toBe(false);
    expect(existsSync(join(oeeScriptRoot, '11_seed_production2_equipment.sql'))).toBe(false);
    expect(existsSync(join(oeeScriptRoot, '09_seed_dashboard_resources.sql'))).toBe(false);

    const manifest = JSON.parse(readFileSync(deploymentManifestPath, 'utf8')) as {
      routineDeployment: string[];
      manualBootstrap: string[];
      manualCleanup: string[];
    };

    expect(manifest.routineDeployment).toEqual(routineDeploymentFiles);
    expect(manifest.manualBootstrap).toEqual(manualBootstrapFiles);
    expect(manifest.manualCleanup).toEqual(manualCleanupFiles);
    expect(manifest.routineDeployment).not.toContain('09_seed_dashboard_resources.sql');

    for (const referencedFile of [
      ...manifest.routineDeployment,
      ...manifest.manualBootstrap,
      ...manifest.manualCleanup,
    ]) {
      expect(existsSync(join(oeeScriptRoot, referencedFile))).toBe(true);
    }
  });

  it('does not target protected master tables from any OEE SQL file', () => {
    const violations = collectOeeSqlFiles(oeeScriptRoot).flatMap((filePath) => {
      const source = readFileSync(filePath, 'utf8');
      return extractTargets(source, 'write')
        .filter((target) => protectedMasterTables.has(target))
        .map((target) => `${filePath}: ${target}`);
    });

    expect(violations).toEqual([]);
  });

  it('keeps the manual bootstrap read-only for IP_PRODUCT_LINE', () => {
    const writeTargets = extractTargets(resourceBootstrap, 'write');
    const protectedReadTargets = extractTargets(resourceBootstrap, 'read')
      .filter((target) => protectedMasterTables.has(target));

    expect(resourceBootstrap).toMatch(/\bFROM\s+IP_PRODUCT_LINE\b/i);
    expect(new Set(writeTargets)).toEqual(new Set(['OEE_RESOURCE']));
    expect(new Set(protectedReadTargets)).toEqual(new Set(['IP_PRODUCT_LINE']));
  });

  it('detects Oracle hint variants that write protected masters', () => {
    for (const sql of [
      'INSERT /*+ APPEND */ INTO IP_PRODUCT_LINE (LINE_CODE) VALUES (\'01\')',
      'UPDATE /*+ INDEX(t) */ IMCN_MACHINE t SET t.MACHINE_NAME = \'X\'',
      'DELETE /*+ FULL(t) */ FROM IP_PRODUCT_ST_MASTER t',
      'MERGE /*+ USE_NL(t) */ INTO IS_PRODUCT_SALE_PRICE t USING DUAL ON (1=0)',
    ]) {
      expect(extractTargets(sql, 'write').some((target) => protectedMasterTables.has(target))).toBe(true);
    }
  });
});
