import { readFileSync } from 'fs';
import { join } from 'path';

describe('OEE MOBILE prerequisite DDL', () => {
  const source = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/07_mobile_prerequisites.sql'),
    'utf8',
  );
  const cellSeed = readFileSync(
    join(__dirname, '../../../../../oracle_db_scripts/oee/08_seed_production2_cells.sql'),
    'utf8',
  );

  it('contains the event contract and guarded Oracle objects', () => {
    expect(source.trimStart()).toMatch(/^DECLARE\b/);
    expect(source).toContain('CREATE TABLE OEE_DOWNTIME_EVENT');
    expect(source).toContain('EVENT_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY');
    expect(source).toContain('UQ_OEE_DTE_START_REQ UNIQUE (ORGANIZATION_ID, START_REQUEST_ID)');
    expect(source).not.toContain('UQ_OEE_DTE_END_REQ UNIQUE (ORGANIZATION_ID, END_REQUEST_ID)');
    expect(source).toContain('CREATE UNIQUE INDEX UX_OEE_DTE_END_REQ');
    expect(source).toContain('CASE WHEN END_REQUEST_ID IS NOT NULL THEN ORGANIZATION_ID END');
    expect(source).toContain('CASE WHEN END_REQUEST_ID IS NOT NULL THEN END_REQUEST_ID END');
    expect(source).toContain('CREATE UNIQUE INDEX UX_OEE_DTE_OPEN');
    expect(source).toContain('CASE WHEN END_TIME IS NULL THEN ORGANIZATION_ID END');
    expect(source).toContain('CK_OEE_DTE_RESOURCE');
    expect(source).toContain('CK_OEE_DTE_PROCESS');
    expect(source).toContain('CK_OEE_DTE_WORK_SEGMENT');
    expect(source).toMatch(/USER_TABLES/);
    expect(source).toMatch(/USER_CONSTRAINTS/);
    expect(source).toMatch(/USER_INDEXES/);
    expect(source.split(/\r?\n/).filter((line) => line.trim() === '/').length).toBeGreaterThan(1);
  });

  it('keeps existing CELL master values and rejects cross-tenant key ownership', () => {
    expect(cellSeed.trimStart()).toMatch(/^DECLARE\b/);
    expect(cellSeed).toContain('RAISE_APPLICATION_ERROR');
    expect(cellSeed).toContain('WHEN NOT MATCHED THEN INSERT');
    expect(cellSeed).not.toContain('WHEN MATCHED THEN UPDATE');
    expect(cellSeed).not.toMatch(/UPDATE\s+SET/i);
    expect(cellSeed.match(/'CELL'\s*,\s*\d+\s*,\s*'Y'\s+FROM DUAL/g)).toHaveLength(15);
  });
});
