-- 메뉴 카테고리(사이드바 구성) 테이블
-- 근거: apps/backend/src/entities/menu-category.entity.ts, menu-category-item.entity.ts
-- 사용 화면: /system/menu-categories. 배포 도구: oracle-db 스킬 execute-file ('/' 구분).
-- 단일 사업장이지만 tenant 컬럼(COMPANY/PLANT_CD)은 엔티티 스키마 그대로 유지.

CREATE TABLE MENU_CATEGORIES (
  COMPANY        VARCHAR2(20)  NOT NULL,
  PLANT_CD       VARCHAR2(20)  NOT NULL,
  CATEGORY_CODE  VARCHAR2(50)  NOT NULL,
  LABEL_KEY      VARCHAR2(200) NOT NULL,
  ICON_NAME      VARCHAR2(50),
  SORT_ORDER     NUMBER        DEFAULT 0   NOT NULL,
  IS_ACTIVE      CHAR(1)       DEFAULT 'Y' NOT NULL,
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY     VARCHAR2(50)  NOT NULL,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_MENU_CATEGORIES PRIMARY KEY (COMPANY, PLANT_CD, CATEGORY_CODE)
)
/

CREATE TABLE MENU_CATEGORY_ITEMS (
  COMPANY        VARCHAR2(20)  NOT NULL,
  PLANT_CD       VARCHAR2(20)  NOT NULL,
  MENU_CODE      VARCHAR2(100) NOT NULL,
  CATEGORY_CODE  VARCHAR2(50)  NOT NULL,
  SORT_ORDER     NUMBER        DEFAULT 0   NOT NULL,
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY     VARCHAR2(50)  NOT NULL,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_MENU_CATEGORY_ITEMS PRIMARY KEY (COMPANY, PLANT_CD, MENU_CODE),
  CONSTRAINT FK_MENU_CAT_ITEM_CAT FOREIGN KEY (COMPANY, PLANT_CD, CATEGORY_CODE)
    REFERENCES MENU_CATEGORIES (COMPANY, PLANT_CD, CATEGORY_CODE)
)
/

CREATE INDEX IX_MENU_CAT_ITEM_CAT ON MENU_CATEGORY_ITEMS (COMPANY, PLANT_CD, CATEGORY_CODE)
/
