-- ERP 품목 마스터 인터페이스
-- 대상: ITEM_MASTERS (COMPANY='40', PLANT_CD='1000')
-- 소스: XMES_INV_ITEM_MASTER_V@ERP_PROD (ORGANIZATION_ID=308)
-- 기준: PURCHASE_ORDER_ITEMS에 존재하는 품목만 동기화
-- 동작: 기존 전체 삭제 후 ERP 기준 재적재 (TRUNCATE+INSERT 방식)
DELETE FROM ITEM_MASTERS WHERE COMPANY = '40' AND PLANT_CD = '1000'
/
INSERT INTO ITEM_MASTERS (
    ITEM_CODE, PART_NO, ITEM_NAME, ITEM_TYPE, SPEC, UNIT,
    BOX_QTY, USE_YN, IQC_FLAG,
    COMPANY, PLANT_CD, CREATED_BY, CREATED_AT, UPDATED_AT, ERP_LAST_UPD_DATE
)
SELECT
    E.ITEM_CODE,
    E.ITEM_CODE,   -- PART_NO: ERP는 품번 미제공 → 품목코드로 대체 (NOT NULL 보장)
    E.ITEM_NAME,
    E.ITEM_TYPE,
    E.SPEC,
    NVL(E.UOM, 'EA'),
    E.BOX_QTY,
    'Y',
    'Y',
    '40',
    '1000',
    'ERP-IF',
    SYSTIMESTAMP,
    SYSTIMESTAMP,
    E.LAST_UPDATE_DATE
FROM XMES_INV_ITEM_MASTER_V@ERP_PROD E
JOIN (
    SELECT DISTINCT ITEM_CODE
    FROM PURCHASE_ORDER_ITEMS
    WHERE COMPANY = '40' AND PLANT_CD = '1000'
) POI ON E.ITEM_CODE = POI.ITEM_CODE
WHERE E.ORGANIZATION_ID = 308
/
COMMIT
/
