/**
 * @file 메뉴 코드 유효성 검증 — 프론트 menuConfig.ts의 leaf 메뉴 코드와 동기화된 화이트리스트
 * @description 운영 정책상 신규 페이지 추가 시 개발자가 이 파일과 menuConfig.ts를 동시에 수정한다.
 *              자동 동기화 없이 명시적 등록을 유지한다.
 *
 * 초보자 가이드:
 * 1. 새 페이지 추가 시: menuConfig.ts에 leaf 추가 + KNOWN_LEAF_CODES에 코드 추가 (둘 다)
 * 2. menu-category-items API는 이 화이트리스트를 통과한 코드만 받아들임
 * 3. SYS_MENU_CATEGORY는 관리 화면 자체의 메뉴 코드
 */
const KNOWN_LEAF_CODES: ReadonlySet<string> = new Set<string>([
  // 단독 메뉴 (__ROOT__ 매핑 대상)
  'DASHBOARD', 'WORKFLOW',
  // MONITORING
  'MON_EQUIP_STATUS',
  // OEE
  'OEE_DASHBOARD','OEE_DRILLDOWN','OEE_LOSS','OEE_ENTRY','OEE_MST_RESOURCE','OEE_MST_REASON',
  // MASTER
  'MST_PART','MST_BOM','MST_PARTNER','EQUIP_MASTER','MST_PROCESS','MST_PROD_LINE',
  'MST_ROUTING','MST_WORK_CALENDAR','MST_WORKER','MST_WORK_INST','MST_WAREHOUSE',
  'MST_LABEL','MST_PROCESS_CAPA','SYS_DOCUMENT',
  // INVENTORY
  'INV_MAT_STOCK','INV_TRANSACTION','INV_MAT_PHYSICAL_INV','INV_MAT_PHYSICAL_INV_APPLY','INV_MAT_PHYSICAL_INV_HISTORY',
  'MAT_HOLD',
  // PRODUCT_MGMT
  'PROD_RECEIVE','PROD_RECEIPT_CANCEL','PROD_ISSUE','PROD_ISSUE_CANCEL','PROD_DEFECT_TRANSFER',
  // MATERIAL
  'MAT_REQUEST','MAT_REQUEST_OTHER',
  'MAT_ISSUE','MAT_ISSUE_OTHER','MAT_ISSUE_HIST','MAT_LOT','MAT_LOT_SPLIT','MAT_LOT_MERGE','MAT_SHELF_LIFE',
  'MAT_SHELF_LIFE_REINSPECT','MAT_SHELF_LIFE_HISTORY','MAT_SCRAP',
  'MAT_STOCK_TRANSFER','MAT_ADJUSTMENT','MAT_MISC_RECEIPT','MAT_RECEIPT_CANCEL',
  // EQUIPMENT
  'EQ_MOLD_MGMT','EQUIP_INSPECT_ITEM_MASTER','EQUIP_INSPECT_ITEM','EQUIP_INSPECT_CALENDAR',
  'EQUIP_DAILY','EQUIP_PERIODIC_CALENDAR','EQUIP_PERIODIC','EQUIP_HISTORY',
  'EQUIP_PM_PLAN','EQUIP_PM_CALENDAR','EQUIP_PM_RESULT',
  // SHIPPING
  'SHIP_PACK','SHIP_BOX_STOCK','SHIP_PALLET','SHIP_PALLET_SHIP','SHIP_CONFIRM','SHIP_ORDER','SHIP_HISTORY','SHIP_RETURN',
  // OUTSOURCING
  'OUT_VENDOR','OUT_ORDER','OUT_RECEIVE',
  // SYSTEM
  'SYS_COMPANY','SYS_DEPT','SYS_USER','SYS_ROLE','SYS_CONFIG',
  'SYS_CODE','SYS_SCHEDULER','SYS_ER_VIEW','SYS_MENU_CATEGORY','SYS_IMPR_REQ',
]);

export function isValidMenuCode(code: string): boolean {
  return KNOWN_LEAF_CODES.has(code);
}

export function listKnownMenuCodes(): string[] {
  return Array.from(KNOWN_LEAF_CODES);
}
