-- OEE 비가동사유 6대 로스 최소 시드
-- 근거: docs/plans/2026-07-06-oee-foundation.md Task 1 Step 2
-- ORGANIZATION_ID=1 (은성 단일 사업장). 배포 도구: oracle-db 스킬 execute-file ('/' 구분).

INSERT INTO OEE_DOWNTIME_REASON (REASON_CODE, ORGANIZATION_ID, PROCESS_CODE, REASON_NAME, LOSS_BUCKET, OEE_FACTOR, SORT_ORDER) VALUES ('MAT_WAIT',   1, '*', '자재 대기',     'MATERIAL',        'AVAILABILITY', 10)
/
INSERT INTO OEE_DOWNTIME_REASON (REASON_CODE, ORGANIZATION_ID, PROCESS_CODE, REASON_NAME, LOSS_BUCKET, OEE_FACTOR, SORT_ORDER) VALUES ('SETUP',      1, '*', '셋업/단품교체', 'SETUP',           'AVAILABILITY', 20)
/
INSERT INTO OEE_DOWNTIME_REASON (REASON_CODE, ORGANIZATION_ID, PROCESS_CODE, REASON_NAME, LOSS_BUCKET, OEE_FACTOR, SORT_ORDER) VALUES ('BREAKDOWN',  1, '*', '설비 고장정지', 'AVAIL_DOWN',      'AVAILABILITY', 30)
/
INSERT INTO OEE_DOWNTIME_REASON (REASON_CODE, ORGANIZATION_ID, PROCESS_CODE, REASON_NAME, LOSS_BUCKET, OEE_FACTOR, SORT_ORDER) VALUES ('NO_OPER',    1, '*', '작업자 부재',   'AVAIL_DOWN',      'AVAILABILITY', 40)
/
INSERT INTO OEE_DOWNTIME_REASON (REASON_CODE, ORGANIZATION_ID, PROCESS_CODE, REASON_NAME, LOSS_BUCKET, OEE_FACTOR, SORT_ORDER) VALUES ('MINOR_STOP', 1, '*', '미세정지',      'PERF_MINOR_STOP', 'PERFORMANCE',  50)
/
INSERT INTO OEE_DOWNTIME_REASON (REASON_CODE, ORGANIZATION_ID, PROCESS_CODE, REASON_NAME, LOSS_BUCKET, OEE_FACTOR, SORT_ORDER) VALUES ('SPEED_LOSS', 1, '*', '속도저하',      'PERF_SPEED',      'PERFORMANCE',  60)
/
INSERT INTO OEE_DOWNTIME_REASON (REASON_CODE, ORGANIZATION_ID, PROCESS_CODE, REASON_NAME, LOSS_BUCKET, OEE_FACTOR, SORT_ORDER) VALUES ('PREPROC_WAIT', 1, '*', '前공정 대기', 'MATERIAL',        'AVAILABILITY', 15)
/
COMMIT
/
