-- SHIFT is retained for API compatibility; values are canonical A-J work segments.
CREATE OR REPLACE NONEDITIONABLE VIEW V_OEE_PLAN_TIME AS
WITH dates AS (
  SELECT TRUNC(SYSDATE - (8.5 / 24)) AS WORK_DATE FROM DUAL
  UNION
  SELECT WORK_DATE FROM OEE_PLAN_TIME
  UNION
  SELECT WORK_DATE FROM OEE_PRODUCTION_RESULT
  UNION
  SELECT WORK_DATE FROM OEE_DOWNTIME_EVENT
), ranges AS (
  SELECT ORGANIZATION_ID, RANGE_TYPE, WORK_TYPE AS SHIFT,
         TO_NUMBER(SUBSTR(CASE WHEN LENGTH(TRIM(START_TIME)) = 4 THEN TRIM(START_TIME) || '00' ELSE TRIM(START_TIME) END, 1, 2)) * 3600
           + TO_NUMBER(SUBSTR(CASE WHEN LENGTH(TRIM(START_TIME)) = 4 THEN TRIM(START_TIME) || '00' ELSE TRIM(START_TIME) END, 3, 2)) * 60
           + TO_NUMBER(SUBSTR(CASE WHEN LENGTH(TRIM(START_TIME)) = 4 THEN TRIM(START_TIME) || '00' ELSE TRIM(START_TIME) END, 5, 2)) AS START_SECONDS,
         TO_NUMBER(SUBSTR(CASE WHEN LENGTH(TRIM(END_TIME)) = 4 THEN TRIM(END_TIME) || '00' ELSE TRIM(END_TIME) END, 1, 2)) * 3600
           + TO_NUMBER(SUBSTR(CASE WHEN LENGTH(TRIM(END_TIME)) = 4 THEN TRIM(END_TIME) || '00' ELSE TRIM(END_TIME) END, 3, 2)) * 60
           + TO_NUMBER(SUBSTR(CASE WHEN LENGTH(TRIM(END_TIME)) = 4 THEN TRIM(END_TIME) || '00' ELSE TRIM(END_TIME) END, 5, 2)) AS END_SECONDS,
         NVL(TO_NUMBER(NULLIF(TRIM(ATTRIBUTE01), '')), 0) AS START_OFFSET,
         NVL(TO_NUMBER(NULLIF(TRIM(ATTRIBUTE02), '')), 0) AS END_OFFSET
    FROM ICOM_WORKTIME_RANGES
   WHERE RANGE_TYPE IN ('SMTWORKTIME', 'WORKTIME')
     AND WORK_TYPE IN ('A','B','C','D','E','F','G','H','I','J')
), segments AS (
  SELECT r.RESOURCE_ID, r.ORGANIZATION_ID, r.PROCESS_CODE, d.WORK_DATE, wt.SHIFT,
         CAST(d.WORK_DATE AS TIMESTAMP)
           + NUMTODSINTERVAL(wt.START_OFFSET, 'DAY')
           + NUMTODSINTERVAL(wt.START_SECONDS, 'SECOND') AS SEGMENT_START_TIME,
         CAST(d.WORK_DATE AS TIMESTAMP)
           + NUMTODSINTERVAL(wt.END_OFFSET, 'DAY')
           + NUMTODSINTERVAL(wt.END_SECONDS, 'SECOND') AS SEGMENT_END_TIME
    FROM OEE_RESOURCE r
    CROSS JOIN dates d
    JOIN ranges wt
      ON wt.ORGANIZATION_ID = r.ORGANIZATION_ID
     AND wt.RANGE_TYPE = CASE WHEN r.PROCESS_CODE = 'SMT' THEN 'SMTWORKTIME' ELSE 'WORKTIME' END
   WHERE r.USE_YN = 'Y'
     AND r.PROCESS_CODE IN ('SMT', 'ASSY')
     AND r.RESOURCE_TYPE IN ('LINE', 'CELL')
)
SELECT s.RESOURCE_ID, s.ORGANIZATION_ID, s.PROCESS_CODE, s.WORK_DATE, s.SHIFT,
       s.SEGMENT_START_TIME, s.SEGMENT_END_TIME,
       NVL(ov.PLANNED_MINUTES,
         (CAST(s.SEGMENT_END_TIME AS DATE) - CAST(s.SEGMENT_START_TIME AS DATE)) * 1440) AS PLANNED_MINUTES,
       NVL(ov.PLANNED_STOP_MINUTES, 0) AS PLANNED_STOP_MINUTES,
       NVL(ov.NET_LOAD_MINUTES,
         (CAST(s.SEGMENT_END_TIME AS DATE) - CAST(s.SEGMENT_START_TIME AS DATE)) * 1440) AS NET_LOAD_MINUTES
  FROM segments s
  LEFT JOIN OEE_PLAN_TIME ov
    ON ov.RESOURCE_ID = s.RESOURCE_ID
   AND ov.ORGANIZATION_ID = s.ORGANIZATION_ID
   AND ov.WORK_DATE = s.WORK_DATE
   AND ov.SHIFT = s.SHIFT
   AND ov.OVERRIDE_YN = 'Y'
 WHERE s.SEGMENT_END_TIME > s.SEGMENT_START_TIME
/
