-- V_OEE_PLAN_TIME: 계획가동시간 파생 뷰 (공정별·2교대)
-- 근거: docs/plans/2026-07-06-oee-dashboard.md Task 2
-- 근무일(HOLIDAY_YN='N') × 공정 근무시간대(WORK/BREAK). 야간(end<start)은 +1440. OVERRIDE_YN='Y' 우선.

CREATE OR REPLACE VIEW V_OEE_PLAN_TIME AS
WITH wt AS (
  SELECT ORGANIZATION_ID, PROCESS_CODE, SHIFT,
         SUM(CASE WHEN RANGE_TYPE='WORK'  THEN DUR ELSE 0 END) AS PLANNED,
         SUM(CASE WHEN RANGE_TYPE='BREAK' THEN DUR ELSE 0 END) AS BRK
    FROM (
      SELECT ORGANIZATION_ID, PROCESS_CODE, SHIFT, RANGE_TYPE,
             CASE WHEN E_MIN >= S_MIN THEN E_MIN - S_MIN ELSE E_MIN - S_MIN + 1440 END AS DUR
        FROM (
          SELECT ORGANIZATION_ID, PROCESS_CODE, SHIFT, RANGE_TYPE,
                 TO_NUMBER(SUBSTR(START_HHMM,1,2))*60 + TO_NUMBER(SUBSTR(START_HHMM,3,2)) AS S_MIN,
                 TO_NUMBER(SUBSTR(END_HHMM,1,2))*60   + TO_NUMBER(SUBSTR(END_HHMM,3,2))   AS E_MIN
            FROM OEE_WORKTIME_RANGE
        )
    )
   GROUP BY ORGANIZATION_ID, PROCESS_CODE, SHIFT
)
SELECT r.RESOURCE_ID, r.ORGANIZATION_ID, c.WORK_DATE, wt.SHIFT,
       NVL(ov.PLANNED_MINUTES,      wt.PLANNED)              AS PLANNED_MINUTES,
       NVL(ov.PLANNED_STOP_MINUTES, wt.BRK)                  AS PLANNED_STOP_MINUTES,
       NVL(ov.NET_LOAD_MINUTES,     wt.PLANNED - wt.BRK)     AS NET_LOAD_MINUTES
  FROM OEE_RESOURCE r
  JOIN OEE_WORK_CALENDAR c ON c.ORGANIZATION_ID = r.ORGANIZATION_ID AND c.HOLIDAY_YN = 'N'
  JOIN wt ON wt.ORGANIZATION_ID = r.ORGANIZATION_ID AND wt.PROCESS_CODE = r.PROCESS_CODE
  LEFT JOIN OEE_PLAN_TIME ov ON ov.RESOURCE_ID = r.RESOURCE_ID AND ov.WORK_DATE = c.WORK_DATE
                            AND ov.SHIFT = wt.SHIFT AND ov.OVERRIDE_YN = 'Y'
 WHERE r.USE_YN = 'Y'
/
