CREATE OR REPLACE NONEDITIONABLE VIEW V_OEE_PLAN_TIME AS
WITH dates AS (
  SELECT TRUNC(SYSDATE - (8.5 / 24)) AS WORK_DATE FROM DUAL
  UNION
  SELECT WORK_DATE FROM OEE_PLAN_TIME
  UNION
  SELECT WORK_DATE FROM OEE_PRODUCTION_RESULT
  UNION
  SELECT WORK_DATE FROM OEE_DOWNTIME_EVENT
), shift_windows AS (
  SELECT 'DAY' AS SHIFT,
         '08:30:00' AS START_CLOCK,
         '17:30:00' AS END_CLOCK,
         0 AS START_OFFSET,
         0 AS END_OFFSET
    FROM DUAL
  UNION ALL
  SELECT 'NIGHT',
         '20:30:00',
         '05:30:00',
         0,
         1
    FROM DUAL
), segments AS (
  SELECT r.RESOURCE_ID, r.ORGANIZATION_ID, r.PROCESS_CODE, d.WORK_DATE, w.SHIFT,
          CAST(d.WORK_DATE AS TIMESTAMP)
            + NUMTODSINTERVAL(w.START_OFFSET, 'DAY')
            + NUMTODSINTERVAL(
                TO_NUMBER(SUBSTR(w.START_CLOCK, 1, 2)) * 3600
                  + TO_NUMBER(SUBSTR(w.START_CLOCK, 4, 2)) * 60
                  + TO_NUMBER(SUBSTR(w.START_CLOCK, 7, 2)),
                'SECOND'
              ) AS SEGMENT_START_TIME,
          CAST(d.WORK_DATE AS TIMESTAMP)
            + NUMTODSINTERVAL(w.END_OFFSET, 'DAY')
            + NUMTODSINTERVAL(
                TO_NUMBER(SUBSTR(w.END_CLOCK, 1, 2)) * 3600
                  + TO_NUMBER(SUBSTR(w.END_CLOCK, 4, 2)) * 60
                  + TO_NUMBER(SUBSTR(w.END_CLOCK, 7, 2)),
                'SECOND'
              ) AS SEGMENT_END_TIME
     FROM OEE_RESOURCE r
     CROSS JOIN dates d
     CROSS JOIN shift_windows w
    WHERE r.USE_YN = 'Y'
      AND r.PROCESS_CODE IN ('SMT', 'ASSY')
      AND r.RESOURCE_TYPE IN ('LINE', 'CELL')
)
SELECT s.RESOURCE_ID, s.ORGANIZATION_ID, s.PROCESS_CODE, s.WORK_DATE, s.SHIFT,
       s.SEGMENT_START_TIME, s.SEGMENT_END_TIME,
       NVL(ov.PLANNED_MINUTES,
         540) AS PLANNED_MINUTES,
       NVL(ov.PLANNED_STOP_MINUTES, 60) AS PLANNED_STOP_MINUTES,
       NVL(ov.NET_LOAD_MINUTES, 480) AS NET_LOAD_MINUTES
  FROM segments s
  LEFT JOIN OEE_PLAN_TIME ov
    ON ov.RESOURCE_ID = s.RESOURCE_ID
   AND ov.ORGANIZATION_ID = s.ORGANIZATION_ID
   AND ov.WORK_DATE = s.WORK_DATE
   AND ov.SHIFT = s.SHIFT
   AND ov.OVERRIDE_YN = 'Y'
 WHERE s.SEGMENT_END_TIME > s.SEGMENT_START_TIME
/
