CREATE OR REPLACE NONEDITIONABLE VIEW V_OEE_LIVE AS
WITH clock_now AS (
  SELECT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) AS NOW_KST FROM DUAL
), elapsed_plan AS (
  SELECT pt.*, n.NOW_KST,
         LEAST(pt.SEGMENT_END_TIME, n.NOW_KST) AS EFFECTIVE_END_TIME,
         LEAST(pt.NET_LOAD_MINUTES,
           GREATEST(0, (CAST(LEAST(pt.SEGMENT_END_TIME, n.NOW_KST) AS DATE)
             - CAST(pt.SEGMENT_START_TIME AS DATE)) * 1440)) AS EFFECTIVE_NET_LOAD_MIN
   FROM V_OEE_PLAN_TIME pt
    CROSS JOIN clock_now n
   WHERE pt.SEGMENT_START_TIME < n.NOW_KST
), downtime AS (
  SELECT p.ORGANIZATION_ID, p.RESOURCE_ID, p.WORK_DATE, p.SHIFT,
         SUM(GREATEST(0,
           (CAST(LEAST(NVL(e.END_TIME, p.NOW_KST), p.EFFECTIVE_END_TIME) AS DATE)
             - CAST(GREATEST(e.START_TIME, p.SEGMENT_START_TIME) AS DATE)) * 1440)) AS DOWN_MIN
    FROM elapsed_plan p
    JOIN OEE_RESOURCE r ON r.RESOURCE_ID = p.RESOURCE_ID
    JOIN OEE_DOWNTIME_EVENT e
      ON e.ORGANIZATION_ID = r.ORGANIZATION_ID
     AND e.PROCESS_CODE = r.PROCESS_CODE
     AND e.RESOURCE_TYPE = r.RESOURCE_TYPE
     AND e.RESOURCE_CODE = r.REF_CODE
     AND e.START_TIME < p.EFFECTIVE_END_TIME
     AND NVL(e.END_TIME, p.NOW_KST) > p.SEGMENT_START_TIME
   GROUP BY p.ORGANIZATION_ID, p.RESOURCE_ID, p.WORK_DATE, p.SHIFT
), production AS (
  SELECT ORGANIZATION_ID, RESOURCE_ID, WORK_DATE, SHIFT,
         SUM(PLAN_QTY) AS PLAN_QTY, SUM(OUTPUT_QTY) AS OUTPUT_QTY,
         SUM(GOOD_QTY) AS GOOD_QTY, AVG(PICKUP_RATE) AS PICKUP_RATE
    FROM OEE_PRODUCTION_RESULT
   GROUP BY ORGANIZATION_ID, RESOURCE_ID, WORK_DATE, SHIFT
), operands AS (
  SELECT p.RESOURCE_ID, p.PROCESS_CODE, p.ORGANIZATION_ID, p.WORK_DATE, p.SHIFT,
         p.EFFECTIVE_NET_LOAD_MIN AS NET_LOAD_MIN,
         GREATEST(0, p.EFFECTIVE_NET_LOAD_MIN - NVL(d.DOWN_MIN, 0)) AS RUN_MIN,
         LEAST(p.EFFECTIVE_NET_LOAD_MIN, NVL(d.DOWN_MIN, 0)) AS DOWNTIME_MIN,
         r.IDEAL_CT, NVL(pr.PLAN_QTY, 0) AS PLAN_QTY, NVL(pr.OUTPUT_QTY, 0) AS OUTPUT_QTY,
         NVL(pr.GOOD_QTY, 0) AS GOOD_QTY, NVL(pr.OUTPUT_QTY, 0) AS TOTAL_QTY, pr.PICKUP_RATE
    FROM elapsed_plan p
    JOIN OEE_RESOURCE r ON r.RESOURCE_ID = p.RESOURCE_ID
    LEFT JOIN downtime d ON d.ORGANIZATION_ID = p.ORGANIZATION_ID AND d.RESOURCE_ID = p.RESOURCE_ID
      AND d.WORK_DATE = p.WORK_DATE AND d.SHIFT = p.SHIFT
    LEFT JOIN production pr ON pr.ORGANIZATION_ID = p.ORGANIZATION_ID AND pr.RESOURCE_ID = p.RESOURCE_ID
      AND pr.WORK_DATE = p.WORK_DATE AND pr.SHIFT = p.SHIFT
), rates AS (
  SELECT o.*,
         CASE WHEN NET_LOAD_MIN > 0 THEN RUN_MIN / NET_LOAD_MIN ELSE 0 END AS AVAILABILITY,
         CASE WHEN PLAN_QTY > 0 THEN OUTPUT_QTY / PLAN_QTY ELSE 0 END AS PLAN_ACHIEVE,
         CASE WHEN RUN_MIN > 0 THEN OUTPUT_QTY / (RUN_MIN / 60) ELSE 0 END AS UPH,
         CASE WHEN RUN_MIN > 0 AND IDEAL_CT IS NOT NULL THEN (IDEAL_CT * OUTPUT_QTY) / (RUN_MIN * 60) ELSE 0 END AS PERFORMANCE,
         CASE WHEN TOTAL_QTY > 0 THEN GOOD_QTY / TOTAL_QTY ELSE 0 END AS QUALITY
    FROM operands o
)
SELECT r.RESOURCE_ID, r.PROCESS_CODE, r.ORGANIZATION_ID, r.WORK_DATE, r.SHIFT,
       r.NET_LOAD_MIN, r.RUN_MIN, r.DOWNTIME_MIN, r.AVAILABILITY, r.IDEAL_CT,
       r.PLAN_QTY, r.OUTPUT_QTY, r.PLAN_ACHIEVE, r.UPH, r.PERFORMANCE,
       r.GOOD_QTY, r.TOTAL_QTY, r.QUALITY, r.PICKUP_RATE,
       r.AVAILABILITY * r.PERFORMANCE * r.QUALITY AS OEE
  FROM rates r
/
