-- V_OEE_LIVE: 실시간 OEE + 부가지표 (가동/성능/양품/OEE, UPH, 계획달성, 픽업)
-- 근거: docs/plans/2026-07-06-oee-dashboard.md Task 6. 계산은 oee-calc.ts와 동일 규칙(분모0→0, clamp없음).

CREATE OR REPLACE VIEW V_OEE_LIVE AS
SELECT b.*, b.AVAILABILITY * b.PERFORMANCE * b.QUALITY AS OEE
  FROM (
    SELECT pt.RESOURCE_ID, r.PROCESS_CODE, pt.ORGANIZATION_ID, pt.WORK_DATE, pt.SHIFT,
           pt.NET_LOAD_MINUTES AS NET_LOAD_MIN,
           NVL(op.RUN_MIN, 0)  AS RUN_MIN,
           NVL(op.DOWN_MIN, 0) AS DOWNTIME_MIN,
           CASE WHEN pt.NET_LOAD_MINUTES > 0 THEN NVL(op.RUN_MIN,0) / pt.NET_LOAD_MINUTES ELSE 0 END AS AVAILABILITY,
           r.IDEAL_CT,
           NVL(pr.PLAN_QTY, 0)   AS PLAN_QTY,
           NVL(pr.OUTPUT_QTY, 0) AS OUTPUT_QTY,
           CASE WHEN NVL(pr.PLAN_QTY,0) > 0 THEN NVL(pr.OUTPUT_QTY,0) / pr.PLAN_QTY ELSE 0 END AS PLAN_ACHIEVE,
           CASE WHEN NVL(op.RUN_MIN,0) > 0 THEN NVL(pr.OUTPUT_QTY,0) / (NVL(op.RUN_MIN,0) / 60) ELSE 0 END AS UPH,
           CASE WHEN NVL(op.RUN_MIN,0) > 0 AND r.IDEAL_CT IS NOT NULL
                THEN (r.IDEAL_CT * NVL(pr.OUTPUT_QTY,0)) / (NVL(op.RUN_MIN,0) * 60) ELSE 0 END AS PERFORMANCE,
           NVL(pr.GOOD_QTY, 0)   AS GOOD_QTY,
           NVL(pr.OUTPUT_QTY, 0) AS TOTAL_QTY,
           CASE WHEN NVL(pr.OUTPUT_QTY,0) > 0 THEN NVL(pr.GOOD_QTY,0) / pr.OUTPUT_QTY ELSE 0 END AS QUALITY,
           pr.PICKUP_RATE
      FROM V_OEE_PLAN_TIME pt
      JOIN OEE_RESOURCE r ON r.RESOURCE_ID = pt.RESOURCE_ID
      LEFT JOIN (
        SELECT RESOURCE_ID, WORK_DATE, SHIFT,
               SUM(CASE WHEN STATUS='RUN'  THEN DURATION_MIN ELSE 0 END) AS RUN_MIN,
               SUM(CASE WHEN STATUS='DOWN' THEN DURATION_MIN ELSE 0 END) AS DOWN_MIN
          FROM OEE_OPERATION_LOG GROUP BY RESOURCE_ID, WORK_DATE, SHIFT
      ) op ON op.RESOURCE_ID = pt.RESOURCE_ID AND op.WORK_DATE = pt.WORK_DATE AND op.SHIFT = pt.SHIFT
      LEFT JOIN (
        SELECT RESOURCE_ID, WORK_DATE, SHIFT,
               SUM(PLAN_QTY) AS PLAN_QTY, SUM(OUTPUT_QTY) AS OUTPUT_QTY, SUM(GOOD_QTY) AS GOOD_QTY,
               SUM(DEFECT_QTY) AS DEFECT_QTY, AVG(PICKUP_RATE) AS PICKUP_RATE
          FROM OEE_PRODUCTION_RESULT GROUP BY RESOURCE_ID, WORK_DATE, SHIFT
      ) pr ON pr.RESOURCE_ID = pt.RESOURCE_ID AND pr.WORK_DATE = pt.WORK_DATE AND pr.SHIFT = pt.SHIFT
  ) b
/
