-- P_OEE_BUILD_SUMMARY: 근무조 마감 스냅샷 생성 (V_OEE_LIVE → OEE_DAILY_SUMMARY MERGE)
-- 근거: docs/plans/2026-07-06-oee-dashboard.md Task 7. 과거 조회 시 스냅샷 없으면 폴백 없이 오류(API 409).

CREATE OR REPLACE PROCEDURE P_OEE_BUILD_SUMMARY (p_work_date DATE) IS
BEGIN
  MERGE INTO OEE_DAILY_SUMMARY t
  USING (SELECT * FROM V_OEE_LIVE WHERE WORK_DATE = TRUNC(p_work_date)) s
     ON (t.RESOURCE_ID = s.RESOURCE_ID AND t.WORK_DATE = s.WORK_DATE AND t.SHIFT = s.SHIFT)
  WHEN MATCHED THEN UPDATE SET
     t.NET_LOAD_MIN=s.NET_LOAD_MIN, t.RUN_MIN=s.RUN_MIN, t.DOWNTIME_MIN=s.DOWNTIME_MIN,
     t.AVAILABILITY=s.AVAILABILITY, t.IDEAL_CT=s.IDEAL_CT, t.PLAN_QTY=s.PLAN_QTY, t.OUTPUT_QTY=s.OUTPUT_QTY,
     t.PLAN_ACHIEVE=s.PLAN_ACHIEVE, t.UPH=s.UPH, t.PERFORMANCE=s.PERFORMANCE,
     t.GOOD_QTY=s.GOOD_QTY, t.TOTAL_QTY=s.TOTAL_QTY, t.QUALITY=s.QUALITY, t.PICKUP_RATE=s.PICKUP_RATE, t.OEE=s.OEE
  WHEN NOT MATCHED THEN INSERT
     (RESOURCE_ID, PROCESS_CODE, ORGANIZATION_ID, WORK_DATE, SHIFT, NET_LOAD_MIN, RUN_MIN, DOWNTIME_MIN,
      AVAILABILITY, IDEAL_CT, PLAN_QTY, OUTPUT_QTY, PLAN_ACHIEVE, UPH, PERFORMANCE, GOOD_QTY, TOTAL_QTY, QUALITY, PICKUP_RATE, OEE)
     VALUES
     (s.RESOURCE_ID, s.PROCESS_CODE, s.ORGANIZATION_ID, s.WORK_DATE, s.SHIFT, s.NET_LOAD_MIN, s.RUN_MIN, s.DOWNTIME_MIN,
      s.AVAILABILITY, s.IDEAL_CT, s.PLAN_QTY, s.OUTPUT_QTY, s.PLAN_ACHIEVE, s.UPH, s.PERFORMANCE, s.GOOD_QTY, s.TOTAL_QTY, s.QUALITY, s.PICKUP_RATE, s.OEE);
  COMMIT;
END;
/
