-- 생산2팀 2층 조립 CELL 기준정보 시드
-- 근거: docs/reports/oee-mobile-collaboration/2026-08-07-production2-cell-reassessment.md
-- 대상 tenant: COMPANY='EUNSUNG', PLANT_CD='1'
-- 실제 PK(PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE)별 MERGE만 수행하며
-- 대상 18개 키 이외의 PLANTS 행은 변경하지 않는다.
-- 실행 도구: oracle-db execute-file ('/' 한 줄 구분)

MERGE INTO PLANTS target
USING (
  SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD,
         'EUNSUNG' AS PLANT_CODE, '-' AS SHOP_CODE, '-' AS LINE_CODE, '-' AS CELL_CODE,
         '은성전장 홍성공장' AS PLANT_NAME, 'PLANT' AS PLANT_TYPE, 0 AS SORT_ORDER, 'Y' AS USE_YN
  FROM DUAL
) source
ON (
  target.PLANT_CODE = source.PLANT_CODE
  AND target.SHOP_CODE = source.SHOP_CODE
  AND target.LINE_CODE = source.LINE_CODE
  AND target.CELL_CODE = source.CELL_CODE
)
WHEN MATCHED THEN UPDATE SET
  target.PLANT_NAME = source.PLANT_NAME,
  target.PLANT_TYPE = source.PLANT_TYPE,
  target.SORT_ORDER = source.SORT_ORDER,
  target.USE_YN = source.USE_YN,
  target.UPDATED_BY = 'SYSTEM',
  target.UPDATED_AT = SYSTIMESTAMP
  WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE,
  PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE,
  source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN,
  'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP
);
/

MERGE INTO PLANTS target
USING (
  SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD,
         'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, '-' AS LINE_CODE, '-' AS CELL_CODE,
         '2층 작업장' AS PLANT_NAME, 'SHOP' AS PLANT_TYPE, 10 AS SORT_ORDER, 'Y' AS USE_YN
  FROM DUAL
) source
ON (
  target.PLANT_CODE = source.PLANT_CODE
  AND target.SHOP_CODE = source.SHOP_CODE
  AND target.LINE_CODE = source.LINE_CODE
  AND target.CELL_CODE = source.CELL_CODE
)
WHEN MATCHED THEN UPDATE SET
  target.PLANT_NAME = source.PLANT_NAME,
  target.PLANT_TYPE = source.PLANT_TYPE,
  target.SORT_ORDER = source.SORT_ORDER,
  target.USE_YN = source.USE_YN,
  target.UPDATED_BY = 'SYSTEM',
  target.UPDATED_AT = SYSTIMESTAMP
  WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE,
  PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE,
  source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN,
  'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP
);
/

MERGE INTO PLANTS target
USING (
  SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD,
         'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '-' AS CELL_CODE,
         '생산2팀' AS PLANT_NAME, 'LINE' AS PLANT_TYPE, 20 AS SORT_ORDER, 'Y' AS USE_YN
  FROM DUAL
) source
ON (
  target.PLANT_CODE = source.PLANT_CODE
  AND target.SHOP_CODE = source.SHOP_CODE
  AND target.LINE_CODE = source.LINE_CODE
  AND target.CELL_CODE = source.CELL_CODE
)
WHEN MATCHED THEN UPDATE SET
  target.PLANT_NAME = source.PLANT_NAME,
  target.PLANT_TYPE = source.PLANT_TYPE,
  target.SORT_ORDER = source.SORT_ORDER,
  target.USE_YN = source.USE_YN,
  target.UPDATED_BY = 'SYSTEM',
  target.UPDATED_AT = SYSTIMESTAMP
  WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE,
  PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE,
  source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN,
  'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP
);
/

MERGE INTO PLANTS target
USING (
  SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD,
         'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '50' AS CELL_CODE,
         'CMA' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 50 AS SORT_ORDER, 'Y' AS USE_YN
  FROM DUAL
) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP
  WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '51' AS CELL_CODE, 'O1XX' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 51 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '52' AS CELL_CODE, 'DN8' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 52 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '53' AS CELL_CODE, 'CD6' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 53 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '54' AS CELL_CODE, 'HG' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 54 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '55' AS CELL_CODE, 'MOC28' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 55 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '56' AS CELL_CODE, 'ECM' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 56 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '57' AS CELL_CODE, 'AE_EV' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 57 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '58' AS CELL_CODE, 'UPPER' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 58 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '59' AS CELL_CODE, 'EOP' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 59 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '60' AS CELL_CODE, '대양전기' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 60 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '61' AS CELL_CODE, 'BMA' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 61 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '62' AS CELL_CODE, 'TSMOST' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 62 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '63' AS CELL_CODE, 'AS' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 63 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

MERGE INTO PLANTS target
USING (SELECT 'EUNSUNG' AS COMPANY, '1' AS PLANT_CD, 'EUNSUNG' AS PLANT_CODE, '2F' AS SHOP_CODE, 'PROD2' AS LINE_CODE, '64' AS CELL_CODE, 'LED' AS PLANT_NAME, 'CELL' AS PLANT_TYPE, 64 AS SORT_ORDER, 'Y' AS USE_YN FROM DUAL) source
ON (target.PLANT_CODE = source.PLANT_CODE AND target.SHOP_CODE = source.SHOP_CODE AND target.LINE_CODE = source.LINE_CODE AND target.CELL_CODE = source.CELL_CODE)
WHEN MATCHED THEN UPDATE SET target.PLANT_NAME = source.PLANT_NAME, target.PLANT_TYPE = source.PLANT_TYPE, target.SORT_ORDER = source.SORT_ORDER, target.USE_YN = source.USE_YN, target.UPDATED_BY = 'SYSTEM', target.UPDATED_AT = SYSTIMESTAMP WHERE target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE, PLANT_NAME, PLANT_TYPE, SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT) VALUES (source.COMPANY, source.PLANT_CD, source.PLANT_CODE, source.SHOP_CODE, source.LINE_CODE, source.CELL_CODE, source.PLANT_NAME, source.PLANT_TYPE, source.SORT_ORDER, source.USE_YN, 'SYSTEM', 'SYSTEM', SYSTIMESTAMP, SYSTIMESTAMP);
/

COMMIT;
/
