DECLARE
  v_count NUMBER;
  v_columns VARCHAR2(4000);
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM OEE_RESOURCE
   WHERE REF_CODE IS NULL
      OR PROCESS_CODE NOT IN ('SMT', 'ASSY')
      OR RESOURCE_TYPE NOT IN ('LINE', 'CELL')
      OR USE_YN NOT IN ('Y', 'N');

  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'OEE_RESOURCE contains rows outside the managed resource contract');
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM (
      SELECT ORGANIZATION_ID, REF_CODE
        FROM OEE_RESOURCE
       GROUP BY ORGANIZATION_ID, REF_CODE
      HAVING COUNT(*) > 1
    );

  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'OEE_RESOURCE contains duplicate organization/line mappings');
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'OEE_RESOURCE'
     AND COLUMN_NAME = 'REF_CODE'
     AND NULLABLE = 'Y';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OEE_RESOURCE MODIFY (REF_CODE NOT NULL)';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'UX_OEE_RESOURCE_REF';

  IF v_count > 0 THEN
    SELECT LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY COLUMN_POSITION)
      INTO v_columns
      FROM USER_IND_COLUMNS
     WHERE INDEX_NAME = 'UX_OEE_RESOURCE_REF';

    IF v_columns <> 'ORGANIZATION_ID,REF_CODE' THEN
      EXECUTE IMMEDIATE 'DROP INDEX UX_OEE_RESOURCE_REF';
      v_count := 0;
    END IF;
  END IF;

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_OEE_RESOURCE_REF ON OEE_RESOURCE (ORGANIZATION_ID, REF_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_RESOURCE' AND CONSTRAINT_NAME = 'CK_OEE_RESOURCE_PROCESS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE OEE_RESOURCE ADD CONSTRAINT CK_OEE_RESOURCE_PROCESS CHECK (PROCESS_CODE IN ('SMT', 'ASSY'))]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_RESOURCE' AND CONSTRAINT_NAME = 'CK_OEE_RESOURCE_TYPE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE OEE_RESOURCE ADD CONSTRAINT CK_OEE_RESOURCE_TYPE CHECK (RESOURCE_TYPE IN ('LINE', 'CELL'))]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_RESOURCE' AND CONSTRAINT_NAME = 'CK_OEE_RESOURCE_USE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE OEE_RESOURCE ADD CONSTRAINT CK_OEE_RESOURCE_USE CHECK (USE_YN IN ('Y', 'N'))]';
  END IF;
END;
/
