DECLARE
  v_table_count NUMBER;
  v_invalid_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_table_count
    FROM USER_TABLES
   WHERE TABLE_NAME IN (
     'OEE_OPERATION_LOG',
     'OEE_PLAN_TIME',
     'OEE_DAILY_SUMMARY',
     'OEE_PRODUCTION_RESULT',
     'OEE_DOWNTIME_EVENT'
   );

  IF v_table_count <> 5 THEN
    RAISE_APPLICATION_ERROR(-20031, 'OEE shift contract preflight requires all five OEE tables.');
  END IF;

  EXECUTE IMMEDIATE q'[SELECT COUNT(*) FROM OEE_OPERATION_LOG WHERE SHIFT IS NULL OR SHIFT NOT IN ('DAY', 'NIGHT')]'
    INTO v_invalid_count;
  IF v_invalid_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20032, 'OEE_OPERATION_LOG contains a non-DAY/NIGHT SHIFT.');
  END IF;

  EXECUTE IMMEDIATE q'[SELECT COUNT(*) FROM OEE_PLAN_TIME WHERE SHIFT IS NULL OR SHIFT NOT IN ('DAY', 'NIGHT')]'
    INTO v_invalid_count;
  IF v_invalid_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20033, 'OEE_PLAN_TIME contains a non-DAY/NIGHT SHIFT.');
  END IF;

  EXECUTE IMMEDIATE q'[SELECT COUNT(*) FROM OEE_DAILY_SUMMARY WHERE SHIFT IS NULL OR SHIFT NOT IN ('DAY', 'NIGHT')]'
    INTO v_invalid_count;
  IF v_invalid_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20034, 'OEE_DAILY_SUMMARY contains a non-DAY/NIGHT SHIFT.');
  END IF;

  EXECUTE IMMEDIATE q'[SELECT COUNT(*) FROM OEE_PRODUCTION_RESULT WHERE SHIFT IS NULL OR SHIFT NOT IN ('DAY', 'NIGHT')]'
    INTO v_invalid_count;
  IF v_invalid_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20035, 'OEE_PRODUCTION_RESULT contains a non-DAY/NIGHT SHIFT.');
  END IF;

  EXECUTE IMMEDIATE q'[SELECT COUNT(*) FROM OEE_DOWNTIME_EVENT WHERE WORK_SEGMENT IS NULL OR WORK_SEGMENT NOT IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'DAY', 'NIGHT')]'
    INTO v_invalid_count;
  IF v_invalid_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20036, 'OEE_DOWNTIME_EVENT contains an unsupported WORK_SEGMENT.');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_DOWNTIME_EVENT'
     AND CONSTRAINT_NAME = 'CK_OEE_DTE_WORK_SEGMENT';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OEE_DOWNTIME_EVENT DROP CONSTRAINT CK_OEE_DTE_WORK_SEGMENT';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OEE_DOWNTIME_EVENT MODIFY (WORK_SEGMENT VARCHAR2(5))';
END;
/

BEGIN
  UPDATE OEE_DOWNTIME_EVENT
     SET WORK_SEGMENT = 'DAY'
   WHERE WORK_SEGMENT IN ('A', 'B', 'C', 'D', 'E');

  UPDATE OEE_DOWNTIME_EVENT
     SET WORK_SEGMENT = 'NIGHT'
   WHERE WORK_SEGMENT IN ('F', 'G', 'H', 'I', 'J');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_DOWNTIME_EVENT'
     AND CONSTRAINT_NAME = 'CK_OEE_DTE_WORK_SEGMENT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE OEE_DOWNTIME_EVENT ADD CONSTRAINT CK_OEE_DTE_WORK_SEGMENT CHECK (WORK_SEGMENT IN ('DAY', 'NIGHT'))]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_OPERATION_LOG'
     AND CONSTRAINT_NAME = 'CK_OEE_OPLOG_SHIFT';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OEE_OPERATION_LOG DROP CONSTRAINT CK_OEE_OPLOG_SHIFT';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_PLAN_TIME'
     AND CONSTRAINT_NAME = 'CK_OEE_PLANTIME_SHIFT';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OEE_PLAN_TIME DROP CONSTRAINT CK_OEE_PLANTIME_SHIFT';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_DAILY_SUMMARY'
     AND CONSTRAINT_NAME = 'CK_OEE_SUMMARY_SHIFT';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OEE_DAILY_SUMMARY DROP CONSTRAINT CK_OEE_SUMMARY_SHIFT';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_PRODUCTION_RESULT'
     AND CONSTRAINT_NAME = 'CK_OEE_PROD_SHIFT';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OEE_PRODUCTION_RESULT DROP CONSTRAINT CK_OEE_PROD_SHIFT';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_OPERATION_LOG'
     AND CONSTRAINT_NAME = 'CK_OEE_OPLOG_SHIFT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE OEE_OPERATION_LOG ADD CONSTRAINT CK_OEE_OPLOG_SHIFT CHECK (SHIFT IN ('DAY', 'NIGHT'))]';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_PLAN_TIME'
     AND CONSTRAINT_NAME = 'CK_OEE_PLANTIME_SHIFT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE OEE_PLAN_TIME ADD CONSTRAINT CK_OEE_PLANTIME_SHIFT CHECK (SHIFT IN ('DAY', 'NIGHT'))]';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_DAILY_SUMMARY'
     AND CONSTRAINT_NAME = 'CK_OEE_SUMMARY_SHIFT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE OEE_DAILY_SUMMARY ADD CONSTRAINT CK_OEE_SUMMARY_SHIFT CHECK (SHIFT IN ('DAY', 'NIGHT'))]';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'OEE_PRODUCTION_RESULT'
     AND CONSTRAINT_NAME = 'CK_OEE_PROD_SHIFT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE OEE_PRODUCTION_RESULT ADD CONSTRAINT CK_OEE_PROD_SHIFT CHECK (SHIFT IN ('DAY', 'NIGHT'))]';
  END IF;
END;
/
