DECLARE
  v_count NUMBER;
  v_valid NUMBER;
BEGIN
  -- Preserve legacy rows; only new line-based entries populate LINE_CODE.
  SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'IP_EQUIP_DOWNTIME_RESULT' AND COLUMN_NAME = 'LINE_CODE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE IP_EQUIP_DOWNTIME_RESULT ADD (LINE_CODE VARCHAR2(20 BYTE) NULL)';
  END IF;

  SELECT COUNT(*) INTO v_valid
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'IP_EQUIP_DOWNTIME_RESULT' AND COLUMN_NAME = 'LINE_CODE'
     AND DATA_TYPE = 'VARCHAR2' AND DATA_LENGTH = 20 AND CHAR_USED = 'B'
     AND NULLABLE = 'Y';
  IF v_valid <> 1 THEN
    RAISE_APPLICATION_ERROR(-20001, 'IP_EQUIP_DOWNTIME_RESULT.LINE_CODE must be nullable VARCHAR2(20 BYTE)');
  END IF;
END;
/
COMMENT ON COLUMN IP_EQUIP_DOWNTIME_RESULT.LINE_CODE IS '생산라인 코드 (동일 조직의 IP_PRODUCT_LINE.LINE_CODE, 기존 실적은 NULL)';
/
