###################################
#
###################################
[SERIALCOMM]
COMPORT =2
BAUDRATE =19200
DATABITS = 8
STOPBITS =1
PARITY = N
NULLDISCARD=1
INPUTMODE=1
INPUTBUFFERSIZE=24
OUTPUTBUFFERSIZE=24
INPUTLENGTH=0
DELAY=2.00
LOGTRACE=Y
####################################
# 
####################################
[PLC]
plc_send_ascii_data=Y
plc_start_address=0
plc_end_address=0
PLC_ADD_START=101
PLC_ADD_COUNT=32
PLC_ID=01
PLC_COMMAND_TYPE=RSB
PLC_ADDRESS_LENGTH=06
PLC_ADDRESS_START_MARK=%DW
PLC_WRITE_COMMAND_TYPE=WSB
AUTOSERVICE=N
REMOTE_DATABASE=XXDB
REMOTE_USER_ID=INFINITY21_JSERP
REMOTE_PASSWORD=INFINITY21_JSERP
AUTOLOGON=N
PLC_CHANNEL=00
SEND_DATA_TO_REMOTE_DB=Y
[DATABASE]
delay=.00
REMOTE_USER_ID=INFINITY21_PIMMES
REMOTE_PASSWORD=INFINITY21_PIMMES
