[DATABASE]
DBMS=O10
SERVERNAME          =ESDBext
SERVERNAME_EXTRANET =ESDBEXT 
HOSTNAME            =
HOSTNAME_EXTRANET   =192.168.0.100
DATABASE            =XE
USERID=ADMIN
DATABASEPASSWORD=8888

##############################################
## MES
##############################################
LOGID=INFINITY21_JSMES
LOGPASSWORD=73787073787384895049957483776983

#LOGID=INFINITY21_JSLCD
#LOGPASSWORD=73787073787384895049957483766768

VERSION= 100
INTERNET_HOST=61.81.47.240
INTERNET_PORT=21
INTERNET_USER=INFINITY21
INTERNET_PASSWD=Passw0rd
INTERNET_DIRECTORY = /INFINITY21_UPGRADE_CENTER/JSMES

FTP_HOST         =192.168.175.100
FTP_PORT         =21
FTP_HOST_EXTRANET=192.168.175.100
FTP_USER   =INFINITY21
FTP_PASSWD =Passw0rd
FTP_DIRECTORY=/INFINITY21_UPGRADE_CENTER/JSMES

FTP_HOST2         =192.168.1.100
FTP_PORT2         =21
FTP_HOST_EXTRANET2=192.1.100
FTP_USER2   =INFINITY21
FTP_PASSWD2 =Passw0rd
FTP_DIRECTORY2=/INFINITY21_UPGRADE_CENTER/JSMES

FTP_HOST3         =192.168.0.100
FTP_PORT3         =21
FTP_HOST_EXTRANET3=192.168.0.100
FTP_USER3   =INFINITY21
FTP_PASSWD3 =Passw0rd
FTP_DIRECTORY3=/INFINITY21_UPGRADE_CENTER/JSMES

DEFAULTLANGUAGE=K

[APPLICATION]
APPLICATIONNAME=INFINITY21 JSMES
APPLICATIONINITIAL=M
RUNAPPLICATION=INFINITY21_JSMES.EXE
ERRORLOGTRACE=Y
OPENSHEETPOSITION = 23
[DISPLAY]
title_text_color=65535
header_color=10485760
title_back_color=0
dw_head_background=dw_background1.bmp
dw_background=userdefine
head_fontsize=20
row_height=180
fontsize=15
row_y_position=0
rowperpage=30
retrieve_interval=10
scroll_interval=5
footer_back_color=15588606
dw_header_back_color=15121863
dw_background_color=12632256
dw_background_color_odd=16744576
DUAL_MONITOR_X=7,000
DUALMONITOR=E
8_CHN_INTERVAL=8
8_CHN_MAX_TEMP_RANGE=60
8_CHN_MIN_TEMP_RANGE=20
SEGMENTMACHINE=001
segmentinterval=5
START_CHANNEL=N
SEGMENTAUTOOPEN=N
graphchangeinterval=3
8CHANNELMACHINE=001
[LANGUAGE]
LANG=KR
